### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1013]
When I try to compile (an admittedly rather large) script using Ampersand-v3.17.4 [development:6f9f6d9ed], a fatal error occurs in the postprocessing part that creates the frontend. It is currently stopping work in a project.

Here is the error:

![afbeelding](https://user-images.githubusercontent.com/8522589/65153515-2d008080-da2a-11e9-86ef-abb7f384652f.png)

## Analysis

As the script has been growing over the last weeks/months, I had already noticed that compile times were increasing in what I perceived as a non-linair fashion. This worried me somewhat, but since I have a rather powerful laptop with lots of RAM (32 GB), I didn't mind that much. 

I've checked with TaskManager: when compiling the script, only some 38% of that 32 GB are being used by (all) programs. So that does not seem to be the problem.

Earlier today, I had some problems upgrading to the latest Ampersand version, which uses a new Haskell version, so that might be the problem. I have restored my application source to the status of the beginning of the day. That compiled without error (albeit slow).

Also, I have compiled the sources that resulted in the error using the old Ampersand-v3.17.2 [development:254cacd10] (version of mid July). This also gives the heap-error.

Looking on the Internet, it looks like it is a node.js memory limitation, for which there may be different causes.

**Comment by Michiel-s** [comment]
Hi @RieksJ, I think this has to do with the size of your prototype application and the number of files (generated javascript and html) that is bundled into `project.js` by the command `gulp build-project` you run after generating the prototype.

Gulp is using NodeJs to run this. There is a default max heap memory for NodeJs [see](https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory). You can increase this for running scripts with `node --max-old-space-size=2048 yourFile.js`. This will allocate max 2GB of heap memory.

Since we are using the Gulp-cli, you need to pass this argument to gulp, which will pass it through to NodeJs. [see](https://stackoverflow.com/questions/37272998/gulp-call-and-retry-last-allocation-failed-process-out-of-memory).
So use
`gulp build-project --max-old-space-size=2048`

Let me know if this fixes your problem.

**Comment by Michiel-s** [comment]
@RieksJ you closed the issue, can we conclude that the comment above fixed the problem?

**Comment by RieksJ** [comment]
yes.
