### ISSUE TITLE
VariableDeletedCheckbox

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#106]
I have tried to run  ...\git\ampersand-models\NVWA DTV\Referentielijsten.adl[master:f638ba08], which I have compiled from Ampersand v3.1.0[master:c9f2b42].
Formerly, the role FAB could happily delete a variable from one of the Referentielijsten. Currently, however, deleting a variable does not work...
(Could it be that the VariableDeletedCheckbox has suffered from bitrot during the past few days?)
Although Han has been the last person to make a change in the related portion of Referentielijsten.adl (line 87), he is clueless. Maybe Michiel knows how to make cheese from this....  :-)

**Comment by stefjoosten** [comment]
Michiel, hij loopt nog niet helemaal soepel (of liever: helemaal niet zo soepel). Zie mijn [videobericht](https://youtu.be/oemv3eWnENo) voor details. Ik zet het issue weer even open.

**Comment by Michiel-s** [comment]
Om dit issue op te lossen hebben we het volgende nodig aan haskell zijde:
1) In $allInterfaceObjects in Generics.php moet bij de betreffende interfacebox een flaggetje komen indien het een expressie is met een property als blaadje. Het attribuut `exprIsProp` is nu al opgenomen, maar deze is, naast `rel :: A * B [PROP]`, ook true voor de identiteit expressie `I[Concept]`. In de backend moet ik die er nu weer uit filteren op basis van heeft geen subinterfaces én de relation is gespecificeerd. Gewenste situatie, exprIsProp geeft alleen true voor expressies met een PROP relatie op de tgt.
2) De views generator in GenFrontend.hs moet indien het een property expressie betreft zoals hierboven gedefinieerd, niet het template Atomic-OBJECT.html pakken, maar Atomic-PROPERTY.html

**Comment by hanjoosten** [comment]
A simple fix would be to redefine the isProp function. Currently, for the expression ```I``` the definition of isProp is True. @stefjoosten, is there a reason that the identity expression is a property? 
If isProp (```I```) == True, then why do we have this issue? 

I have created a branch to test if there would be any damage, but Sentinel does not find any.

**Comment by hanjoosten** [comment]
I had a chat with Stef about this issue.

After a long story (call me for details, i'm not going to type it all down here) we came to the following conclusion:

Changing the definition of isProp is unacceptable, because it would violate the semantics. However, at the frontend, we would like to know that we have
The implementation of the property relation is currently a boolean. This is confusing. A better solution is to let the field have either:
 *  \<NULL\>, which will mean that the property is false
 * a value, equal to the value of the corresponding atom (in A), which will mean that the property is true.

(Any other value can be considered as an error, but the sql generator will generate queries that will regard anything not \<NULL\> the same as true)

This solution makes that in most cases the representation will not be Boolean, and therfore will be far less confusing for people trying to understand the semantics of whatever they see in the database

Now if we have a field that contains a property relation, it should get a template with the following requirements:
 * The user should intuitevly see somthing that has two values (eg. a checkbox would do)
 * When the user can edit the field, then the content should be set to \<NULL\> or to the value of the corresponding atom, depending on the assumed intent of the user.

To do so, the following changes need to be made:
 1) In Haskell, the representation-type of the field that contains the property will have to be made equal to the representation-type of the source (or target) concept.
 2) In Haskell, Add a field in $allInterfaceObjects, that tells iff a relation is the identity relation.
3) In the frontend, use the template for property values iff isProp = true and isIdent = false.

@Michiel-s , how would that be? If you agree with this solution, I will make a branch for you to experiment with

By the way: This will also close issue #150 , which is very related with this topic.

**Comment by Michiel-s** [comment]
In your proposed solution:
1) Note that this is already the case as long as I know. So no change is
needed. This is also the confusion in ticket #150, which can be closed.
2) That would be great. I understand you already did this.
3) Agree. Note that this is also something you have to do in the
GenFrontend.hs file

I'll take care of the required changes in the php framework and prepare the
required template 'Atomic-PROPERTY.html'

One of the design principles of the new frontend is that no Ampersand
artefacts (like the notion of properties) or knowledge about their behavior
is required after/behind the API. Therefore a property will be represented
by a checkbox (default) and deals with true/false. The php framework will
transform this into ampersand stuff based on Generics.php. We shouldn't
implement the things you describe about templates that implement the
property behavior with null (when absent) or the atomid (when true). This
is not according to the mentioned design principle.

Anyway. I agree with the proposed solution and that works fine for me.
Op wo 26 aug. 2015 om 16:52 schreef Han Joosten <notifications@github.com>

**Comment by hanjoosten** [comment]
Fixed. I think also the frontend works well now. @Michiel-s , iff you agree, please close this issue.

**Comment by Michiel-s** [comment]
I've tested the behavior and I looks like it's working as requested. Thanks.
