### ISSUE TITLE
Publishing of Docker images

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1067]
# What happened
Han tried to build and run RAP, using the [README of RAP3.](https://github.com/AmpersandTarski/RAP/blob/master/README.md) However, as the 'docker-compose build' was running Han ran into an error. A package from the GitHub Package Registry, docker.pkg.github.com/ampersandtarski/ampersand/ampersand:latest, failed to open due to missing "auth credentials". See https://github.com/AmpersandTarski/RAP/issues/75.

# What I expected
I expect that everybody who runs our 'docker-compose build' recipes NEVER runs into a mistake. I would also expect that Han, of all people, has no fewer authorizations than I do. So this error came as a complete mistake.

# Analysis
The answer is in https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages. 
Even for merely pulling a docker image from the GitHub Package Registry, GitHub requires an authentication token. After Han generated one he could pull the desired image.

# Diagnosis
This is a stumbling stone for outside users, which hampers the adoption of our project. So we must publish images 'for the whole wide world' in a repo that anyone can read. I suggest we use Docker Hub for this purpose.

**Comment by Michiel-s** [comment]
Fully agree. I think we should move back to [docker hub](https://hub.docker.com/). Github launched package registry feature last year, including support for docker images. However, there are some drawbacks:
* You cannot delete images from public repo (also not as owner/admin of a repository). See [documentation](https://help.github.com/en/packages/publishing-and-managing-packages/deleting-a-package). This is really annoying, since we have several images from feature branches pushed. See https://github.com/AmpersandTarski/Ampersand/packages/81415/versions
* Limited support/overview of pushed images on Github.com. e.g. I cannot filter, sort, search 
 https://github.com/AmpersandTarski/Ampersand/packages/81415/versions
* Tags like 'master', 'latest', etc don't show the correct push date. The date of the first push is shown. Maybe this is fixed now?

Combined with the fact that you need a Github account and configure credentials to pull images, I suggest to move to Docker hub

**Comment by stefjoosten** [comment]
We need a stable list of "maintained images" in "The tools we use". Preferrably documented so that the reader can rebuild these images, so she can trust these images.
