### ISSUE TITLE
Failed opening required '...\bootstrap/../lib/autoload.php'

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1096]
# What happened

I generated a prototype without docker. After spinning up the application, I got the following error message:
![image](https://user-images.githubusercontent.com/1159672/88427731-cee3bd00-cdf3-11ea-9d92-5f01955520a5.png)

# What I expected

A working prototype

# Version of ampersand that was used
4.0.2

# Screenshot / Video

# Context / Source of ampersand script

**Comment by Michiel-s** [comment]
As of version 4.x the Ampersand compiler doesn't run `composer install` anymore. Composer is PHP package manager that install all required libraries. The result is a `autoload.php` that is included by our prototype framework. The error you get is because that file isn't found.

Solution for you to move forward: run `composer install` in The generated prototype directory (probably in your xampp htdocs folder).

Furthermore, in the prototype framework code, let's add a check for the existence of the autoload file and provide a more helpful error message when it does not exist. E.g. suggesting to run composer install.

**Comment by Michiel-s** [comment]
Btw, you won't run into this issue when using Docker, because the composer install step is part of the Dockerfile.
