### ISSUE TITLE
Daemon doesn't correctly ignore invariant violations

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1107]
When I'm using `Ampersand-v4.1.0 [HEAD:cd1fb60*]` to run in daemon-mode on my script, this is the output (note that the top of the figure shows how I ran the daemon):

![image](https://user-images.githubusercontent.com/8522589/90499581-00794b00-e14a-11ea-88f8-afe708e74a70.png)

Here is the output when running the daemon with `--ignore-invariant-violations`

![image](https://user-images.githubusercontent.com/8522589/90499787-459d7d00-e14a-11ea-8b2a-f5aeb6ae8ab4.png)

I would have expected that the latter didn't show any of the rule-violations.

Here is a list of (possible) issues that I have found so far when using `ampersand daemon`: 
- the option `--ignore-invariant-violations` doesn't work. Please fix this.
- I have found that `--ign` provides no error, bug `--ing` is an invalid option. Can we use `--ign` as a shortcut for --ignore-invariant-violations`?
- some options, e.g. `--verbosity` do not seem to function as suggested. For example, `--verbosity error` does not show errors when I make a syntax error in my script.

What set of options do I need to provide the daemon with to only get the basic syntax and type errors?

**Comment by hanjoosten** [comment]
- The option --ignore-invariant-violations should be made available in te daemon.
- `--ign` could be expanded using your tab key if you are on linux. Unfortunatly this doesn't work on windows. This cannot be fixed by us, for we use a library to parse the options.
- --verbosity works as implemented. Run `ampersand daemon --help` to see what is possible.

**Comment by RieksJ** [comment]
`--verbosity error` is possible according to `--help`. Then I type `1 2 3` in my script. What should the daemon then do? I do not see an error...

**Comment by hanjoosten** [comment]
Could you supply some more context?  What exactly are you doing? Don't you get any errors? What is in your  .ampersand file?

**Comment by hanjoosten** [comment]
There are several levels of verbosity. Debug, info, warn and error. I guess error is the least verbose.

**Comment by RieksJ** [comment]
So what is an error that gets logged? Can you give an example?

**Comment by hanjoosten** [comment]
Before ampersand 4.0, we only had the `--verbose` switch. So everything that was printed to the user's terminal was either always printed to the terminal, or only when the `--verbose` switch was turned on. 

Since ampersand 4.0, we have the ability to do this more subtle. Depending on the switch, we have `Debug`, `Error`, `Warn` and `Info` (in that order). Having this ability does not mean that all type of messages that is thrown onto the terminal suddenly has the right level. In the process of going to 4.0, all messages were `--verbose` was required have been set to `Debug` level. All others have been set to `Info`. On an adhoc basis, some messages have been set to `Warn` or `Error`.

So if you want messages to show or not to show, you could play around with these different settings. If you find that some type of messages have the wrong level, we could pretty easy change those.

**Comment by RieksJ** [comment]
I've added @Michiel-s to sort things out and properly define the various levels, as he had some nice ideas about that earlier.

In the meantime, I would like to have a verbosity level that has the following properties:
- it does NOT show which files are being included (which currently is pretty much always the case, and is very distracting because it happens all the time)
- it does NOT show any violations that the daemon may detect.
- it does NOT show 'smart warnings' about (in)Correct Capitalization.
- it DOES show syntax errors and typing errors.

I do not care what that severity level is being called - if it already exists or not.
I suggest to make this the default severity level, but if that cannot be done, to specify in this ticket what the severity level for this behavior is called.
Does that make sense?

**Comment by hanjoosten** [comment]
* I changed the level of the message that tells about what files are read to logDebug. That means the message is only there at the most verbose level. 
* To NOT show the violations of invariants, you have to use `--ignore-invariant-violations`, which has been fixed.
* You can suspress ALL warnings either by using `--verbosity error` or `--no-warnings` . Both should work now. (has been fixed)
* Most typing errors are detected as syntax errors. They will be shown unless you set the verbosity level to `silent`.

**Comment by RieksJ** [comment]
would be nice if the pull request was actually reviewed and accepted.
