### ISSUE TITLE
TXT-related VIEWs should be possible

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1112]
The following (partial) scripts show how to include fixed texts in an interface:
~~~
BOX [ "label 1": TXT "Text 1 (normally formatted)"
    , "label 2": V;"Text 2 (formatted as 'STRONG')"[IfcText] cRud <STRONG>
    ]
...
POPULATION IfcText CONTAINS ( "Text 2 (formatted as 'STRONG')" )
~~~
where 
- the text of `label 1` can use the `TXT` syntax because it needs no formatting, and
- the text of `label 2`  cannot use that syntax because it is supposed to printed in **boldface (strong)**. It requires the developer to create an expression , provide a population statement for it, and reinstall the database - not only initially, but also after every text-modification.

If we were to consider `TXT` as a special keyword that would automatically add a subsequent string to the concept `TXT`, it would be easy to create VIEWs for it (we already have the html-template for 'STRONG'), allowing the above syntax to become:
~~~
BOX [ "label 1": TXT "Text 1 (normally formatted)"
    , "label 2": TXT "Text 2 (formatted as 'STRONG')" <STRONG>
    ]
~~~
which is much more readable and maintainable).

**Comment by hanjoosten** [comment]
Currently @Michiel-s and I are working on a feature to enhance the syntax of VIEW statement (see issue #1089). We have been discussing things like this the other day. This seems to lead to the integration of BOX VIEW and maybe even INTERFACE constructs in a natural way. A long time ago we discussed this (see issue #133). Since then, a lot of experience has been gained with interfaces. 
The wish to have inline HTML for simple things is obvious. It enables the usecases @RieksJ asks for in this issue. 

I am currently struggling with my developer setup (I try to use vscode, wsl2, devcontainers to get a better developer experience). I hope that I can get this to work soon, and then I can finish the feature branch pretty soon, I guess. @Michiel-s is likely to have some work at the frontend too because of changes.

**Comment by hanjoosten** [comment]
The syntax for fixed texts will be quite simple. Something like:
~~~
BOX [ "someLable" : HTML "<STRONG>Text 2</STRONG>"
        , ""somotherlabel" : expr
    ]
~~~
The idea is that you can enter a string, that will be put directly into the generated HTML. This gives a lot of freedom (and danger ;) )

**Comment by sjcjoosten** [comment]
Love the idea of ``HTML``. Are we allowing something unbalanced like ``</DIV><DIV>``? If so, can we rename that to RAWHTML to highlight its danger? (I imagine TXT, TEXT, RTF, MD, IMGURL, ... could all be examples of non-dangerous labels for text if we ever need those, and RAWJSON could be another example of a dangerous label if we ever need it. Not proposing any of these labels right now, just proposing to rename HTML to RAWHTML)

**Comment by hanjoosten** [comment]
Good point. RAWHTML it will be.

**Comment by Michiel-s** [comment]
Indeed HTML is great idea! But I don't see why we should make explicit that it is dangerous by using `RAWHTML` instead of `HTML`. HTML is markup language, there isn't something like RAWHTML. The use of HTML templates is already a feature in the ampersand stack, to create application specific HTML view. In either way, the developer/modeler should understand what he/she is doing.

I issues to start to occur frequently, we could decide to add a HTML validator functionality that checks if valid markup is provided, including checks like 'are all <tags> closed'.

So I vote to just use `HTML` as keyword.

**Comment by sjcjoosten** [comment]
I'd be happy to use ``HTML`` as a keyword for validated HTML, and ``RAWHTML`` as a keyword for unvalidated HTML. From what Han is saying, the HTML will not be validated, so I'd vote for ``RAWHTML``. From what Michiel is saying, the HTML is validated, so I'd vote for ``HTML``.

**Comment by stefjoosten** [comment]
Having both `HTML` and `RAWHTML` gives the programmer a choice. However, we don't want to let a programmer choose between validated and unvalidated HTML in the source code of an Ampersand script. This choice is made by the compiler constructors and not by the programmer.

From this perspective, I vote for `HTML` as label. Let us hope we can implement HTML validation soon and let us trust users to use HTML diligently in the meantime.
