### ISSUE TITLE
Strange text coloring switch in VSCode terminal window

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1133]
When using the command `Ampersand: start checker` in VSCode, it creates a terminal in which subsequently the daemon is being started. The problem here is that after a few lines of 'ordinary' texts, which demonstrate that the VSCode settings themselves seem to be ok, the colours are changed (specifically, it seems that the background color is changed to yellow). This makes the output useless, i.e. virtually unreadable. Here is a screenshot of what happens:

![image](https://user-images.githubusercontent.com/8522589/103528721-bbe61600-4e84-11eb-895e-0afad020d2a0.png)

This does not seem to be an issue of VSCode, or the terminal, because the initial output is ok (black on white). 

When I provide it a `.ampersand` file as the error suggests, the output is immediately white-on-yellow (=useless).

Could it be that the daemon is trying to do 'pretty/coloured' text output? If so, please undo that.

**Comment by hanjoosten** [comment]
The ampersand daemon died with an exitstate. The reason for that is reported as an error, even suggesting what you should do. That's ok. 
So you provided the .ampersand file, as requested. Note that at that moment, before the daemon is restarted, the terminal is in a colored state. This time because of the coloring of the exitfailure, but it could also be cause by some other command you gave, not ampersand-related at all. 

My exprience with this behaviour is that if you do some modifications in your files, pretty soon the newly started daemon will sync with the colors again, so you'll be fine. Maybe not strait away, but after 2 or 3 changes it normally is. 
(You could even fiddle around, try to see the daemon will last in the yellow/white state. My guess is it whont take long). 

There are only very few reasons that the daemon will exit. The above one is the only one I can think of now. 

If all above 'tricks' don't work, just close that terminal before you restart the daemon.

**Comment by RieksJ** [comment]
Here is another screenshot: 

![image](https://user-images.githubusercontent.com/8522589/103549415-9e767380-4ea7-11eb-8a63-e1fa73af2005.png)

It shows that I restart a clean command shell. Then I manually run the daemon and this daemon does not find any errors. Still, the output is colored. And this continues to be the case. Your guess that it whont take long is contradicted with my experience.

**Comment by hanjoosten** [comment]
It is likely that the terminal detection doesn't work on your system. In vscode this is [configurable](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration). The terminal you are using looks like cmd. I'd recomend to use powershell on windows, for cmd is *really* very old.

There is also a switch in Ampersand that prevents autodetection of the terminal: `--[no-]terminal` . You might want to fiddle around with this. 

let us know if above solved this for you.

**Comment by RieksJ** [comment]
CMD.exe and powershell both suffer from this. The `--no-terminal` option didn't resolve the issue. 

The '[configurable](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration)' was indirectly helpful: when scrolling somewhat further to the '[Next Steps](https://code.visualstudio.com/docs/editor/integrated-terminal#_next-steps)' section it suggested I look at [Mastering VS Code's Terminal](https://www.growingwiththeweb.com/2017/03/mastering-vscodes-terminal.html) - an external blog with plenty of power user tips for the terminal. That showed me how to hard-configure terminal colors, and changing 'yellow' to something appropriate is a workaround that works for me.
