### ISSUE TITLE
Dependency in Composer for wikimedia/composer-merge-plugin requires update

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1161]
# What happened
I ran a Docker build for an ampersand application of my own, to run it locally. When building it, I got the following error message:
```
Step 12/24 : RUN composer install --prefer-dist --no-dev --profile
 ---> Running in e168f006df06
[8.3MiB/0.00s] Installing dependencies from lock file
[8.4MiB/0.01s] Verifying lock file contents can be installed on current platform.
[9.6MiB/0.02s] Your lock file does not contain a compatible set of packages. Please run composer update.
[9.6MiB/0.02s] 
  Problem 1
    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
[9.2MiB/0.02s] Memory usage: 9.23MiB (peak: 9.62MiB), time: 0.02s
ERROR: Service 'voortbrenging' failed to build : The command '/bin/sh -c composer install --prefer-dist --no-dev --profile' returned a non-zero code: 2
```
I did what is asked and added a line `RUN composer update` in the Dockerfile. With this result:
```
Step 12/25 : RUN composer update
 ---> Running in 112212de1f1d
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - wikimedia/composer-merge-plugin[v1.3.0, ..., v1.4.1] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires wikimedia/composer-merge-plugin ^1.3 -> satisfiable by wikimedia/composer-merge-plugin[v1.3.0, v1.3.1, v1.4.0, v1.4.1].

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
ERROR: Service 'voortbrenging' failed to build : The command '/bin/sh -c composer update' returned a non-zero code: 2
```
I looked in `composer.json` and saw on line 16:
```
          "wikimedia/composer-merge-plugin": "^1.3",
```
I changed this to:
```
          "wikimedia/composer-merge-plugin": "^2.0",
```
The result is that it works, but I don't know why.

@Michiel-s  Could you look into this and provide a sustainable solution for all of us? I'm hesitant to commit this change of `composer.json` to the repo because I don't know what I'm doing.

**Comment by RieksJ** [comment]
The log you provide says:
~~~
Root composer.json requires wikimedia/composer-merge-plugin ^1.3 -> satisfiable by wikimedia/composer-merge-plugin[v1.3.0, v1.3.1, v1.4.0, v1.4.1]
~~~
which suggests that 
~~~
"wikimedia/composer-merge-plugin": "^1.3"
~~~
won't match versions 2 and higher. That makes sense since a change in the major version number signals that the code for `composer-merge-plugin` is not backwards compatible. This may or may not be relevant to the code that you use the plugin for. That's up to you to check, and correct if need be. One way to do that is to update the version number as you did, and see if everything (still) works, which you say you did. So if everything still works (specifically the stuff that the merge-plugin is used for), you can close this issue.

**Comment by Michiel-s** [comment]
That package `composer-merge-plugin` is removed 8 months ago and part of release v1.7.1 of the prototype framework, see: ampersandtarski/prototype#28

I think you need to update the `FROM` base image in your Dockerfile...
