### ISSUE TITLE
Allowed boolean values

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1167]
This morning I noticed that importing a JSON file that worked last week no longer works, giving the following error:

![image](https://user-images.githubusercontent.com/8522589/114979438-272f8300-9e8b-11eb-8e8c-504cdf87dcf3.png)

The culprit is here:

![image](https://user-images.githubusercontent.com/8522589/114979542-52b26d80-9e8b-11eb-8e72-22e58867f465.png)

I have verified that this is caused by me upgrading from `prototype-framework:v1.9.0` to ``prototype-framework:v1.9.3`

To me, it is (obviously) OK to output a specific set of boolean values, and I currently do not care whether that is `true`, `True`, `TRUE`, or `1`. However, I would really like to see the input of boolean values be a bit 'forgiving'. 

Concretely this means that it should be ok to at least be able to write
- `true`, `True`, `TRUE` (i.e. `true` in a case-insensitive fashion), or `1`
- `false` (case-insensitive), or `0`

Please fix this.

**Comment by RieksJ** [comment]
Note though that the internal representation of booleans SHOULD be unambiguous, so that expressions such as `aBool;'True'` do not need to be formulated as `aBool;('true' \/ 'True' \/ 'TRUE' \/ 'OK')`. Therefore, boolean values in the internal data model MUST be constrained to (*documented!*) values, e.g. `True` and `False` (case sensitive). 

This issue only asks to be lenient when importing booleans from external sources, such as JSON objects.
I have not looked into any consequences this might or should have regarding excel-files imports.

**Comment by stefjoosten** [comment]
Atoms in Ampersand are case sensitive. That's bad news, @RieksJ ! I'm sorry about that, but it is a choice in Ampersand and design choices in a language have to be implemented for 100%. For good reasons, by the way, because every exception in any design rule creates maintenance work and technical debt in the future for which we have no resources. This is a dear lesson learnt in other projects too!

Slightly better is the news that JSON messages are not defined in the language (yet, but keep track of issue #1164. They will one day...) As long as the value in a key-value pair of JSON is not designated as an atom, it must be *translated* to an atom before telling Ampersand. In that translation you could transform it to an atom. However, once JSON messages are used inside the realm of Ampersand, this kite won't fly either.

So the real question is where to specify the semantics of  (exec-engine rules yet to be added):
```
RULE I[RieksJBool]=('true' \/ 'True' \/ 'TRUE' \/ 'OK'\/'false' \/ 'False' \/ 'FALSE' \/ 'NOK')
RELATION translate[RieksJBool*Bool] [UNI,TOT]
POPULATION translate[RieksJBool*Bool] CONTAINS
  [ ("true", "True")
  , ("True", "True")
  , ("TRUE", "True")
  , ("OK", "True")
  , ("false", "False")
  , ("False", "False")
  , ("FALSE", "False")
  , ("NOK", "False")
  ]
```
I think the Ampersand compiler is not the place to do it.
Maybe the prototype, but I'm not in favor of that too...

**Comment by RieksJ** [comment]
I would like to emphasize what I wrote: "However, I would really like to see the *input* of boolean values be a bit 'forgiving'". I'm not talking about internal structure. I would like imports (particularly JSON, but I imagine that would go for Excels as well) to accept different syntax, and map that to the boolean values that Ampersand uses internally.

Such translations are very common. Stripping leading zeroes off of integers, disregarding the thousands-separators in floats or integers, converting E-notation to a float, converting various date and/or time formats, this is nothing new. All I suggest to have something similar for booleans. And obviously, Ampersand is not the place to do that as it has its own, well-defined internal data structures (and rightfully so). But it IS something for code that does importing, i.e.:
- INTERFACEs that take user input;
- APIs that take machine input (e.g. JSONs);
- Excel importers
- ... (whatever someone may think of later as a good import mechanism).

**Comment by hanjoosten** [comment]
We have technical type for Booleans. Use the REPRESENT statement to make your string a boolean. Then, the correct JSON is produced.

**Comment by stefjoosten** [comment]
Let me make one additional to Rieks' plea. There comes a point where we'll want to read JSON for adding population to an Ampersand script. The purpose of that is similar to reading a .xlsx-file or a .archimate-file. The problem Rieks signals is new, however: In case of .xlsx we know how Excel writes its values so we can come pretty close to reading all conceivable .xslx-files. The same is true for .archimate-files. In case of JSON we don't always know which application it comes from. We must solely rely on the .JSON standards to see how JSON writes booleans. If it allows multiple ways of writing a Boolean, we must parse that. If the standards say nothing about it, we have an interest in parsing a wide range of possible values.

I missed this point earlier on in the discussion because I missed Rieks's purpose (i.e. reading population into an Ampersand script) so I want to add it here. (Sorry for my initial misinterpreting of your intentions, @Rieksj. Reading is never easy... 😁) For this specific purpose, arguments about the Ampersand syntax are irrelevant. This issue is about interpreting JSON-input, which we don't yet do in the compiler.

**Comment by RieksJ** [comment]
Thanks for mentioning this, Stef. By the way, the original post explicitly mentioned the framework (not the compiler). The JSON import is needed there e.g. for the (future) messaging extensions.
