### ISSUE TITLE
Specification of a/the MrgAtoms (Merge Atoms) function.

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#1170]
There are many use-cases in which a business application (app) asks the user to fill in a form that is, or is going to be, related to a case-file. I'm currently exploring a new way for how to do this, using a [person registration application](https://github.com/AmpersandTarski/Ampersand/files/6396566/exploration.txt) - this is working code so you can try it yourself.

To this end, I define a concept NP (Natural Person) that has all the necessary relations. Also, it has two specializations:
1. `NPReg` is an NP that is officially registered (consolidated), and therefor MUST comply with the associated business rules. It comes with a mechanism that can convert it into an `NPForm`, thus allowing it to be edited.
2. `NPForm` is an NP that is being constructed and/or edited, and therefore does not need to satisfy these rules. It must have mechanisms to convert it into an `NPReg` (once it satisfies the rules for `NPReg`s).

This issue concerns part of the latter mechanism, i.e. when an `NPForm` has been created, and then filled in. For example, if an `NPReg` exists for `Rieks Joosten`, and the user creates an `NPForm` (which is *another* NP), and then fills in `Rieks` and `Joosten` as first- and last name respectively. That would mean we end up with `NP`s (one `NPForm` and one `NPReg`) that have attributes for a single real-world person.

Situations such as these are what the function [`MrgAtoms`](https://github.com/AmpersandTarski/prototype/blob/development/src/Ampersand/Core/Concept.php#L742-L810) has been created for.

However, the current implementation of `MrgAtoms` produces errors that show it doesn't seem to know how to handle situations such as these (in the demo, you can see this when you check the 'OK' box of `NPForm`: 'np_e'. 

![image](https://user-images.githubusercontent.com/8522589/116509425-8cd83200-a8c3-11eb-9931-a33c8c7d56ec.png)

I would like to see:
- a proper specification for `MrgAtoms` that shows how to deal with atoms in the same classification tree (particularly the situation where these atoms are siblings, as that is what I need)
- a corresponding implementation for `MrgAtoms`, that makes the demo work

**Comment by hanjoosten** [comment]
Without knowing the exact details, it seems to me that this specialisation of NP's is a false one. The fact that an NP is consolidated or not can be specified with a PROP relation. However, I can see that in doing so you would have to include that relation in lots of expressions all over the place, that now must include that PROP relation. If we had reusable expressions (which we currently do not have unfortunatly), that would solve the problem.

**Comment by RieksJ** [comment]
You are right. PROP-relations and specializations are very, very similar (in fact, it is how they are implemented). I couldn't tell whether or not "this specialisation of NP's is a false one", because I have no clue what this means (or what 'a true one' would be). 

I do know that I've been thinking quite a bit about this, and I've done various implementations. All of them were quite tedious to reuse and maintain. I think this is the best way of doing it from the perspective of reuse and maintenance (once `MrgAtoms` gets fixed), which is what matters to *me*. And we need this kind of re-use if we're going to input such objects through messages/streams, or (verifiable) credentials.

**Comment by stefjoosten** [comment]
I would like to see some diagnostic analysis first, because otherwise five persons would have to do that analysis.

For instance: you claim that NPReg and NPForm are both NP. So they are in the same classification tree. Yet, Ampersand claims that they are not. That is inconsistent. So what is the situation here? How can you be sure that MrgAtoms is to blame?

**Comment by RieksJ** [comment]
Note that the amperand source has `CLASSIFY NPForm, NPReg ISA NP`, so they are in the same classification tree. It is not Ampersand that claims they are not, but it is the `MrgAtoms` functions, as shown in the red bar of the screenshot.

**Comment by sjcjoosten** [comment]
> You are right. PROP-relations and specializations are very, very similar (in fact, it is how they are implemented).

This means that you managed to get this script working through a workaround using PROP relations?

> I couldn't tell whether or not "this specialisation of NP's is a false one", because I have no clue what this means

I believe Han is referring to a suggestion on when and when not to use an ISA, which is that when referring to properties that cannot change, an ISA may be used (like whether a resource is an office or furniture), but when referring to properties that do change, an ISA should not be used (like whether a form is completed or not), but a relation should be used instead.

Regardless of whether the script is wrong (I'd like for your script to be allowed but I'd also like MrgAtoms to be commutative - i.e. swapping the arguments does not change what MrgAtoms does - and those two things cannot be true at the same time), I agree that the message in the red bar is wrong.

I don't know how MrgAtoms is implemented right now, but I would suggest that if it is given two atoms from different concepts, it should choose the most specific of the two, if that exists. In your example, there is no most specific atom, which would mean that this script will not work in such an implementation. On the upside, it does keep MrgAtoms commutative.

As a middle-ground way of workaround, perhaps you do not need to distinguish NPForm and NP: any form that satisfies all rules can become registered.

**Comment by sjcjoosten** [comment]
Here's a script for which things will be impossible:

```
CLASSIFY X, Y ISA A
r       :: X * B       [TOT]
s       :: Y * B       [TOT]
```

Here, merging an atom of type X with an atom of type Y will always fail, in the sense that information will be lost: either all links from the `r` or the `s` relation are lost by typing rules, but that's never something that MrgAtoms is supposed to do.

Here's a script for which the situation is better:

```
CLASSIFY X ISA Y
r       :: X * B       [TOT]
s       :: Y * B       [TOT]
```

Now, if we merge some atom of type X with an atom of type Y, no information will be lost, as long as the atom that is created is of the most specific kind (i.e. X).

Things are a bit more difficult if r and s are also ``UNI``, but here the 'should not be in conflict' idea should save us: if the two atoms that are merged violate the ``UNI`` rule, the user will get an error saying that these cannot be merged (in your example, first and last name should match or merging is not allowed).

Given your last post, I lean towards saying that MrgAtoms should be allowed if one of the concepts is the most specific, but that you'll need to model things with an explicit ClearConcept step if you wish to generalize (this would be the step in which the information in `r` or `s` will be lost).

**Comment by RieksJ** [comment]
So the pattern for doing stuff could be something like this (you can add multiplicities as you like):
~~~
CLASSIFY X, Y ISA A
aB   :: A * B
aC   :: A * C
xMDX :: X * MDX 
yMDY :: Y * MDY
~~~
The MDX and MDY can be seen as meta-data for A-atoms, where MDX is the metadata you need if the atom is in state X, and MDY for those in state Y.  When changing state, the meta data would get lost, and if you don't want that, you should make it a relation with A as its source concept. Cool.

**Comment by stefjoosten** [comment]
What about this:
```Ampersand
CLASSIFY X, Y ISA A
CLASSIFY B ISA X
CLASSIFY B ISA Y
```
Now the mergeAtom of an X-atom and a Y-atom makes sense again. And it is commutative (under the known conditions). 
We now have a "diamond shaped" typology. That is: `X` and `Y` have a lub and a glb so they are contained in a lattice.

I ran Rieks' example in rap.cs.ou.nl and changed the typology to:
```Ampersand
CLASSIFY NPForm, NPReg ISA NP
CLASSIFY NPFormReg ISA NPForm
CLASSIFY NPFormReg ISA NPReg
```
The current implementation does not yield a `NPFormReg`. I still get the same message. A peek in the database shows this:
<img width="580" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/116654446-78f70380-a989-11eb-976c-18253eb21fcd.png">
I can imagine that we can make MrgAtoms work in this situation. It should yields a merged atom in `NPFormReg`.

This line of though proposes that MrgAtom works inside a lattice of concepts (i.e. both a lub and a glb are required). That means Rieks' example is wrong, but the error message should of course be more helpful. The fix is then made by the user who clamps his types in between a lub and glb concept.

**Comment by stefjoosten** [comment]
The previous post implies that we need a change in the back-end module [Concept.php](https://github.com/AmpersandTarski/prototype/blob/development/src/Ampersand/Core/Concept.php). First of all, we need functions `glb` and `lub`, to compute the greatest lower bound of two concepts and the least upper bound of two concepts.

```PHP
    /**  lub: least upper bound
     * Compute the most specific concept that generalizes $conceptA and $conceptB, if it exists.
     *
     * @param \Ampersand\Core\Concept $conceptA
     * @param \Ampersand\Core\Concept $conceptB
     * @return \Ampersand\Core\Concept
     */
    public function lub(Concept $conceptA, Concept $conceptB): Concept
    {
        
    }

    /**  glb: greatest lower bound
     * Compute the most generic concept that specializes $conceptA and $conceptB, if it exists.
     *
     * @param \Ampersand\Core\Concept $conceptA
     * @param \Ampersand\Core\Concept $conceptB
     * @return \Ampersand\Core\Concept
     */
    public function glb(Concept $conceptA, Concept $conceptB): Concept
    {
        
    }
```
Then we must adapt `MrgAtoms` to check for the existence of both glb and lub of its arguments.

**Comment by sjcjoosten** [comment]
I don't see how computing a glb and a lub of two atoms (if they exist) helps when merging atoms. Here is another problematic script:

```
CLASSIFY X, Y ISA A
CLASSIFY Z ISA X
CLASSIFY Z ISA Y
r       :: X * B       [TOT]
s       :: Y * B       [TOT]
t       :: Z * B       [TOT]
```

Again, merging an X and a Y-typed atom (let's call them x and y) would need to be of one of the types X, Y, Z or A. It cannot be of type X, Y or A, as then the relations r and s cannot both be stored. Unfortunately, it cannot be made of the type Z either, as then the relation t will be missing. Moreover, even without the problematic TOT on t, neither x nor y is of type Z, so making it of type Z means that we're inventing information out of thin air. (Imagine A=Creature, X=Mammal, Y=Gray, Z=elephant, and x,y are gray mice, and we have no concept for Mouse - as otherwise Z would not be a glb.)

Rieks' [reply](https://github.com/AmpersandTarski/Ampersand/issues/1170#issuecomment-829790964) is spot on, though I hope that the generalization step (in which information gets lost) can remain separate from the merge step (in which no information gets lost or added). We may have to discuss both steps here, so far I have only addressed the merge step and I've assumed that that's what Stef was referring to too.

**Comment by stefjoosten** [comment]
@sjcjoosten, Please clarify "*Unfortunately, it cannot be made of the type Z either, as then the relation t will be missing.*"

I would say that every `z` in `Z` may occur in the domain of `t`, `r`, and `s`. In fact, it *must* occur in all three relations, as they are total. So why can't the `MergeAtoms(x,y)` yield a new atom of type `Z`?

**Comment by stefjoosten** [comment]
@RieksJ replied:
> So the pattern for doing stuff could be something like this (you can add multiplicities as you like):
> 
> ```
> CLASSIFY X, Y ISA A
> aB   :: A * B
> aC   :: A * C
> xMDX :: X * MDX 
> yMDY :: Y * MDY
> ```
> 
> The MDX and MDY can be seen as meta-data for A-atoms, where MDX is the metadata you need if the atom is in state X, and MDY for those in state Y. When changing state, the meta data would get lost, and if you don't want that, you should make it a relation with A as its source concept. Cool.

I may have a problem with this. Are you letting an atom change from one concept to another? That would correspond to an apple becoming an orange over time. If we want to do that, we will one day need a dynamic-type system instead of the current static one. We would also need semantics to state what happens to pairs in which this atom occurs. We'd have an entirely different language. This is also why I teach my students that `Student ISA Person` is probably a modeling error because a person might be a student today, a customer tomorrow, and an employee on yet another occasion.  Dynamically changing behavior should always be modeled in relations because we have instruments to control and manipulate the contents of relations. That is in the very nature of the relational algebra.
@RieksJ can you elaborate on the intention of your reply?

**Comment by sjcjoosten** [comment]
> @sjcjoosten, Please clarify "_Unfortunately, it cannot be made of the type Z either, as then the relation t will be missing._"
> 
> I would say that every `z` in `Z` may occur in the domain of `t`, `r`, and `s`. In fact, it _must_ occur in all three relations, as they are total. So why can't the `MergeAtoms(x,y)` yield a new atom of type `Z`?

Because neither x nor y occur in the domain of t (by their type, they cannot).

**Comment by stefjoosten** [comment]
@sjcjoosten, I still don't understand. Maybe my mind is stuck (you know how I am...). So let me illustrate my thoughts. Let me show (by example) how I think the result of `MrgAtoms(x,y)` can be made of type `Z`:
```Ampersand
CLASSIFY X, Y ISA A
CLASSIFY Z ISA X
CLASSIFY Z ISA Y
RELATION p[A*K] [UNI]
 = [ ("a", "k") ]
RELATION r[X*K] [UNI]
 = [ ("x", "k") ]
RELATION s[Y*K] [UNI]
 = [ ("y", "k") ]
RELATION t[Z*K] [UNI]
 = [ ("z", "k") ]
```
Just to help make things concrete, I have included a shot of the database content:
![afbeelding](https://user-images.githubusercontent.com/275768/116777949-8dadc700-aa6f-11eb-8779-b673751791c7.png)

I would expect that `MrgAtoms(x,y)` yields a new atom (say `m`) and it leaves the database in the following state:

![afbeelding](https://user-images.githubusercontent.com/275768/116778017-e5e4c900-aa6f-11eb-8858-d31b6bbf2ef2.png)

please retry to explain to me why the result of `MrgAtoms(x,y)` cannot be made of the type `Z`.

**Comment by sjcjoosten** [comment]
My fundamental issue with this is that there is no rule that says that if something is of type Y and of type X, it must also be of type Z. To see when this is problematic, perhaps look at my elephant example again.
If there is a fundamental issue, I should be able to demonstrate that this runs in to trouble in the implementation. Indeed it does: try making the relation t total as in my example (rather than UNI) and let me know what MrgAtoms is supposed to do.

**Comment by hanjoosten** [comment]
I think there are two distinct questions to answer with merge:

1. What type will the resulting atom have?
2. It seems logical to me that the links should be calculated by substitution. All links in the original context where one of the original atoms is either source atom or target atom (or both), the original atoms in those links should be substituted with the resulting atom. Depending on the answer on my first question, it could be possible that there are 'invalid' links. (links in relations that do not exist).

**Comment by sjcjoosten** [comment]
My and Stef's answers to Han's first question differ. My answer is: the most specific of the two, assuming they are comparable (otherwise a merge is not allowed). Stef's answer to Han's first question is: the greatest lower bound of the two, assuming this exists (otherwise a merge is not allowed).

To Han's second question, both Stef and my answer to the first question avoid invalid links from occurring, by how specialization works.

**Comment by stefjoosten** [comment]
> My fundamental issue with this is that there is no rule that says that if something is of type Y and of type X, it must also be of type Z. To see when this is problematic, perhaps look at my elephant example again.
> If there is a fundamental issue, I should be able to demonstrate that this runs in to trouble in the implementation. Indeed it does: try making the relation t total as in my example (rather than UNI) and let me know what MrgAtoms is supposed to do.

OK. I have adapted the script to make every relation total. To compile it we need some extra contents in the relations `p`, `r`, and `s`.
```Ampersand
CLASSIFY X, Y ISA A
CLASSIFY Z ISA X
CLASSIFY Z ISA Y
RELATION p[A*K] [UNI,TOT]
 = [ ("a", "p"), ("x", "p"), ("y", "p"), ("z", "p") ]
RELATION r[X*K] [UNI,TOT]
 = [ ("x", "r"), ("z", "r") ]
RELATION s[Y*K] [UNI,TOT]
 = [ ("y", "s"), ("z", "s") ]
RELATION t[Z*K] [UNI,TOT]
 = [ ("z", "t") ]
```
This is the initial state in the database:
![afbeelding](https://user-images.githubusercontent.com/275768/116803740-a1face00-ab1a-11eb-822b-7875eec3d414.png)
I would expect the result of `MrgAtoms(x,y)` to be:
![afbeelding](https://user-images.githubusercontent.com/275768/116804056-171ad300-ab1c-11eb-9ecd-030728b592f2.png)
And as a result, I expect a violation of the totality of t.
Nothing weird about that. We know how to deal with such violations.

**Comment by stefjoosten** [comment]
As for the gray mice: this is a matter of modeling. If the modeler defines Elephant to be the glb of Gray and Mammal, she might be in for a surprise to see that a grey mouse appears to be an elephant. I would say that is a modeling error rather than an issue with MrgAtoms.

**Comment by RieksJ** [comment]
@stefjoosten you are confusing relation algebra itself with its applications. Functions such as MrgAtoms, SetConcept etc. Are like InsAtom, InsPair and the like. They are not like operators such as ;, !, =, etc. Which do not change populations. 

If a developer decides that in his world an apple can be an orange, that's his call to make. He may live in a world that seems magical to you. 

But of course you are right to teach students that lemons cannot become oranges as this is what the vast majority of people agree is true.

**Comment by RieksJ** [comment]
@sjcjoosten I agree that it is best to keep changes in concept membership distinct from MrgAtoms. Keeps things rather tidy.

**Comment by stefjoosten** [comment]
@RieksJ That is a different issue. A fundamental principle in Ampersand is that the only property of an atom that matters is its equality. It is the only thing the relation algebra uses. The type of an atom, as we discuss it, is not a property of an atom. It is merely a consequence of the relation/concept in which it occurs. If you want to attach meaning to atoms, the only way to do that in relation algebra is by means of relations. So if you want to turn Lemons into Pineapples, your best choice is to turn away from Ampersand. It is just not the formalism for that sort of thing. You will need a formalism with very different features, such as attributes, dynamic type checking, a.o.

**Comment by RieksJ** [comment]
And having said that: MrgAtoms is left with the problem that if you merge two atoms a1 and a2 of the same concept A and there is a relation r::A*B [UNI] with population (a1,b1) (a2,b2), then it is ambiguous what MrgAtoms should do. The cuurent implementation would have better be called MrgAtomInto or such.

**Comment by RieksJ** [comment]
@stefjoosten what I said is that there may be a context, inconceivable by you but perhaps not by others, in which light may sometimes be a particle and in some other cases a wave, but never both. In any case, I am more of an engineer than a mathematician and it may be therefore that I see no fundamental difference between being a member of a set of which each atom has   a same property, or having a property that other atoms in a set also have.

**Comment by hanjoosten** [comment]
I like [the 'Elephant' example by Bas](https://github.com/AmpersandTarski/Ampersand/issues/1170#issuecomment-830195780). It demonstrates that in general you cannot pick the lub without adding information. 
It is also shows that you cannot pick the glb without loosing information. 
As I see it now, the discussion upto now could be summarised as follows:

1. We are looking for some practical form of merging of atoms, and we are trying to formalize such action.
2. We agree that the concepts of the involved atoms must be in the same typology.
3. If the involved atoms are in exactly the same concept, the resulting concept is trivial. (will merging make sence at all?) 
4. If the involved atoms are in different concepts, a decision has to be made about the resulting concept. This could either be specified explicitly by the Ampersand modeller or in some automatic way. 
5. As shown by the counterexample, we cannot automatically pick the lub nor the glb. 
6. It is problematic to automatically (randomly) choose the concept of one of the involved atoms, because the action would not be communitive. 

The above leads to the conclusion that merging is either restricted to atoms of the exact same concept, or can only be formalized when the resulting concept is explicitly specified. The consequence of potentially adding or loosing information is then up to the modeller.

**Comment by stefjoosten** [comment]
@hanjoosten, maybe you want to refresh your theory.
# 1. lub and glb
A lub or a glb are not things you pick. They are defined in a partial order, in this case the partial order of classification (ISA) of concepts. A lub or a glb either exists or it doesn't. If you say
```Ampersand
CLASSIFY X, Y ISA A
```
then A is an upper bound of X and Y because X<=A and Y<=A. In this system (with just X, Y, and A) X and Y have no lower bound.
To add a glb, the user must specify:
```Ampersand
CLASSIFY X, Y ISA A
CLASSIFY Z ISA X
CLASSIFY Z ISA Y
```
Now X and Y have a glb (i.e. Z) and a glb (i.e. A)
Note that in both examples, the glb of A and Y is Y.
# Ad 4
You write: "*If the involved atoms are in different concepts, a decision has to be made about the resulting concept.*" 
If the resulting concept is the glb, then there is little choice. If the modeler has specified a glb (e.g. Z) it exists. If the modeler has not specified a glb, Ampersand should not invent one.
# ad 5
It doesn't make sense to talk about "picking" a glb. So indeed, we cannot do that.
# your conclusion
I agree fully. We might restrict merging to atoms of the same concept. Or we demand that the user specifies a glb in his CLASSIFY-statements. Ampersand cannot invent the concept if the modeler fails to specify the glb.

My proposal above shows how I think we can do the second option.

**Comment by hanjoosten** [comment]
There is no need to refresh my theory. There seems to be something wrong in the way I described my thoughts. I'll try to clearify: By 'picking' I mean to answer the question of what concept the resulting atom should be exactly. Please re-read the above with this intention in mind.

**Comment by sjcjoosten** [comment]
> As for the gray mice: this is a matter of modeling. If the modeler defines Elephant to be the glb of Gray and Mammal, she might be in for a surprise to see that a grey mouse appears to be an elephant. I would say that is a modeling error rather than an issue with MrgAtoms.

Can you point out the error, that is: which of the rules do you believe is not true?

**Comment by hanjoosten** [comment]
@stefjoosten writes:

> I agree fully. We might restrict merging to atoms of the same concept. Or we demand that the user specifies a glb in his CLASSIFY-statements. Ampersand cannot invent the concept if the modeler fails to specify the glb.

This suggests that the glb could be picked automatically (if it exists) as the concept of the resulting atom. I disagree, for in that way information is lost: In the elephant example, that would result in an atom in Creature, and we do no longer know anything about the grey colour or it being a Mammal. 
The point is that when we allow two atoms in different concepts to be merged, we need syntax to define the merge action that includes the explicit way to define the resulting concept.

**Comment by stefjoosten** [comment]
After discussing this with Bas, let me try to bring this design issue to a close.

So far, we have discussed three options for `MrgAtoms(x:Atom,X:Concept,y:Atom,Y:Concept)` with `X` is a concept that contains `x` and  `Y` is a concept that contains `y`. The three options differ only wrt their precondition. Operationally these three are the same, so let me suffice by stating that atoms `x` and `y` are substituted by one atom (say `z`) in every pair that contains `x` or `y`. Let's focus on the difference in precondition and what this means for the user. (I use the symbol ![\preceq](https://latex.codecogs.com/svg.latex?\preceq) for inclusion of concepts: ![X\preceq{}A](https://latex.codecogs.com/svg.latex?X\preceq{}A) means `CLASSIFY X ISA A`).
option 1: ![X=Y](https://latex.codecogs.com/svg.latex?X=Y)
option 2: ![X\preceq{}Y](https://latex.codecogs.com/svg.latex?X\preceq{}Y)
option 3: ![(\exists{}Z:Z\preceq{}X\wedge{}Z\preceq{}Y)\wedge(\exists{}A:X\preceq{}A\wedge{}Y\preceq{}A)](https://latex.codecogs.com/svg.latex?(\exists{}Z:Z\preceq{}X\wedge{}Z\preceq{}Y)\wedge(\exists{}A:X\preceq{}A\wedge{}Y\preceq{}A))
Option 1 is included by option 2 and option 2 is included by option 3.

Option 1 (Han's fallback option) is easy to explain and comprehend. However, it does not solve Rieks' problem.
Option 2 (suggested by Bas) does solve Rieks' problem, although Rieks has to make a change in his program. Rieks sounds happy with that change (see above).
Option 3 (suggested by Stef) also solves Rieks' problem, still requiring Rieks to change his program. He can do it in the same way as with option 2 because option 3 includes option 2. Option 3 gives Rieks another way to also solve the problem. He can define a new concept (say `Z`) that is both `NPForm` and `NPReg`.

I discard option 1 because it is unnecessarily restrictive. We can do better. And Rieks' use case shows that we need to do better.

I discard option 3 because it causes confusion to the user if she defines Elephant as the glb of X and Y only to discover that a grey mouse is an elephant (see the example above). As Ampersand will give no help with this problem I think it is reasonable to prevent it.

Option 2 offers good, explainable semantics for MrgAtoms, so let's decide on that.

### Implementation
The current implementation of `MrgAtom` needs to be changed only where it checks its precondition. It should give a meaningful error message if the precondition is not met, e.g. `Cannot merge an atom from concept NPReg with an atom of concept NPForm because neither one includes the other (try adding CLASSIFY NPReg ISA NPForm or vice-versa)`

This issue can be closed when the implementation of MrgAtom is adapted and verified.

**Comment by Michiel-s** [comment]
Hi @stefjoosten, @hanjoosten, @sjcjoosten,

Sorry for my late reply here.

1. I agree that the error message is incorrect. The two specializations `NPReg` and `NPForm` are in the same classification tree. I'll adapt the error message according to Stefs suggestion: `Cannot merge an atom from concept NPReg with an atom of concept NPForm because neither one includes the other (try adding CLASSIFY NPReg ISA NPForm or vice-versa)`

2. A practical solution for you problem @RieksJ, is to first call `ClearConcept(NPForm,<formid>)`. This is the opposite of `SetConcept` and will remove the atom from the NPForm set. In this case that is allowed because `NPForm ISA NP`. Keep in mind that you will loose all links that are specifically for NPForm. Now you can call `MergeAtoms`. Both can be called in the same VIOLATION statement.

Hope this helps.
