### ISSUE TITLE
A scalar should not be allowed to be the source of a univalent relation

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1206]
# What happened
I noticed that the Ampersand compiler allows me to use a BIGALPHANUMERIC as the source of a univalent relation. I compiled the following script and generated a prototype from it.
```Ampersand
CONTEXT "Issue1206"

REPRESENT B TYPE BIGALPHANUMERIC

RELATION r[A*B]

-- The atom of concept B has length 12*26 = 312 characters, so it will not fit in an OBJECT, which is VARCHAR(255).
POPULATION r[A*B] CONTAINS
 [("1", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz")]

RELATION s[B*C] [UNI]

ENDCONTEXT
```
Upon installing the database, the database produces an error message:
![image](https://user-images.githubusercontent.com/275768/131000183-6081e874-f899-4177-b20f-bc8227e9b7f6.png)
# Request
Instead of this runtime error, I would like to see a compile-time error:
```
Relation s may not be UNI because B does not have the technical type OBJECT.
```

**Comment by Michiel-s** [comment]
## Analysis
Because I couldn't believe that this issue here is actually a bug/problem, I started from scratch. I took the script @stefjoosten put in his description:

```
CONTEXT "Issue1206"

REPRESENT B TYPE BIGALPHANUMERIC

RELATION r[A*B]

-- The atom of concept B has length 12*26 = 312 characters, so it will not fit in an OBJECT, which is VARCHAR(255).
POPULATION r[A*B] CONTAINS
 [("1", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz")]

RELATION s[B*C] [UNI]

ENDCONTEXT
```

I generated the prototype and looked at the generated SQL tables. Notice that the relation `r[A*B]` does result in a MariaDB `TEXT` column which we configured for our `BIGALPHANUMERIC` types.
```sql
CREATE TABLE "r"
     ( "A" VARCHAR(255) NOT NULL /* OBJECT */
     , "B" TEXT NOT NULL /* BIGALPHANUMERIC */
     , "ts_insertupdate" TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
     ) ENGINE     = InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_BIN
     , ROW_FORMAT = DYNAMIC
;
```

## My conclusion
Then I ran the prototype and installed the database. All fine! No issues here. I think we can close this issue.

## What could be the problem that Stef was experiencing
What I think that happened is that you first had the script, without the represent type:
```adl
RELATION r[A*B]
```
You than installed the database. Experienced the problem with the `data entry too long`. Adapted the script
```adl
RELATION r[A*B]
REPRESENT B TYPE BIGALPHANUMERIC
```
**But didn't reinstalled the database** or experienced a problem/issue with reinstalling.

But that doesn't provide an explanation for the fact that the concept table for B did show the `Text` type, while table for `r` didn't.   Strange. @stefjoosten, could you just try again from scratch and see what the output is.

**Comment by stefjoosten** [comment]
Will do...

**Comment by hanjoosten** [comment]
@stefjoosten, What was the outcome?

**Comment by stefjoosten** [comment]
This is the outcome: Michiel was right. I made a mistake.

Nevertheless, we should keep allowing scalars to be the source of a univalent relation. But we should implement that relation as a binary table instead of a wide table if the key field might become too long (as is the case with BIGALPHANUMERIC).
