### ISSUE TITLE
Warn when a reinstall of the database is required

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#1208]
When an .adl script is modified, that previously was used to generate a database, that existing database can become invalid. Previously, we had a warning that popped up at runtime. However, in a docker environment, that implementation has bitrotted.

I spoke about this with @Michiel-s . The solution is to write the generated hash into a specific database table. Currently, it is written in a file, but that doesn't work any longer with docker.

**Comment by Michiel-s** [comment]
I can confirm now that this issue is solved with the two PRs merged above.

When not in production mode (=default) the user gets this warning message: 
![image](https://user-images.githubusercontent.com/7961582/139815629-2e92eebf-47eb-4ade-9735-6d4a2bf88ed0.png)

A reinstall of the application will do the trick. If you manually updated the database tables, you can also register the new checksum by doing a GET request to `GET /api/v1/admin/installer/checksum/update`.

The model history is then updated in the special table `__ampersand_model_history__`. E.g. like this one:
![image](https://user-images.githubusercontent.com/7961582/139816163-586b64bc-6702-4a19-920f-5779ec2ad9c1.png)
