### ISSUE TITLE
Runtime equality differs from Compile time equality

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1212]
# What happened
Experimenting with RAP, I got the following  result:
![image](https://user-images.githubusercontent.com/275768/132939560-69bdf17c-ff10-4349-8011-4a970b7de6f7.png)

The compiler recognizes the difference in the names of both interfaces and approves the script.
RAP, however, fails to recognize these interfaces as different and raises an error.

# What I expected
I expected the compiler and RAP to agree on basic matters like equivalence.

# Version of Ampersand that was used

# Steps to reproduce

1. Start RAP and create a new script
2. Type the following code
```Ampersand
   CONTEXT Issue

   INTERFACE "Foo" : "_SESSION"[SESSION] BOX [ id : I ]

   INTERFACE "Foo " : "_SESSION"[SESSION] BOX [ id : I ]

   ENDCONTEXT
```
3. Compile

**Comment by stefjoosten** [comment]
# Analysis
The rule in RAP that is responsible for the error message is:
```Ampersand
    RULE "IDENT Interface" : name;name~ /\ context[Interface*Context];context~ |- I
    VIOLATION (TXT "Interface ", SRC name, TXT " in context ", SRC context;name, TXT " is not unique.")
```

**Comment by hanjoosten** [comment]
This is directly related to #708

**Comment by stefjoosten** [comment]
No, @hanjoosten, #708 is a very different issue. It is about relation names. By the way, issue #708 has been resolved. Issue #1212 (this one) is about labels. I have a hunch that the runtime environment strips trailing spaces where it shouldn't, but I have not figured out (yet) how to prove it. I'd be curious to read  @Michiel-s 's take on this...

**Comment by hanjoosten** [comment]
Sure it is. This issue #1212 has the same root cause as has #708, #816, and maybe some others too. 

The problem here is the following:
We use strings to identify instances of all kind of things (Concepts, Relations, Rules, Interfaces etc.), and we use the Eq on strings to tell them apart. 

In theory, this should work splendedly. However, in practice, it doesn't. This is because we have to comply with restrictions layed upon us because we use stuff like databases, computer languages which simply have their own rules. Like it or not. 

This leaves us to the following options to choose from:

1) Keep using strings as identifiers and use the Eq on strings, without restricting the Ampersand modeller. In fact, this is about ignoring the restrictions the outside world has. That is what we do now.
2) Split identifiers into some restricted name (no whitespace, no non-printable characters, maximum of n characters etc.) and a label (unrestricted string). The actual realization of this will take some thought:
   * What price do we have to pay to be backwards compatible?
   * What restrictions are required for those names?
   * Do we need extra syntax for this?
   * Where do we want to use the Name, where the Lable?

The second option is what is intended with #708, which hasn't been adressed until now, let alone be solved.

**Comment by stefjoosten** [comment]
@hanjoosten, can you explain how your problem analysis relates to the phenomenon I saw here: The equality on interface labels as implemented by the compiler differs from the equality on interface labels as implemented by RAP.

**Comment by hanjoosten** [comment]
It's obvious. The strings in your .adl script are different: they have different lenght. However, somewhere in the backend, or during communication to the backend (The .json file, the database, some .html file or who knows where, the space at the end of the string gets lost.

I think it is undoable to find and solve every possible edge case up front. We have had all kind of problems with these identifying names all over the place. Issue #708 was introduced to have a separate Name (which has all kind of restrictions) and a Label. That will solve all these kind of issues in a systematic manner.

**Comment by Michiel-s** [comment]
Hi @stefjoosten, @hanjoosten,

The problem here is that MariaDB/Mysql strip trailing spaces in `WHERE .. = ..` clauses. So `SELECT 'Foo' = 'Foo '` returns 1 (true)

Let me take you along my thoughts and steps I did to figure this out.

1. First of all I see a IDENT violation. Where does it come from? We have 2 options: userland and/or any of the ADL scripts that are included in a build recipe. In your example clearly not userland, so I start searching for a IDENT statement for the concept Interface in the `AmpersandData` folder of the compiler repo. 

I found: `IDENT Interface: Interface(name,context[Interface*Context])` in `./AmpersandData/FormalAmpersand/Interfaces.adl`

2. Ok! But why is FormalAmpersand included in the build recipe here for RAP? That wasn't the case in my memory. Let me check the RAP repo.

Here I find that the code of ExecEngine function `CompileToNewVersion` is changed significantly in July by @stefjoosten. Next to the `ampersand check --build-recipe Proprotype` two other commands are also executed now:

* `ampersand documentation --no-text --format docx`
* `ampersand population --build-recipe Grid --output-format json` BINGO!

*I note that population script meta population is already loaded into RAP database here... do you really want that?`*

3. What does the build recipe `Grind` do? I see in `HasClasses.hs`:
```hs
-- | An enumeration type for building an FSpec in some common way
data Recipe =
    Standard  -- ^ Plain way of building. No fancy stuff. 
  | Grind     -- ^ Generates population for an atlas.
              --   It assumes that the database is fit to receive that population, as RAP does.
  | Prototype -- ^ A recipe to build a prototyping environment.
  | RAP       -- ^ A recipe to build a Repository for Ampersand Projects (RAP)
              --   The option 'RAP' generates a database that is fit to receive metamodels, so an Atlas is possible.
              --   The 'makeAtlas' button in RAP uses the 'Grind' option to populate the metamodel.
```
and in `CreateFspec.hs`
```hs
= case recipe of
              Standard  -> userScript
              Grind     -> do userScr   <- userScript
                              userFspc  <- pCtx2Fspec env userScr
                              return (grind transformersFormalAmpersand userFspc)
```

4. Ah.. there it is.. so let's check the transformers for FormalAmpersand. Especially the one for `RELATION name[Interface*InterfaceName]` in `Transformers.hs`:

```hs
transformersFormalAmpersand :: FSpec -> [Transformer]
transformersFormalAmpersand fSpec = map toTransformer [
  ...
     ,("name"                  , "Interface"             , "InterfaceName"
      , Set.fromList [Uni,Tot]
      , [ (dirtyId ifc, (PopAlphaNumeric . name) ifc)
        | ifc::Interface <- instanceList fSpec
        ]
      )
```

Looks good to me. The PopAlphanumeric constructor creates a `ScriptString` which is added to the Fspec. Not sure how that is outputted later. So now starts backwards.

5. The meta population from fspec is outputted to a json file when the command `--output-format json`
Let's run that command and see the output for the name and context

```json
{
    "relation": "name[Interface*InterfaceName]",
    "links": [
        {
            "src": "Foo",
            "tgt": "Foo"
        },
        {
            "src": "Foo_32_",
            "tgt": "Foo "
        }
    ]
},
{
    "relation": "context[Interface*Context]",
    "links": [
        {
            "src": "Foo",
            "tgt": "Issue"
        },
        {
            "src": "Foo_32_",
            "tgt": "Issue"
        }
    ]
},
```
All looks good. Two interfaces here in the same Context "Issue", one with name "Foo" and the other with "Foo "


6. Now lets look at the debug log of the RAP4 application right after the script  is compiled by RAP. I searched for 'Foo' and 'Foo '.

My eye was caught by this line: `[2021-09-14 10:33:28] CORE.DEBUG: Atom Foo [InterfaceName] already exists in concept [] {"request_id":"b7d9ca89c2"}`

That is strange.. Why is there already a 'Foo ' in that table? The query executed to check this is stated right above: `[2021-09-14 10:33:28] DATABASE.DEBUG: SELECT "InterfaceName" FROM "InterfaceName" WHERE "InterfaceName" = 'Foo ' [] {"request_id":"b7d9ca89c2"}`.

7. The value for 'Foo' was added earlier.. Could it be that MariaDB/Mysql strip trailing whitespace in WHERE clauses? A google search gave me the answer.. yes! That's not good.

You can try it yourselve:
`SELECT 'Foo' = 'Foo '` returns 1 (true)

Read more: https://stackoverflow.com/questions/3668996/trailing-whitespace-in-varchar-needs-to-be-considered-in-comparison

For MariaDB, 'Foo' and 'Foo ' are the same when querying. Hmm...


**Ok. we have the right analysis here.. now think of a good (and generic) solution to solve**. Let's first discuss this before implementing any changes

**Comment by hanjoosten** [comment]
@Michiel-s , Thanks for this nice analisys! I did some more google-ing, and found on some more evidence that MariaDB ignores trailing whitespace on purpose:

> When string values are compared, they are compared as if by the STRCMP function. STRCMP ignores trailing whitespace and may normalize characters and ignore case, depending on the collation in use.
Source: https://mariadb.com/kb/en/order-by/

I think that this is just what it is. We have to rely on a correct implementation of the database we use. 

Having said that, @stefjoosten and I had a conversation about #1212 (this issue). It resulted in a fresh issue, #1215.

**Comment by hanjoosten** [comment]
I went down this rabbithole even some further. The collation is a setting that influences equality of strings in a table. (See [details](https://mariadb.com/kb/en/supported-character-sets-and-collations/) here.) And [here](https://mariadb.com/kb/en/information-schema-collations-table/) I learned that there is choice how to cope with case sensitivity which makes sence, depending on the usecase. And since MariaDB 10.2 it is also possible to ignore (or not!) trailing whitespace.

**Comment by Michiel-s** [comment]
Reading a bit further... A quick-dirty solution is to use the `BINARY` cast in queries. E.g. changing the query above to `SELECT "InterfaceName" FROM "InterfaceName" WHERE "InterfaceName" = BINARY 'Foo '` However, that would require us to adapt all queries and also taking into account that not all column types support the binary casting. Let's not go that way.

A better solution is to look at the (default) collation of database and tables. Read https://dev.mysql.com/doc/refman/8.0/en/charset-collate.html.

Our installer (implemented in php) creates a new database using the following sql query
```sql
CREATE DATABASE {$this->dbName} DEFAULT CHARACTER SET UTF8
```
So the default character set is `UTF8` and the corresponding default collation is `utf8_general_ci`. See https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html

Our database table structures are generated in the compiler and set other default for the collation that overwrite the database default: `UTF8_BIN`.

E.g. structure for SESSION table:
```sql
CREATE TABLE "SESSION"
     ( "SESSION" VARCHAR(255) UNIQUE NOT NULL /* OBJECT */
     , PRIMARY KEY ("SESSION")
     , "ts_insertupdate" TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
     ) ENGINE     = InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_BIN
     , ROW_FORMAT = DYNAMIC
;
```

This is good, because the UTF8_BIN collation already makes sure that we have case sensitive queries.

It doesn't prevent the trailing whitespace issue. Enter the `nopad` collations, introduced in MariaDB 10.2. See: https://mariadb.com/kb/en/supported-character-sets-and-collations/#no-pad-collations

**We have `utf8_nopad_bin` to fix our issue.**

To try this in e.g. phpmyadmin, run the following sql to see that this fixes the issue:
```sql
SET collation_connection = 'utf8_nopad_bin';
SELECT 'Foo' = 'Foo ';
```

TODO:
- [ ] Adapt code in prototype framework that sets the default coallation for the database
- [ ] Adapt generated db structure queries in compiler
- [ ] Check connection settings in prototype framework

**Comment by hanjoosten** [comment]
In the prototype repo there is still work to be done

**Comment by Michiel-s** [comment]
Somewhere in the back of my mind I though 'didn't we discussed this earlier?'. After a search in our issues, I found #263 where we indeed had the same problem and same analysis. Funny.

**Comment by stefjoosten** [comment]
Everything has been updated to `utf8mb4_nopad_bin` instead of `utf8_nopad_bin`. Since utf8 is a subset of utf8mb4, this yields no problem.

**Comment by stefjoosten** [comment]
I have checked that RAP4 works. The symptoms shown above have all gone. However, there is one tick-box still open. @Michiel-s can you check whether the last tick can be made and then close the issue?

**Comment by Michiel-s** [comment]
Strange, I don't understand why it works, because I found a bug in the fix by @hanjoosten.

My database gives the error message: `Error Code: 1253. COLLATION 'utf8mb4_nopad_bin' is not valid for CHARACTER SET 'utf8'`.

To fix this the char set needs to be changed also from `utf8` to `utf8mb4`.

I'll now do the action points for the prototype framework
