### ISSUE TITLE
Error response from daemon: image with reference ampersandtarski/ampersand:v4.6.2 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64.

### ISSUE THREAD

**Issue by ElMakkiHaddouchi** [AmpersandTarski/ampersand#1284]
# What happened
On my Mac (m1) I am trying the following command:
docker run --platform=linux/arm64 -it -v ${pwd}:/scripts ampersandtarski/ampersand:v4.6.2 check repositoryumcu.archimate

after I tried this command, I get the following warning:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Normally I use this command: 
docker run -it -v ${pwd}:/scripts ampersandtarski/ampersand:v4.6.2 check repositoryumcu.archimate
And when I try adding the tag –platform=linux/amd64  to the command, the error message doesn’t appear.

# What I expected

Run this image on my machine.

# Version of ampersand that was used
4.6.2

# Steps to reproduce

1.
2.
3.
4.

# Screenshot / Video

# Context / Source of ampersand script

**Comment by stefjoosten** [comment]
I had exactly the same issue with my MacBook Pro M1. I used the same solution, which is to add the extra option just like you did. Everything seems to work fine from that point onwards. I don't have a validated explanation for this, so I'm still curious. @ElMakkiHaddouchi do you experience any further problems after using this fix?

**Comment by ElMakkiHaddouchi** [comment]
@stefjoosten 
Nothing else happens when the command is executed. So no error message, but also no result that I expected.

When executing the command I normally get the corresponding violations with the EA model. But now no result appears.

**Comment by Michiel-s** [comment]
Hi @ElMakkiHaddouchi and @stefjoosten, as you can see on Docker Hub we only have images for platform `linux/amd64` available. [Ampersand on Docker Hub](https://hub.docker.com/repository/docker/ampersandtarski/ampersand/tags?page=1&ordering=last_updated)

When you run/build on your machine with `--platform=linux/arm64` (notice ARM not AMD), you basically tell Docker to run image for platform ARM, but there is not an image available for that requirement.

The issue you are facing has something to do with the Apple M1 chip. Not exactly sure why, I'm not a Mac user nor expert.

I believe it is enough to only specify the OS in your case. So use `--platform=linux` will do.

If you need an ARM image because otherwise you cannot run on M1 (shouldn't be the case I believe), let us know. We can add additional platform builds for future releases.

**Comment by hanjoosten** [comment]
@Michiel-s , It might be a good idea to build these anyways?

**Comment by ElMakkiHaddouchi** [comment]
@ Hi Michiel-s, I modified it and tried with --platform=linux. But still an error message appears.

"docker: Error response from daemon: image with reference ampersandtarski/ampersand:v4.6.2 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64."

I think it would be useful if a new platform is built, likewise Han Joosten also indicates.

**Comment by stefjoosten** [comment]
Housekeeping note, @Michiel-s 👋

While tidying up stale branches, we're removing `feature/multi-platform-build` (and its already-closed PR #1410) — the multi-platform Docker work from this issue. A short rationale so it's not a surprise:

- **Buildx has since landed on `main` independently**, as part of the v5.9.3 build-cache work (`docker/setup-buildx-action@v3` + `docker/build-push-action@v6`, now with a shared GitHub Actions cache), so the branch's buildx plumbing is superseded.
- **The published image is deliberately `linux/amd64` only** (arm64 is built on request); we don't build multi-arch by default, because QEMU emulation roughly doubles the build time.
- The branch is ~2 years behind `main` and its PR is closed, so it can no longer be merged cleanly.

Nothing is lost: if we ever want multi-arch again, it's a small addition on today's workflow (`setup-qemu-action` + `platforms: linux/amd64,linux/arm64`) rather than a revival of this branch. Shout if you'd rather we keep it around.
