### ISSUE TITLE
define the project

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1311]
Please see the project definition [Synchronize the documentation of Ampersand with the Ampersand repo](https://github.com/orgs/AmpersandTarski/projects/3/settings). to learn what this project is about. 
But also see the comments below for inspiration about the solution.

**Comment by Michiel-s** [comment]
![image](https://user-images.githubusercontent.com/7961582/182208712-8ddb8047-d721-498c-a9f7-13de8b26d0b1.jpeg)

**Comment by hanjoosten** [comment]
The idea of above image is as follows:

In the _new_ situations, we have a docs directory in both the [Ampersand repository](https://github.com/AmpersandTarski/Ampersand) (= compiler) and in the [Prototype repository](https://github.com/AmpersandTarski/prototype). 
When in either repositories anything is pushed to the main branch (by means of a pull request), we want to trigger a [Github action](https://github.com/features/actions) to build the documentation.
This task will get the docs folders of both repositories to build a single page website that can be made available via [Github pages](https://pages.github.com/).

**Comment by hanjoosten** [comment]
In the _old_ situation, we have our documentation in a [separate repository](https://github.com/AmpersandTarski/documentation). It is managed by means of [Gitbook](https://www.gitbook.com/). Gitbook automates the ci/cd whenever a commit is made to that repository, but it is hard to impossible to keep the documentation in sync with the releases of Ampersand and Prototype.

**Comment by hanjoosten** [comment]
# Suggested solution

To help the team finding a realistic solution for this challenge, please find below some thoughts on what could be done.

To make this list as specific as possible, I will suggest some tooling. Be awere that these are just suggestions. It is well possible that the team brings in other tooling, better fit for the job. 

- [] Create a new repository at [AmpersandTarski](https://github.com/AmpersandTarski). This repo will contain the workflows needed to generate a single page website for the documentation.
- [] Create a new development branch in the [Ampersand repo](https://github.com/AmpersandTarski/Ampersand) for the purpose of [this project](https://github.com/orgs/AmpersandTarski/projects/3). Consider that branch as the main branch for its lifespan. At the end of the project, it will be pulled into the real main branch.
- [] Use this development branch to create a `docs` directory in the Ampersand repo. Let it contain a basic (hello world) page.
- [] Define a github workflow inside the new repo. Goal of that workflow is to generate a single page website from the contents of the docs directory in the development branch of Ampersand. The workflow should be triggered any time when there is a new commit/merge/pull request of the development branch of Ampersand. Use [github pages](https://docs.github.com/en/pages) to serve this single page website. Use [Docusaurus](https://docusaurus.io/docs/) as a generator.
- [] Now do the same for the [prototype repo](https://github.com/AmpersandTarski/prototype). There too, create a development branch. Rename the `doc` directory to `docs`. Make the workflow also trigger on a commit of the development branch of prototype. Within the workflow, now not only copy the docs directory of Ampersand, but also the docs directory of prototype. In the one-pager, these directories should co-exist. Maybe scaffold pages are required to make this happen. If so, these could be created and stored inside the new repo.
- [] Replace the hello-world page in the Ampersand repo with all contents from the [documentation repo](https://github.com/AmpersandTarski/documentation). If all above is realized, that content should be readily served at the github page.
- [] Optionally, you might want to restructure all or some of the documentation. This might be beyond scope, because it could require too much inside knowledge of Ampersand. 



## Pointers 
In order to make these things happen, here are some pointers for further reading:

* [Github workflows](https://docs.github.com/en/actions/using-workflows) is the way ci/cd tasks can be realized within Github.
* [Github pages](https://docs.github.com/en/pages) is the way a single page website can be hosted at Github.
* [Here](https://github.com/LayZeeDK/github-pages-docusaurus/blob/main/.github/workflows/deploy-to-github-pages.yml) and [here](https://github.com/redkubes/docusaurus-deploy-action) you can find examples using docusaurus to generate a github pages site with a github workflow. I expect that other examples can be found easily as well.
