### ISSUE TITLE
AffectedInvConj in $allRelations in Generics.php are not listed

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#138]
AffectedInvConj in $allRelations in Generics.php are not listed

Han and I looked at this issue and concluded that it goes well when the name of the context < name of process, but it goes wrong when the other way around.

WRONG:
```
CONTEXT B IN ENGLISH
  PROCESS A
  	r			        :: A * B [UNI]
  	RULE "rule1" : I[A] |- r;r~
  ENDPROCESS
ENDCONTEXT
```
Ok:
```
CONTEXT A IN ENGLISH
  PROCESS B
  	r			        :: A * B [UNI]
  	RULE "rule1" : I[A] |- r;r~
  ENDPROCESS
ENDCONTEXT
```

**Comment by hanjoosten** [comment]
This was a nice catch! It seemed that there was an error in a very deep function (converse, in Auxiliaries.hs). That function could (in rare cases) return lists that were incorrect. 
Fixed this issue with SHA 5f9e168b37a9fdaffb67bd6eaa540746d868d521

**Comment by Oblosys** [comment]
The problem here is not the definition of `converse`, but the dodgy `Ord` & `Eq` instances on `Declaration`. `Eq` is based on only the id string, but `Ord` is derived, and hence takes into account all details in the data declaration (e.g. position in source).

The new definition of `converse` also assumes `Ord`, so even though it may work for this specific example, it won't solve the underlying problem. After fixing the cause, it's probably best to reinstate the old `converse`, as it is slightly easier to understand and a bit more efficient.

**Comment by hanjoosten** [comment]
@Oblosys, sharp indeed! The derived instance of Ord was buggy. I just redefined it, and rolled back the previous commits for this issue. converse was correct, and easier to read too. 
Thanks for the hint!
