### ISSUE TITLE
Warn about multiple meanings.

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#144]
De FSPEC generator kan niet tegen de volgende syntax:

```
 docICO :: Documentation * Documentation [UNI,IRF,ASY]
 MEANING "The (left) Documentation is a carbon copy of the (right) Documentation"
```

en dan in een ander bestand nog:

```
 docICO :: Documentation * Documentation [UNI,IRF,ASY]
```

Dit geeft de volgende foutmelding

```
 ampersand.exe: !fatal 388 (module FSpec.Motivations) Ampersand v3.1.0[master:9d26222]
   In the English language, too many meanings given for declaration docICO.
```

Beide bestanden hebben een `CONTEXT`-regel  waarin  `IN ENGLISH` voorkomt (en de naam van de `CONTEXT`en is verschillend).

Workaround: de `MEANING` uitkommentarieren. Maar dat lijkt niet echt de bedoeling bij het maken van een fspec...

**Comment by hanjoosten** [comment]
This shouldn't be a fatal. However, there should be one meaning only per relation per language. In this case, there obviously were more than one meanings given for the relation in the English language.
unless we accept multiple meanings (which I would find rather strange), this should result in a user error, that contains the locations of the meanings.

**Comment by RieksJ** [comment]
I agree it should not be a fatal. I also agree that there should only be one meaning. I disagree that tehre obviously were more than one meanings - there was one relation with its meaning not specified, and the same declaration (in another file) with its meaning specified. Therefore, it has only one meaning (as a 'NULL' meaning should, IMHO, not count as a meaning).

**Comment by sjcjoosten** [comment]
I have a question: what if a user specifies the same meaning twice, as in:

    docICO :: Documentation * Documentation [UNI,IRF,ASY]
    MEANING "The (left) Documentation is a carbon copy of the (right) Documentation"
    docICO :: Documentation * Documentation [UNI,IRF,ASY]
    MEANING "The (left) Documentation is a carbon copy of the (right) Documentation"

The duplicate declaration is allowed. Whether or not the duplicate MEANING is allowed depends on whether we believe the identifier for a MEANING is its position in the script, or whether it is the string "The (left) Documentation is a carbon copy of the (right) Documentation". Which is preferable?

I do not know enough about the meaning of things (pun intended) in order to have an opinion about this, which is why I'm asking. It also came as a surprise to me that there can only be one meaning per "(language x declaration)"-pair. Why is this? (I am quite comfortable with giving multiple equivalent - but not equal - definitions of something, even within the same language).

**Comment by RieksJ** [comment]
Again I agree (thereby modifying my earlier opinion) that multiple `MEANING`s should be allowed (which is not the same as multiple meanings, because a meaning may be represented by different `MEANING`s). For example, a single meaning might be expressible both in the active or passive form. 

At a higher level, at least `CONCEPT`s must be allowed to have different meaning, and perhaps therefore, `RELATION`s as well. For example, a concept TelephoneNumber may have the following meanings:
- an identifier for a person that will (supposedly) answer when the number is dialled;
- an identifier for an ISRA-point (telco speak)
- an entry in a routing table (in a SIP implementation)
- and likeli other meanings.

I would argue that we should not apply any constraints unless a PURPOSE is specified that requires its existence, and there is agreement for it. Both seem to lack at this point in time.

**Comment by hanjoosten** [comment]
With only my phone at hand, I cannot see why this fatal arises, but clearly there is no sane thing implemented for the case with multiple meanings in the same language.
Also, if we agree that there may be multiple meanings in the same language, we cannot speak about THE meaning of a relation.

**Comment by hanjoosten** [comment]
I thought that the meaning is some natural language sentence in which we try to catch the semantics of that relation. Obviously a single natural language is used. So if we have multiple instances of MEANING, that all express a single meaning, we need to agree on how to cope with that:
 1. Assume the user doesn't make mistakes, and do no checking at all.
 2. Define some kind of equivalence function and use that. (either exact equivalence or some kind of magic)
3. Disallow multiple instances of MEANING

**Comment by hanjoosten** [comment]
I thought that the meaning is some natural language sentence in which we try to catch the semantics of that relation. Obviously a single natural language is used. So if we have multiple instances of MEANING, that all express a single meaning, we need to agree on how to cope with that:
 1. Assume the user doesn't make mistakes, and do no checking at all.
 2. Define some kind of equivalence function and use that. (either exact equivalence or some kind of magic)
3. Disallow multiple instances of MEANING

**Comment by RieksJ** [comment]
Why not handle it in a similar way as `PURPOSE`? We can (and should) have multiple `PURPOSE`s for concepts, relations, etc. In a similar fashion, we could have multiple `MEANING`s.
So I would go for option 1, leaving it up to the developer, and assume (s)he knows what (s)he is doing, and assume that (s)he will detect and correct any mistakes (s)he may have made.

**Comment by hanjoosten** [comment]
I disagree. In the document generator, the meaning acts as the natlang definition of the relation. There should only be one. The purpose acts to motivate the definition. Multiple reasons can exist for a single definition.

**Comment by RieksJ** [comment]
In a regular dictionary, it is quite common to have multiple natlang statements acting as a definition for the same stuff. Personally, I do not have a problem with leaving this up to the user/developer. But then, I can also live with a single definition. 
The original intention of this issue was to report a bug, where I couldn't define a relation twice and only specify one `MEANING`.

**Comment by stefjoosten** [comment]
*History*: This point has been discussed several months ago by Han and I. We have a pretty good idea of the technical consequences in the tool. 

*Analysis*: We all agree that a good Ampersand model has unicity of meaning. So that is not the issue. The issue here is whether the tool should enforce this. In other words: should Ampersand forbid multiple meanings, or should the programmer solve the problems of his/her own creation?

*Solution*: The Ampersand philosopy is that the programmer solves problems of his/her own creation. So the tool should allow multiple meanings. 

*Fix*: this has impact on maintainability of the Haskell code. Besides it has low prio. So there will be a quick-fix that resolves the fatal, and the solution may take some time.... (Earlier this morning, I have talked this through with @hanjoosten on the phone).

**Comment by hanjoosten** [comment]
I changed the title of this issue. Now we can generate a warning for the case that there are multiple meanings for a specific language. In the rest of the codebase, we should cope with the fact that there may be multiple meanings.

**Comment by stefjoosten** [comment]
@RieksJ can you confirm that this issue still exists?
