### ISSUE TITLE
Ampersand might have an infinite loop ...

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#145]
I have tried to compile the application 'Doosjes' (just checked into the ampersand-models repo), using Ampersand v3.1.0[master:208664f]. After half an hour of running Ampersand, I stopped it. Since the last time that compilation took just a few (say 10) seconds, I have made some modifications that I cannot pinpoint exactly. So I wonder what's going on here. Any ideas?

**Comment by RieksJ** [comment]
Turns out that ampersand - ultimately - terminates. It takes something like 40 minutes.

In an attempt to find out where it goes wrong, I have observed the following.
- CPU is constantly 13% (as usual, meaning that it uses 1 of my 8 processors)
- memory consumption starts with around 300K and increases to around 1350K

I have compiled with different configurations (commenting out different sets of files in 'doosjes.adl'), and I get the impression that it is related to the number of files that is actually included.

**Comment by RieksJ** [comment]
I have also done these tests with the functional specifications generator.
Since this terminates with a LaTeX error within 30 seconds, I assume that the problem is in the prototype generator.

**Comment by hanjoosten** [comment]
Rieks is right. For some reason, it takes a lot of time to generate generics.php . Because of the lazyness of Haskell, this does not happen when a functional specification is generated. I think that the culprit is somewhere in calculating conjuncts, but that is a speculation only. 
(the good news is that it terminates...)

**Comment by hanjoosten** [comment]
The number of include files cannot have anything to do with this issue

**Comment by sjcjoosten** [comment]
The culprit was the function `clos1' in ADL2FSpec. It uses some very expensive operations, like "null (l `isc` r)", and "last l", which both become very slow as l grows. I made sure it doesn't get used anymore, at the expense of generating the smallest possible sequences of total and injective expressions. Goes through in a few seconds now.
