### ISSUE TITLE
Add relation properties FUN(ctional) and BIJ(ective)

### ISSUE THREAD

**Issue by jesper-sk** [AmpersandTarski/Ampersand#1489]
**Is your feature request related to a problem? Please describe.**

Not related to a problem, but I expect its implementation adds to conciseness, readability and understandability of RELATION-statements.

**Describe the solution you'd like**

To the properties-part of a RELATION-statement, add the properties `BIJ` and `FUN`, as shortcuts for the property combinations `INJ + SUR` and `UNI` + `TOT` and indicating bijective and functional relations, respectively. 

**Describe alternatives you've considered**

The obvious alternative is to just specify `r [A * B] [INJ, SUR]` or `r [A * B] [UNI, TOT]` instead of using the proposed shortcuts. But, considering that functional and bijective are well-known as well as commonly occurring binary relations, I believe that adding these shortcuts is warranted.

**Comment by hanjoosten** [comment]
Hi Jesper, thanks for the idea. I like it, and it should be pretty easy to implement. @stefjoosten , what do you think?

**Comment by stefjoosten** [comment]
Sure. Good idea! This one is easy:
* adapt the parser to accept BIJ and FUN
* adapt the P-structure with Bij and Fun
* In the transformation to the A-structure, transform Fun to Uni and Tot and transform Bij to Uni, Tot, Inj, and Sur.
* In FormalAmpersand, do the same.
I think that should do the trick... 🙂

**Comment by stefjoosten** [comment]
# Reflection
@jesper-sk , a bijection is a function, so Uni, Tot, Inj, and Sur. So it differs from an inverse function, which is just Inj and Sur.

In the past, we used to have a special syntax for functions, with an arrow between the source and target concepts. We removed that syntax because having two syntaxes for exactly the same thing confused our students a lot. That is why we only have the syntax `RELATION r[A*B]` for declaring relations.

**Comment by stefjoosten** [comment]
@jesper-sk,  I think your storyline is sound. In mathematics, a bijection is a function that is both injective and surjective. Consequently, we can define a bijective relation as a relation that is both injective and surjective. To distinguish the words bijection and bijective makes all the difference. Since Ampersand defines the notations `TOT`, `INJ`, `SUR`, AND `UNI` as adjectives, it makes sense to define `FUN` and `BIJ` to mean functional and bijective respectively.

I have discussed this with @hanjoosten and I will consult some real mathematicians to see if we are doing anything strange, because I want Ampersand to be 100% consistent with mathematically accepted language. (In a quick scan, authoritative locations on the internet do not contradict this storyline, but don't give conclusive answers either.)

**Comment by SimonvRoozendaalOrdina** [comment]
This feature has been added in the branch [Add-prop-BIJ-FUN](https://github.com/AmpersandTarski/Ampersand/tree/Add-prop-BIJ-FUN) .

This branch is a derivative of the [ATLAS-import](https://github.com/AmpersandTarski/Ampersand/tree/feature/atlas-import) branch still running on Ampersand 4, which prevents pushing the functionality to the main branch. As a result, this feature will only become accessible when the ATLAS-import branch is converted to/implemented in Ampersand 5.

**Comment by hanjoosten** [comment]
@Stefjoosten has consulted @WolframKahl about this issue. The details of that will be included in this discussion by @stefjoosten as soon as he has got time for this. 

An outcome of this discussion was that a function could be only injective: The well-known partial function. What we intend here with function is called a mapping, which is a relation that is total and injective. So I substituted the keyword "FUN" by the keyword "MAP", to reflect that.

**Comment by hanjoosten** [comment]
Since version 5.1.3 we have these two new keywords: `MAP` and `BIJ`, which are documented [here](https://ampersandtarski.github.io/ampersand/reference-material/syntax-of-ampersand#properties).
