### ISSUE TITLE
Boolean property isn't implemented correct. 

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#150]
Consider the following definition:

```
RELATION r[A*A] [PROP]
```
The semantics is that IFF the relation is populated, the property is true. 

However, currently this is implemented by a boolean in the database. 

Such a boolean can have THREE values. The queries generated with Ampersand only check to seen that there is a value. This leads to the following interpretation:

Value in database | interpretation in Ampersand Expression
------------ | -------------
true | true
Null | false

If, by some accident, the value `false` would occur in the relation, that would be interpreted as `true`.
This is obviously confusing.

This has to do with the fact that & is about the existence of things. 

What would be the right solution?

**Comment by RieksJ** [comment]
I'm not sure that I understand your point. AFAIK, &-properties (endo-relations with the `[PROP]`-constraint) are implemented as they should be implemented, namely as an endo-relation that is a subset if the identity relation `I`. This is also what I see when looking in the database with phpMyAdmin: the value can either be the 'dirty identifier' or `NULL`. That makes the SQL code that checks to see whether or not there is something there, valid.

The BOOLEAN stuff would only apply if you have a non-endo relation the source or target concept `C` of which would have a `REPRESENT C TYPE BOOLEAN` representation. Then, it can have three values (`NULL`, some representation for 'true' and another for 'false', which I don't know because I don't use them).

And indeed, properties and booleans are different things. So what is the actual problem you have?

**Comment by Michiel-s** [comment]
I agree with Rieks. Don't understand the problem.
Op wo 12 aug. 2015 om 16:24 schreef Rieks <notifications@github.com>

**Comment by stefjoosten** [comment]
Experiment:

Suppose we have
```
RELATION r[A*A] [PROP]
ROLE User MAINTAINS "Prop_r[A*A]"

REPRESENT A TYPE INTEGER
POPULATION r[A*A] CONTAINS
  [(1,1), (1,3)]
RULE "Prop_r[A*A]" VIOLATION (TXT "khsdfkjh", TGT I)
```
