### ISSUE TITLE
Error! 501 Not Implemented: TgtConcept of interface: 'Issue163' is scalar and can not have subinterfaces

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#163]
The script of 
[Issue163.adl](https://github.com/AmpersandTarski/ampersand-models/blob/master/Tests/ShouldSucceed/Issue163.adl) returns a runtime error:

Error! 501 Not Implemented: TgtConcept of interface: 'Issue163' is scalar and can not have subinterfaces

There is no reason to disallow scalars on the root of a BOX. Hence, it should be allowed, or a good reason should be made explicit.

**Comment by stefjoosten** [comment]
This is perhaps more complicated than it seems. To be continued....

**Comment by RieksJ** [comment]
Perhaps it also helps to provide a good reason for actually having scalars on the root of a BOX. My understanding of a 'scalar' is that this is a way to represent atoms internally, whereas INTERFACEs have to do with concepts and atoms, which is a different level. Obviously, any concept/atom must be allowed to be the root of a BOX. If the internal representation prohibits this, then perhaps the error should be that the chosen representation of a concept is incompatible with the fact that  the concept is used as the root of a BOX.

**Comment by hanjoosten** [comment]
A good reason for NOT discriminating between scalars and non-scalars is that the Ampersand theory doesn't do so. 
I see no reason to forbid it. We all preach that ther must be a reason to forbid something. Having to supply a reason for not forbidding is the other way round.

**Comment by Michiel-s** [comment]
Having a concept at the root of an interface box means that there follows data regarding that concept. E.g. the contact information about a Person. 

As we agreed with the introduction of the technical types and REPRESENT statement, the default representation of a concept is an object. Thereby Person is by default represented as an object which can have attributes specified by the interface BOXes. That makes sense.

Concepts that are not represented as objects (in our case the scalars), are in my opinion concepts that are not suitable for having attributes, because we represent them as scalars. E.g. say the concept Age is represented as integer. Thereby the Age atom is represented as an integer and not an object. Giving an integer attributes does not make sense to me.

So where the Age (integer) can have relations in the &-domain, it cannot have attributes when implementing this in the technical worlds. The interfaces are about this transformation between &-world and other worlds. Therefore I would forbid having scalars at the root of a interface box.

**Comment by hanjoosten** [comment]
We need to distinguish between the Ampersand theory, that only speaks about concepts and relations between them., and any kind of realization (e.g. the zwolle frontend).
In your previous comment you seem to suggest that if a concept has a representation, it should not be the source of a relation that is TOT. The only reason you give is that it doesn't make sense to you. 
I suspect that there could be a real reason, but only based on the realization using an object oriented approach (as zwolle has, as far as I know). 

As a counterexample, let's assume a an amount payable on a bill. Let's make the representation FLOAT. Now I need to know if that amount exceeds the cash limit of the person the bill was sent to. In &, I would have the relation exceeds[AmountPayable*CashLimit]. I see no reason to disallow this. I genually don't.

**Comment by Michiel-s** [comment]
I do make the distinction between Ampersand theory and the realization. "So where the Age (represented as integer) can have relations in the &-domain, it cannot have attributes when implementing this in the technical worlds. The interfaces are about this transformation between &-world and other worlds. Therefore I would forbid having scalars at the root of an interface box." I do *not* want to suggest that a concept with a scalar representation cannot be the source of a relation, only that it cannot be used at the root of a BOX.

The interface definitions are about converting, translating, or whatsoever, the &-world into the realizations (e.g. mysql db, zwolle frontend). The realizations use the representations. Now my point is, that for concepts with a scalar rep at the src of an interface box, this means that both:
1) the atom should be presented as a scalar (because of the representation),
2) the atom should be presented as an object (because of the interface box),
This is contradictory.

**Comment by RieksJ** [comment]
Thought you was on holiday leave...

I have the following (somewhat ambiguous) position. 
* I need scalars to be represented using views. In risk management, for example, I would like to specify a view for Risks (which is L,M,H, or 1,2,3,4,5, and hence would be a scalar) depending on whether or not I was the risk owner, which certainly is not a default thing in Ampersand to do.
* In the current practice, I find myself creating VIEWs for stuff (such as risks) where the VIEW does not have a 'Risk' as root, but some other concept, that has a relation with 'Risk' as well as with other stuff (e.g. likelihoods, impacts, and whatever else I need). 

So my dilemma is that functionally I agree with Han/Stef, while in practice I do not (yet?) have actual problems with the implementation that require interfaces/views on scalars. 

In order to further the discussion and obtain a clear understanding of actual issues, I would like to ask @hanjoosten to provide an Ampersand script that illustrates his needs (involving  the relation exceeds[AmountPayable*CashLimit]), or any other script that is illustrative to this point.

**Comment by hanjoosten** [comment]
@RieksJ The example is allready in this ticket. It is the one that causes the error. Whatever is the soloution to this ticket must prevent a runtime error on this script. So either it is fixed in the frontend (my prefference), or a rule should be agreed upon that can be tested design-time. This rule should then be implemented in the Haskell part, so the Ampersand modeller will be prevented from making this so-called error.
I need to know what rule to check on, and how to tell that to the &-modeller.

**Comment by RieksJ** [comment]
@hanjoosten Ok. So you need to know what to check on. In the original ticket, you say "There is no reason to disallow scalars on the root of a BOX. Hence, it should be allowed, or a good reason should be made explicit.". I think that Michiel has a valid reason, namely that 

1. we should clearly distinguish between statements in the algebraic domain (e.g. relation, concept, rule, atom, pair, etc.), and statements that deal with mapping this stuff onto real systems, of which INTERFACE, VIEW, BOX and REPRESENT are examples, and
2. he shows that allowing scalars to have boxes presents a dilemma that cannot be resolved unambiguously (contradiction).

From this, it seems logical to forbid the definition of boxes on concepts for which a REPRESENTATION statement is defined (or inferred). Consequently, I propose to check for that in Haskell, and produce an error message like "BOXes (or BOX-like structures such as COLS, ROWS, etc.) cannot be used for Concepts for which a REPRESENTATION TYPE has been defined."

**Comment by stefjoosten** [comment]
@Michiel-s. We discussed this, but did not conclude it. Let's have a phone call about this.

**Comment by Michiel-s** [comment]
I'll close this issue for now. As explained above, the introduction of technical representations results in certain constraints for these technical world. E.g. is you specify `REPRESENT datum TYPE DATE` the database field can only contain date values. In the html frontend you see an datepicker (by default). This requires data from the api being a date representation and nothing more. INTERFACE boxes imply a substructure for the target atom of the expression. We can't have both.

If you do want box interfaces, don't use the represent statement for that concept.

Therefore: scalar cannot be used as target in interface expressions that are followed by an interface box. I've implemented a check an error message for this (4e5f241ea4d815969a47c9f1f9ad119c6d5c826d).

**Comment by stefjoosten** [comment]
@Michiel-s. I have tried to run ampersand\AmpersandData\FormalAmpersand\Atoms.ifc on commit branch_#228@3a3cdb40aabfc0c9c084918e4304d0f667e81a59 . This script is demonstrable on the master, but not on branch_#228. So maybe we should skype about this.

**Comment by hanjoosten** [comment]
Currently, the check is done runtime, but it should be implemented designtime. The need for that is demonstrated recently (see issue #784)

**Comment by hanjoosten** [comment]
This check is one of the checks that should be built according to issue #745

**Comment by hanjoosten** [comment]
Fixed by implementing a static check. In these cases the Ampersand compiler will issue an error.
