### ISSUE TITLE
REPRESENT of two concepts in the same typology must be equal

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#181]
A test should be done to ensure that no two concepts in the same typology have different represent-types.

**Comment by RieksJ** [comment]
How about this:

- if a concept without a REPRtype is added to a typology without a REPRtype, that's ok;
- if a concept without a REPRtype is added to a typology with a REPRtype, the concept will be (automatically) assigned the REPRtype;
- if a concept with a REPRtype is added to a typology without a REPRtype, all concepts in the typology will be (automatically) assigned the REPRtype;
- if a concept with a REPRtype is added to a typology with a REPRtype, the REPRtypes must be equal; if not an error is thrown.

**Comment by hanjoosten** [comment]
Of course. Two or more REPRESENT statements adressing concepts that belong to the same typology, and having different representation types, will cause an error.

**Comment by Michiel-s** [comment]
Han, That's only a reply to the last bullet of Rieks.

How about the first 3. The first is obvious. The 2nd en 3rd are very nice
in my opinion. That statements in my &-script when having specialization.
Op vr 11 sep. 2015 om 06:29 schreef Han Joosten <notifications@github.com>

**Comment by hanjoosten** [comment]
Think again: Your script is stateless, so after typechecking, every concept belongs to exactly one typology (= the set of concepts connected to each other by CLASSIFY statements). Now each Represent statements in fact tells something about the representation type of the typology the concept belongs to. All represent statements that tells something about a single typology MUST have the same TYPE. 
So all the bullits are hanmdled

**Comment by Michiel-s** [comment]
@hanjoosten, I believe this ticket is fixed right? Please close it if so.

**Comment by hanjoosten** [comment]
Nope. It is still open, as long as [this test case](https://github.com/AmpersandTarski/ampersand-models/blob/master/Tests/ShouldFail/Issue181.adl) does not fail.

**Comment by sjcjoosten** [comment]
Here's how I'm going to implement this:
first off, REPR is going to be similar to CLASSIFY, saying ``REPRESENT A TYPE INTEGER`` will mean roughly the same as ``CLASSIFY A ISA INTEGER`` with some differences:
- the only way to 'get to' TYPEs, is via the second argument of ``REPRESENT _ TYPE _``
- the first argument of ``REPRESENT _ TYPE _`` must be a user-define type for now, whereas ``CLASSIFY _ ISA _`` takes user-defined types in both arguments.
- This way, the namespaces of TYPEs and Concepts remain completely separated.

To find the representation of a concept, here are the rules:
- For every concept X, we have ``REPRESENT X TYPE Storable``
- For every Type X, we have "X ISA Storable" (note that there is no syntax to write ISAs between TYPEs, this is intentional, as these are all built-in)
- For every concept X, use as representation whatever is the least type that fits it. This will generate a "Storable" type for everything "in a topology without a REPRType", but since the least is used, and "X ISA Storable", this can be overwritten.
- In the case of Issue181.adl, A will get TYPE INTEGER. B, however, has both INTEGER and FLOAT as types, which is not allowed since there exist INTEGERs that do not fall into the range of FLOAT, and vice versa: there is no ISA between INTEGER and FLOAT.
- It may be possible in the future to add "SHORTINT ISA ARBITRARYPRECISIONINTEGER", or something similar. If this would be the case, then having ``CLASSIFY A ISA B``, where ``REPRESENT A TYPE SHORTINT`` and ``REPRESENT B TYPE ARBITRARYPRECISIONINTEGER``, will be perfectly valid. Currently, however, there are no overlapping built-in types.

**Comment by hanjoosten** [comment]
Sounds good! When are you done ;-))

**Comment by sjcjoosten** [comment]
Here's something to think about:

```
CLASSIFY A ISA C
CLASSIFY B ISA C
TYPE A INTEGER
TYPE B DATE
```

Is the script described above allowed? In the view described above, it is. C would, of course, get only the most generic type ``Storable``. Since `INTEGER` and `DATE` are both ``Storable``, there is no problem. If something else is desired, please let me know.

**Comment by hanjoosten** [comment]
No, this is not allowed: Two or more REPRESENT statements adressing concepts that belong to the same typology, and having different representation types, will cause an error.

**Comment by sjcjoosten** [comment]
If I follow your reasoning, the following is not allowed either:

```
CLASSIFY A ISA C
TYPE A INTEGER
```

In this case, C will be `Storable`, whereas A will be `INTEGER`.

Note that the following will be fine:
```
CLASSIFY A ISA C
TYPE C INTEGER
```

In this case, A is `Integer`, because C is.

**Comment by hanjoosten** [comment]
The rules are pretty straitforward:

1) All concepts of a typology have the same TYPE

2) The TYPE is determined by the REPRESENT statement(s) (if any) of any of the concepts in the typology.

3) If there is no REPRESENT statement for any of the concepts of a typology, the type will be `OBJECT` (or `storable`, if you wish)

**Comment by Michiel-s** [comment]
Please do not mix the OBJECT representation with the idea of `storage`. We have OBJECT and several scalar representations (INTEGER, DATE, etc). All of these are `storable`. So OBJECT isa storable and INTEGER isa storable. But INTEGER is **not** an OBJECT.

The implicit meaning of not specifying a representation type in the script is that it is an OBJECT in the technical world (prototypes).

**Comment by sjcjoosten** [comment]
Excellent, so we probably want OBJECT to be the default, right?

**Comment by hanjoosten** [comment]
Right

2015-11-14 20:03 GMT+01:00 Sebastiaan Joosten <notifications@github.com>:
