### ISSUE TITLE
Multiple input in Excel-include does not work properly

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#183]
@hanjoosten , Please look at commit 9da7ee3.

You can reproduce the bug by compiling Views.adl in the presence of Views.xlsx.
Then start the application, assume role "User", and inspect tab "Concepts".
The third concept is a combination: `Term,Composition`, whereas the Excel sheet specifies the , as a multiple-input delimiter.

**Comment by Michiel-s** [comment]
Han, can you explain how the multi input works?
Op di 8 sep. 2015 om 10:44 schreef Han Joosten <notifications@github.com>

**Comment by hanjoosten** [comment]
Well, in brief it comes down to this:

Suppose you have a relation rel[A*B]

Then you can populate that relation like this:

![hjo 20150909 08 23 48](https://cloud.githubusercontent.com/assets/1159672/9754713/2ff3d6ba-56cc-11e5-8cfa-5546b7300742.jpg)

In cell B2 you see that the concept name is placed within brackets. Between the concept name and the close-bracket, there is a [single punctuation character](http://unicode.org/charts/PDF/U2000.pdf) .
Now instead of writing a single atomvalue in the cells in column B, you can concatenate the atom values by placing the punctuation character inbetween the atomvalues. 
So in this example, you would have the relation ```rel[A*B]``` populated with [ (a1,bi), (a1,b2), (a1,b3) ]

Note that this only goes for values with a string representation. That is simply because it isn't possible to have for insteance a date field in Excel, containing multiple dates separated by a character.
