### ISSUE TITLE
Php error: Can't use function return value in write context

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/ampersand#185]
I get the following message when using the new interface:
Fatal error: Can't use function return value in write context in /Applications/XAMPP/xamppfiles/htdocs/fw/Database.php on line 232

My guess is that "empty(Concept::getGeneralizations($concept))" – the code on that line – is only available in a newer version of PHP than the one I use. If this is the case, then I suggest checking the PHP version somewhere and showing a decent error message (including the required version).

**Comment by sjcjoosten** [comment]
While we're at it: I'm getting "Error connecting to the database: username / password are probably incorrect." when the real issue is that MySQL is not working properly. I know this from the mysqli_connect warning - any PHP with warnings suppressed (or someone not reading the warnings) would steer the user in the wrong direction.

**Comment by Michiel-s** [comment]
1) You're correct. "Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error." I'll add the php version check.

2) You should suppress the php warnings in the output, because otherwise the exception message cannot be displayed correctly. This is a default setting in localsettings.php `ini_set("display_errors", false);`. Have you changed this? Or: "Although display_errors may be set at runtime (with ini_set()), it won't have any effect if the script has fatal errors. This is because the desired runtime action does not get executed." Did you had any fatal errors?

If I stop mysql, I get the following output. This looks good to me.
![image](https://cloud.githubusercontent.com/assets/7961582/9745628/671570bc-5673-11e5-90c9-c47836d57bab.png)

**Comment by Michiel-s** [comment]
Hi @sjcjoosten, please close this issue if you think it is solved this way.
