### ISSUE TITLE
Zwolle interface and ONE

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#188]
Recently, the Zwolle interface has become the one and only interface we support. However, since then, a few of our regression test scripts fail, saying:

```
ampersand.exe: Cannot read template file views\Atomic-TYPEOFONE.html
```

 I have done a diagnosis, and want to share these insights:
For instance, one of the failing scripts is [CheckDanglingPurposes](https://github.com/AmpersandTarski/ampersand-models/blob/master/Tests/ShouldSucceed/CheckDanglingPurposes.adl). There is a single INTERFACE statement in it:
```
INTERFACE Iface : I[ONE] BOX [ "" : I[ONE] ]
```

There is no error coming out of the parser/typechecker. This means, that we accept this interface statement as valid ADL. The user would expect something to see the ONE atom. (or whatever). The generation fails, because there is no template file `views\Atomic-TYPEOFONE.html` .

I raise this ticket, because I am not sure what the correct solution would be. I see several options:
 1. Disallow the above interface statement. This can only be done if we have a rule that this statement would violate.
 2. Make this work, by supplying a meaningful template file. I wonder what that would look like though. 
 3. Maybe some other solutions?

@stefjoosten , @RieksJ , your thoughts please

**Comment by RieksJ** [comment]
In the Zwolle front-end, 'INTERFACE's should not use the `ONE` atom, but use `SESSION` atoms (for INTERFACEs that should appear in the menu bar). The statement you listed should be changed into

     INTERFACE Iface : I[SESSION] BOX [ "" : I[SESSION] ]

It is correct that there is no error from the parser/typechecker, as the `ONE` atom still exists (and I recall a discussion with someone other than me that argued that it should remain in existence).

It is also correct that there is no template file, since there is nothing to show. I would expect that the above example would also be resolved by the line:

     INTERFACE Iface : I[ONE] Box [ "" : V[ONE*SomeOtherConcept] ]

**Comment by hanjoosten** [comment]
I just talked with @stefjoosten at the phone. His story is more or less the same as what @RieksJ says above. However, he argues that there is no reason that ONE could not be the target of an interface expression. This has as a consequence, that the template must exist. A nicely styled '1' symbol would suffice. 

@Michiel-s , could you add a template showing a small icon for in `views\Atomic-TYPEOFONE.html` ?

That would also close this ticket
