### ISSUE TITLE
Excel import based on interfaces

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#190]

**Comment by RieksJ** [comment]
This may not be trivial in case the interface is allowed to not just create, but also to update atoms (which can currently be done because we use store 'dirty' identifier in excel files). We might need different INTERFACEs (with different cRUd settings) to do that. 

Let's keep the current ExcelImporter running until there is a new one that is satisfactory.

**Comment by RieksJ** [comment]
Sorry, shouldn't have closed it

**Comment by Michiel-s** [comment]
Tested and merged in branch 228
