### ISSUE TITLE
MySQL access information misplaced?

### ISSUE THREAD

**Issue by WolframKahl** [AmpersandTarski/ampersand#212]
WIth yesterdays development version,  3816e5b33ce5a2450cf82dbf2f876f6b5befc9d8, calling

    ampersand ... --sqlLogin="<login>" --sqlPwd="<password>" theatre.adl

deposits the database access information only in

    theater.proto/theater.proto/generics/theater.proto/theater.proto/generics/dbSettings.php

, but not in

    theater.proto/theater.proto/localSettings.php

from where they are taken at run-time.
(Also, the options `--sqlLogin` and `--sqlPwd` are not mentioned by `ampersand --help`.)

**Comment by hanjoosten** [comment]
There is something wrong indeed. The usage of passwords at the command line has evaluated in time. As you point out, it needs to be looked into. I did a small inspection of what we have:

Currently, this is what I see: 

 1. LocalSettings.php. This file allways contains the default credentials ampersand/ampersand. They are not infulenced by the command line switches _--sqlLogin="foo" --sqlPwd="bar"_ .
 2. generics\dbSettings.php. This file contains the contents of the command line swithches, or else the defaults. 

The framework allways seems to use the credentials of LocalSettings.php

@Michiel-s Could you tell in what cases dbSettings.php is used? Is it used at all? Or is this obsolete?

@RieksJ told me that if localSettings.php is copied to includes\LocalSettings.php, that it will be used instead of the one that is generated( = copied from ampersand\static\zwolle) . This doesn't seem to work for me. I might do something wrong. 

As soon as I know how this all is supposed to work, I can document that and/or fix the current behaviour.

**Comment by RieksJ** [comment]
I would agree that “includes\LocalSettings.php” does not work. Please try “include\LocalSettings.php” (the difference is the name of the directory, of which the last character should be an ‘e’, not an ‘s’.
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by Michiel-s** [comment]
@hanjoosten the generics\dbSettings.php is indeed obsolete. #198 proposes to stop this file from being generated. I wasn't aware of the --slqLogin and --sqlPwd switches. Are there more of these that should have effect on the frontend that I'm not aware of?

The solution of RieksJ is correct and the way to go. I'll close this ticket.

**Comment by hanjoosten** [comment]
Then I will remove these switches and the generation of dbSettings.php, then close this ticket

**Comment by WolframKahl** [comment]
On Tue, Nov 03, 2015 at 01:46:54PM -0800, Han Joosten wrote:
> Then I will remove these switches and the generation of dbSettings.php, then close this ticket

I think that forcing all ampersand user into a single unsafe
(because of publicly known password) database account
is not desirable in the long term.

I believe that some way to customise SQL user and password
should be offered --- is there another way?
(I mean something more user-friendly than editing PHP files after generation...)


Wolfram

**Comment by hanjoosten** [comment]
The PHP user/password is for the account the database itself runs in. That is configurable in the generated LocalSettings.php for each prototype, even  afterwards. Also, this feature ensures that no credentials have to pass through the ampersand executable itself. That may feel safe, because no trust is required in the ampersand development. 
LocalSettings.php can be seen as a config file. no more, no less.
I think for now this is really well enough, also taking in mind that we do not want to do too much for specific implementation.
