### ISSUE TITLE
frontend-functionality for passwords

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#216]
I have written a login-application, using `REPRESENT Password TYPE PASSWORD` . The second time I tried to log in, the front-end had already filled in the password. Nice functionality for thugs!  It would be better that passwords are never filled in automatically.

**Comment by sjcjoosten** [comment]
My guess is that it's your browser doing the filling-in. Can you try the following:
 - reset the database
 - go to the password thing
If the password is again filled in automatically, then you probably let your browser remember your passwords. Also, Chrome tends to mark the field yellow to indicate that it has been filled in by autofill.

It is possible to block this explicitly, but I suggest we do not, as it is quite useful that browsers remember passwords.

**Comment by Michiel-s** [comment]
@stefjoosten you're right, as with all other relations/expressions the values are shown if populated.

In case of the PASSWORD template, this is only done when the password is editable. Otherwise, it always displays 8 stars `**********`.

To use the password for login routine, you require a login pattern with a exec engine production rule. E.g. sessionAccount is populated when sessionLoginPwd = accountPwd and sessionLoginName = accountName. Note that the sessionLoginPwd should also be depopulated to have your expected behavior.
