### ISSUE TITLE
Delete button does not work in Referentielijsten.adl

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#226]
I have compiled Referentielijsten.adl (https://github.com/AmpersandTarski/ampersand-models/blob/master/NVWA%20DTV/Referentielijsten.adl) with Ampersand v3.2.0[master:db4eef0], build time: 13-Nov-15 17:57:53 West-Europa (standaardtijd).

This is a demonstrable Ampersand model, in which the role FAB can create, edit and delet variables in a historic adminstration. However, deleting a variable works no longer (just this. The rest still works). Just when I press the SAVE button, I get the following screen:

![image](https://cloud.githubusercontent.com/assets/275768/11162624/35c3cc68-8aab-11e5-82ae-32f4d89bf083.png)

As far as I can tell this is a front-end error message. I detected this behaviour one or two weeks ago and decided to wait a little. But it seems persistent, so here is the issue.

**Comment by Michiel-s** [comment]
@stefjoosten you've issued the exact same ticket a while ago #97. There I refer to #60, which I closed yesterday. The current open ticket that will solve this issue is #141. However, this is still a mayor task as it will require to refactor the way updates are sent between frontend and backend. Work in progress.

Work around fore now: auto commit changes (option under horn-icon in menu bar).
