### ISSUE TITLE
Treatment of tabulations

### ISSUE THREAD

**Issue by WolframKahl** [AmpersandTarski/Ampersand#232]
`Examples/ProjectAdministration/ProjectAdministration.adl` has `Assignment`, which previously was just an “objectified relation”, following the pattern:

```
CONCEPT T "objectified R : A * B"
RELATION pi[T*A] [UNI,TOT]
RELATION rho[T*B] [UNI,TOT]
RULE "Create T" : R |- pi~;rho
RULE "Delete T" :  pi~;rho |- R
```

In this kind of context, I have not yet seen the following additional rule:

```
RULE "T uniqueness": pi;pi~/\rho;rho~ |- Id
```

(Equality follows from totality of `pi` and `rho`.)

With that additional rule, which I would assume is omitted only as an oversight,
the whole specification just says that “`(T , pi , rho)` is a tabulation for `R`”.

Would a shortcut declaration syntax for this make sense / be welcome?

E.g.:

```
TABULATION "Objectified R" T pi rho : R
```

That way, specifiers would also not be tempted to replace the Create/Delete pair with a single equivalence...

**Comment by RieksJ** [comment]
You are correct. It is an oversight. We can use the `IDENT` statement, which is a shortcut syntax for specifying a set of ralation that identify atoms in a specific concept. In your case, it would be used to identify Ts, as follows:

    IDENT "T uniqueness" :  T (pi, rho)

The general syntax is:

    IDENT "{rule name}": {Concept} ( {e1}, {e2}, ....)
where: 
* {rule name} is the name of the rule 
* {Concept} is the name of the Concept for atoms of which the rule specifies identifiers
* {e[i]} are expressions whose source concept must be {Concept}.
AFAIK, this translates into the following rule:

    RULE "{rule name}":  {e1};{e1}~ /\ {e2};{e2}~ /\ ... |- I[{Concept}]

@sjcjoosten observed a long time ago that while this is practical for many situations, the `;` operators should be replaced with `<>` operators, but they are not supported (yet?) in Ampersand.

**Comment by sjcjoosten** [comment]
@RieksJ let's discuss `<>` in a separate ticket. In the case proposed by @WolframKahl , there is no difference between `;` and `<>`, as the relations `pi` and `rho` are functions.
The purpose of objectifying a relation, is to change it into functions, which is different from the purpose of the IDENT statement. The IDENT statement does not require functions, while TABULATION does, therefore:
- IDENT and TABULATION would serve different purposes from a design perspective
- IDENT and TABULATION have different definitions

So I think it makes perfect sense to create separate syntax for this purpose. A way forward could be:
- create `Examples/ProjectAdministration/ProjectAdministrationTabulated.adl` as a first example
- fix ampersand such that it allows the new syntax. I propose that we add the syntax to the P-structure, but not to the A-structure (maybe only change the A-structure for the A2P convertor). This way, we can give better error messages
- add some try cases that test the new syntax

I would favor syntax that includes brackets:
``
TABULATION "Objectified R" T (srcT, tgtT) : r
``
this would allow some adaptations later, such as omitting the `(srcT,tgtT)` to get the default behavior, or even writing `((pi1,pi2),tgtT)` if the source of `r` is already an objectified relation, in which case `pi1` would stand for the composition of `srcT` and `pi1`.

Do we like the word `TABULATION`? Where does the word come from?

**Comment by RieksJ** [comment]
I was just referring to the rule-stuff. If we're talking objectified relations, then let's ponder about non-binary relations as well that I would like to be objectified/conceptualized/tabulated. I can imagine a `Hit` to be a ternary relation between a `Hitter`, a `Victim` and an `Object`, with `MEANING "A Hitter has hit a Victim with an Object"`. How would we do that?

**Comment by sjcjoosten** [comment]
So if you want to objectify a non-binary relation, the question is: which relation do you want to `objectify'? This is especially important since Ampersand does not deal with non-binary relations.

However, we could create a concept for all Hitter-Victim pairs:

`
TABULATION HVPair (fst,snd) : V[Hitter*Victim]
`

Now, there could be a relation between HVPair and Objects, which we may consider to be ternary. In that case, suppose we call it `used`:

`
RELATION used[HVPair*Object]
`

Now we can create the objectified relation of it. Since we are playing *clue* (in Dutch: *cluedo*), I have called the object `Guess`.

`
TABULATION Guess (hvPair,object) : used
RULE hitter = hvPair;fst
RULE victim = hvPair;snd
`

So my last paragraph mentioned `((pi1,pi2),tgtT)`, which might be another syntax-sugar extension, in which case we could replace the above with the following:

`
TABULATION Guess ((hitter,victim),object) : used
`

However, to allow this last syntax, ampersand would have to guess `fst` and `snd`, which in this case it might do based on the earlier TABULATION. In any case, the first step would be to make the following go through:

`
RELATION allPairs[Hitter*Victim]
RULE allPairs = V
TABULATION HVPair (fst,snd) : allPairs
RELATION used[HVPair*Object]
TABULATION Guess (hvPair,object) : used
RULE hitter = hvPair;fst
RULE victim = hvPair;snd
`

**Comment by WolframKahl** [comment]
On Sun, Nov 29, 2015 at 02:33:29AM -0800, Sebastiaan Joosten wrote:
> I would favor syntax that includes brackets:
> ``
> TABULATION "Objectified R" T (srcT, tgtT) : r
> ``

Agreed.

> Do we like the word `TABULATION`? Where does the word come from?

2.14 in

@Book{Freyd-Scedrov-1990,
  title = {Categories, Allegories},
  author = {Freyd, Peter J. and Scedrov, Andre},
  year = 1990,
  series = {North-Holland Mathematical Library},
  volume = 39,
  pages = {xviii+296},
  publisher = "North-Holland",
  address = {Amsterdam},
  ISBN = {0-444-70368-3 and 0-444-70367-5 (pbk)}
}

: ``A pair of maps $f$, $g$ \emph{tabulates" a morphism $R$ if

  $f\converse \comp g = R$,
  $f \comp f\converse \meet g \comp g\converse = 1$.

  We say that $R$ is \emph{tabular} if it has a tabulation [...]''

(``map'' is ``univalent and total morphism'')


Wolfram

**Comment by RieksJ** [comment]
W.r.t. terminology: I would have been surprised if there hadn't been a reference in literature for tabulation. Cool. Nevertheless, Ampersand does not want to frighten its (not so mathematically oriented) users, by not using 'impressive' terms. So Ampersand uses the term 'relation' rather than 'morphism'. For now, I think tabulation may do, but I have a similar itching intuition about the word as @sjcjoosten seems to have. 

W.r.t. the ternary relations: for now I think we should not go in that direction. For one, its ugly (objectifying a `V` seems awkward). Also, the symmetry that I have in mind gets lost, which is far from satisfactory. Finally, the (little) practical need may not justify the effort.

W.r.t. the syntax: How about this:

    r :: A * B  TABULATION R(a,b)
    
Which would be equivalent to
    
    r :: A * B
    a :: R -> A
    b :: R -> B
    IDENT Rs: R(a,b)

**Comment by sjcjoosten** [comment]
My itch was actually the other way around. `TABULATION` seems to focus on the implementation, which is to make a multi-column table (Dutch: brede tabel) out of it. I am happy to hear that it has a mathematical background, too. I'll try to find Freyd & Scedrov, it's also the book Jaap van der Woude keeps referring to.

I like Rieks' syntax. Rieks, can you decide where to put the [ASY]-annotations in your syntax?

For the ternary relations part, I feel it's rather elegant, but it requires some additional support for tabulating a V, which is an outstanding wish for me. It would maybe help to convince you: in particular, I would like to be able to write `(A*B)` for the concept that is the tabulated `V[A*B]`. For your ternary relation – using your syntax for the tabulation – it would be:

```
used :: (Hitter*Victim)*Object TABULATION Guess ((hitter,victim),object)
```

**Comment by RieksJ** [comment]
I guess your question about [ASY]-annotations is: 'where to put multiplicities and alike properties, such as ASY'. Right? Here's my proposal:

    r :: A * B  [TOT,SUR] TABULATION R(a,b)

That would make `TABULATION` parse similar as `MEANING`.

B.t.w., ORM uses the terms 'Objectification' or 'Reification' for what we're trying to do with TABULATION. Would either be a reasonable substitute?

**Comment by sjcjoosten** [comment]
Right, let's treat `TABULATION` syntax similar to `MEANING`.

I don't like Reification, and am a bit hesitant about Objectification since our Concepts are called Concepts instead of Objects

**Comment by RieksJ** [comment]
We could also call it 

* `r :: A * B  CONCEPTUALIZATION R(a,b)` but that takes longer to type than TABULATION.
* `r :: A * B  CONCEPT R(a,b)` where the `(a,b)` distinguishes it from a 'real' CONCEPT definition.
* `r :: A * B  NOMINALIZATION R(a,b)` (which is a term from linguistics). But then, that also has this ichy 
quality...
*  `r :: A * B  NAMED R(a,b)` as a compromise.

Whatsay? At a first glance I think the second one (`CONCEPT R(a,b)`) is the best (for now).

**Comment by stefjoosten** [comment]
Hm, I want to let it all sink in before making definite choices here.

**Comment by RieksJ** [comment]
I just realized that we might also want to conceptualize expressions. One example that I would expect would turn up in Formal Ampersand, would be the conceptualization of rule violations. But I would not want to confine it to rules. I would want to use any expression. Do we want separate syntax for that or do we want to have a unified syntax?

**Comment by stefjoosten** [comment]
To me it is clear that this is is stuff for Amper4.

An important consideration is to have explainable syntax with keywords that resonate to concepts our users will (think they) understand. So `TABULATION` beats `REIFICATION`, and `TABLE` beats `TABULATION`.
There are various use cases that I want to serve and I want to distinghuish:
1. tabular information, as we get it from (for example) spreadsheets;
2. objectification of a relation;
3. identification of atoms.

I'm sure there are more use cases. I don't want a separate syntactic concept for each use case. I'd rather serve each use case by a small number of intuitive syntactic concepts. I like the bracketed notation suggested by Sebastiaan.

**Comment by stefjoosten** [comment]
I have written the result of above discussions in the Ampersand documentation https://ampersandtarski.gitbooks.io/documentation/content/syntax/the-tabulation-statement.html
