### ISSUE TITLE
Something funny with reruns

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#239]
I have a seemingly straightforward situation, which gives normal behaviour when the Exec-Engine does not maintain a rule, but too many reruns if it maintains the rule.

I will first show the situation as intended, with the Exec-Engine active. Here is the code snippet:

    RULE newStatement : I[Concept] |- exists[Statement*Concept]~;exists[Statement*Concept]
    VIOLATION ( TXT "{EX} NewStruct;Statement"
              , TXT ";exists[Statement*Concept];Statement;_NEW;Concept;" , SRC I
              , TXT ";onBehalfOf[Statement*Account];Statement;_NEW;Account;" , SRC V[Concept*SESSION];'_SESSION'
              )
    ROLE ExecEngine MAINTAINS newStatement

Here is the behaviour I get, when this rule is maintained by the Exec-Engine:
![image](https://cloud.githubusercontent.com/assets/275768/11680844/3b18c51a-9e5b-11e5-9605-d2478385bd0d.png)
When I disable this by commenting out the ROLE assignment, we get to see the text that is intended for the Exec-Engine:
![image](https://cloud.githubusercontent.com/assets/275768/11680891/affe2e9c-9e5b-11e5-8519-227582daf9d3.png)

I have done this with Ampersand v3.2.0[master:93b27c2*], build time: 01-Dec-15 14:37:29 West-Europa (standaardtijd)

@Michiel-s do you have a hunch?

**Comment by RieksJ** [comment]
There are two problems with your `VIOLATION` statement.

1. You use fully typed relations (i.e. `exists[Statement*Concept]`) rather than relation names (e.g. `exists`). The violation-text parser does not accommodate for fully typed relations; this is not necessary, since the type of the relation must be known at run-time anyway, and is derived from the contents of the subsequent concept-specification-arguments. Solution: replace the text `exists[Statement*Concept]` with the text `exists`, and replace the text `onBehalfOf[Statement*Account]` in the next line with the text `onBehalfOf`.
2. I expect that this won't solve all your problems, since this second line attempts to fill the relation `onBehalfOf[Statement*Account]` with a pair of atoms, that are of type (`Statement`,`SESSIONS`) rather than of type (`Statement`,`Account`). I would think that the phrase `SRC V[Concept*SESSION];'_SESSION'` should be extended to read somewhat like `SRC V[Concept*SESSION];'_SESSION'; sessionAccount`

Note: the issue under (1) will be solved when violations, views and interfaces are treated in the same way. I would expect that then, the issue under (2) would result in a type-error.

**Comment by stefjoosten** [comment]
Nice! I was hoping it was something with my violation statements. I will try this and see if this fixes the problem.
