### ISSUE TITLE
REPRESENTATION type in Mindmaps.adl

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#247]
Since the transition to Haskell 7.10.3, Mindmaps.adl does not compile.
The erroneous files are found in AmpersandTarski/ampersand-models@048ebdb7169c7b56ce7aa00f02e0dd2adabb91eb.

The compiler objects against the DATE fields in Mindmaps.xlsx, for example: 

```
Representation mismatch
    Found: `42348.0`,
    as representation of an atom in concept `Moment`.
    However, the representation-type of that concept is (implicitly) 
    defined as ALPHANUMERIC. The found value does not match that type.
  "Mindmaps.xlsx":
   Sheet: Beweringen, B3
```

It does so for all DATE fields in the spreadsheet.

**Comment by hanjoosten** [comment]
@sjcjoosten This is introduced by the integration of the REPRESENT into the type system. The parser of excel will return a numeric value for the date. Since it does not know the representation at parsetime, that should be OK. I will look into this if I have time, but maybe you know what is going on sooner.

**Comment by hanjoosten** [comment]
Looking at the code, this has been solved somewhere long ago. If you don't agree, feel free to reopen this issue.
