### ISSUE TITLE
Default CRUD

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#253]
As discussed with @Michiel-s today, the following tasks should be built:

 * [x] The default for CRUD syntax will be all uppercase 
 * [x] This can be overwritten by means of a new **temporary** switch: --crud-defaults=<CRUD>  (where <CRUD> is to be replaced with a string containing the word `crud` in the appropriate upper/lower case.~~
 * [x] ~~In settings.json, the defaults should be shown.~~
 * [x] In the appropriate .json files and Generics.php, CRUD-variables may no longer be `null`.

**Comment by hanjoosten** [comment]
Related to issue #228

**Comment by RieksJ** [comment]
Nice that we will have the CRUD syntax. However, I do not like the `--crud-default`-switch, because its use implies that the INTERFACE specification becomes ambiguous, making it more difficult to re-use them in other applications/contexts. Instead (or: additionally), I would like to be able to define a default CRUD per INTERFACE, e.g. as follows:

     INTERFACE "ifc name" : DEFAULT {CRUD}  {expression} {CRUD}  -- etc.

Where:
* {CRUD} is a CrUd-tyntax
* the `DEFAULT {CRUD}` tells you what the default is for `"ifc name"`
* the other `{CRUD}` specifies the CRUD actions on the target of the preceeding `{expression}`

**Comment by hanjoosten** [comment]
The idea of the --crud-default is to lift the pain of having default "CRUD". @Michiel-s said that the switch would allow you guys at TNO to use your own default. 

The additional syntax for interfaces is something we should consider separately. This affects VIOLATION and VIEW statements as well, so this should move to issue #133 , I guess.

**Comment by RieksJ** [comment]
Yes. And we will use our own default, implying that interfaces that you guys and us guys define will behave differently. At this point in time, that's not an issue. As time progresses, and use will become more prevalent, it may or may not become an issue.

W.r.t. VIOLATION and VIEW statements, I do not see a major problem. Syntax is already context-dependent: the `U` in crUd for example is forbidden in the presence of a Scalar target atom. I don't see why it could not be forbidden (if that were necessary) in the context of a VIOLATION or VIEW statement. Alternatively, we could make it an attribute of Zwolle interfaces, e.g.:

    <Zwolle for="Manager" whenMissing="Sorry, you are not a manager" crud="CrUd">

**Comment by stefjoosten** [comment]
I dislike the option `--crud-default=`, because it is an external influence on the semantics of a script. It allows us to have two different semantics for one script. This is bound to confuse users. I suggest to have "CRUD" as the default for any missing crud-annotation. In this way we can tell the students and other users that doing nothing will give them everything. Adding "CRUD" gives them no restriction and switching any character to lowercase will restrict the functionality.

**Comment by hanjoosten** [comment]
Spoken to @Michiel-s . I'll do this in the branch `branch_#228`

**Comment by hanjoosten** [comment]
link to issue #228

**Comment by hanjoosten** [comment]
@Michiel-s, I added the temporary --crud-defaults switch as we discussed last week. (in the branch)

**Comment by hanjoosten** [comment]
The rest of what should happen is in issue #141 , so this issue can be closed. If you think that is too early, go ahead and reopen this issue. Please motivate.
