### ISSUE TITLE
Security in Production

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#271]
This page has been moved to our book. [See here](https://ampersandtarski.gitbooks.io/documentation/prototypes/limitations-and-features.html). The reason behind this is that this is not an issue, but has to do with the current status of security wrt Ampersand. Of course, the book should be updated when the status of Ampersand wrt security grows more mature.

**Comment by sjcjoosten** [comment]
It is quite easy to check whether some SQL injection attack has been implemented. Enter ```'\``` in some field. If it comes out looking the same way as it came in, at least something has been done to handle the input correctly (some people still make mistakes in how to handle the input, so it's not a guarantee of security, but it does show that it has not been forgotten).

Another injection attack is the HTML injection. This can be tested by entering something like ```&quot;"><img />```.

Then there is cross site scripting. The issue is as follows:
Say our server is server A, for Ampersand, and our user B, for Bob, is logged in: there is a current session, and the cookie is in his browser.
Now Bob goes to server E (for Eve), without logging out first, and Server E is malicious: it contains a frame or something with a carefully crafted URL. When B receives the page from E, his browser will see the frame and make a request from B to A, that causes Bob to do something on A without him knowing it. Some browsers have some mechanisms to prevent this, but since we do not want to force Bob to be on a certain browser, we should really prevent it at the A side. The issue with this is that preventing it also makes it any external API a bit harder to use. My guess is therefore that this type of attack is not prevented.

Concerning your link: all of the defence options boil down to "Defence Option 3" with database specific escaping, but Option 1 and Option 2 are ways to use built-in functionality that does exactly this through an API that prevents you from forgetting it. Ampersand provides a similar API that prevents you from forgetting it, albeit possibly a more restrictive one.

I would summarise that yes, security of our generated applications is important, but no, let's not focus on SQL injections too much, it is just one of the things that must be secure, and I'm guessing that it already is.

**Comment by stefjoosten** [comment]
There is a subtle difference here: being secure is one thing, being able to show (and explain) that it is secure is a different thing. I have made this issue for the latter purpose.

________________________________________
Van: Sebastiaan Joosten <notifications@github.com>
Verzonden: woensdag 13 januari 2016 12:32
Aan: Joosten, Stef
Onderwerp: Re: [ampersand] SQL-security (#271)

It is quite easy to check whether some SQL injection attack has been implemented. Enter '\ in some field. If it comes out looking the same way as it came in, at least something has been done to handle the input correctly (some people still make mistakes in how to handle the input, so it's not a guarantee of security, but it does show that it has not been forgotten).

Another injection attack is the HTML injection. This can be tested by entering something like &quot;"><img />.

Then there is cross site scripting. The issue is as follows:
Say our server is server A, for Ampersand, and our user B, for Bob, is logged in: there is a current session, and the cookie is in his browser.
Now Bob goes to server E (for Eve), without logging out first, and Server E is malicious: it contains a frame or something with a carefully crafted URL. When B receives the page from E, his browser will see the frame and make a request from B to A, that causes Bob to do something on A without him knowing it. Some browsers have some mechanisms to prevent this, but since we do not want to force Bob to be on a certain browser, we should really prevent it at the A side. The issue with this is that preventing it also makes it any external API a bit harder to use. My guess is therefore that this type of attack is not prevented.

Concerning your link: all of the defence options boil down to "Defence Option 3" with database specific escaping, but Option 1 and Option 2 are ways to use built-in functionality that does exactly this through an API that prevents you from forgetting it. Ampersand provides a similar API that prevents you from forgetting it, albeit possibly a more restrictive one.

I would summarise that yes, security of our generated applications is important, but no, let's not focus on SQL injections too much, it is just one of the things that must be secure, and I'm guessing that it already is.

�
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/271#issuecomment-171261291>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by sjcjoosten** [comment]
I was fearing that that would be the reason... Well, as I wrote: Ampersand provides a similar API that prevents you from forgetting it, albeit possibly a more restrictive API. This means that as far as Ampersand goes, it offers a nice ```secure layer``` into which arbitrary strings may be entered, which will prevent SQL-injection actions from happening. The key point is to position Ampersand's API as a more convenient alternative to the prepared statements and stored procedures approaches. This is how you "show" it. Of course, the real security risks then comes from mistakes in the API's service layer.

**Comment by RieksJ** [comment]
AFAIK, we currently use Ampersand for the purpose of fleshing out functional specifications, not for creating production software. For that purpose, there is no need to be secure at the SQL level.

Having said that, purpose-creep may cause the purpose to slide more towards the generation of actual production software. But then we should care about many more issues (e.g. performance on large populations, transitive closures etc.). How about documenting some (future) purposes, and create a list of issues that need to be addressed for each of such purposes?
