### ISSUE TITLE
Transaction Theory

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#279]
This issue is a discussion about the fundamentals of Transactions. In this issue, we can discuss freely about this topic.

In https://www.gitbook.com/book/ampersandtarski/documentation/edit#/edit/master/modeling/transaction%20theory.md I want to collect the insights that are developed in a more definitive form. The documentation must emerge from that. I hope it works.

First of all, I want @sjcjoosten to add a concrete proposal to that chapter, because he has something in mind. I am sure @WolframKahl will have ideas, because this topic is about consolidation of ECA-rules in the language. From a more practical point of view, I expect that @RieksJ, @hanjoosten and @Michiel-s  will have many ideas too, based on their experiences with the exec-engine, interfaces and applications made in the recent past. I want to ask everyone to bear with the theorists for a while, and wait a little to see what comes from that. As soon as practice kicks in, I will open a wider discussion. For the time being, feel free to add your comments to this issue, so no good ideas (and bad ideas) will get lost by accident.

**Comment by sjcjoosten** [comment]
Thank you Stef for the setup. I moved your changes to a separate branch: "WithTransactions". Choosing the branch happens in the top right hand corner. This way, the master branch can describe Ampersand as it is, while we are working on the documentation of Ampersand as it will be.

**Comment by sjcjoosten** [comment]
I put my 2 cents in the gitbook. Basically, I propose to add rules to interfaces (much like CRUD is added to interfaces, but with the RULE-syntax), where ``pre(..)`` and ``post(..)`` must be written around every expression.

Rules of the form ``post(relation) = pre(..)`` can definitely be translated into automatic functionality, as such rules describe the new value of ``relation`` exactly. The ampersand engine can try to rewrite the rules to that form as much as possible. On runtime, we might consider using some sort of SAT-solving techniques to determine whether ``post(relation)`` is uniquely determined by the rules and by what the user already entered about ``post(otherstuff)``.

Note that this approach is so general, that the current execEngine rules could be neatly expressed in this form:
``post(someRelation) = pre(someRelation) - stuffThatNeedsToBeDeleted \/ stuffThatNeedsToBeInserted``
There are two exceptions to this:

1. execEngine rules that caused a chain of events cannot be expressed this way, or rather: this new approach does not take steps recursively. You should express everything in one step.
2. execEngine rules that used to change pairs that are not visible in the interface, may not work. I'm not sure about this one, since it is very implementation dependent. In any case, if there is any non-determinism outside of what you can see, there is a problem (although we might consider showing relations that fall outside of the visible region in such cases)

**Comment by stefjoosten** [comment]
Great! I ought to have thought of that myself (but apparently I am still human). Thanks for pointing it out and taking the action.

Stef Joosten

M +31 (0)6 51348895
skype: stef.joosten



-----Oorspronkelijk bericht-----
Van: Sebastiaan Joosten [mailto:notifications@github.com]
Verzonden: zondag 17 januari 2016 19:24
Aan: Joosten, Stef
Onderwerp: Re: [ampersand] Transaction Theory (#279)

Thank you Stef for the setup. I moved your changes to a separate branch: "WithTransactions". Choosing the branch happens in the top right hand corner. This way, the master branch can describe Ampersand as it is, while we are working on the documentation of Ampersand as it will be.

—
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/279#issuecomment-172360894>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by stefjoosten** [comment]
(1) `'TopStack'` is a stack, because `'TopStack';V[Stack]` is well typed.
(2) `'TopStack'` is a `NonEmptyStack`, because `'EmptyStack' = I[Stack] - I[NonEmptyStack]`.
(3) Every `NonEmptyStack` has one item, because `item` is a function.
(4) `'TopStack'` has one item, because (2) and (3).
(5) The script does not define the item that is associated with `'TopStack'`, so this script contains a violation of the totality of `item`.

**Comment by sjcjoosten** [comment]
Ah yes, I assumed that 'TopStack' and 'EmptyStack' would be allowed to be the same stack, this is not necessarily true of course. So the script forbids the topstack to be empty. However, the script does not contain a violation of the totality of item, it's just that the population of item has not been specified (and indeed, there should be some item that belongs to topstack if it is nonempty). Also, the relation substack has to be filled in for 'TopStack' as well. I'll change the example slightly such that 'TopStack' and 'EmptyStack' can overlap.

**Comment by sjcjoosten** [comment]
I'm assuming https://www.gitbook.com/book/ampersandtarski/documentation/edit#/edit/WithTransactions/modeling/transaction%20theory.md closes this issue
