### ISSUE TITLE
Normalizer takes forever to compile a script

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#280]
Consider the following script

```
 CONTEXT Issue280 IN ENGLISH

 RELATION p[A*B] [UNI,TOT]
 RELATION q[A*C] [UNI]
 RELATION r[B*C] [UNI]
 RELATION s[A*C] [UNI]
 RELATION t[B*C] [UNI]

 RULE "Issue280":
    (q;V /\ p;(I-r;r~)) \/ (p /\ q;-I;r~)
 \/
    (s;V /\ p;(I-t;t~)) \/ (p /\ s;-I;t~)
 |- -V

 ENDCONTEXT
```

When I try to compile this script using Ampersand v3.2.0[HEAD:9f8f087](mid december 2015), it keeps wanting memory and does not (seem to) terminate. Note that when you remove either the term with the `pref`-stuff or that with the `post`-stuff, it does not have any problems.

**Comment by hanjoosten** [comment]
I bet this is a normalizer issue.

**Comment by hanjoosten** [comment]
# Diagnosis

Now I have the proof: It is a normalizer issue. I have shortened the above example. (names of concepts and relations reduce to something of length 1. With this script, it turns out that at some time, in the function `normDNF` (NormalForms.hs), the new DnfClause is called with an expression. The function `(foldr1 (.\/.)) (conss dc) returns an expression:

```
(-(p;(I[B] - r;r~)) /\ -(q;-I[C];r~) /\ -(p;(I[B] -t;t~)) /\ -(s;-I[C];t~))
 \/ 
(-(p;(I[B] - r;r~)) /\ -(q;-I[C];r~) /\ -(p;(I[B] -t;t~)) /\ -p)
 \/ 
(-(p;(I[B] - r;r~)) /\ -(q;-I[C];r~) /\ -(s;V[C*B]) /\ -(s;-I[C];t~))
 \/ 
(-(p;(I[B] - r;r~)) /\ -(q;-I[C];r~) /\ -(s;V[C*B]) /\ -p)
 \/ 
(-(p;(I[B] - r;r~)) /\ -p /\ -(p;(I[B] - t;t~)) /\ -(s;-I[C];t~))
 \/ 
(-(p;(I[B] - r;r~)) /\ -p /\ -(p;(I[B] - t;t~)))
 \/
(-(p;(I[B] - r;r~)) /\ -p /\ -(s;V[C*B]) /\ -(s;-I[C];t~))
 \/ 
(-(p;(I[B] - r;r~)) /\ -p /\ -(s;V[C*B]))
 \/ 
(-(q;V[C*B]) /\ -(q;-I[C];r~) /\ -(p;(I[B] - t;t~)) /\ -(s;-I[C];t~))
 \/ 
(-(q;V[C*B]) /\ -(q;-I[C];r~) /\ -(p;(I[B] - t;t~)) /\ -p)
 \/ 
(-(q;V[C*B]) /\ -(q;-I[C];r~) /\ -(s;V[C*B])/\ -(s;-I[C];t~))
 \/ 
(-(q;V[C*B]) /\ -(q;-I[C];r~) /\ -(s;V[C*B]) /\ -p)
 \/ 
(-(q;V[C*B]) /\ -p /\ -(p;(I[B] - t;t~)) /\ -(s;-I[C];t~))
 \/ 
(-(q;V[C*B]) /\ -p /\-(p;(I[B] - t;t~)))
 \/ 
(-(q;V[C*B]) /\ -p /\ -(s;V[C*B]) /\ -(s;-I[C];t~))
 \/ 
(-(q;V[C*B]) /\ -p /\ -(s;V[C*B]))
```

Then, that expression is used in `disjNF opts expr`. There is no result It takes forever. 

When the same script is run using the new normalizer, ampersand exits within a reasonable amount of time.

**Comment by hanjoosten** [comment]
# Other findings
In the script, there is a subexpression ```(p /\ q;-I;r~)```. Since there are no CLASSIFY statements, the expression ```q;-I``` can never have any population at all. For that reason, ```(p /\ q;-I;r~)``` cannot contain any population either.   this same reasoning goes for ```(p /\ s;-I;t~)```. 

Hence, there could be some rewriting done:

```
     RULE "Issue280":
        (q;V /\ p;(I-r;r~)) \/ (p /\ q;-I;r~)
     \/
        (s;V /\ p;(I-t;t~)) \/ (p /\ s;-I;t~)
     |- -V
```

could be rewritten as 
```
     RULE "Issue280":
        (q;V /\ p;(I-r;r~))
     \/
        (s;V /\ p;(I-t;t~))
     |- -V
```

**Comment by hanjoosten** [comment]
@stefjoosten, will you fix this normalizer issue?

**Comment by hanjoosten** [comment]
With ampersand v3.10.0 it compiles in less than a second, so this problem has been solved some time ago.

I added this script as a testcase in travis. When something changes in future that causes this problem to re-appear, travis will notice by being slow.
