### ISSUE TITLE
Problems with ExecEngine rule evaluation?

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#295]
I created a protype (using Ampersand v3.2.0[HEAD:9f8f087]) from the following script:

~~~
CONTEXT "Bug295" IN ENGLISH

IDENT Persona: Persona(pActor,pParty) -- a 'Persona' is the combination of a Person and Organization.
pActor :: Persona * Person       [UNI,TOT]
pParty :: Persona * Organization [UNI,TOT]

ROLE ExecEngine MAINTAINS "Auto delete incomplete Persona"
RULE "Auto delete incomplete Persona": I[Persona] /\ pActor;pActor~ /\ pParty;pParty~
VIOLATION (TXT "{EX} DelAtom;Persona;", SRC I[Persona])

accPerson  :: Account * Person       [UNI]   
accOrg     :: Account * Organization [UNI]   
accPersona :: Account * Persona      [UNI]

ROLE ExecEngine MAINTAINS "If an account has a Person and Organization, there must be a corresponding Persona"
RULE "If an account has a Person and Organization, there must be a corresponding Persona":
   accPerson~;accOrg |- pActor~;pParty
VIOLATION (TXT "{EX} NewStruct;Persona"
               ,TXT ";pActor;Persona;_NEW;Person;",       SRC I[Person]
               ,TXT ";pParty;Persona;_NEW;Organization;", TGT I[Organization]
          )     

POPULATION accPerson CONTAINS [ ("Acc_1", "Ad Min") ]
POPULATION accOrg    CONTAINS [ ("Acc_1", "Organo") ]
POPULATION accPerson CONTAINS [ ("Acc_2", "Be Pos") ]
POPULATION accOrg    CONTAINS [ ("Acc_2", "Organo") ]

ENDCONTEXT
~~~

When initializing the database using the specified population, there are too many reruns of the ExecEnging. It keeps finding both rules to be in violation. When I discard Account `Acc_2`, then there is no problem (and a Persona is created like you would expect).

**Comment by stefjoosten** [comment]
Hi @Rieks,
From the phrase `MAINTAINS "Auto delete incomplete Persona"`, I guess that you intend to have a rule with `MEANING "Every Persona must have a pActor and a pParty."`. So, I think you intended to write
(1)  `RULE "Auto delete incomplete Persona": I[Persona] |- pActor;pActor~ /\ pParty;pParty~`
instead of
(2)  `RULE "Auto delete incomplete Persona": I[Persona] /\ pActor;pActor~ /\ pParty;pParty~`

Rule (1) means what you intended. Rule (2) means: Everything is a `Persona` and has a `pActor` and a `pParty`. That explains the behaviour you saw.

In the generator, I tried replacing rule (1) by rule (2). That helps! In any case all symptoms are gone and the database population behaves as I expect it to.

# Reflection
I have run into similar mistakes regularly. I know the feeling it produces: "Ampersand is buggy GRRRR". I get stuck without realising that it is my own fault. Can we make Ampersand point in a more helpful direction? Is there anything we can do to guess the user's intentions?

# Closure
Rieks, would you close this issue if this answer solves your issue?
Cheers,
Stef

**Comment by RieksJ** [comment]
Yes it does. Your suggestion about the rule I intended is right. In retrospect, it's (again) one of these 'stupid' things that happen (regularly, alas). These things seem to be unavoidable (for me, at least). It is good to see that some (minimal) documentation about intentions helps (others) to find my bugs. Great. 

As another pondering, it is obvious that the rule you suggest does not rewrite to the rule I had, and so are different. Makes me think about how I came to write my rule, noticing that I have written rules 'your style' so many times already. Seems that if I see an expression `r[A*B]` I interpret it as: for all a \elem A and b \elem B, r(a,b) is true. Applying that on `I[Persona] /\ pActor;pActor~ /\ pParty;pParty~` that would then be: for all p,p' \elem Persona, we have: p = p' AND there is an actor for p AND there is a party for p. That is a different wording from what you say, namely that every atom that exists must be \elem Persona.

**Comment by WolframKahl** [comment]
On Sat, Jan 30, 2016 at 11:15:50PM -0800, Stef Joosten wrote:
> Hi @Rieks,
> >From the phrase `MAINTAINS "Auto delete incomplete Persona"`, I guess that you intend to have a rule with `MEANING "Every Persona must have a pActor and a pParty."`. So, I think you intended to write
> (1)  `RULE "Auto delete incomplete Persona": I[Persona] |- pActor;pActor~ /\ pParty;pParty~`
> instead of
> (2)  `RULE "Auto delete incomplete Persona": I[Persona] /\ pActor;pActor~ /\ pParty;pParty~`
> 
> Rule (1) means what you intended. Rule (2) means: Everything is a `Persona` and has a `pActor` and a `pParty`. That explains the behaviour you saw.

I always thought that a relational expression R used as a formula, which includes use as a `RULE`, means that $R = V$.
Is this correct?

(But $I = V$ only very rarely... With that reading, (2) even means: Every two things are the same `Persona`, and have the same `pActor` and the same `pParty`.)

(Personally, I also find imperative rule names like "Auto delete incomplete Persona" strange in the declarative Ampersand setting; even the phrase `MAINTAINS "Auto delete incomplete Persona"` sounds funny from that perspective, since `MAINTAINS` seems to demand a descriptive statement, not an imperative command. How about "Persona completeness", which would fit better with the `MEANING` mentioned above.)


Wolfram

**Comment by stefjoosten** [comment]
Hi Wolfram,
You are right. The meaning of `RULE I[Persona] /\ pActor;pActor~ /\ pParty;pParty~` is odd. Yet, an author is free to write down any expression as a rule.

From `V[X*X]=I[X]` follows that `X` contains at most one element. This means that Rieks' rule can contain at most one `Persona`, which must have a `pActor` and `pParty`.
