### ISSUE TITLE
Test on proper partitioning rule does not work

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/ampersand#298]
```
-- Klant, KlantRol en Beheerder zijn disjuncte deelverzamelingen van Identiteit
CLASSIFY Klant ISA Identiteit
CLASSIFY KlantRol ISA Identiteit
CLASSIFY Beheerder ISA Identiteit
RULE identiteiten : I[Identiteit] 
    =  (((I[Identiteit] - I[Beheerder])-I[KlantRol]) )
    \/ (((I[Identiteit] - I[KlantRol] )-I[Klant]))
    \/ (((I[Identiteit] - I[Klant]    )-I[Beheerder])) 
```

This should express the fact that no Identiteit can exist that is not a Klant, KlantRol or Beheerder.

(Of course, this could also be written as ```RULE I[Identiteit] = I[Klant] \/ I[KlantRol] \/ I[Beheerder]```, but that is not the point of this issue. )

When this rule is in effect, an Identiteit can be inserted that is none of the smaller concepts, which is wrong.

**Comment by WolframKahl** [comment]
Let
```
Pop(Identiteit) = {1,2,3,4}
Pop(Beheerder) = {1}
Pop(Klant) = {2}
Pop(KlantRol) = {3}
```
Then your rule holds: ```4`` is in all three disjuncts.

For your English formulation,. actually 
```
I[Identiteit] |- I[Klant] \/ I[KlantRol] \/ I[Beheerder],
```
would be more natural.

**Comment by stefjoosten** [comment]
I wonder what is going on here. @hanjoosten, do you have a test script for this issue to share with us?

# Hypothesis
Could it be that the compiler treats `I[Identiteit] |- I[Klant] \/ I[KlantRol] \/ I[Beheerder]` as an assumption, because it is (erroneously) considered to be derivable from the ISA statements in the script. Could it be that it generates no code as a result of that assumption? We should check this in generics.php with Han's test script.

**Comment by hanjoosten** [comment]
I added a even more simple example, which fails as well. 

```
CLASSIFY Even ISA Natural
CLASSIFY Odd  ISA Natural

POPULATION Natural CONTAINS ["thisShouldFail" , "one" , "two"]
POPULATION Even    CONTAINS ["two"]
POPULATION Odd     CONTAINS ["one"]


RULE ruleTwo : I[Natural]
   |- ( I[Natural] - I[Even])
   \/ ( I[Natural] - I[Odd])
```

**Comment by hanjoosten** [comment]
## Diagnose

The normalizer does the following steps, before the SQL generator is called:

```
Normalization steps:
     -(-I[Natural] \/ I[Natural] - I{-Eps-}[Even];I[Even];I{-Eps-}[Even] \/ I[Natural] - I{-Eps-}[Odd];I[Odd];I{-Eps-}[Odd])
 <=> { De Morgan }
     I[Natural] /\ -(I[Natural] - I{-Eps-}[Even];I[Even];I{-Eps-}[Even]) /\ -(I[Natural] - I{-Eps-}[Odd];I[Odd];I{-Eps-}[Odd])
 <=> { Avoid complements, using law x/\-y = x-y }
     (I[Natural] - (I[Natural] - I{-Eps-}[Even];I[Even];I{-Eps-}[Even])) - (I[Natural] - I{-Eps-}[Odd];I[Odd];I{-Eps-}[Odd])
 
```

**Comment by stefjoosten** [comment]
As far as I'm concerned, this test file should not be in ShouldFail, because
I[Natural] - I[Even] = {"thisShouldFail" , "one"} and I[Natural] - I[Odd] = {"thisShouldFail" , "two"}, so the union of the two equals I[Natural].

**Comment by WolframKahl** [comment]
From
```
CLASSIFY Even ISA Natural
CLASSIFY Odd  ISA Natural
```
we have:
```
I[Even]   |-  I[Natural]
I[Odd]    |-  I[Natural]
```
Together with
```
RULE ruleTwo : I[Natural]   |- ( I[Natural] - I[Even])    \/ ( I[Natural] - I[Odd])
```
we obtain (since ```(A - B) ∩ B = ∅```):
```
I[Even]   |-  I[Natural]
          |-   (I[Natural] - I[Even])    \/ ( I[Natural] - I[Odd])
          |-   I[Natural] - I[Odd]
```
, and analogously:
```
I[Odd])  |- I[Natural] - I[Even]
```

Conversely, from ```I[Even]   |- I[Natural] - I[Odd]``` and ```I[Odd]  |- I[Natural] - I[Even]``` we obtain:
```
I[Natural]    |-  (I[Natural] - I[Even])   \/  I[Even]
              |-  (I[Natural] - I[Even])   \/ ( I[Natural] - I[Odd])
```
So, in the presence of the two ```CLASSIFY```s, the ```RULE ruleTwo``` is just equivalent to:
```
I[Even]   |- I[Natural] - I[Odd]
I[Odd])_  |- I[Natural] - I[Even]
```
And, in the presence of the two ```CLASSIFY```s, this is furthermore equivalent to:
```
I[Even]  /\ I[Odd] = ∅
```
So rules of the shape of the rules ```ruleTwo``` and ```identiteiten``` only assert disjointness, but say nothing about completeness of the intended partition.

In short, I think there is no issue here (as I had hoped to establish already with my first post here...), and I suggest closing this.

**Comment by stefjoosten** [comment]
I agree with Wolfram
