### ISSUE TITLE
Enhancement: Enforcement statement.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#311]
Currently, we have two ways of enforcing rules: Invariant or by a role that maintains it. The Invariant is the default. Lex Wedemeijer has suggested a long time ago to uncouple enforcement from the declaration of a rule.

There are other ways of enforcement. e.g. by computing the population of a relation. There could be more enforcement types possible in the future.

Enabling a rule to derive the population of a relation has been asked for by @RieksJ. Currently, this can be done by using the ExecEngine. There is a well known pattern while writing this for the ExecEngine: The _equivalence pattern_.

I've discussed this with @stefjoosten the other day. As result of this discussion, we propose a syntax.

**Comment by hanjoosten** [comment]
# ENFORCE statement

![enforcement](https://cloud.githubusercontent.com/assets/1159672/13042287/46d0a280-d3bf-11e5-9cd7-6ccff0fc5329.png)

There can be at most one ENFORCE statement for any rule. The semantics will depend on the subtype:

 * INVARIANT is the default for a rule. The modeler can choose to make it explicit. Violations are rejected by the database. 
 * MAINTAINEDBY will replace the current MAINTAINS statement. Violations are thrown to the mentioned roles.
 * DERIVE will do an automated task. The rule will require to be of a specific format: Either 
    * ```relation = <Expression> ``` or
    * ```<Expression> = relation```.
The relation will be derived using the expression. Obviously, checks will be required to assure that no loops can be introduced in the derivation. Maybe it will be possible (later on) to add more formats for rules in the derivation subtype. The firstmentioned subtype is assumed when the optional relation is absent.

**Comment by RieksJ** [comment]
Currently, the ExecEngine is a ROLE, and hence fits the paradigm of having rules that are either invariants and or process-rules, i.e. rules to which one or more ROLEs are assigned for the purpose of MAINTAINing them, and VIOLATION-statements that provide the guidance for instances of such ROLEs for MAINTAINing the RULEs. I suggest we stick to this paradigm, since (a) it does not preclude us from specifying ROLEs other than the ExecEngine, and (b) it reminds us of the ongoing discussion on the integration of INTERFACEs, VIEWs and VIOLATIONs. Thus, I would change the syntax as follows:

* Do not require 'INVARIANT' in the absence of other syntax parts, as it is implicit.
* I suggest to replace the 'DERIVE' part by a more generic means for providing assistance to the ROLEs that must MAINTAIN the rule. This may be texts, interluded with variables as discussed in the last nerd-weekend, as well as INTERFACEs of various kinds. Such texts (both the 'fixed'/predefined/hardcoded texts and the data that is derived from the violation) may depend on the ROLE that maintains the rule, thus allowing instructions not only to be customized for different roles, but also provide different means of resolving violations

**Comment by hanjoosten** [comment]
It is a good point of bringing up the VIOLATION-statement part of the current RULE statement. It shows that we need to rethink ( = create an &-model for this enhancement!) that too. Currently, the statement has different purposes:
 * For invariants: Show the reason that the user isn't allowed to do whatever he is doing.
 * For process rules: Show guidence to solve the violation.
For derivations, there is no message required at all. 

your first bullet: ```Do not require 'INVARIANT' in the absence of other syntax parts, as it is implicit.``` of course: there can be at most one ENFORCE statement for any rule. The INVARIANT is the default.

I suggest that we discuss this enhancement by phone first, as Stef and I did. This should result in an ampersand model about this topic.

**Comment by RieksJ** [comment]
I would like to widen the discussion to the specification of RULEs themselves, as this also includes the currently existing `PURPOSE`, `MEANING` and `MESSAGE` constructs that may be relevant in the discussion.

**Comment by WolframKahl** [comment]
>  * DERIVE will do an automated task. The rule will require to be of a specific format: Either 
>     * ```relation = <Expression> ``` or
>     * ```<Expression> = relation```.
> The relation will be derived using the expression.

Is this meant as an assignment? If yes, I would strongly advocate using ```:=``` instead of ```=```.
If yes, I also find ```DERIVE``` a suprising name.
(Satisfying an equality ```R = E``` is, at leasts sometimes, possible in different ways than by assigning ```E``` to ```R```.)

What special syntax and variables are avialable in the expression, and how are the evaluated?
(E.g., anything like ```\old(R)```?)

What is the intended relationship between the rule itself and the ``relation = <Expression> ``` in the DERIVE clause?


Wolfram

**Comment by RieksJ** [comment]
After discussion with Stef, I have the following suggestions:

1. In the `MAINTAINEDBY` clause, at at least one `ROLE` MUST be specified, as well as one `VIOLATION` statement, since such statements provide the man or machine that is supposed to maintain the rule with precise instructions (for machine enforcements) or with guidance (for human enforcements) as to how to maintain/enforce the rule.  
2. Rename `MAINTAINEDBY` to `ENFORCEDBY`, so as to emphasise that they are actually enforcing the rule. 
3. Rename `DERIVE` to `COMPUTING` (which better says what's going on, and personally I have some nostaltic reasons)
4. The `COMPUTING` clause MUST then mention at least one relation, each of which MUST occur in the rule that is being enforced. 
5. The idea is to have `enforcers`, examples of which are the invariant-enforcer (that rolls back a transaction if the rule is violated, optionally providing an error message), human-enforcers (denoted by rolenames, and given instructions using the violation-statments), the 'computing-enforcer', that attempts to repair any violations by (de)populating the named relations (returning an error if that cannot be done in a unique way). The idea of having enforcers paves the path to future extensions to other means of enforcement, without this leading necessarily to a (further useless) classification of rules or enforcements.

**Comment by hanjoosten** [comment]
@WolframKahl : The idea is to make a cleaner distinction between a rule (= an expression that is supposed to be True) and it's enforcement (what to do with violations). The discussion about all of this is  broader that can be written down effectively in this issue. I invite you to participate by using Skype. I know @stefjoosten will be looking forward to hearing of you.

**Comment by hanjoosten** [comment]
@RieksJ I discussed a proposal for the syntax with Stef. Most of your points will be in there. I will replace the syntax diagram above in the very near future.

**Comment by stefjoosten** [comment]
Lex has written down some fresh ideas on this topic. Here is the draft paper.
[2016BMSD_LexWedemeijer_aMetaModel for BusinessRules with AccessControl.pdf](https://github.com/AmpersandTarski/Ampersand/files/241828/2016BMSD_LexWedemeijer_aMetaModel.for.BusinessRules.with.AccessControl.pdf)
Lex has submitted this to a (small) congress on Rhodos.

**Comment by hanjoosten** [comment]
That's cool. An overview of a related (earlier) work can be found [here](http://www.ou.nl/documents/987531/41f1ce32-2982-43f5-a173-cbc754e7773d). Is that paper available somewhere?

**Comment by hanjoosten** [comment]
@stefjoosten and I had a conversation on this topic, triggered by the fix that caused issue #345. We conclude that the concept `Enforcement` should be made more explicit. We currently see four types of enforcement. The above mentioned three, where Invariants can come in two types:
1) The invariant is enforeced by means of the structure of the database: e.g. when a relation r[A*B] is stored in the database in the concepttable of A (because r is univalent). The structure of the database enforces the UNI rule.
2) An invariant can be enforced, by some implicit action. When some relation r is both TOT and UNI, it still could be possible to do an insert of a new tuple and a delete of another tuple, as long as this happens in a single transaction. In the screen (the interface) a single field could be used. Whenever the user changes the value in the field, the new value is inserted, and implicitly the old value should be removed. 

(and beside these two variants of an invariant, we have the automated derivation and the enforcement by signalling some role)

@stefjoosten also came up with the idea that the enforcement could be different depending on the context. He will elaborate on this soon.

**Comment by RieksJ** [comment]
I would like to point out that #398 has some things to say about this, too.
In particular, that the issue we seem to be dealing with here may need some attention from the perspective of havving 'belly-contexts' and 'interface-contexts'.

My suggestion would be that 
- in a 'belly-context', invariants are maintained by the database.
- in an 'interface-context', invariants may (temporarily) be violated, which is useful since the purpose of interface-contexts is to act in 'discussions' between two contexts for the purpose of reaching the appropriate agreement that can be committed into the 'belly-context'.

**Comment by sjcjoosten** [comment]
My 2c: there are three categories, each has three ways to deal with violations of a given rule R:

- The central database can either block if R is violated, or call the exec-engine to fix R (and then make sure R is not violated), or just allow R to be violated
- Each interface can either block if R is violated (given that it can determine that), meaning that it will not get sent to the server, or have some automatic correction when R is violated (and then make sure it won't be sent to the server if it didn't help), or just allow R to be violated
- A user responsible for a rule can decide to reverse the transaction that caused R to be violated, take another action to fix R, or simply ignore it when R is violated.

Maybe the above simplifies if we view this as two actions: fix/block or allow, and add more categories. Note that various combinations can be useful:

- Maybe some of the interfaces correct R, but others do not.
- It was formerly allowed for R to be violated, but there may not be any new violations.
- The rest of the violations have to be fixed by R, although some may be left unfixed forever.

Can we get a better name for categories? I like 'role', or 'agent', but it might be strange to see the central database as such
