### ISSUE TITLE
Bug reading Excel files by generator (Ampersand)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#317]
When I define a concept to have an ALPHANUMERIC representation, 
and I populate it using an Excel file that is INCLUDEd in my script, 
and the cell contains a string consisting of digits, e.g. `1`, `10`, or `20000`,
then a `Representation mismatch` error is generated, as follows:

     Error(s) found:
     Representation mismatch
         Found: `10.0`,
         as representation of an atom in concept `VarValue`.
         However, the representation-type of that concept is
         defined as ALPHANUMERIC. The found value does not match that type.
       "_Profile_TGN_Autos verkopen.xlsx":
        Sheet: Profiles, C3
     ==============================
     Representation mismatch
         Found: `20000.0`,
         as representation of an atom in concept `VarValue`.
         However, the representation-type of that concept is
         defined as ALPHANUMERIC. The found value does not match that type.
       "_Profile_TGN_Autos verkopen.xlsx":
        Sheet: Profiles, C4

The error messages say that sequences of alphanumeric characters have been found, and that they include a dot followed by a zero. However, the cells contain the text strings `10` and `20000` respectively, and the cells are even formatted as containing texts. 
[picture1](https://cloud.githubusercontent.com/assets/8522589/13371288/d28aea1c-dd22-11e5-8675-31d1e62916ff.png)

**Comment by hanjoosten** [comment]
Excel has a lot of features, that we by design do not want to know about. This might be confusing. The picture1 you attached shows that you use a feature of Excel to look at a numeric value as if it were a string value. However, this does not change the type of that numeric value. It is a feature of Excel. 
In the interface of Excel to Haskell, there is no knowledge about the view. So we get a numeric value, independent of how you view it in Excel. 

Having said that, The good news for you is that we make an exception. When numeric values are found  in the .xlsx file, and the &-representation is `string-like`, then a conversion is done. This has been [implemented two weeks ago](https://github.com/AmpersandTarski/ampersand/pull/308).

**Comment by RieksJ** [comment]
The following figure shows how REPRESENT is specified/expected to work in different contexts. It says that irrespective of the source of a population (e.g. an Excel file, a keyboard, an &-script), if the concept to be populated is of type ALPHANUMERIC, then the source must be or become a string, and (only) if it is of type FLOAT must it be or become a float. 

![picture1](https://cloud.githubusercontent.com/assets/8522589/13373210/5200bc7a-dd61-11e5-9581-769a124726d9.png)

The good news seems to be that this more or less works for alphanumerics. @hanjoosten: Does it also work for the other REPRESENTations (e.g. FLOATs)? If not, I guess this issue should be reopened.

**Comment by hanjoosten** [comment]
In the table above, we could add .xlsx files. In such context, only text, float and bool exist.

**Comment by RieksJ** [comment]
Another option would be to create a new issue that tells us where the ampersand excel import deviates (or reopen this one). After all, the ExcelImporter (prototype extension) works fine in such cases.

**Comment by hanjoosten** [comment]
Go ahead. And please explain what problem it is you are looking for to eliminate. If you work with the current master, there should be no problem.
