### ISSUE TITLE
Database structure of INJ relations are still giving headaches

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/ampersand#318]
This issue is related to #169 

The whole processing of edit and delete on INJ relations is still not right. A couple of points that make it very hard to implement:
* In the new frontend, we do not have the previous/old target value of a modified expression.
* Expression can be relations that are flipped, which impacts the way it should be processed
* Relations can be administered in either the src table (UNI), tgt table (INJ) or n-n table (neither UNI nor INJ).
* Depending on whether the relation in TOT or SUR, the stable or modified column can be set to null ór the row should be deleted.
* ... some stuff I probably don't oversee right now.

@hanjoosten could you look into the option to administer INJ relations the same way as UNI relations, that is: **in the table of the src concept**? This would really simplify the code needed in the backend framework. It would also make the code understandable again.

**edit:**
In some strange way, a relation with INJ and UNI defined is already administered in the source concept table. However when I add the TOT constraint, it switches to the target concept table. So:
`r :: A * B [INJ,UNI]` --> in table A
`r :: A * B [INJ,UNI,TOT]` --> in table B

For me this is unpredictable behavior, as far as I know, the TOT and SUR shouldn't effect the db structure. What is going on here, please explain..

**Comment by WolframKahl** [comment]
On Sat, Feb 27, 2016 at 01:06:49AM -0800, Michiel-s wrote:
> could you look into the option to administer INJ relations the same way as UNI relations, that is: **in the table of the src concept**?

If a relation R from A to B is INJ but not UNI, any element a from the source concept A may be associated with multiple elements from the target concept. So unless you want to get into representation of multiple values in a single cell, this can only work for relations that are also UNI (which would mean that in the presence of both INJ and UNI, it is the UNI that determines the representation). (Or do you want to make the key of the table of the src concept consist of both A and B? Then all other columns of that table would suffer duplication.)

**Comment by hanjoosten** [comment]
There are some arbitrary choices made. as you have seen, 
Lets consider a relation r [A*B]. If the relation has no properties, the relation wil be administered in a separate binary table. 
If r is UNI, it is possible to administer r in the same table as A. However, if r is INJ, it is possible to administer r in the same table as B. If r is both INJ and UNI, r can be administered equally well in A as in B. There are some more things taken into account, but I have to check the code for details, for it is quite some time ago. In any way, it would not be right that the frontend would have to know the choices being made. They might even change in future. 
I think that in case r is both UNI and INJ, we once decided to put it into the table with the most attributes. This eliminates the amount of tables required. But I am not sure if we only had this idea or that we acutally implemented it that way. 
Let's see what @stefjoosten has to say about your request.

**Comment by Michiel-s** [comment]
> WolframKalf: If a relation R from A to B is INJ but not UNI, any element a from the source concept A may be associated with multiple elements from the target concept. 

I agree and understand. The problem is not with relations that are defined INJ, but for those that have a combination of INJ ánd UNI, TOT and SUR. I currently don't understand the logic behind where to expect it in the database. I do not agree with @hanjoosten about the backend not needing to know the choices being made here, since it influences the update and delete queries needed.

I'm looking forward for @hanjoosten to dive into the code and explain the logic. For know I see:

rel property | table | remark
--------------- | ------ | ---------
UNI | source | I understand
UNI, INJ | source | or not always?? @hanjoosten said something about the table with most columns?
UNI, TOT | source | I understand
UNI, SUR | source | I understand
UNI, INJ, TOT | target | **for me this is the odd one out**
UNI, INJ, SUR | source | I understand
UNI, INJ, TOT, SUR | source | I understand
INJ | target | I understand
INJ, TOT | target | I understand
INJ, SUR | target | I understand
INJ, TOT, SUR | target | I understand


note: I've only looked into the possible combination with at least a UNI or INJ, otherwise it's a n-n table.

**Comment by WolframKahl** [comment]
On Sun, Feb 28, 2016 at 05:05:57AM -0800, Michiel-s wrote:
> UNI, INJ, TOT | target | **for me this is the odd one out**
> UNI, INJ, SUR | source | I understand

For me, both of these are odd:

UNI without TOT in source requires optional entries,
while INJ with SUR in target does not require them.

Analogously, INJ without SUR in target requires optional entries,
while UNI with TOT in source does not require them.


Wolfram

**Comment by hanjoosten** [comment]
Wolfram wrote:
> UNI without TOT in source requires optional entries,

An optional entry in a database table is no problem at all. So UNI without TOT could perfectly be administerd in the table that holds the source of `r`. 
> while INJ with SUR in target does not require them.

Yes, this could be a better choice.

I have been looking for the code where this is taking place. It is the function `makeEntityTables` in `ADL2Plug.hs`. I think this code is not very elegant. The possibility is taken into account that not all relations are to be stored in SQL tables. (We have been experimenting with php plugs some time ago). 

In short what this function should do is to create an TblSQL for each typology (= group of concepts connected by CLASSIFY statements). Then, all user defined relations should be distributed among those TblSQLs. Each user defined relation must be in exacly one table, unless that relation is neither UNI or INJ. (Then such relation will need a BinSQL of its own). 

The distrubution could be pretty straitforward, as far as I can see. Lets decide by the properties of r[A*B]

| INJ | UNI | TOT | SUR | ConceptTable where r is stored |
|---|---|---|---|---|
| False | False | don't care | don't care | neither A or B. In a link table (BinSQL) |
| True | False | don't care | don't care | B |
| False| True | don't care | don't care | A |
| True | False | don't care | don't care | B |
| True | True | don't care | don't care | there is a choice, A or B would both do. |

This table can be found more or less the same in the sourcecode. (lines 363 to 370 of ADL2Plug.hs). But now I see how it is implemented: In some cases we don't store `r`, but we store `r~`. Hmmm. I think that that causes the trouble @Michiel-s is having. Technically, it is not wrong what is going on, but it is hard to explain. 

I have very little time in the next couple of weeks, otherwise I am very tempted to rewrite this function. @WolframKahl do you like to have a shot on it? ;-)

**Comment by hanjoosten** [comment]
I am looking into it currently. Not sure when I wil commit.

**Comment by stefjoosten** [comment]
I have talked with Han and Michiel separately about this. That has clarified some issues, I think. This stuff is too complicated for a GitHub discussion. In order to make more progress, I suggest a Skype session between Han and Michiel.

**Comment by stefjoosten** [comment]
Currently my helicopter-perspective is that the API needs knowledge about the back-end to make CRUD-functions (inserts, deletes, updates). For example, the API cannot decide when to use an UPDATE, because the JSON structure does not provide the key-fields of tables.

The right solution is to formulate the correct information in the JSON-structure, so that the API doesn't have to figure out anything.

For now, the practical solution is to use knowledge of how the table is built. I think the best way is that Han and Michiel solve this over Skype. Then we know exactly what information is needed in the API and we can reimplement it the way it should be..

**Comment by Michiel-s** [comment]
This issue is solved for now. There are still a very few combinations that can not be handled by the new frontend, because of missing 'previous' value of a link.

This applies to (sub)interfaces WHERE the relation is editable (crUd) AND the tgt of the expression is a scalar (i.e. with representation type) AND the interface expression is univalent AND ((the relation is flipped AND table in which the rel is administrated is src) OR (the relation is not flipped AND rel table is tgt)). In short: A complex situation and you will be informed by an info message (blue one) when it occurs
