### ISSUE TITLE
case-sensitivity in the API framework

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#320]
Since a few days I am getting a !404 Not Found error when installing a database. Here is a screen-shot:
![image](https://cloud.githubusercontent.com/assets/275768/13546047/3bcceb32-e2a1-11e5-9aa7-d72da660cbe7.png)

I have compiled Blik/Arch.adl from commit d257c85eb5aaa96efc195fc39bd9a41a65b0873f with Ampersand v3.4.0[master:6421e7f], build time: 03-Mar-16 15:32:08 West-Europa (standaardtijd). Then I copied the application to htdocs/Blik2/, because I wanted to run the application from that location.

@Michiel-s showed me that the !404 Not Found message comes from a capital sensitivity bug. It might show up in Windows only. The application has been moved (by hand) to the directory "Blik2" on the htdocs-directory, but the code was looking for "blik2" instead. Renaming the directory to "blik2"  helps by avoiding this issue.

**Comment by Michiel-s** [comment]
After consulting with Stef we found that this is caused by case-sensitivity of the API framework which is currently used in the master branch. The feature branch 228 will replace this old API framework by a new one. Probably this already solves the issue, but we'll keep this ticket open until we are sure.

**Comment by Michiel-s** [comment]
Ok. I've intensively studied this issue and can conclude the following:

### Diagnosis
The issue only occurs when:
- the application backend runs on a Windows machine, because the windows file system is case insensitive.
- and you use a virtual path to the application folder, e.g. http://localhost/**myapp**. When you place the application directly in the htdocs folder (i.e. no virtual path), there is no issue.
- and you approach the application by using the "wrong" casing for the virtual path (e.g. http://localhost/**MyApp**

### Analysis
In the situation where all of the above occurs, but the API framework we use (Slim v2) cannot match the routes, because the requested URI doesn't exactly match the physicalPath + registered route. This relates to the code in the constructor function of \Slim\Environment

### Possible solutions:
- Rewrite all requested urls to lowercase -> does not fix the problem, and causes other new issues
- Make Apache server case sensitive so that a wrong virtual path will not open the application -> not possible, because it relies on the OS. We cannot change Windows.
- Change the way the Slim framework matches routes -> we can suggest a non-case sensitive match for virtual paths, but since there are also many non-windows deployments, I don't think this change will be accepted.

### Conclusion
Although this is a shitty bug, we have to deal with it and navigate to the correct virtual path.
