### ISSUE TITLE
Application produces "! 405 Method Not Allowed: PUT is not allowed" error when using SIAM

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/ampersand#322]
When I use SIAM.adl in Blik/Arch.adl, instead of Login.adl, I get a disturbing message:
![image](https://cloud.githubusercontent.com/assets/275768/13707856/ff87d71c-e7ab-11e5-9ed6-c98467039ed1.png)
I suspect version management of this bug, because SIAM worked fine earlier on.

I have compiled Arch.adl with Ampersand v3.4.0[master:6421e7f], build time: 03-Mar-16 15:32:08 West-Europa (standaardtijd). Could it be that the version of SIAM.adl@59bbb04d6cf9b77fd43472306c3327e2ab0f61cb that I use works with the compiler in branch 228, but not in the Ampersand-master? @RieksJ do you have any idea?

**Comment by RieksJ** [comment]
This has nothing to do with SIAM.adl - it is related to front-end stuff. I had this error myself, and if I remember correctly, @Michiel-s fixed this in the ExecEngine.php file, which I then used locally for the time being as it is properly fixed in branch 228. Since I expect a pull request for this branch shortly, I suggest to wait for that fix or if you really need this urgently, to drop me a note so I can send you the repaired ExecEngine.php file.

**Comment by stefjoosten** [comment]
Thx!
Glad that SIAM is all right.
Is the implication that this is a version management issue?

**Comment by RieksJ** [comment]
I don't think so. I recall that it is an ordinary bug, something having to do with the coupling of session users and active roles in the frontend (what is shown in the menu and stuff).

**Comment by RieksJ** [comment]
In the current status of branch_#228, this is fixed (actually, for quite some time already).
