### ISSUE TITLE
ADL-agnostic (pre)Parser Directives

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#33]
For purposes such as:
1. (better) support testing (e.g. to conditionally include/select test populations), 
2. facilitate the compilation of different prototypes and/or fspecs in a project that has multiple ADL files, where each prototype uses a different subset of the project's ADL files,
3. allow others to play with an adl file in a stand-alone fashion so as to evaluate its use or needed changes for a project (e.g. by conditionally including a set of demo-interfaces and demo-populations - an example of which would be an ADL file that allows users to login and do some account management).

parser directives are called for. Realizing that this increases the "beheerslast", parser directive syntax) should be ADL-agnostic. For starters (i.e. to accommodate purposes 1, 2 and 3), the following (minimum) syntax is proposed for an `<if-expression>`:

```
 #IF <condition> 
 <textlines>
 #ENDIF
```
and `<set-line>` and `<clr-line>`

```
 #SET <variablename> (TRUE | FALSE)
 #CLR <variablename>
```
This can be specified in a BNF-like notation as follows: 

```
<if-expression> ::= <if-line> <textlines> <endif-line>
<if-line> ::=  #IF <condition> 
<condition> ::=  [NOT] <variablename> [EXISTS]
<textlines> ::= ( <ADL text>  |  <set-line> | <clr-line> )
<set-line> ::= #SET <variablename> (TRUE | FALSE)
<clr-line> ::= #CLR <variablename>
<endif-line> ::= #ENDIF
```

**Comment by stefjoosten** [comment]
I don't like this idea. Let us keep the issue here as a place to collect insights on this issue. For now, we will leave this issue unhandled without closing it. (Is there a kind of hibernate mode for this type of issue?)

**Comment by RieksJ** [comment]
@Stef: What in particular is it that you do not like? Any of its purposes perhaps?

**Comment by stef** [comment]
hey, the stef here that get's triggered by github when people summon me by writing @stef - you sure you want to hear what i don't like?

**Comment by RieksJ** [comment]
@stef: I can sortof guess what you don't like (i.e. getting mails like the one you reacted on). My apologies.

@stefjoosten What in particular is it that you do not like? Any of its purposes perhaps?

**Comment by stefjoosten** [comment]
Hi Stefan, I'm sorry for that. Since my name is Stef, I can't think of any 100% reliable way to prevent people from writing (at)Stef in their github posts. Let me try to find out what we can do about this... (any ideas?)



Stef Joosten

M +31 (0)6 51348895
skype: stef.joosten




-----Oorspronkelijk bericht-----
Van: Stefan Marsiske [mailto:notifications@github.com]
Verzonden: woensdag 25 maart 2015 11:11
Aan: Joosten, Stef
Onderwerp: Re: [ampersand] ADL-agnostic (pre)Parser Directives (#33)

hey, the stef here that get's triggered by github when people summon me by writing @stef<https://github.com/stef> - you sure you want to hear what i don't like?

—
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/33#issuecomment-85969267>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by hanjoosten** [comment]
I don't like the idea of Rieks too. It is already possible to split definitions into separate files, using INCLUDE. Doing this in a smart way, using comments for whoever is going to use any specific configuration, should enable most of the required possibilities.

Also, looking at the proposed syntax, this uses variables that can be set and cleared. Scary!

My main objection is the lack of balance between usage and 'beheerslast'. 

My 2c...

**Comment by stef** [comment]
well then you have to live with my snarky comments from time to time in your fine project ;)

**Comment by RieksJ** [comment]
@stefjoosten What in particular is it that you do not like? Any of its purposes perhaps?

Now that there is a new parser, is it still really that cumbersome?

**Comment by RieksJ** [comment]
I still have not heard any other argument other than that the beheersrlast is too big, without any specification stating what the beheerslast constitutes of. I find that quite frustrating as I have written preparsers in Forth, which have not provided any beheerslast other than defining/creating it, and it was surprisingly simple.
Note that I'm talking here about **ADL-agnostic** and **preparser**s; for that, in particular, I cannot fathom what the beheerslast would be. 
Also note that I'm not talking here about say macro's for implementing equivalence relations (which I think is a good idea as well, and I can see where beheerslast would come there)

If, for example, you look at the SIAM module right now, the ever increasing number of small files and the beheerslast for maintaining them such that you can actually do some configuration in the SIAM-Module-include file that you have to make is quite big, too. But then, if you don't use it, you don't have the problems.

**Comment by RieksJ** [comment]
The work that I've been doing since I originally created this ticket has convinced me of the fact that 

- INTERFACEs cannot be reused in the same way as we can re-use concepts, relations and rules (using INCLUDEs), and
- there is a real benefit to be able to do so.

In my perception, this tips the balance between usage and 'beheerslast' (as mentioned by @hanjoosten) of implementing this pre-processing feature in favor of the users/programmers.

The following snippet exemplifies the user/programmer beheerslast that could be avoided (the example is taken from a real project):
~~~
         , "Details"   : I cRud COLS
            [ "Control for": isCtrlOfObj cRUd 
            , "Description": objDescr cRUd 
#IF ToDoListModule EXISTS
            , "To do list": objToDoMsg cRud
#ENDIF 
            ]
#IF SourceDocReferenceModule EXISTS
         , "Source doc": objSrcID;srcID~ cRud BOX <ROWSNL>
            [ "Show reference info": I-srcEditRefInfoFlg cRud COLS
               [ "Source document reference info": srcRef cRud
               , "URL of source doc": srcURL cRud
               , " ": I cRud BOX <ROWSNL> [ "Edit Reference": I cRud BOX <PropertyButton> [ property : srcEditRefInfoFlg cRUd ] ]
               ]
            , "Edit reference info": srcEditRefInfoFlg cRud COLS   
               [ "Source document reference info": srcRef cRUd
               , "URL of source doc": srcURL cRUd
               , " ": I cRud BOX <ROWSNL> [ "Done editing": I cRud BOX <PropertyButton> [ property : srcEditRefInfoFlg cRUd ] ]
               ]
#ENDIF
            ]
~~~
This snippet can compile into 4 variants, depending on the settings of the variables 'ToDoListModule' and 'SourceDocReferenceModule'. Currently, programmers would need to create an interface for every of this variant, and INCLUDE the right interface whenever needed. Also, any change in one of these interfaces would have to be propagated to the other interfaces. Thus, having the pre-processing features reduces the user/programmer beheerslast of this interface by approximately a factor 4.

Not having the pre-processing feature does not incentivise module-makers to create reusable interfaces. An example is the SIAM module, that could provide quite generic and nice interfaces e.g. for logins, accountmanagement and such, that would adapt to the SIAM features that would be included or excluded. Currently though, SIAM module users make such interfaces themselves. 

Having a pre-processing feature could turn the tables: whenever a project comes up with a very nice interface (for SIAM, that would be MPTrx, which has a nice interface with buttons, registration, etc.), it can be readily converted into a more generically useful interface and it could be included in the SIAM module for re-use by others.

**Comment by hanjoosten** [comment]
Since this is an issue no-one will put effort into, I will close this.

**Comment by RieksJ** [comment]
Hidde-Jan is going to do a quick impact-analysis.

**Comment by bartMarinissen** [comment]
Hi,

At the request of Rieks, I am working on something along these lines. More to come later.

**Comment by hanjoosten** [comment]
Just my 2p:

- In order to keep this stuff out of the parser itself, the parser mustn't be modified.
- I would suggest that the syntax of all directives are comments in adl. Then these files remain valid adl.
- The feedback in the error messages of ampersand contain the line and column number of the symbols. It would become hard for the usere if these numbers become wrong.

**Comment by hanjoosten** [comment]
@bartMarinissen : don't hesitate to contact me if you want help in any way. We could have a skype session where I can tell you about the current code.

**Comment by bartMarinissen** [comment]
@hanjoosten sounds good. Shoot me an e-mail at bart.marinissen@tno.nl and we can set something up.

**Comment by bartMarinissen** [comment]
I am currently working on this at the following branch: https://github.com/bartMarinissen/Ampersand/tree/feature/pre-compiler.
Almost all of the work for hooking into the parser is done in commit: https://github.com/bartMarinissen/Ampersand/commit/0015e7363b712b46145429f27a6c145d0cc03006

The remainder of the work is to actually implement a pre-processor. The current version has something that seems to work, but has ugly code for the moment.

This implimentation takes a slightly different approach than suggested. Rather than using
    #SET <variablename> (TRUE | FALSE)
    #CLR <variablename>
to set variables, they are set in INCLUDE statements. The current syntax for that is
    INCLUDE "filename" ["List", "Of", "Defined", "Variables"]
I think that should become something closer to
    INCLUDE "filename" -- [List Of Defined Variables]
That is, put the variables in a comment, and have them simply be whitespace-delimited.

Moreover, the current implementation does not have negation in the IF statement (or an ELSE clause) This severely limits the expressive power, so the 'guard' of the IF statement should at least include some way to negate. Perhaps we can also easily add simple predicate logic.

**Comment by RieksJ** [comment]
Ik wil graag even met je sparren om na te gaan of dit in onze behoeften voorziet.
Ik stel me (bijvoorbeeld) voor dat modules geladen kunnen worden door het INCLUDEn van 1 bestand.
Volgens het voorstel moet je daar dan de variabelen aan meegeven die daarin nodig zijn.
Echter, dat ene bestand doet zelf ook weer INCLUDEs, en de daar ge-include bestanden hebben nu juist die variabelen nodig.
Misschien moeten we (samen met Michiel) een paar test-cases specificeren.

Rieks

**Comment by bartMarinissen** [comment]
> Ik stel me (bijvoorbeeld) voor dat modules geladen kunnen worden door het INCLUDEn van 1 bestand. Volgens het voorstel moet je daar dan de variabelen aan meegeven die daarin nodig zijn. Echter, dat ene bestand doet zelf ook weer INCLUDEs, en de daar ge-include bestanden hebben nu juist die variabelen nodig.

Wat je schetst klopt, met een extra feit. Variabelen die 'aan' staan worden gepropageerd in includes dus:
```
file0.adl:
----------
INCLUDE file1.adl ["debug"]
```
```
file1.adl:
----------
INCLUDE file2.adl 
```
```
file2.adl:
----------
-- IF debug
debugging code here
-- ENDIF
```
In dit geval zou de debugging code actief zien, omdat de "debug" flag doorgegeven wordt. Een include geeft alle 'flags' mee die aan staan in het bestand waar de include gedaan wordt.

Een aantal test-cases lijkt me nog steeds nuttig, maar ik hoop/verwacht dat dit nog steeds in de behoeften voorziet. Mocht ik het fout hebben, of als er nog iets anders is, als je een keer langsloopt kunnen we dit best bespreken.

P.S.
When I said:
>Een include geeft alle 'flags' mee die aan staan in het bestand waar de include gedaan wordt.

I realized this might be a problem if a file is included twice in different contexts. I am not sure how the current code would behave in that case.

**Comment by Michiel-s** [comment]
@RieksJ, @bartMarinissen, what is the status of the preparser? There is still an open PR #858. Can we close the issue already?

**Comment by RieksJ** [comment]
No, we cannot (yet). After I reviewed the stuff for the first time (and accepted it), I found a bug. This has to be fixed before merging it.

**Comment by hanjoosten** [comment]
Travis-ci reports this bug due to the testcase of @RieksJ

**Comment by RieksJ** [comment]
That's good, because that's the bug I found.

**Comment by bartMarinissen** [comment]
Christmas holiday got in the way, sorry for the delay. I expect that, after the last commit on feature/preProcessor, the tests will pass.

**Comment by Michiel-s** [comment]
PR #858 is merged
