### ISSUE TITLE
Experimental type check on interface refs

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/ampersand#34]
Hey Bas,

Ater implementing an 'isa' type check on view annotations, I did a little experiment using the same method for a less restrictive type check on interface refs (ie. ``target objExr `isa` source ifcExpr || source ifcExpr `isa` target objExpr`` instead of ``target objExr == source ifcExpr``, for the code below).

```JavaScript
INTERFACE ..
BOX [ ..
    , "label": objExpr INTERFACE RefInterface
..  ]
INTERFACE RefInterface : ifcExpr
..
```

Commit 5cad373ee2f19547d4c6bbaf85e4722f3f054452 on branch experimental-interface-ref-check contains a proof of concept implementation. Do you think this is a good idea, or am I missing something here? The check is done parallel to disambiguation and adding epsilons, so it won't have an adverse effect the quality of the type errors.

To prevent having to topologically sort the interfaces to access their source concepts, I simply run an extra `typecheckTerm` on the expression of the referenced interface (`ifcExpr` above). It's not extremely elegant, but doesn't cost much time.

The approach precludes using information from interface refs to disambiguate either `objExpr` or `ifcExpr`, but type checker does not seem to do that for boxes either (all types are disambiguated locally), so that shouldn't be a problem.

**Comment by Oblosys** [comment]
Sorry for the double assignment, I thought you could assign multiple people.

On ampersand-models, I've added a test case (in a special branch, until we know this approach is feasible)

**Comment by Oblosys** [comment]
Just found out that disambiguation is non-local after all. (unfortunately I don't have the test case anymore that gave me the idea it wasn't) This means that an object expression with an interface ref will sometimes require disambiguation where it wouldn't if the interface ref was expanded. Root interfaces are non-ambiguous (right?) so it won't make a difference there.

It does however also have an impact on the cost of re-disambiguating/type-checking each referenced interface, as this turns out not to be a local computation. Will this be problematic?

**Comment by Oblosys** [comment]
The last point can be solved by pairing the interfaces with their disambiguated objects.

**Comment by sjcjoosten** [comment]
I agree with this statement: "an object expression with an interface ref will sometimes require disambiguation where it wouldn't if the interface ref was expanded."
I do not believe this is a problem.

Something I do believe is a problem, is that no epsilons are inserted (I think.. I just read the code). This does not fit in the way the type checker is supposed to work: types are checked to ensure that epsilons can be inserted, and any place where two non-identical types are found to "match", an epsilon is inserted to account for the difference between them. I found it a bit difficult to insert epsilons at first (which explains why I just checked string equality), but it may currently be a bit more straight-forward thanks to your refactoring.

As an aside: "Guarded" is Applicative and not a Monad, since one of the requirements was to have all type errors reported in parallel. Using a Monad, this would not be possible. I enjoyed seeing you make the "mkIncompatibleViewError" function, such that all the error messages reside in CtxError. I frown upon its use for interface refs, as it contains English text (intended for the user) outside of CtxError: this is precisely what "not exporting any constructors" was supposed to prevent.

**Comment by Oblosys** [comment]
That's why I added the comment "-- **Abuse** view error to show interface ref error" (and **experimental** and **proof of concept**.) There should of course be an appropriately named error function (the asymmetric view error even gives an incorrect message), but I'd rather hold off on that until we are sure this approach is going to work.

Adding an epsilon to the `objExpr` is trivial, as we can return the source of `ifcExpr` on type checking the ref. Since this guarantees an epsilon in the composition of the two, I'm not sure if you want to add epsilons to `ifcExpr` a well. This would require gathering all refs to each interface and join them, but since interface expressions may also be used for creating top-level interfaces, I have a feeling you will end up with the most generic one anyway.

**Comment by hanjoosten** [comment]
Ending up with the most generic one is good, because that ensures that the interface ref is most usefull. However, if the target of the objExpr is more specific, that should not result in an error. 
At this moment, this still doesn't work, as can be seen in SHA: 770ce28ed5bee6284c5452a4df84f7ae35bc2736

**Comment by hanjoosten** [comment]
hmm. links didn't work... I ment to link to the commit I did a minute ago on ampersand-models. (Commit 770ce28)

**Comment by Oblosys** [comment]
Are you sure you're using the latest master? When I try Fire.adl it compiles without a problem, both before and after your workaround. See [ampersand-models/blob/master/Tests/ShouldSucceed/InterfaceRefCheck.adl](https://github.com/AmpersandTarski/ampersand-models/blob/master/Tests/ShouldSucceed/InterfaceRefCheck.adl) for some examples on what is allowed for interface refs.

**Comment by hanjoosten** [comment]
Oops. You were right. I thought I used a recent version of ampersand, but it was a slightly older one... :disappointed: I must have been asleep... :sleeping:

**Comment by hanjoosten** [comment]
So this issue could be closed?

**Comment by Oblosys** [comment]
Sounds good to me. I kept it open because there were some unanswered questions above, but quite some time has passed, so I assume everyone agrees with the current solution.
