### ISSUE TITLE
Affected conjuncts not complete.

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand#345]
The list of affected conjuncts specified for each relation is not complete. This allows transactions to be committed that do not satisfy the invariant rules!

The attached file provides an overview with the affected conjuncts specified for r[A*B] in all 16 combinations possible. I marked the relations that have missing conjunct specifications in yellow.

According to @hanjoosten this is an normalizer issue.

[Overview with affected conjuncts for 16 relations.pdf](https://github.com/AmpersandTarski/ampersand/files/185852/Overview.with.affected.conjuncts.for.16.relations.pdf)

**Comment by Michiel-s** [comment]
I used the following script as input:
```
CONTEXT Test2 IN ENGLISH
r :: A * B

rUni :: A * B [UNI]
rUniTot :: A * B [UNI,TOT]
rUniInj :: A * B [UNI,INJ]
rUniSur :: A * B [UNI,SUR]

rUniTotInj :: A * B [UNI,TOT,INJ]
rUniTotSur :: A * B [UNI,TOT,SUR]
rUniInjSur :: A * B [UNI,INJ,SUR]
rUniTotInjSur :: A * B [UNI,TOT,INJ,SUR]

rTot :: A * B [TOT]
rTotInj :: A * B [TOT,INJ]
rTotSur :: A * B [TOT,SUR]
rTotInjSur :: A * B [TOT,INJ,SUR]

rInj :: A * B [INJ]
rInjSur :: A * B [INJ,SUR]

rSur :: A * B [SUR]

ENDCONTEXT
```
In branch 228, you can run the report yourself by calling in browser
http://pathtoapp/api/v1/admin/report/relations

**Comment by Michiel-s** [comment]
Related to ticket #256. Here the issue of missing SUR check is also discussed.

**Comment by stefjoosten** [comment]
I have made an update, Ampersand v3.5.0[branch_#228:1b47613*], build time: 25-Mar-16 09:08:48 West-Europa (standaardtijd).
It produces a different [overview](https://github.com/AmpersandTarski/ampersand/files/189497/Overview2.with.affected.conjuncts.for.16.relations.pdf). It shows some improvement, but the issue has not been resolved completely.

**Comment by Michiel-s** [comment]
Just branch from 228. Then you can experiment as much as you like without disrupting RieksJ:)

**Comment by RieksJ** [comment]
On retrospect, it may not have been the update of @stefjoosten that was disruptive, but something else. After all, the last days all sorts of things that used to be 'good' turned out to be 'no more good', such as database tables, endo-properties, and what not. I agree with Michiel to branch and experiment. 

I would also like to suggest to clean up branch_#228 asap so as to get it a stable, working version. What started as a branch for introducing the CRUD stuff so that we could actually start editing in INTERFACEs again, turned into a branch that also refactored interfaces, excel imports and what not more. There is no argument that this refactoring etc. is useful. It is. But let's now focus on getting all the stuff that used to work, working again (which currently is not the case), and get a new stable version again.

**Comment by Michiel-s** [comment]
@stefjoosten any update on this issue yet?

**Comment by RieksJ** [comment]
@stefjoosten could you try your changes again?

**Comment by stefjoosten** [comment]
@Michiel-s  could you test and close this?

**Comment by Michiel-s** [comment]
Hi. I've tested the fix of @stefjoosten and can conclude that every conjunct (for multiplicity constraints) are now mentioned as affected conjunct for the relations.

However, I also see that the UNI and INJ conjuncts are now mentioned. Given the current implementation this means that the generated sql queries for those conjuncts are also executed when a corresponding relation is hit. Since these constraints are impossible to violate (except in the situation where a relation is both UNI and INJ), this is a loss in performance. I do like the fact that all conjuncts are mentioned now (including the UNI and INJ ones). I'll open a new ticket to formulate a solution for the performance loss.

Consider this issue closed.
