### ISSUE TITLE
Compositional alternative to <?>

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/ampersand#36]
Here's an idea I just had for a more compositional alternative to `<?>`. If we have a function `f :: a -> b -> Guarded C` that we want to apply to the results of two guarded expressions `guardedA :: Guarded A` and `guardedB :: Guarded B` this could be expressed elegantly with a monad: 
    
    testM :: Guarded C
    testM =
     do { a <- guardedA
        ; b <- guardedB
        ; f a b
        }
    
but with our applicative functor we get:

    testA1 :: Guarded C
    testA1 = (\(a,b) -> f a b) <?> ((,) <$> guardedA <*> guardedB)

I don't have a good intuition for the `<?>` combinator (which may come later), but it is also not very compositional, which requires us to tuple and untuple the a and b arguments.

On the other hand, if we use a function `unguard :: Guarded (Guarded a) -> Guarded a`, we can simply use `<$>` to compose the arguments and consolidate the nested `Guarded`'s aftwerwards:

    testA2 :: Guarded C
    testA2 = unguard $ f <$> guardedA <*> guardedB

The definition of `unguard` is straightforward:

    unguard :: Guarded (Guarded a) -> Guarded a
    unguard (Errors errs) = Errors errs
    unguard (Checked g)   = g  

Other people must have run into this as well, so I thought a combinator like this would be in an Applicative/Error functor module somewhere, but I haven't found it so far.

**Comment by sjcjoosten** [comment]
testM :: Guarded C
testM =
 do { a <- Errors [PE "hello"]
    ; b <- Errors [PE "world"]
    ; f a b
    }

results in testM = Errors [PE "hello"] (if there were a monad definition for testM), whereas:

testA1 = f <$> Errors [PE "hello"] <*> Errors [PE "world"]

results in testA1 = Errors [PE "hello", PE "world"]. (This is precisely your example btw)

I'd be fine with Guarded being a Monad, if it were not for the Functor-Applicative-Monad proposal, by which it becomes a requirement that testM and testA1 give identical results. Because of this, we are forced to choose: either make it a Monad, but return only the first error encountered, or make it an Applicative that returns both, and not a Monad. The "unguard" (typically called "join" when talking about Monads) function is precisely what is missing in order to turn an Applicative into a Monad. In effect, adding it gives us the strength of a Monad back (without the do-notation). I like your notation, so I say we should have it!

PS: the reason unguard is not there, is that it occurs in only one place, where it has been written out explicitly: we get Parse errors, except when parsing succeeds, in which case we may get type-check errors.
PS2 on your remark about the <$> operator:
the <$> is the same as "fmap", and it is also the same as "pure/return" together with "<*>", so instead of
f <$> arg
we may write
pure f $ <*> arg

**Comment by Oblosys** [comment]
Yes, I was aware of the definition of `<$>`. My remark was to explain how you could use it in combination with `unguard`. I'm also aware of the reasoning behind `Guarded` not being a monad, as it's described in the code, and you also explained it in issue #35.

I would not agree with declaring `Guarded` a monad while also keeping the parallel error behavior for `<*>`. It may seem like a easy way to get the best of both worlds, but as it break basic laws relating the two (i.e. `(<*>) = ap`) it may lead to confusing situations. (this is why I'm all in favor of the Functor-Applicative-Monad proposal) Since the parallel errors are a requirement, we can keep `Guarded` applicative-only.

I indeed missed the obvious similarity between `unguard` and monadic join. In fact `unguard` is related to `join` exactly the same as `<?>` is related to `flip (>>=)`. The thing is that you can define `unguard` (or `unapply`, `joinA`, ..) on an applicative functor without requiring a full monad. Having `Applicative` plus a way to throw and catch errors is enough to declare it. I could not find any packages doing that however.

There's a couple of places in P2AConverters where rewriting `<?>` to `unguard` is beneficial, most notably `typecheckTerm`. On the other hand, the simpler cases (`f <?> gExp`) do not get shorter (`unguard $ f <$> gExp`), but we could choose to use `unguard` anyway for consistency and the fact that it is slightly more intuitive (to me at least.) I'll commit the changes separately, so you can decide which ones to cherry pick.
 
P.S. your definition of `testA1` may seem similar to mine if `guardedA` or `guardedB` yields an error and you only look at the resulting value, but if you check the type, you will see they are in fact quite different. (apply `unguard` to your version to get mine)

**Comment by sjcjoosten** [comment]
I'm sorry, I did not read your earlier note correctly. <?> indeed is flip (>>=), but I read it as <$>. I never really saw a difference between the two (<?> or unguard), but your example together with the reference to typecheckTerm makes it perfectly clear why you would want to use unguard.

I'm not sure whether we should define the two seperately (as above) or have one in terms of the other:
unguard = id <?>
or the other way around, which is:
f <?> a = unguard (f <$> a)

Looking forward to reading your commits!

**Comment by Oblosys** [comment]
The commits are on the branch. The reason why I didn't define one using the other is that I believe that it may be a good idea to only have one of them, and maybe also a bit that the explicit definition is easier to understand for someone who is not familiar with applicative functors. The equivalence is mentioned in a comment though.

**Comment by sjcjoosten** [comment]
Ok excellent!

**Comment by Oblosys** [comment]
P2A_Converters.hs no longer uses `<?> `, but since the combinator is also used in CreateFSpec.hs, I've left the definition in tact.
