### ISSUE TITLE
Error messages related to multiplicity- and other relation-type constraints (e.g. TOT, IRF)

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#366]
Error messages for multiplicity- and other relation-type constraints (e.g. `UNI`, `TOT`, `RFX`, `IRF`, `PROP`etc.) are satisfactory for developers, but are a source of questions from the public in the context of demonstrations. For example, the error message associated with `TOT` is `r[A\*B\ is not total`, which is not clear to the general public. 

Currently, the way to do this is to create your own rule for such constaints. This not only defeats the purpose of specifying `UNI`, `TOT`, etc.  - which is very handy for developers, but also takes up needless additional effor by the developer.

I would very much like to see a **practical** solution for this. One suggestion could be to introduce a syntax such as `ERRMSG TOT[r[A*B]] "here goes the errormessage text". We may want to do that for at least `TOT` (and perhaps `SUR`). Any other ideas?

**Comment by Michiel-s** [comment]
I have another suggestion: if the prototype generator provides an attribute at the rule defintions in `rules.json` specifying which constraint is related to the rule (UNI, TOT, etc), then we can make this default error message configurable in `localsettings.php`.

@hanjoosten: could you add this attribute to the relation definition like this:
```
{
            "origin": "line 29:7, file C:\\Dev\\ampersand\\projects\\ProjectAdministration\\ProjectAdministration.adl",
            "tgtConcept": "Assignment",
            "ruleAdl": "I[Assignment] |- assProject;assProject~",
            "pairView": null,
            "name": "TOT assProject::Assignment*Project",
            "constraint" : "TOT" <-- null if not a standard constraint, but a user defined complex rule
            "meaning": "assProject[Assignment\\*Project] is total",
            "srcConcept": "Assignment",
            "conjunctIds": [
                "conj_82"
            ],
            "message": "assProject[Assignment\\*Project] is not total"
        }
```

**Comment by RieksJ** [comment]
Here is another idea. Since the multiplicity constraint violation stems from activities in an INTERFACE, there is a good chance that the INTERFACE allows for repairing of the multiplicity constraint (currently, this even is required if you want to get stuff done). If there is a way to detect which (updatable) fields in the INTERFACE would allow for the reparation of the multiplicity constraint, that field could be colored red, which would vastly improve the user's experience.

**Comment by hanjoosten** [comment]
I totally agree that the violation messages are not practical for demonstrations. However, since the properties in relations are only syntactic suger to specify rules, we do not want extra stuff. I fixed the error messages for TOT and SUR (and UNI and INJ, but these are realized by the database strucure, so the will not happen during runtime). 
I do not think it is a good idea to let this kind of information escape into the json file, as @Michiel-s  suggests.

**Comment by WolframKahl** [comment]
On Tue, Apr 12, 2016 at 08:28:20AM -0700, Han Joosten wrote:
> However, since the properties in relations are only syntactic suger to specify rules, we do not want extra stuff.

However, for a relation
```
Height[Person*FLOAT]
```
it still makes sense to specify UNI, but this does not correspond to the usual rule
```
Height~;Height |- I[FLOAT]
```
since ```I[FLOAT]``` does not exist, if I understand things correctly.

Even ```isSubidentity(Height~;Height)```, which translates into
```
isLeftSubidentity(Height~;Height) /\ isRightSubidentity(Height~;Height)
```
, the second of which translates into
```
forall C : Concept .
  forall  R : [C*FLOAT] .
    R ; (Height~;Height) |- R
```
, will probably not be testable as an inclusion on [C*FLOAT], since it will need equality on FLOAT.

Even domain-minimality [Desharnais-Moeller-2001] needs an equality test, so I currently see no algebraic way to specify univalence for such relations. This leaves only the semantic definition, which is realised by the database structure. This in turn then makes the algebraic laws available for reasoning, but only for reasoning.

Story still unfinished...


Wolfram
