### ISSUE TITLE
Templates for [PROP]s do not seem to work

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#367]
Example is in the UETP project. Im using branch_#288 [74aae2b]. The property should show in the red circle of the image below:

![picture1](https://cloud.githubusercontent.com/assets/8522589/14225753/13ac4e70-f8ce-11e5-8a81-2d4069ded529.png)

**Comment by Michiel-s** [comment]
@RieksJ 

This screenshot is not enough for me to diagnose the issue. As far as I know the build-in property template is correct.

Could you:
* Provide the part of the Interface definiton of the `Prm`
* Provide the declaration of the relation used in this interface expression
* Provide any view definitions that are defined for the target concept
* Check if you have a template with the name `View-PROPERTY.html` in your include folder

**Comment by RieksJ** [comment]
I've cleaned up and checked in UETP (tno-models commit [fd524bb]); the bug remains.
You can reproduce as follows:
- compile UETP, install database
- click on menu-bar item 'Cases'
- create a new transaction (give it a name), and click on it so as to edit it further
- in the 'Concerns and Criteria' tab, create a new concern (some text will do)
- add a stakeholder name to it (e.g. shr1) to get rid of one error message
- create a new criterion (arbitrary text)
Now you should see the properties 'Prm' and 'Acc', of which 'Prm' is checked and 'Acc' is not checked.
However, you do not (even) see the checkboxes.

**Comment by RieksJ** [comment]
I have noted that some other properties do have the checkbox, but I can't get that to show because of issues #371/#372.

**Comment by Michiel-s** [comment]
I've found your issue. As I already though, a custom template kicks in.

* The tgt of your Prm interface expression critPromise is a Criterion (because it's a PROP).
* There is a DEFAULT view specified for Criterion -> `Criterion`
* This view is assigned a custom template -> Criterion.html
* You haven't implemented checkbox/prop functionality in this template.

Solution: 
* create a property view for Criterion and assign the build in template: `VIEW propCriterion : Criterion HTML TEMPLATE "View-PROPERTY.html" ENDVIEW`
* Add this view to your Prm interface: `<propCriterion>`
