### ISSUE TITLE
INVARIANT and SIGNALS logging should mention the rule

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#368]
The logs in the red rectangle do not mention the rule names, but should.

![picture1](https://cloud.githubusercontent.com/assets/8522589/14225780/21a31788-f8cf-11e5-8d6a-0627218cc6bd.png)

**Comment by RieksJ** [comment]
Turns out signals and invariants, such as in the red rectangle, should also be put on the screen as they contain working information for Users, as shown in the screenshot below:

![picture2](https://cloud.githubusercontent.com/assets/8522589/14225911/b749d64c-f8d3-11e5-9b32-9af7aee5a34e.png)

**Comment by Michiel-s** [comment]
First issue is fixed by commit a2c21da

Second comment is not relevant, since a log is shown which is not used for showing signals or invariants to endusers. The log shows that violations are calculated, but it depends e.g. on the current role of the user if he/she gets these violations presented. Of course invariant violations are always shown.
