### ISSUE TITLE
'GLUE' revisited - alternatively called aliasing?

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#382]
Consider the following piece of script:

```
 IDENT Variables: Variable(varScope,varName)
 varScope :: Variable * Scope [UNI,TOT]
 varName :: Variable * Name [UNI,TOT]  REPRESENT Name TYPE ALPHANUMERIC
 varExplanation :: Variable * Text [UNI]    REPRESENT Text TYPE ALPHANUMERIC
 varValue :: Variable * Value [UNI]   REPRESENT Value TYPE ALPHANUMERIC

 CLASSIFY Term ISA Variable -- a Term can be evaluated to produce a value; as such it can be seen as a Variable
```

For readability, robustness against typo's and the like, I would like to be able to define a relation `termValue :: Term * Value` that is 'GLUE'd to the relation `varValue`, which I define to mean that both `termValue |- varValue` and `I[Term];varValue |- termValue`. In 2006, we had the keyword `GLUE` that did this (if I recall correctly), as follows: 

```
 termValue :: Term * Value    
 GLUE termValue = varValue 
```

(see \RAPRelatedPatterns\Oude RAP versies\RAP2.oldadl', line 28, in the ampersand-models repo)
Anyone share some need for this? (Note: I'm not solliciting solutions, I merely want to check whether or not I'm the only one that feels this need).

**Comment by stefjoosten** [comment]
Yes, I share this need. You remember the `GLUE` keyword correctly. It was there in the stone age of Ampersand, because I felt it was necessary, but could not build it in a usable way. I think around 2006 or later we decided to leave it until we had mastered the ISA.
Today, that is the case. So it is not surprising to see the need for this resurface.

I would like to see some kind of inheritance mechanism in Ampersand. (A `GLUE`-like construct mentioned above could be part of it.) I would like to reuse patterns, or parts of patterns. I would like to rename concepts, relations, rules in a different context, to adapt fluently to the language of that other context. I am actually looking for inspiration in good examples of such systems. I see for example the name space mechanism of XML, the module system of Haskell, to name just two.  @Wolfram, could your knowledge inspire me here?

**Comment by sjcjoosten** [comment]
Can we define `GLUE termValue = varValue` as syntax sugar for:

```
CLASSIFY source(termValue) ISA source(varValue)
CLASSIFY target(termValue) ISA target(varValue)
RULE termValue |- varValue
```

(where I pretend `source` and `target` exist and do what they seem to do)

If so, that should not be too hard to implement.

**Comment by RieksJ** [comment]
I wouldn't mind having the `=` sign mean 'is an alias for', i.e. the population of both relations are identical (basically making both the concept-names and relation-names aliases of one another).
Then we might use `GLUE termValue ISA varValue` as what @sjcjoosten described.

**Comment by sjcjoosten** [comment]
Great idea, then let's use `GLUE termValue ISA varValue` as syntax sugar for:

```
CLASSIFY source(termValue) ISA source(varValue)
CLASSIFY target(termValue) ISA target(varValue)
RULE termValue |- varValue
```

and `GLUE termValue IS varValue` as syntax sugar for:

```
GLUE termValue ISA varValue
GLUE varValue ISA termValue
```

**Comment by Michiel-s** [comment]
We have the ENFORCE feature nowadays. See #1204

That allows for the request of Rieks here in this issue.

Furthermore we have the feature on EQUALS in #851

Let's close this one.
