### ISSUE TITLE
Can the type checker generate a more helpful error here?

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#437]
I used Ampersand v3.5.1[development:28036cb] to compile

```
{-01-} CONTEXT BugX IN ENGLISH
{-02-}
{-03-} CLASSIFY Concern ISA Variable
{-04-}
{-05-} varValue :: Variable * VarValue [UNI]
{-06-} varTrace :: Variable * Assignment [UNI,INJ]
{-07-} asmValue :: Assignment * VarValue [UNI,TOT]
{-08-}
{-09-} RULE "one": (I[Variable]-I[Concern]);varValue |- varTrace;asmValue
{-10-} RULE "two": (I[Variable]-I[Concern]) |- varTrace;(I-asmValue;asmValue~)
{-11-}
{-12-} ENDCONTEXT
```

This resulted in the following output:

```
Error at symbol () in file BugX.adl at line 10 : 51
  Cannot disambiguate: I
  Please add a signature.
  You may have intended one of these:
  I[Concern]
  I[Variable]
```

Note that `line 10:51` refers to the `I` in `I-asmValue;asmValue~`. 

After spending quite some time, I discovered that `RULE "two"` does not match at the very end, i.e. the target concept of the expression `I-asmValue;asmValue~` does not match the target concept of the left hand side of the rule. 
@sjcjoosten: can you arrange an error message that is more helpful (e.g. that points this out) rather than the (unhelpful, albeit like correct) message that asserts a disambiguity in `I`?

**Comment by sjcjoosten** [comment]
I'm afraid not, there is no way for me to determine the type of `(I-(asmValue;asmValue~))` without knowing the type of the I used there, since `-` takes the type of its first argument. Solving the ambiguity first should help you get the error message you wanted.

**Comment by RieksJ** [comment]
I am flabbergasted. In the rule `I` occurs three times, two of which have their concept specified. For the third `I`, it seems obvious to me that its concept should be `Assignment` - I do not see what other concept could possibly be used here since Assignments are not in any `CLASSIFY` statement. Still, you tell me that for you there is no way to determine the type. So what am I missing here, or what?

**Comment by hanjoosten** [comment]
Stating `it seems obvious to me...` is normally good enough for a modeller to avoid errors like this. However, it isn't well enough for a machine. 

If I look at the rule, I could formulate something completely different:
It seems obvious to me that its concept should be `Variable` . This is quite easy to see, because the target of `I` must match the target concept of  `(I[Variable]-I[Concern])`. 

The conclusion is that there is an error in the script. `I` cannot be typed. Luckily for us all, the typechecker does a great job in finding all errors. In most cases, an error message is produced that is clear at first sight. In this case it is arguable if the error message is is guessing the intent of the modeller well enough. However, it is a result of the way the typechecker is implemented. I agree with Bas that it is not a reason to change that implementation. 

This leaves us with two alternatives for this issue. We could either close it, or leave it open. In both cases, nothing will be changed at the error message level. Leaving it open only causes this issue to appear on the backlog, knowing that nothing will be done for it ever.

**Comment by RieksJ** [comment]
I agree that the type checker does a great job in finding all errors. The next thing is that it should point the user in a right direction. If I follow the advise of the error message, the error is not solved. Therefore, the errormessage is wrong. I disagree with anybody that insists that it is acceptable that tools provide guidance for solving an error that, when followed, does not solve that error. If nothing is done about that, then we should be continuously reminded of this. Therefore, I reopen this ticket.

**Comment by hanjoosten** [comment]
@RieksJ suggests that it is possible that in all cases a single message could give guidence that is well enough to solve an error. The current implementation cannot do that. In cases like this, where there is a combination of mistakes in the script, i doubt that it is possible at all. To do an execellent job in such cases, one must know that no guidence can be generated. However, the current implementation cannot do so either. As long as no one has any clue about how to implement this wish, no progress can be made at all for this issue. As each open issue has a maintenance cost, I suggest to close it.

**Comment by RieksJ** [comment]
What I suggested is that _if_ an error message provides guidance in some case, such guidance should actually help to solve the problem rather than sending users into the wrong way. The error message I mentioned sent me into the wrong way. 

For me, I can live with the way it is (even if it irritates me at some point). However, for students and other &-apprentices meaningful, i.e. helpful error messages seem quite important to me. I suggest @stefjoosten to decide whether to close this ticket or do something about it.

**Comment by stefjoosten** [comment]
I had the same discussion with @sjcjoosten in the past. In my recollection they were as fiercly debated as above. I'm still not sure what causes the confusion. But now I have a hunch...

Let me reason from the assumption that the set of concepts is closed, and all concepts are contained in the script. The concepts are `Concern`, `Variable`, `VarValue`, and `Assignment`. Now the type checker has to make a choice as to which of these four fits `I` on line 10 : 51.  Both the target of `varTrace` and the source of `asmValue` are `Assignment`. The concept `Assignment` is involved in no generalization or specialization whatsoever. Could this line of reasoning explain Rieks' shock?

Let me reason from the assumption that the set of concepts is open, and there may be more concepts than the ones contained in the script. Now assume that there may be a concept `C`, which is a specialization (i.e. a subset) of `Assignment`. Obviously, `I[Assignment]-asmValue;asmValue~` has a different value than `I[C]-asmValue;asmValue~`. So the expression is ambiguous and must be rejected. Could this line of reasoning explain how the type checker works?

@sjcjoosten Is a type checker conceivable that reasons from a closed set of concepts? I guess that would solve Rieks' issue... Do we want that? Or not? Why

**Comment by sjcjoosten** [comment]
It would be possible to make some of the type checker reasoning more closed, though I'm not sure that would solve this problem. A problem in doing so, is that scripts are more likely to end up changing meaning as changes to the ISA structure are made. The old type checker reasoned like that, and also had that effect sometimes. I'm out of ideas on how to make that work.

Frankly, I don't understand why the error message sent Rieks in the wrong way: if the ``I`` pointed to by the error message were disambiguated as ``I[Assignment]`` (which according to the explanation, was obvious to him), you would get the right error message.

In any case, I'm leaving this open, so Stef can close it or propose a concrete change.

**Comment by RieksJ** [comment]
The error message that was provided only points to one error, where there are more. The suggestions point to the 'wrong' direction (from a user point of view) because none of them will result in the rule becoming correct. 

Would it be possible to check the suggestions of the type-checker to see if either/any of them makes sense (i.e. would actually result in a type-correct RULE rather than some non-obvious partial expression), and if not, it might provide a more general kind of instruction for fixing the issues, which in this case might be something like:
~~~
Error at symbol () in file BugX.adl at line 10 : 51
  Cannot disambiguate: I
  However, I also cannot find any possible solutions for disambiguation.
  Please check the rule carefully for erroneous types
( mogelijk gevolgd door nog wat suggesties als je die kunt verzinnen ).
~~~
Whatsay?

**Comment by sjcjoosten** [comment]
This makes a lot of sense and sounds like a great idea to me. I might be able to detect that the 'Cannot disambiguate' arises because of a type error that I can't yet point at exactly. How would this be as an error:

```
Error at symbol () in file BugX.adl at line 10 : 51
  Cannot disambiguate: I
  Please add a signature.
  This arises trying to match Concern and Variable, which are incompatible.
```

In case there is an ISA between the two (or more) concepts, we could write: of which X is the most generic and Y is the most specific. That doesn't apply to this example but I'm adding it as a note in case the above seems like a good solution.

**Comment by RieksJ** [comment]
This error message suggestion of @sjcjoosten ignores the fact that there is no signature that would produce a correct expression. I would like to see that in an error message (and preferably some ideas about what WOULD help).

**Comment by sjcjoosten** [comment]
I edited my comment, how about now?

**Comment by RieksJ** [comment]
deleted @sjcjoosten's most recent comment and updated mine.

**Comment by RieksJ** [comment]
I edited my comment, how about now?

**Comment by sjcjoosten** [comment]
I want to avoid writing `there is no way', as there might be one, it's just that I cannot (within reasonable performance) find it if it exists. Also, I have no idea what to put on the ``...``.

**Comment by RieksJ** [comment]
Ok. How about:
~~~
Error at symbol () in file BugX.adl at line 10 : 51
  Cannot disambiguate: I, and there is no obvious way that it might be disambiguated.
  Such situations are known to be caused by multiple type-errors.
  Please carefully check the signatures of all relations involved in this rule.
~~~

**Comment by sjcjoosten** [comment]
Great, I can definitely do that, and maybe I can do better, tell me what you think:

~~~
Error at symbol () in file BugX.adl at line 10 : 51
  Cannot disambiguate: I, and there is no obvious way that it might be disambiguated.
  Such situations are known to be caused by multiple type-errors in a single expression.
  In this case, such a type conflict occurs between the concepts Concern and Variable.
  Please carefully check the signatures of all relations involved in this rule.
~~~

**Comment by stefjoosten** [comment]
@RieksJ could you let me know whether or not the assumption of a closed set of concepts, as mentioned above, explains your flabbergastedness? Here is the explanation again:
 - Let me reason from the assumption that the set of concepts is closed, and all concepts are contained in the script. The concepts are `Concern`, `Variable`, `VarValue`, and `Assignment`. Now the type checker has to make a choice as to which of these four fits `I` on line 10 : 51.  Both the target of `varTrace` and the source of `asmValue` are `Assignment`. The concept `Assignment` is involved in no generalization or specialization whatsoever. So in a closed world, there is no ambiguity: `Assignment` is the only possible type for `I` on line 10 : 51. Could this line of reasoning explain Rieks' shock?

**Comment by RieksJ** [comment]
Yes, this line of reasoning was the one I followed - it also seems quite natural to do.

Following thie line of reasoning, I would have expected to see an error message stating that the target concept of expression `varTrace;(I-asmValue;asmValue~)`, being `Assignment`, would need to match the target concept of expression `(I[Variable]-I[Concern])`, which is either 'Concern' or 'Variable'. That would have been a much more appropriate/helpful error message.

Does this mean that we now have 2 suggestions for improvement:
- having the type-checker verify that any suggestions that it makes actually solve the users problem, and
- providing an error message of the kind I described here for situations as in this ticket
?

**Comment by sjcjoosten** [comment]
@stefjoosten ?

**Comment by sjcjoosten** [comment]
I won't be able to offer anything considering the first suggestion. Frankly, I don't believe that there exists and efficient algorithm for it, but I'd love to see such algorithms implemented (by others).

Given my assignment by RieksJ, I'm assuming that the error message https://github.com/AmpersandTarski/Ampersand/issues/437#issuecomment-317735133 is a satisfactory solution?

**Comment by RieksJ** [comment]
For the second bullet, yes.
For the first bullet, let's see what @stefjoosten has to say.

**Comment by stefjoosten** [comment]
I believe I understand the source of all confusion. Rieks assumes a closed set of concepts (hereafter: CsoC). His reasoning is consistent with that assumption. And it is consistent with the "old" typechecker, which we had until some years ago. Sebastiaan apparently assumes an open set of concepts (hereafter: OsoC). These are two very different assumptions.

Since Sebastiaan is sticking with the OsoC, I am afraid that the error message https://github.com/AmpersandTarski/Ampersand/issues/437#issuecomment-317735133 will not be a satisfactory solution for Rieks in the long run, even if this message is good enough for Rieks' specific example.

Rieks' argument that "it seems natural" is insufficient for me. If we would go for the "natural" things, we would be following many bad habits that are considered "natural" in the IT-world. In our project, we do things differently for very good reasons. These good reasons are what I am looking for. For now, I can only use my personal preference to justify a choice between the CsoC or the OsoC. And personal preference is too little to go on. By the way, I would prefer a CsoC intuitively (as Rieks does). But we won't do so until we have better arguments.

So now I am curious to learn all the solid arguments for either CsoC or OsoC. I have but a few:
 - CsoC can produce better type errors, because there are fewer choices to be made. This argument is supported by Rieks' argumentation and example, which is not much to support the argument.
 - OsoC is what we have now in our type system. This argument is not in favour of either assumption, but it defines the status quo.
 - OsoC is implementable, because it is implemented in our current system. Sebastiaan, are you saying (above) that you don't believe that CsoC is implementable (efficiently)? If so, I think we must challenge that; I find it difficult to believe. We have to get to the bottom of that.

**Comment by sjcjoosten** [comment]
To be more precise: I believe that the type suggestion problem for CsoC is NP-hard.
I define the type suggestion problem for CsoC as follows:

input: a parsable ampersand expression and a set of relation declarations and concept-ISA rules. The size of the script (in a parsable layout) is the size of the input.
problem: is there a type annotation (fully annotating every relation, I, V, and unary complement in the ampersand expression) such that the expression is well typed.

Note that determining whether a fully annotated expression is well typed is the same for CsoC and OsoC.

It is trivial to see that the type suggestion problem for CsoC is in NP. I have no proof to support that it is NP-hard (and therefore NP-complete), nor do I think such a proof would be interesting, as I believe the OsoC to be a better way to go regardless of whether the type suggestion problem for CsoC is NP hard. So I'm not really eager to get to the bottom of that.

**Comment by stefjoosten** [comment]
In that case, we will let this issue rest due to a lack of good arguments. Who knows that one day such arguments can pop up. I'm glad we have this discussion well documented for now.

I am closing the issue. We can reopen it when new arguments pop up that might lead to progress.

**Comment by stefjoosten** [comment]
Reopening, because the error message still has to be improved.

**Comment by sjcjoosten** [comment]
Stef is cleaning up this issue, please sit tight (Stef can remove this comment when he's done)

**Comment by stefjoosten** [comment]
I'm done cleaning up.

**Comment by RieksJ** [comment]
Having given it some thought, I am not convinced that the line `In this case, such a type conflict occurs between the concepts Concern and Variable.`, is helpful to the programmer. People like me expect error messages to state the kind of error that is detected, and provide information that helps me find and correct it. This line does neither, leaving me in a confused state as to what it is trying to convey. I suggest to leave the line out.

Perhaps this might be an improvement (where the second line in the message sums up the concepts that appear in the expression, and fail to make the expression type-correct):
~~~
Error at symbol () in file BugX.adl at line 10 : 51
  Cannot disambiguate: I, and there is no obvious way that it might be disambiguated.
  (None of the concepts 'Concern', 'Variable' or 'Assignments' will solve this issue).
  Such situations are known to be caused by multiple type-errors in a single expression.
  Please carefully check the signatures of all relations involved in this rule.
~~~
