### ISSUE TITLE
Parser should not accept anything behind ENDCONTEXT

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#439]
I accidentally added a statement to a script after the ENDCONTEXT keyword. The compiler didn't complain, but the statement was disregarded. It took me a while to find out wat was going on. 

I would expect that after the ENDCONTEXT keyword nothing but whitespace is allowed.

**Comment by RieksJ** [comment]
I can understand why you would expect this to be the case, but that does not make it a bug. So let's discuss this a bit more.

I can see several sides to this:

1. I would agree that this is a bug if the text is actually parsed and errors could result from that. If the text behind an `ENDCONTEXT` is treated as a comment, then I do not agree that this qualifies as a bug - I would welcome this, because it would allow me to put a script-chunk temporarily behind the `ENDCONTEXT` without loosing it - particularly if this script-chunk would contain `{-`-`-}`-comments (that are hard to comment out in a larger block). Situations where this is useful are 

- I need to demonstrate, but I'm still working on some feature that does not completely compile
- I want to keep code of a script that I'm re-using in the file, but do not need that code (yet) in the particular application that I need it for - e.g. I'm debugging and want to keep stuff 'small'.

2. Currently, the keywords `CONTEXT` and `ENDCONTEXT` have no real meaning (other than that script texts should be surrounded by them to be interpreted). This could be an argument to either do away with them, or to think about a proper meaning. 

3. One way of putting `CONTEXT`s to use is as `SERVICE`s, where a `SERVICE` can be seen as a kind/specialization of `CONTEXT` - it has been discussed earlier in [issue#143](https://github.com/AmpersandTarski/Ampersand/issues/143). I think this is (still) a very good idea, and we will be needing it e.g. in different (kinds of) interfaces (humans, excelsheet imports, other webservices).

4. I recall, but do not have a reference to the description of a picture that showed a distinction we need between a 'belly-context' (a databases containing the 'view of the world' of some stakeholder) and 'interface-contexts' that serve as a context for translating between multiple different 'belly-contexts'.

**Comment by hanjoosten** [comment]
Ok. Fair enough. These seem to be valid arguments not to fix this unintentional behaviour. The other points you made here (about some kind of (con? :) )fusion with context, service, interface) deserve some kind of issue of their own. There is much more to be said/thought about that.
