### ISSUE TITLE
Error in difference operator 

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#444]
It seems that the code generated for binary negations, e.g. `(I[Variable] - I[Concern])`, or more in general: `r - s` is incorrect. You can see this because INTERFACEs show populations that I do not expect. Merge pull request #443 seems to introduce this error.

@Michiel-s can we look at this tomorrow, or would a code-inspection of the code generator do the trick? If not, I hope to provide a small example...

I have seen this behaviour (running Ampersand v3.5.1[development-21f43a1]) whereas in Ampersand v3.5.1[development:28036cb] the negations are fine.

**Comment by RieksJ** [comment]
Having started clean again, I have trouble repoducing these errors... Let's put this on hold for now until there is a proper diagnosis.

**Comment by Michiel-s** [comment]
@hanjoosten could you also check if this type of problem occurs in other SQL queries that are generated.

**Comment by stefjoosten** [comment]
This looks like an error in the compilation of the difference operator. I am surprised, because I thought we had tested that Stuff reasonably thoroughly.

**Comment by Michiel-s** [comment]
@stefjoosten this bug is introduced in the recent merge of improving performance of queries (#443). Nothing to worry about.

The last lines of this difference query (before #443) would be:
```sql
ON t1.src = t2.src AND t1.tgt = t2.tgt 
WHERE t2.src IS NULL OR t2.tgt IS NULL
```
We've added `WHERE t1.src = '_SRCATOM'` in between to be able to save a subquery added by the backend. The problem occurs in this statement in combination with the existing WHERE clause. I've added parentheses to show precedence:
```sql
ON t1.src = t2.src AND t1.tgt = t2.tgt 
WHERE (t1.src = '_SRCATOM' 
AND t2.src IS NULL) OR t2.tgt IS NULL
```
This should however be:
```sql
ON t1.src = t2.src AND t1.tgt = t2.tgt 
WHERE t1.src = '_SRCATOM' 
AND (t2.src IS NULL OR t2.tgt IS NULL)
```
It was difficult to diagnose this bug, but easy to fix. @hanjoosten knows how to fix this.

**Comment by stefjoosten** [comment]
Aha! Bitrot!  😂

**Comment by hanjoosten** [comment]
Good catch! Theoretically this could have been a problem in the previous generator as well. For that reason, the fix scatters brackets in all AND and OR constructs in the SQL code now. There is no reason to omit them. Better safe than sorry.
