### ISSUE TITLE
Identity Management in RAP3

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#452]
As a tutor in the OBR-course of the Open University of the Netherlands, I must be able to manage the accounts of my students.
# Account management process in RAP3

A tutor typically makes accounts for students by submitting a spreadsheet of his group. From that point on, he can manage individual accounts.
# Design decisions specifically for RAP3

Students are typically identified by their student number.
# Implementation decisions

For identity management in RAP3, we will use the SIAM-module. With respect to the original SIAM-module in the master, I have added a middle part to names, so I can cope with Dutch names that have small words in the middle (such as "van" and "op den").
# Other

@RieksJ, would you mind supervising this part of RAP3, as you are most familiar with SIAM, being its author.

**Comment by RieksJ** [comment]
That's ok. 

1. **the idea of Modules (including 'SIAM'), is that they provide the smallest basis for some functionality**. Any additions, like the one you did on `personMiddle` must be (sufficiently) generic if you want to include them in the basic module files. Based on the explanation of `personMiddle`, which states that it accommodates a situation that is particular to the Dutch situation, I would reject it for inclusion in `SIAM_PersonReg.adl`. It would be a precedent for others to include similar situational solutions in an otherwise generic file.

2. **extending a module in general should imply creating another file that users may or may not include**. Examples of this already exist, e.g. the login-with-assistance, and the use of ISO authentication levels. In a similar fashion, you could create a `SIAM_DutchPersonReg.adl` that would extend the `SIAM_PersonReg.adl` file with Dutch-specific stuff (e.g. `personMiddle`). You should then also add the following line to the `SIAM_Module-example.adl` file: 
   `-- INCLUDE "./SIAM_DutchPersonReg.adl" -- Person registration to be used in Dutch contexts`
which allows users to use the file or not, to their choosing.

3. **use names that are in line with names that already exist in the module". The name of the relation `personMiddle` should then either become `personMiddleName`, or `personMiddlepart`.

I will be updating the SIAM module shortly so that it becomes more in line with the current developments (and the deployed branch #228).

**Comment by WolframKahl** [comment]
I recommend against using the name “middle part” for small words such as "van" and "op den", since at least in English-speaking countries, the term “middle name” is used for “non-first given name”. A safer alternative might be “prefix”.

**Comment by stefjoosten** [comment]
I am in touch with people at the IT-department of the Open University. I am entering details in this issue to keep track of progress on this topic.

Hubert Vogten (hubert.vogten@ou.nl) knows everything about single-sign-on in the yOUlearn application. Whenever a student is registered for a particular course, access to the corresponding application is granted automatically. That is precisely what I want for RAP3.  It works with a message-bus and is restricted to applications within the OU-datacenter. Hubert is willing to show us how this is done in yOUlearn.

Maarten Scholl is the technical guru, who has the details necessary to get this done.

**Comment by Michiel-s** [comment]
Outdated issue. Login is implemented. Needs improvement, but issue is continued in RAP repository
