### ISSUE TITLE
Semantics of internal functions isUni, isTot, isSur etc. 

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#466]
The semantics of a family of internal functions in Ampersand has not been clear, leading to several problems. The family is all functions based on properties, of the form isTot, isUni, isSur etc. 

We have been saying that a relations is total, iff it has the `TOT` property. Based on these functions, we derive the database structure. However, the modeller can tell how the enforcement should been done, as an invariant (thus, by the system/database) or by signalling a ROLE. The database structure however does not take this into account. The database generation does not take roles into account.

**Comment by Michiel-s** [comment]
Stale issue.

I think this is not a problem nor unclear anymore after the many refactoring we did.

Relations properties have there semantics defined in set theory. For different outputs we transform into other aspects. For example, the isTot is reflected as mandatory attribute in a generated diagram, but allowed to be null in the database table structure because in our prototype architecture the rule engine enforced the totality, not the database.

Let's close this issue
