### ISSUE TITLE
Not able to restore database

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#471]
After I generate my application with release Ampersand-v3.5.2 [development:18027cc], I see no option to install my database. Also, the database is not generated using some kind of automagically:

![knipsel](https://cloud.githubusercontent.com/assets/1159672/16277542/ad1cb728-38b3-11e6-9a4a-11f413d0b6a7.PNG)

Is this by design? If so, please explain. If not, please fix.

**Comment by Michiel-s** [comment]
Hi @hanjoosten, no this is not by design. But I also don't see the application extension menu item (icon with 9 dots) and no top level interfaces. You probably do have those enabled/defined. This makes me think that you have an error communicating with the api.  You could check your network monitor (inspection window of browser) for a hint. Otherwise we'll take a look together.

**Comment by Michiel-s** [comment]
I already know the issue now. And will fix it asap. Sorry for the inconvenience. You can browse to http://<pathtoyourapp>/#/admin/installer to do an install in the mean time.
