### ISSUE TITLE
Erratic behaviour violation messages

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#482]
Version 3.6.0
Might have a relation with #440. I closed it because error messages came up. But maybe that was too soon, may new problems creeped in.

Today I have been working on rules and changing rules and violation messages, but I cannot make sense of what happens.
Things I have encoutered without changing anything in the datafile.
- with two rules working as expected I added a third rule. Suddenly the first rule doesn't produce a message anymore.
- rule A has 2 messages, rule B has 10 messages, after removing rule B, suddenly rule A has 10 messages.
- after editing data in the webinterface, all rules produce the messages I expected.

In between several tests I have deleted proto's, browser history, reinstalled the database more than once. 
If there is anything specific you want me to test, let me know.

**Comment by stefjoosten** [comment]
Hi Esther, it is very difficult for me to make sense out of this. Is it possible for you to report this in a way that the undesired behaviour is reproducible by an Ampersand-team member?

**Comment by EstherHageraats** [comment]
I did what I could with the limited knowledge I have of the architecture of the system.
The 8 test-steps logged in the text-file are reproducible on my computer.
In the zipfile: adl-file, xlsx-file and txt-file.
Hope it will help.
[Issue 482.zip](https://github.com/AmpersandTarski/Ampersand/files/367196/Issue.482.zip)

**Comment by Michiel-s** [comment]
Hi Esther,

The following is happening:

When you add or remove a rule in your script (or change the order of the rules), the generated rules are still the same, BUT the conjunction of which they are made of have other ids. In the database violations to rule are cached by storing the src and tgt atoms for the broken conjucts.

So if you change your rules, you need to reset the database in order to clear the cache and reevaluate the violations. Otherwise you could experience this strange behavior you described.

Let's keep this ticket open to remind me that a fix is needed here. I'm thinking of clearing the cache automatically when the conjuncts file is changed.

**Comment by EstherHageraats** [comment]
OK, nice to know the cause, I know what to do now. 
Seems a good idea to fix this, as changing rules is not a strange thing to do during model development.
Thanks, Michiel.
