### ISSUE TITLE
'_SESSION' atoms do not seem to be typed

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#517]
Consider the following script:

```
qboxAbbr :: QBox * QBoxAbbr     REPRESENT QBoxAbbr TYPE ALPHANUMERIC

INTERFACE "QBox Mgt" FOR QBoxMgr: '_SESSION' cRud BOX
   [ "Name" : qboxAbbr cRud
   ]
```

This script does not produce a type error at compile time. However, it does produce runtime errors because of the (undetected) type error. I consider it a bug that an error is not generated compile time.

**Comment by hanjoosten** [comment]
I disagree. In this case, there is an atom of the concept QBox with a value `_SESSION`.  There is nothing wrong with that, unless that your intention might be different. 

I know of no rule that the value of an atom in any concept must not be `_SESSION`.

**Comment by RieksJ** [comment]
The point being that `_SESSION` is a reserved word/atom, and treated as such by the frontend.

**Comment by hanjoosten** [comment]
> This script does not produce a type error at compile time. However, it does produce runtime errors because of the (undetected) type error. I consider it a bug that an error is not generated compile time.

a) Indeed, there is no compile time error.
b) @RieksJ : Please show the details of the runtime error
c) @Michiel-s: Is it true that no atoms can have the value _SESSION, when they belong to another concept than SESSION? If so, why is this exception needed? Is there a valid reason for that?

**Comment by sjcjoosten** [comment]
If ``_SESSION`` is to be a reserved word, I suggest changing the Ampersand syntax for it to ``SESSION``, without quotes, rather than ``'_SESSION'``. The script mentioned seems to be correct under this interpretation. If you agree, please change this ticket to a feature request and reassign me.

**Comment by RieksJ** [comment]
This would imply that the meaning of `SESSION` becomes context-dependent, as it would represent both the current session(atom) and the Concept that represents the set of all session(atom)s. This could be quite confusing if not for mathematicians, then certainly for engineers. I would not object to a reserved word such as `MYSESSION` or so.
@Michiel-s: can you comment on the impact of this?

**Comment by stefjoosten** [comment]
Stop. I need a diagnosis first.

# Symptoms
1. The script that Rieks presents is being compiled without errors. On runtime it produces the following error:
![image](https://cloud.githubusercontent.com/assets/275768/18426275/a79339ce-78c0-11e6-8999-202c6e4775a5.png)
2. Ampersand interprets the expression `'_SESSION'` as a singleton atom of type `QBox`. If `'_SESSION'` were typed explicitly, the code fragment would read:
~~~
qboxAbbr :: QBox * QBoxAbbr     REPRESENT QBoxAbbr TYPE ALPHANUMERIC

INTERFACE "QBox Mgt" FOR QBoxMgr: '_SESSION'[QBox] cRud BOX
   [ "Name" : qboxAbbr cRud
   ]
~~~


# Diagnosis
This is a clear violation of the Ampersand principle that errors must be prevented by the compiler.

The assumption that `'_SESSION'` is a reserved word is incorrect. Fact is that `'_SESSION'[SESSION]` is an atom with a special status.

To use the atom '_SESSION'[QBox] may be strange or even confusing, but there is no reason to forbid its use. To students I would advise to choose a different name, though.

# Analysis
Since we have an error, some action is needed. What options are there? Well, Either the compiler should prevent this runtime error or it should give an appropriate error message. @RieksJ seems to prefer the error message. @Michiel-s doubts the motivation for that. @sjcjoosten points out a consequence of changing  `'_SESSION'` to a reserved word (which is to turn it into a real reserved word).

# Decision and motivation
One principle of Ampersand is to try avoid exceptions to general rules. For this reason, I don't want to forbid the atom '_SESSION'[QBox]. Therefore, we must look at the intended semantics of Rieks' script. This script should yield an empty screen, because there are no interfaces on `SESSION`. When Ampersand produces warnings, this script ought to produce the warning: "Your script will produce a prototype with an empty screen, because it contains no interface on `SESSION`."

**Comment by RieksJ** [comment]
Since `_SESSION` performs the same (or at least: a similar) role as `ONE`, I think we should look at this from the both perspectives. Consider the following script:
~~~
CONTEXT Test IN DUTCH

-- INCLUDE "TEST.xlsx"

-- CONCEPT ONE "this is the set of Accoutns"

RELATION accPerson[ONE*Person] [UNI,TOT]
RELATION accUserid[ONE*UserID] [UNI,INJ,TOT]
RELATION accPassword[ONE*Password] [UNI,TOT]

POPULATION accPerson   CONTAINS [ ("A1", "Pietje Puk") ]
POPULATION accUserid   CONTAINS [ ("A1", "ppuk@vb.com") ]
POPULATION accPassword CONTAINS [ ("A1", "*****") ]

CONCEPT SESSION ""

INTERFACE "SessionRoles" FOR ExecEngine : '_SESSION';V[SESSION*Role] BOX [ "ignored" : I]

INTERFACE Overview : '_SESSION';V[SESSION*ONE]
COLS[ "Account" : I
    , "Person" : accPerson
    , "Userid" : accUserid
    , "Password" : accPassword
    ]

ENDCONTEXT
~~~

This script does not produce type errors, so you would expect `ONE` to be a (user-defined) concept, which may not be adviseable, but should (according to @stefjoosten) also not be forbidden.

However if a user wants to define this, his concept `ONE`, he gets an error:
~~~
Parsing stumbled upon keyword "ONE"
at that point expecting upper case identifier or string
~~~

It would be nice to have a clean specification of what the texts `ONE` and `_SESSION` actually mean, not only from a relation-algebraic perspective, but also from a (prototype)engineering perspective

**Comment by stefjoosten** [comment]
@RieksJ, you are quite right. This is a beautiful example of an exotic script. I'm flabbergasted that it finds its way through the compiler without errors. This script deserves a place in "shouldFail". Highest time to pay some attention to this issue.

@sjcjoosten, given that `ONE` represents the universal singleton, can we prevent statically (e.g. by type checking) that the user assigns his own atoms to this concept? Or should we detect this when checking the correctness of populations?

**Comment by sjcjoosten** [comment]
ONE comes with the rule ``I[ONE] = V[ONE]``, which would prevent adding more than one atom to it. This rule is not checked as far as I know, and I think it should.

Furthermore, the rule is not violated by Rieks' example, since only the atom "A1" is used. If you want to disallow this, I propose that we create a dedicated atom, say ``_ONE`` (or in a syntax similar to what we choose for the magic/special atom in the concept ``SESSION``), such that the following would be accepted:

``
POPULATION accPerson   CONTAINS [ (_ONE, "Pietje Puk") ]
POPULATION accUserid   CONTAINS [ (_ONE, "ppuk@vb.com") ]
POPULATION accPassword CONTAINS [ (_ONE, "*****") ]
``

If we were to do that, we can enforce that ``_ONE`` is always in the population of ``ONE``, such that adding "A1" to it is not allowed by the rule ``I[ONE]=V[ONE]``.

**Comment by Michiel-s** [comment]
Better late than never. Hereby my explanation of what's happening with _SESSION in the prototype backend code.

1) _SESSION is a reserved word that gets replaced with the user's current Ampersand session atom.
2) This search/replace action is performed on the query just before it is sent to the database.
3) At this point the code has no sense of atoms, relation, concepts anymore. All '_SESSION' parts of the query string are replaced. You can experience this by typing '_SESSION' in an alphanumeric textbox and see that your session id is stored and returned.

For sure this is wrong, insecure and we need to fix this. I'll increase the priority and fix this asap.

From my point of view, atom _SESSION should only be replaced when it is part of the SESSION concept.
And _SESSION should only be replaced when it is defined as such in the ampersand script. That implies that when a **user** provides _SESSION as a value, it will not be replaced.

Solution is to work with prepared database statements. Which is also the solution for sql injection (#271).

I'll let you guys decide whether _SESSION should be a reserved keyword in ampersand scripts or that _SESSION is also a valid atom for any other concept.

**Comment by hanjoosten** [comment]
The search/replace action that is performed on the query just before it is sent to the database isn't a very nice solution in either ways. Thought it works for now, in the long run this is inevitable going to give problems. Someone might populate an atom with `THE_SESSION_OF_PETER`, so also substrings aren't safe now.

**Comment by Michiel-s** [comment]
I agree, as I already pointed out myself.

> For sure this is wrong, insecure and we need to fix this. I'll increase the priority and fix this asap.

**Comment by Michiel-s** [comment]
>I wrote: I'll let you guys decide whether _SESSION should be a reserved keyword in ampersand scripts or that _SESSION is also a valid atom for any other concept.

With respect to that: it must be a reserved keyword to represent the current session atom, because it can occur in generated sql queries and the prototype backend cannot know if it concerns the SESSION concept. E.g. 

```adl
r :: A * B
s :: B * C

INTERFACE "test" : r;'_SESSION[B]';s
```
this results in an interface object with src concept A, tgt concept C and a query that contains '_SESSION'. In this case it is not the session atom, but a singleton of B. The information that the interface expression contains concept B and not concept SESSION is not available in the prototype.

**Comment by Michiel-s** [comment]
Todo:
- [ ] make sure that _SESSION for user/execengine input is only replaced when it concerns the SESSION concept. (prototype backend -> action Michiel)
- [ ] make sure _SESSION can only be used as singleton atom for the SESSION concept (ampersand scripts -> action @hanjoosten or @sjcjoosten )

**Comment by sjcjoosten** [comment]
On the parser side, here's my proposal for making this type-safe:

Apart from having atoms like 'Hans' and 'Piet', we also have atoms like numbers (12345). This depends on the ``REPRESENTS`` statements. I propose to do something similar here. Concretely, ``SESSION`` becomes something that is represented by its own separate built-in type. This way, 'Hans' and 'Piet' are no longer allowed inside that concept, because of a type mismatch (just like you cannot insert 'Hans' into something is a number). In fact, the only element that does have the right type, will be ``_SESSION``.

**Comment by Michiel-s** [comment]
An update to this issue.
As of #721 _SESSION is **only** replaced in generated queries (for interfaces, conjunct evaluation, view segments and violation segments). User input is not replaced anymore.

This doesn't solve the problem of this issue yet, because the singleton '_SESSION' for other concepts apart from SESSION can still be specified in Ampersand. This is the case for the script of Rieks in his initial comment, where _SESSION is considered an atom in QBox. The generated query contains _SESSION (no user input!) and is replaced by the session id.
```
qboxAbbr :: QBox * QBoxAbbr     REPRESENT QBoxAbbr TYPE ALPHANUMERIC

INTERFACE "QBox Mgt" FOR QBoxMgr: '_SESSION' cRud BOX
   [ "Name" : qboxAbbr cRud
   ]
```
