### ISSUE TITLE
Are the testscripts wrong, or the typechecker?

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#519]
@stefjoosten found an error in the parser. The [branch *bugfix_with_generalisations*](https://github.com/AmpersandTarski/Ampersand/tree/bugfix_with_generalisations) that is meant to fix it.

I would like an expert opinion on this issue by @sjcjoosten, because this is about the type system. (SJ: I have isolated this question and moved it to issue #520)

Here are some links:
 * The [commit](https://github.com/AmpersandTarski/Ampersand/commit/266bb23c66290a8eadb6713be565645394ab43d6) containing the change that Stef made
 * The [branch *bugfix_with_generalisations*](https://github.com/AmpersandTarski/Ampersand/tree/bugfix_with_generalisations) that is ment to be used to fix the consequences.
 * The [log of Travis ](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/157461678) (see line 700 and other `*FAIL*` instances in this log.)

**Comment by stefjoosten** [comment]
# Diagnosis

The error was found in `ParseTree.hs`. The definition of equality for `P_Gen`, in the following code fragment.

~~~~
data P_Gen =  P_Cy{ gen_fp ::  Origin            -- ^ Position in the Ampersand file
                  , gen_spc :: P_Concept         -- ^ Left hand side concept expression
                  , gen_rhs :: [P_Concept]       -- ^ Right hand side concept expression
                  }
            | PGen{ gen_fp  :: Origin         -- ^ the position of the GEN-rule
                  , gen_spc :: P_Concept      -- ^ specific concept
                  , gen_gen :: P_Concept      -- ^ generic concept
                  }
instance Ord P_Gen where
 compare p1 p2 = compare (gen_spc p1,gen_gen p1, origin p1) (gen_spc p2,gen_gen p2,origin p2)
instance Eq P_Gen where
 p1 == p2 = (compare p1 p2 == EQ)
~~~~
The error is that `compare` will not work if a `P_Cy` is involved, because `gen_gen` is not defined for `P_Cy`. this error is visible in [ParseTree.hs](https://github.com/AmpersandTarski/Ampersand/blob/development/src/Ampersand/Core/ParseTree.hs) on commit e49d70b9124f635a34c1193e3b002c665bf6e075

Apparently, the equivalence suggested by the current implementation is equivalent to the standard Haskell `Ord`. For this reason  I suggest to use Haskell's `deriving (Eq, Ord)`:
~~~~
data P_Gen =  P_Cy{ gen_fp ::  Origin            -- ^ Position in the Ampersand file
                  , gen_spc :: P_Concept         -- ^ Left hand side concept expression
                  , gen_rhs :: [P_Concept]       -- ^ Right hand side concept expression
                  }
            | PGen{ gen_fp  :: Origin         -- ^ the position of the GEN-rule
                  , gen_spc :: P_Concept      -- ^ specific concept
                  , gen_gen :: P_Concept      -- ^ generic concept
                  } deriving (Eq, Ord)
~~~~
The suggested correction works as far as Travis is concerned. However, this does not close this issue...

**Comment by stefjoosten** [comment]
@hanjoosten if you believe issue #520 covers this, you may close this.

**Comment by hanjoosten** [comment]
I reopend this issue. I removed gen_concs (commit d10339da457bed5f1b32446e284e4e7fd16b5153) and rewritten the place where it was used. I believe it was used to get the generic concepts of a P_Gen. However, now again there are test scripts that fail. I really would like @sjcjoosten to have a look.

**Comment by hanjoosten** [comment]
See the [travis outcome](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/157567426)

**Comment by sjcjoosten** [comment]
Please tell me where in the travis outcome to look. There are several kinds of errors. Line 700 says Start testing of `try37.adl`: ***Pass***, does not seem to be a bug.

**Comment by hanjoosten** [comment]
Ah. See what you mean. Forget the line number 700. In the last travis outcome, the FAIL are on different lines. There are 6 testcases that failed because the should fail, but the typechecker sees no error:

- Issue142TooGeneric.adl
- Ticket237.adl
- Try1.adl
- Try48.adl
- Try49.adl
- try4.adl
 There is one case that should succeed, but it fails:
- specializeTest.adl

**Comment by sjcjoosten** [comment]
Did not test yet (we don't have the pie-rule anymore do we?). Feel free to reopen if it is not fixed.

**Comment by hanjoosten** [comment]
Could you explain your fix? It seems wierd that this is correct.

**Comment by sjcjoosten** [comment]
```A ISA B```

is syntax sugar for:

```A IS A /\ B```
