### ISSUE TITLE
Erroneous delete-behaviour within transaction.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#524]
# Experiment

Take `ampersand\testing\Travis\testcases\prototype\shouldSucceed\specializeTest.adl` and make a prototype using 

```
Ampersand --verbose -pD:\htdocs\klad specializeTest.adl
```

Switch both autocommit and autosave off in the browser. Navigate to `Gs`. Click the trash-can of `Jack`. (see screenshot)

![image](https://cloud.githubusercontent.com/assets/275768/18416613/8fb03c78-7819-11e6-9164-d6cf5d4c0a32.png)

After clicking the trash-can, Jack is deleted in spite of the fact that I (as a user) have not committed the transaction. I would have expected a SAVE button to appear.
![image](https://cloud.githubusercontent.com/assets/275768/18416641/2ea6e67e-781a-11e6-8149-512ba5d8fc50.png)

**Comment by stefjoosten** [comment]
# Analysis
In Atoms.php at line 615 it shows that items can be replaced, links can be removed, and items can be added. A fourth type of `$patch['op']` is required to delete things within a transaction.

![image](https://cloud.githubusercontent.com/assets/275768/18416692/b4609958-781b-11e6-8455-a52707de9bab.png)

**Comment by Michiel-s** [comment]
Indeed, this functionality is not yet completely consistent. Currently the Delete (trashbin) and Create, implemented by http DELETE and POST calls are not cached as changes in the frontend. The 'auto commit' and 'auto save' switches have no affect here. There's is a reason for that and we should make it clear for the user when to expect what behavior.

Adding a fourth patch operation is in my opinion not the way to go. The patch operations we support are a subset of an IETF standard for this (https://tools.ietf.org/html/rfc6902).

Another more complicated solution would be to include the DELETE and POST calls in the changes cache. To be continued.

**Comment by Michiel-s** [comment]
The autocommit switch is removed from the front end some time ago. We do still have the autosave. Auto save determines if changes to fields are directly send to the API (i.e. onBlur of data fields). Clicking on the trash bin triggers a delete immediately, but I think this is expected behavior, because the user clicks on it.

Without the autocommit switch, I don’t think there is any confusion about the effect of clicking the trash bin icon. Furthermore a confirmation is required in a dialog window (see also #430.
