### ISSUE TITLE
Time limit of initialization of database

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#527]
The time limit currently can be set in localSettings.php. This limit is used whenever there is a call to php. 
When initializing the database, the entire period required to construct all tables and inserting all rows into these tables, has to be within the given time period. 

I would like to see that for each query in the initialization phase, the [timer is reset](http://ca3.php.net/set_time_limit). This way, the time limit can be kept relatively low, and still be able to initialize/reset the database, and import values.

**Comment by hanjoosten** [comment]
Nice to have: If you know how many queries there are, this might be made visible in a [progress bar](http://www.w3schools.com/bootstrap/bootstrap_progressbars.asp) :smiley:

**Comment by Michiel-s** [comment]
@hanjoosten  please check if my commit solves your time limit issue.

Notice that in my case many times it is not the default population but the ExecEngine, that kicks in during the initialization phase, that's causing the time out. I'm not sure if we should also apply the time limit trick to this part, because the ExecEngine is also used outside the reinstallation process.

**Comment by hanjoosten** [comment]
When there are lots of tables in the script, creating all tables including all indexes will also take too long. So I copied your solution there.

**Comment by hanjoosten** [comment]
I wouldn't do this same thing for the ExecEngine, for that was the initial cause of setting a time limit all together, if I remember well. Since there is a lot that can go wrong in defining the behaviour of the ExecEngine by the modeller, I suggest to leave this as it is now. If you disagree, reopen the issue.

**Comment by Michiel-s** [comment]
Great. I agree.
