### ISSUE TITLE
Bug: infinite loop detected in function executePHPStr in module PHP.hs

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#557]
# Reproduction
The context of this issue is repository Ampersand, branch feature/InjUniDefinition, SHA a170548f4cc23f9a79c44f25a735a68180206bea. The behaviour is reproduced by: 

~~~~~~
D:\git\ampersand\testing\Travis\testcases\prototype\shouldSucceed>ampersand --verbose --validate --sqlLogin="root" --sqlPwd="" --meta-tables --proto Archimate1.adl
~~~~~~
# Symptoms
I have identified the location in the Ampersand compiler where the infinite loop occurs by introducing `verboseLn` statements in function `executePHPStr `. The execution proceeds to show  `executePHPStr: 4` and then fails.
![image](https://cloud.githubusercontent.com/assets/275768/20028498/c3e844aa-a333-11e6-9f1d-11710f4b2423.png)

**Comment by hanjoosten** [comment]
Unfortunately, on linux, this solution does not seem to work

**Comment by hanjoosten** [comment]
## Diagnosis

It turned out, that the --validate was the culprit. There was no loop whatsoever.

### working of --validate
--validate does a check on each and every rule in a script. For each rule, the violations are retrieved in two different ways. The results of each of them are compared, and they should be equal. If both ways to retrieve the violations come up with different results, at least one of the ways must be wrong. 

The first way is over Haskell. The violations are calculated using the relation algebra implemented in Haskell.
The second way is using a temporary database: Based on the script the database is generated and populated with the initial population. Then the query that is build for the violations of the rule is run, yielding the violations. 

### So what went wrong?
The query is run by invoking php as a child process. The result was read from stdout. There is some buffering going on. Only the first part of the buffer was returned. In most cases so far, that was enough. However, in the case of Archimate1.adl, compiled with the --meta-tables swich, there was a rule where the violations didn't fit in the first part of the buffer. Then the subprocess was waiting for the buffer to be emptied, but the parent process was waiting for the child process to end. Deadlock. 

### Solution
My solution was to let PHP write its output into a temporary file instead of to stdout. This goes well on Windows. The child process terminates, and then the file was read and removed. 

This solution has been tested on windows, and there it works well. 

### New problem
On Linux, (i.e. Travis), this solution doesn't work for some reason. Archimate1.adl causes nontermination again. Therefore, Travis tests fails.

### Conclusion
The real fix would be to bypass php. When we use a haskell package for SQL (there exists several), we could query the database directly from within ampersand. This has several benefits. However, it would mean quite some rewriting of code. Untill that time, Archimate1.adl has been seperated into another directory, where --validate is not part of the regression test. By doing so, Travis-ci builds again.

**Comment by stefjoosten** [comment]
As long as the Archimate1.adl-test doesn't pass Travis, we must leave this issue open.
That will most likely last until issue #559 has been resolved.
