### ISSUE TITLE
Memory size error in (very)large prototype

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#561]
In RAP3 I did the following test:

I loaded more than 500 versions of the script of Arbeidsduur. This results in quite a large database, with about 400000 records in total. 

Then, from that script, I enabled the destroy of a single loaded context. 

This resulted in the following error:

![image](https://cloud.githubusercontent.com/assets/1159672/20037337/f97c166a-a41d-11e6-8214-3023d75f98c3.png)

**Comment by hanjoosten** [comment]
@Michiel-s , this is probably the caching mechanism. Any ideas about when caching should be overruled to prevent these kind of errors?

**Comment by stefjoosten** [comment]
First, how can we get evidence that the caching mechanism is to blame?

**Comment by Michiel-s** [comment]
We can disable the cache and check if the error still occurs.

**Comment by Michiel-s** [comment]
Still experiencing issues? In a large application of myself I don’t see this happening.
In the meantime a lot has improved in the prototype backend implementation. Maybe this issue is fixed?! Performance (duration and memory usage) is now logged for every request. See /log/performance.log
I’ll close this issue. Feel free to reopen if needed
