### ISSUE TITLE
Non-navigable INTERFACE in RAP3

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#566]
I compiled and ran RAP3 from repo ampersand-models@218f159fa0a73135b24f85ce11dc21d3bfd0063a, using the compiler from ampersand@6b615957e8aec416db782423236884f218ca454f with command line
~~~~~~
C> ampersand.exe --meta-tables --meta-file --verbose -pD:\htdocs\AmpersandPrototypes\RAP3\ "RAP3.adl"
~~~~~~
 `git\ampersand-models\RAP3\RAP3_LoginForDevelopment.ifc`, in r  there is an interface called `Login (DEV)`. After generating the application, navigating to that interface results in a missing HTML-page message (404). I wondered whether the brackets in the name were to blame, but that is not the case...

![image](https://cloud.githubusercontent.com/assets/275768/20541036/c8ebd64e-b0fb-11e6-9ab3-1d080661a83d.png)

**Comment by RieksJ** [comment]
I have no clue.
I have made sure I have the same ampersand.exe version, yet I cannot reproduce the error.
Obviously, since the compiler does not complain, the interface is being compiled.

It resembles [RAP issue 11](https://github.com/AmpersandTarski/RAP/issues/11), where I get the error and you guys cannot reproduce it. 

@stefjoosten: I think a proper diagnosis is called for using your installation. Perhaps a session with @Michiel-s migth shed some light here.

**Comment by Michiel-s** [comment]
I cannot diagnose the issue with the information provided. As @RieksJ suggest, a meeting is necessary.

**Comment by stefjoosten** [comment]
@hanjoosten, I have reproduced this error by:
 - deleting the entire generated application from my htdocs folder
 - compiling RAP3@218f159fa0a73135b24f85ce11dc21d3bfd0063a with Ampersand-v3.7.2 [development:6b61595] with the command line argument:
~~~~~~
ampersand.exe --meta-tables --meta-file --verbose -pD:\htdocs\AmpersandPrototypes\RAP3\ "RAP3.adl"
~~~~~~
The error still shows up...  :-(

**Comment by stefjoosten** [comment]
Due to his Master's 2nd pair of eyes, this bug got scared the heck out of this system....
Issue closed

**Comment by Michiel-s** [comment]
Sometimes waiting is enough to fix an issue:)
