### ISSUE TITLE
ampersand-models/ZwolleFrontEnd/EURent: README still up-to-date?

### ISSUE THREAD

**Issue by WolframKahl** [AmpersandTarski/Ampersand#577]
(I found no issue tracker for ampersand-models, and therefore report here.)

The file `EURent README.adl` contains:
````
  1) Create the prototype, and run "installer.php" to initialize the
     database with the demo population.
````
I cannot find `installer.php`: neither in this directory, nor in the generated prototype.
(But some population is displayed in OVERVIEW.)
````
  1) In the Menu bar, click on 'EU-Rent Website'
````
This shows:
````
    Home EU-Rent Website 

         s89b860apb02vbm1kvak7hjk94 

        Create a new rental
        or select your case
````
and an entry box besides the last two lines.

The README continues:
````
     a) Click 'Edit' and enter the following information:
        - Enter reference number for your new rental: 'Pete's rental'
        - Click 'Save'
        A new rental form has been created;
        the yellow box (bottom right) shows signals that tell the user what
        (s)he should do
````
There is no `Edit` to click.
If I enter  `Pete's rental` in the entry field, I get: `RentalCase not found!` in red below that field.

There is also no `Save` to click.

I am stuck.

**Comment by hanjoosten** [comment]
@RieksJ , could you please have a look at this?

**Comment by WolframKahl** [comment]
(It is now working out that I will only be able to talk about Ampersand next Tuesday. EURent looked attractive since it was relatively recently updated (that's how I found it), and the README contains a script for doing a demo. Are there other models like that? There is a lot of stuff in `ampersand-models`...)

**Comment by RieksJ** [comment]
The `README.adl` is up to date. The Application Status paragraph says: `The application is known to have compiled with "Prototype v3.0.1.2964".` You may have to delve up this version of `prototype.exe` though.

But I guess you do not want `README.adl` to be up to date, but you want EURent to work with the current Ampersand tools. That's another story, given the (significant) changes, in particular w.r.t. interfacing, that have taken place since then. And the fact that Michiel is again currently working on interfacing. A dilemma here is when to put effort into this. If nobody uses it, there's no point to update EURent. If it will be used on a more or less regular basis, there is.

**Comment by WolframKahl** [comment]
Well, what do you guys use for your demos, or to show the system off to visitors and students?

`Examples/ProjectAdministration` ( #215 ) has even less recently been updated than EURent, and EURent has a nice kind of scope, with at least two special-purpose interfaces for different roles.


By the way, I find in `EURent Ontology.adl` (why white space in file names? ...):
````
carType :: Car -> CarType
PRAGMA  "Car with license plate" "is a "
MEANING "Every car is of a specific type (brand, model)."
````
(The `MEANING` seems to suggest `UNI,TOT`, but neither is there, nor did I find them specified later.)
````
contractedCarType :: RentalCase * CarType [UNI]
PRAGMA "The contractual type of the car being rented under" "is"
MEANING "Rental contracts may specify the car type of the rental."
````
The `may` strongly suggests that `contractedCarType` does not need to be total. (For a flexible rental company, one might even consider to drop `UNI` with unchanged `MEANING`...)

But: then
````
RULE "Rented car type integrity": rcAssignedCar |- contractedCarType;carType~
MEANING "The type of a rented car must be the same as the type mentioned in the contract."
````
has the consequence that if the type was not specified in the contract, no car can be assigned.

**Comment by WolframKahl** [comment]
> If nobody uses it, there's no point to update EURent. If it will be used on a more or less regular basis, there is.

I would like to have the capability to show off Ampersand on a more or less regular basis, in particular to students interested in doing projects with me. If I know that EURent is maintained, then that saves me a lot of hunting.

(From the README, its purpose was for comparison with DEMO-3   —  did that lead to a paper?)

**Comment by RieksJ** [comment]
Ok. Let me start by saying that you convinced me to put some effort in getting EURent working more or less properly - at least sufficiently for you (and others?) to show off Ampersand. 

To answer your questions:

- In `carType :: Car -> CarType`, the `->` is shorthand for `*` in combination with `[UNI,TOT]`. It is (still?) allowed syntax, but nobody seems to use it any more.
- `contractedCarType :: RentalCase * CarType [UNI]` is not total, because a `RentalCase` may be in the situation where it is only partially filled in. That's why there also is a rule that will urge a user to provide a value and make `contractedCarType` total, similar to e.g.:
~~~
ROLE User MAINTAINS "Required field: Car type"
RULE "Required field: Car type":  I[RentalCase] |- contractedCarType;contractedCarType~
VIOLATION (TXT "Required field 'Car type' must be filled in")
~~~
- You are right about the consequences of the rule `Rented car type integrity`. These consequences are actually intended. The assigned car must comply with the customers wish (as he may have a limited budget to spend on the car), so a car can only be assigned after the customers wish has been made explicit

**Comment by RieksJ** [comment]
@WolframKahl I have checked in a new version of EURent, so that you can see if you can get it to compile and run. It's not all done, but I do appreciate any (preliminary) feedback that you may have, e.g. wishes you have for showing the stuff off as you would like to do it.

**Comment by WolframKahl** [comment]
@RieksJ , thank you very much! I will explore this hopefully soon!
