### ISSUE TITLE
MYSQL error 2006: MySQL server has gone away in query: COMMIT

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#579]
While revising (the TNO development version of) EURent, which is going as it should, at some point I was taken by surprise with the error as mentioned in the title of this issue, leading to the following output: 

![image](https://cloud.githubusercontent.com/assets/8522589/20864613/54812676-b9f0-11e6-8b18-e73158a0669f.png)

I have been able to reproduce this bug with the following, smaller script (allowing others to think along):
~~~
CONTEXT Issue579 IN ENGLISH
-- https://github.com/AmpersandTarski/Ampersand/issues/579

rcDriver :: RentalCase * PersonRef [UNI]
rcRenter :: RentalCase * PersonRef [UNI]
rcDrivingLicense :: RentalCase * DrivingLicense [UNI]
contractedPickupBranch :: RentalCase * Branch [UNI]
contractedDropOffBranch :: RentalCase * Branch [UNI]
contractedStartDate :: RentalCase * Date [UNI]
contractedEndDate :: RentalCase * Date [UNI]
contractedCarType :: RentalCase * CarType [UNI]

rcSig :: RentalCase * RentalCase [PROP] 

ROLE ExecEngine MAINTAINS "DelPair rcSig"
RULE "DelPair rcSig":
rcSig
|- I[RentalCase] /\ 
   (  rcDriver;rcDriver~
   \/ rcRenter;rcRenter~
   \/ rcDrivingLicense;rcDrivingLicense~
   \/ contractedPickupBranch;contractedPickupBranch~
   \/ contractedDropOffBranch;contractedDropOffBranch~
   \/ contractedStartDate;contractedStartDate~
   \/ contractedEndDate;contractedEndDate~
   \/ contractedCarType;contractedCarType~
   )
VIOLATION (TXT "{EX} DelPair;rcSig;RentalCase;", SRC I, TXT ";RentalCase;", TGT I)

ENDCONTEXT
~~~
I have noted that whenever you comment out one of the terms `\/ relation;relation~` from the expression, you do not see this error.

**Comment by RieksJ** [comment]
I have been able to reproduce this bug with the following, smaller script (allowing others to think along):
~~~
CONTEXT Issue579 IN ENGLISH

rcDriver :: RentalCase * PersonRef [UNI]
rcRenter :: RentalCase * PersonRef [UNI]
rcDrivingLicense :: RentalCase * DrivingLicense [UNI]
contractedPickupBranch :: RentalCase * Branch [UNI]
contractedDropOffBranch :: RentalCase * Branch [UNI]
contractedStartDate :: RentalCase * Date [UNI]
contractedEndDate :: RentalCase * Date [UNI]
contractedCarType :: RentalCase * CarType [UNI]

rcSig :: RentalCase * RentalCase [PROP] 

ROLE ExecEngine MAINTAINS "InsPair rcSig"
RULE "InsPair rcSig":
   I[RentalCase] /\ 
   (  rcDriver;rcDriver~
   \/ rcRenter;rcRenter~
   \/ rcDrivingLicense;rcDrivingLicense~
   \/ contractedPickupBranch;contractedPickupBranch~
   \/ contractedDropOffBranch;contractedDropOffBranch~
   \/ contractedStartDate;contractedStartDate~
   \/ contractedEndDate;contractedEndDate~
   \/ contractedCarType;contractedCarType~
   ) |- rcSig
VIOLATION (TXT "{EX} InsPair;rcSig;RentalCase;", SRC I, TXT ";RentalCase;", TGT I)

ENDCONTEXT
~~~
I have noted that whenever you comment out one of the terms `\/ relation;relation~` from the expression, you do not see this error.

**Comment by hanjoosten** [comment]
Hmm. We all seem to have different settings of MySQL. I am allready thinking of lifting the minimum version of it, and this is another argument in favor of that.

I did some googleing on this issue. In [this thread](http://stackoverflow.com/questions/10474922/error-2006-hy000-mysql-server-has-gone-away) you can find a remedy (raising the value of MAX_ALLOWED_PACKET in your MySQL configuration). This might help. 

I do not want to go into the path where we have to hunt bugs that are specific for a single installation. If this thing gets reproducable in common, up-to-date installed configurations, it becomes another buiscuit.

**Comment by Michiel-s** [comment]
@hanjoosten is just before me with providing the answer. I run into this issue myself a couple of months ago.

The problem occurs due to a very large default population for a single concept/relation, which get's inserted in a single query. When the query exceeds 1 MB (default config of mysql) you'll receive this error.

Short term fix: 
in XAMPP\mysql\bin\my.ini, under [mysqld] set `max_allowed_packet = 1M` to a higher value. Restart your database

Long term fix:
split up default population, provided in mysql-instsaller.json, into multiple queries. Or redefine this "import" function. I have some thoughts about this.

**Comment by RieksJ** [comment]
It is not that I doubt that large populations give a similar error, but the default population of the above (little!) script is zilch (zero, naught, nothing, niente, nada).

**Comment by Michiel-s** [comment]
@RieksJ, Ah, now I see that you've also posted a small script to illustrate the problem. Sorry for that.

In this case it is not because of a large population, but probably because of a large query itself. The one generated from your heavy expression is about 300!! lines. Kind of makes me think you should rewrite this functionality/check into multiple components.

I can't reproduce the error myself. You write that if you comment out one line of the expression, you don't have the error. I think there is your tipping point in the size of the query your database accepts.

Can you verify your max allowed packet size? http://localhost/phpmyadmin/server_variables.php

**Comment by RieksJ** [comment]
My max_allowed_packet = 1,048,576 (which I think is default).

Makes me wonder what is so special about the expression; it seems to be quite straightforward, so why should the query be so big? But then, it is what it is.

I can imagine that the sql-generator could throw an error (or warning) when it generates queries that are bigger that what is by default allowed (or by configuration constant)

**Comment by Michiel-s** [comment]
Rieks just changed the rule expression in the initial post. Turns out that the first mentioned expression resulted in +/- 300 lines (the inspair rule). When switchting the left hand and right hand side of the implication (as currently shown in de delpair rule), this results in a query of +/- 36.000 lines. There the real blow up ( #582 ). This query indeed exceeds the 1MB limit.

**Comment by sjcjoosten** [comment]
So this issue is about getting big (>1MB) to the prototype generator, resulting in code that cannot be executed under the default SQL settings: do we want to allow this, do we want to issue a warning, or do we want to identify the problematic rule and tell the user to simplify his rule (assuming the rule is more involved than the example here)?

**Comment by RieksJ** [comment]
I can imagine a new option (say: --sql-maxquirysize=xxx, where xxx is either the number of bytes) that specifies the max. size of sql queries. 

An error is generated as well as a pointer to the problematic rule when

- in case the option is specified, the size of the generated query exceeds xxx.
- in case the option is not specified, the size of the generated query exceeds the default set for SQL databases (1MB)

**Comment by sjcjoosten** [comment]
I agree. I propose to also generate the required size:

```
Error generating SQL code for Rule so-and-so
The generated SQL expression has size xx1, which exceeds the [default] limit of xx1.
Re-run ampersand with the switch --sql-maxquerysize=xx1 and make sure that max_allowed_packet in mysql.ini is at least as large as this value.
```

Feel free to edit this comment in order to improve the desired message.

**Comment by hanjoosten** [comment]
This seems a wrong way. The 'size' of a query? Do you mean the length of the string that expresses the query? Is that prettyprinted? ( lol) What if the query has relationnames that are lengthy. Or not? This is VERY subjective. Let's not waste time on this. If we signal such cases, let's diagnose the reason for being so large, and solve that.

**Comment by sjcjoosten** [comment]
Yes, I was referring to the size of the prettyprinted query. I agree that this does not seem as important as fixing the underlying cause, #582 
A major advantage of the fix proposed here, is that the cases that are so large for some reason become 'fails' when testing them. That is, issues similar to #582 become more visible in our current test-setup.

**Comment by hanjoosten** [comment]
That should be pretty straitforward. you can choose between prettyprinted-with-comments or non-prettyprinted-without-comments. If the length of either one of them is greater than someValue, then fail, dumping whatever info you like. Not nice, but effective for this purpose.

**Comment by hanjoosten** [comment]
The normalizer has been turned off (see issue #582), which effectively fixes this problem.

**Comment by sjcjoosten** [comment]
If you are here after getting the following message:

```
The SQL that is being generated by your script, is probably way too complex. This is likely due to a glitch in the normalizer or SQL generator. Please upload your script as a comment to https://github.com/AmpersandTarski/Ampersand/issues/579 . This enables us to investigate so we can produce better SQL in future. Thanks! Btw: You can still use the --sqldump switch to see the generated SQL. That output would help us too.
```

Please reopen this issue.
