### ISSUE TITLE
Blowup of expression size in SQL

### ISSUE THREAD

**Issue by sjcjoosten** [AmpersandTarski/Ampersand#582]
In issue #579 Rieks devised the following script:

```
CONTEXT Issue579 IN ENGLISH

a :: RentalCase * PersonRef [UNI]
b :: RentalCase * PersonRef [UNI]
c :: RentalCase * DrivingLicense [UNI]
d :: RentalCase * Branch [UNI]
e :: RentalCase * Branch [UNI]
f :: RentalCase * Date [UNI]
g :: RentalCase * Date [UNI]
h :: RentalCase * CarType [UNI]

rcSig :: RentalCase * RentalCase [PROP] 

ROLE ExecEngine MAINTAINS "InsPair rcSig"
RULE "InsPair rcSig": rcSig |- I /\ (  a;a~  \/ b;b~  \/ c;c~  \/ d;d~  \/ e;e~  \/ f;f~  \/ g;g~  \/ h;h~)
VIOLATION (TXT "{EX} DelPair;rcSig;RentalCase;", SRC I, TXT ";RentalCase;", TGT I)

ENDCONTEXT
```

It seems to blow up into a big query of 36000+ lines of SQL, which I think illustrates an issue with the normaliser, that is: I believe that there is also a big RA expression internally.

I expect that it is possible to have no such blowup by turning off some things done by the normaliser.

**Comment by Michiel-s** [comment]
The delpair variant of this rule, results in +/- 36.000 lines of sql. That's the real problem.

**Comment by WolframKahl** [comment]
I just double-checked in `Core/AbstractSyntaxTree.hs`: Ampersand is indeed missing the following expression constructors:
````
dom R := I /\ R ; R~
ran R := I /\ R~ ; R
````
I assume that `[PROP] ` means subidentity/coreflexive/monotype   —  is `[PROP] ` actually used to do single-column representations? Since `dom` and `ran` produce subidentities, any optimisation for  `[PROP] ` would reward uses of `dom` and `ran`...
(If `[PROP] ` does mean subidentity, then the `I /\ ` in the original expression is superfluous, unless it magically produces translation to `dom` internally. But if you have that magic, then you can make it trigger also on the `rcSig |-`.)

With `dom`, the rule above becomes:
````
RULE "InsPair rcSig": rcSig |- dom a  \/ dom b  \/ dom c  \/  dom d  \/ dom e \/ dom f  \/ dom g \/ dom h
````

**Comment by stefjoosten** [comment]
The normalizer has been switched off, because the added value of normalizing before code generation is low.

What we want is code optimization, but this goes much further than normalizing alone.
