### ISSUE TITLE
Specific kinds of VIEW do not work in prototypes

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#591]
The idea of the following script is that atoms in `Amount` are rendered on the screen as `{atom} (Euro)`. Similarly, atoms in `NumberOfDays` are to be rendered as `{atom} (Days)`. This is done by defining relevant `VIEW`s: 
~~~
CONTEXT Issue591 IN ENGLISH

REPRESENT Amount TYPE ALPHANUMERIC
REPRESENT NumberOfDays TYPE INTEGER 

rentalDailyTariff :: Rental * Amount    
rentalPeriod :: Rental * NumberOfDays
rentalCharge :: Rental * Amount

VIEW "EuroPerDay": Amount { "number": I, "unit": TXT " (Euro/Day)" } ENDVIEW
VIEW "Euro": Amount       { "number": I, "unit": TXT " (Euro)"     } ENDVIEW
VIEW "Days": NumberOfDays { "number": I, "unit": TXT " (Days)"     } ENDVIEW

POPULATION rentalDailyTariff[Rental*Amount]  CONTAINS [ ("Rental_000", "5") ]
POPULATION rentalPeriod[Rental*NumberOfDays] CONTAINS [ ("Rental_000", 10) ]
POPULATION rentalCharge[Rental*Amount]       CONTAINS [ ("Rental_000", "50") ]

POPULATION rentalDailyTariff[Rental*Amount]  CONTAINS [ ("Rental_001", "3") ]
POPULATION rentalPeriod[Rental*NumberOfDays] CONTAINS [ ("Rental_001", 4) ]
POPULATION rentalCharge[Rental*Amount]       CONTAINS [ ("Rental_001", "5") ]

POPULATION rentalDailyTariff[Rental*Amount]  CONTAINS [ ("Rental_002", "12345") ]
POPULATION rentalPeriod[Rental*NumberOfDays] CONTAINS [ ("Rental_002", 125) ]
POPULATION rentalCharge[Rental*Amount]       CONTAINS [ ("Rental_002", "12345125") ]

INTERFACE "Issue591 Demo": V[SESSION*Rental] cRud COLS
   [ "Daily tariff" : rentalDailyTariff cRud <EuroPerDay>
   , "Period"       : rentalPeriod cRud <Days>
   , "Total charge" : rentalCharge cRud <Euro>
   ]

ENDCONTEXT
~~~
However, running this script produces the following screen. As you can see, the atoms are rendered, but the subsequent texts are not:

![image](https://cloud.githubusercontent.com/assets/8522589/21220800/f115f46c-c2ba-11e6-9acc-8f88088d366d.png)

**Comment by hanjoosten** [comment]
The view info is available in the json file. Therefor, I don't see the reason why this would be in the prototype generator.

**Comment by Michiel-s** [comment]
@hanjoosten I agree.

@RieksJ and I diagnosed the issue. The problem lies with the fact that view data of scalar types, specified in view statement between brackets (`number : I` and `unit : TXT " (Euro/Day)"` in example below), cannot be communicated via the json api interface. This only works for non-scalar, i.e. concepts with OBJECT as technical type (= default).

`VIEW "EuroPerDay": Amount { "number": I, "unit": TXT " (Euro/Day)" } ENDVIEW`

It is however possible to specify a HTML TEMPLATE for a scalar type. This is the solution (for now) for @RieksJ's use case. The following is implemented:

`VIEW "EuroPerDay": Amount HTML TEMPLATE "AmountEuroPerDay.html" ENDVIEW`

The addition of the unit text is done in the html template.

**Comment by RieksJ** [comment]
That the specified VIEW cannot work does not mean that there is no bug.
It should either work, or produce a (preferably compile time) error.

**Comment by Michiel-s** [comment]
The required functionality in this feature request will be possible after we implement #1089. I'll therefore close this issue. We'll keep track of the use case in #1089
