### ISSUE TITLE
No declarations match the relation

### ISSUE THREAD

**Issue by dartheide** [AmpersandTarski/Ampersand#595]
I have some problems building RAP3.
I’m using ampersand 373 build  on debian (18-12-2017). 
I changed the  SeqOntology.adl, Scripts.adl, Scripts.docadl -} to +} 

Now its stops on Analyse.ifc. 

Error at symbol () in file Analyse.ifc at line 26 : 32
  No declarations match the relation: genspc[Gen*Concept]
==============================
Error at symbol () in file Analyse.ifc at line 26 : 53
  No declarations match the relation: gengen[Gen*Concept]
==============================
Error at symbol () in file Analyse.ifc at line 27 : 33
  No declarations match the relation: gengen[Gen*Concept]
==============================
Error at symbol () in file Analyse.ifc at line 27 : 54
  No declarations match the relation: genspc[Gen*Concept]
==============================
Error at symbol () in file Analyse.ifc at line 26 : 32
  No declarations match the relation: genspc[Gen*Concept]
==============================
Error at symbol () in file Analyse.ifc at line 26 : 53
  No declarations match the relation: gengen[Gen*Concept]
==============================
Error at symbol () in file Analyse.ifc at line 27 : 33
  No declarations match the relation: gengen[Gen*Concept]
==============================
Error at symbol () in file Analyse.ifc at line 27 : 54
  No declarations match the relation: genspc[Gen*Concept]

I placed FARelations.adl back in place and ampersand Finished processing the model.

**Comment by hanjoosten** [comment]
This issue with RAP3 was because of a change in FormalAmpersand, that @stefjoosten made last week. I've made sure that those changes are not in ampersand v 3.8.0, which I released today. You should be able to build RAP3 (in the master branch of ampersand-models) with ampersand v 3.8.0

Also please note that RAP3 is for a specific purpose at OU. If it works for you, that's great, but it is still in development and there might be OU specific things built in. 

If you still find these problems, you can reopen this issue, but I've seen it work on my machine.
