### ISSUE TITLE
Represent type Object is not recognized.

### ISSUE THREAD

**Issue by jpwijbenga** [AmpersandTarski/Ampersand#616]
While doing the example, I tried to explicitly state that two concepts should be represented by type 'object', but this seems not to be allowed. This seems inconsistent, because Object is the default type, right? Is this desired behavior?

Example fragment:
```adl
REPRESENT Date TYPE DATE
REPRESENT Name, Description TYPE ALPHANUMERIC
REPRESENT Person, Project TYPE OBJECT
```

**Comment by hanjoosten** [comment]
Any concept without REPRESENT will be Object. There is no need to specify that, and there is no syntax for it as well. This is on purpose. 

NB: Note that all concepts that are related to each other in CLASSIFY statements must all have the same representation. Concepts without a REPRESENT statement will automatically have the representation of the other related concepts.

**Comment by hanjoosten** [comment]
@jpwijbenga : If this didn't answer your question, please reopen the issue.

**Comment by Michiel-s** [comment]
@hanjoosten I don't agree. Something that is true should be prohibited to be stated explicitly. According to formal ampersand every concept has a represent type. OBJECT is the default. Why shouldn't you be able to specify this with `REPRESENT Concept TYPE OBJECT`.

Even better, it prevents undesired affects. For example:
```adl
CONCEPT Person ""
-- I don't specify its represent type, because I want it to be an object

...... more of my model .......

CONCEPT Employee ""
CLASSIFY Employee ISA Person
REPRESENT Employee TYPE ALPHANUMERIC
```
In the example above the concept Person is automatically of type ALPHANUMERIC, because of the classify statement and the rule @hanjoosten describes in his comment. I didn't want this to happen. The following statement would have prevented this and showed me the rule violation: `REPRESENT Person TYPE OBJECT`

**Comment by Michiel-s** [comment]
@jpwijbenga, this issue is fixed and merged to developement. Next release of Ampersand will allow you to specify `REPRESENT <Concept> TYPE OBJECT.
Thanks very much for reporting.
