### ISSUE TITLE
Funny side effect of <COLSNL>

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#632]
I have an interface called "MijnAanvragen". 
~~~~~~
INTERFACE MijnAanvragen FOR Aanvrager : '_SESSION'; sessionAccount cRud
ROWS [ "Aanvragen" : aangemaaktDoor~ CRud COLS
       [ "Indienen" : I-ingediend cRud BOX <PropertyButton> 
           [ property : ingediend cRUd 
           , disabled : (I - aanvraagCompleet) \/ ingediend cRud
           ]
       , "nummer" : aanvraagnummer CRUd
       ]
     ]
~~~~~~
This is what it looks like:
![image](https://cloud.githubusercontent.com/assets/275768/23264121/97acbc32-f9e0-11e6-888d-62fc136f038d.png)
Now I will change the first occurrence of `COLS` to `BOX <COLSNL>`. The code has now changed into:
~~~~~~
INTERFACE MijnAanvragen FOR Aanvrager : '_SESSION'; sessionAccount cRud
ROWS [ "Aanvragen" : aangemaaktDoor~ CRud BOX <COLSNL>
       [ "Indienen" : I-ingediend cRud BOX <PropertyButton> 
           [ property : ingediend cRUd 
           , disabled : (I - aanvraagCompleet) \/ ingediend cRud
           ]
       , "nummer" : aanvraagnummer CRUd
       ]
     ]
~~~~~~
This is what the screen now looks like: 
![image](https://cloud.githubusercontent.com/assets/275768/23264265/0ad8adba-f9e1-11e6-844c-7f0741991efd.png)
Very much to my surprise, the + (plus) symbol is no longer there. As a consequence, I cannot make a new `Aanvraag` in the second situation, whereas I could do that in the first situation.

**Comment by RieksJ** [comment]
I expect the revised interfaces (branch feature/refactor_ifc) to solve this problem. 

Having said that, I also expect that (on a somewhat longer run), we'll get rid of the +, the garbage tin etc. because they only provide a minimalistic way of adding Objects with an empty set of initial set of values, whereas in practice I also need to create objects from a non-empty set of values (e.g.: for account registration).
