### ISSUE TITLE
VIEWs that act on I[C] should also act on `i :: C * C [PROP]` 

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#633]
Consider the scriptlet
~~~
VIEW "PA": Transaction
{ "Promise": ttPromise;V;'P'[IfcText]
, "Accept": ttAccept;V;'A'[IfcText]
} ENDVIEW 

POPULATION IfcText CONTAINS [ "P", "A" ]
REPRESENT IfcText TYPE ALPHANUMERIC

varTrx :: Variable * Transaction [UNI,TOT]
varName :: Variable * IfcText [UNI]
varP :: Variable * Variable [PROP]
varA :: Variable * Variable [PROP]

INTERFACE "Variables": varTrx~ cRud COLS
   [ "Name" : varName cRud
   , "Status" : I cRud <PA>
   ] 
~~~
which works as expected, meaning that whenever `varP` or `varA` (or both) are set, the letters `P`, `A` (or both letters) are shown in the `Status` column.

Now suppose I distinguish between 'specialvars' and non-'specialvars', and only for specialvars I would like to show these letters. Here is what that would look like:
~~~
specialVar :: Variable * Variable [PROP]

INTERFACE "Variables": varTrx~ cRud COLS
   [ "Name" : varName cRud
   , "Status" : specialVar cRud <PA>
   ] 
~~~
I would expect that it would work - after all it worked for this other 'property' (i.e.: `I`).
However, the view does not work.

**Comment by Michiel-s** [comment]
I'm closing this stale issue.

But from what I see here above I think there is no issue. The `VIEW PA` is defined for concept `Transaction`. In the specified interface definitions this view is used for the expression `I[Variable]` (first part) and `specialVar[Variable]` (second part). So I guess this script should give an error because the view doesn't apply to concept `Variable`.
