### ISSUE TITLE
Database deadlock

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#635]
This is not something that seems to be easily reproducible.
I did the following:
compiled the MPTrx application, and start both Firefox and Chrome
I used different accounts for logging into the different sessions.
Then on one I created an MPTrx transaction
Then, more or less simultaneously, I had both accounts claim a (different) role in a multi-parti transaction.
In firefox, this led to the following screen:

![image](https://cloud.githubusercontent.com/assets/8522589/23362062/331bd5c0-fcf4-11e6-9553-c7eda6dd5f01.png)

Of course, this is pushing prototypes to their limit. 
I do not expect this bug to be resolved anytime soon,
but nevertheless I think it is worth mentioning that it is indeed a bug.

**Comment by stefjoosten** [comment]
It is definitely a bug. It proves that we do not have a safe multi-user capability...  :-( 
(yet :-)  )

**Comment by LloydRutledge** [comment]
This caused a crash for the student server today, during the crunch week. Until it's fixed, is there a usage pattern users can follow to avoid this deadlock, such as user specific prefixes or suffixes in names in the code to prevent table overlap? Also important: what are the recovery steps? Can just de SQL server be restarted, for example?

**Comment by Michiel-s** [comment]
After merge commit 53eda81 I think it is way less likely that a deadlock will occur. This is due to the changed order of updating the conjunct violation cache in table __all_signals__.
Before refactoring the backend code, the table was updated directly after evaluating the conjunct. I think (but am not sure) that the all signals table was locked during the whole rule checking phase. This is relatively long (in some cases it can be up to several seconds).
In the new situation the all signals table gets updated only once just before closing the transaction.

I'll close the issue for now. Please let me know when you encounter the error again, because then I have to investigate other potential causes.
