### ISSUE TITLE
Fatal error: Unsupported protocol in URI

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#640]
During processing an Ampersand file with version 3.8.2. (ArchiMate extension) the following message appears: 
   Fatal error: Unsupported protocol in URI "Archisurance.xml"

The ArchiMate .xml file is not processed. Ampersand continues with the Ampersand script and even creates the prototype, but without the content of the ArchiMate .xml file.

Testfiles are attached (renamed them to .txt extension in order to be able to attach them to this issue).

[Archisurance gecorrigeerd - Copy.xml.txt](https://github.com/AmpersandTarski/Ampersand/files/862626/Archisurance.gecorrigeerd.-.Copy.xml.txt)
[MyArchisurance - Copy.adl.txt](https://github.com/AmpersandTarski/Ampersand/files/862625/MyArchisurance.-.Copy.adl.txt)

**Comment by hanjoosten** [comment]
@stefjoosten can you look into this? The message is from the HXT package that you use ([see here](http://www.fh-wedel.de/~si/HXmlToolbox//hdoc/src/Text-XML-HXT-Arrow-DocumentInput.html))

**Comment by hanjoosten** [comment]
This is probably related with [this issue of alga](https://github.com/mrkkrp/alga/issues/4). [The fix that they made there](https://github.com/mrkkrp/alga/commit/48a9c489385ab52057f66044a1a8be35651f4cd1) could very well be the right thing to do for us as well. I'll have a look as soon as I find time for this.

**Comment by stefjoosten** [comment]
This fix was one step of the process. However, nothing was generated.
The reason was that the XML-tag of an Archi repo is no longer `archimate:model`, but `archimate:ArchimateModel`.
I have adjusted `ArchiAnalyze.hs` on line 540 wrt this aspect in branch Archi-extension, commit @f73805909dbb38402a3e74058d40abb9d8fcc949

I have not looked into the Archi-policy on versions. So we are likely to have a problem with different versions of Archi.
