### ISSUE TITLE
Error initializing prototype: Table 'ampersand_archimetal.session' doesn't exist

### ISSUE THREAD

**Issue by filetp** [AmpersandTarski/Ampersand#661]
The prototype 'archimetal' was generated with Ampersand (v3.8.3 19-apr) without any errors.
When initializing the prototype an error appears that table `session` doesn't exist.

![image](https://cloud.githubusercontent.com/assets/22689893/25276756/fbb793a4-269b-11e7-84e7-4fd193b0387c.png)

What causes this error?
[CaseArchimetal.zip](https://github.com/AmpersandTarski/Ampersand/files/946966/CaseArchimetal.zip)

**Comment by hanjoosten** [comment]
There are several possible causes for this. I don't know exacly what is going on in your case. When a prototype is generated, Ampersand will generate an entire directory of stuff. At that point, no connection with the database is made. 
When a users goes to the url of the prototype, A connection with the database is being made. If this fails because the database does not exist, the database is being created at the spot. You can observe that because it takes longer to launch the prototype if you do so for the first time. 
If the database however allready exists, it is assumed that it still is valid, in a way that the database structure is according the adl specification. This is only assumed, not checked. So if you modified relations, (or in rare cases even rules) in your model, this assumption is false. That could cause an error like yours. An obvious way to overcome this, is to reinstall the database. This is also what the errormessage suggests you to do. 
Most of the time, when you get a red error message like this, you can expand it by clicking on it.  It will show some more information, which sometimes contains a clue about what is going on. 
I suggest you reinstall your database. Please let us know if that solved this issue.

**Comment by filetp** [comment]
Hi Han, thx for your quick reaction.

My situation is as follows:
The database was not present. In fact, I manually deleted the earlier version of the database from within MySQL (phpMyAdmin) to make sure there were no leftovers from previous attempts.
Re-installing results in the same message.

**Comment by filetp** [comment]
Interestingly (and certainly surprisingly), the problem seems to find it's cause in the ` .xml` file.
In the attached `.zip` archive you'll find an `EIRA.adl` script which basically only `INCLUDE`s the rogue `.xml` file (name: `EIRA_v1_1_0_ArchiMate.xml`). Compiling it to a prototype leads to the same error.

If another .xml file (name: `OpenDay added.xml`)) is `INCLUDE`d instead of the rogue one, a prototype is generated that works fine!

Hope this helps analyzing the issue
[EIRA.zip](https://github.com/AmpersandTarski/Ampersand/files/949007/EIRA.zip)

**Comment by stefjoosten** [comment]
I tried to reproduce this behaviour with EIRA.zip. I compiled EIRA.adl with `Ampersand-v3.8.6 [FormalAmpersand:562571467], build time: 01-Aug-17 07:48:26`
It compiled as I'd expect:
~~~
C:> ampersand.exe --verbose -pD:\htdocs\AmpersandPrototypes\EIRA  EIRA.adl
Reading file EIRA.adl
Reading file EIRA_v1_1_0_ArchiMate.xml
ArchiCount.txt written
ArchiMetaModel.adl written
EIRA_v1_1_0_ArchiMate.xml has been interpreted as an Archi-repository.
Checking on rule violations...
No violations found.
No signals for the initial population.
Generating prototype...
  Generating settings.json
  Generating mysql-installer.json
  Generating relations.json
  Generating rules.json
  Generating concepts.json
  Generating conjuncts.json
  Generating interfaces.json
  Generating views.json
  Generating roles.json
Generating frontend..No user includes (there is no directory .\include)
  Generating RouteProvider.js
..done.

Prototype files have been written to D:\htdocs\AmpersandPrototypes\EIRA
  Trying to download and install Composer libraries... Succeeded. (stdout is empty)
~~~
When I run it, I get no errors, in contrast with what Peter mentions above:
![image](https://user-images.githubusercontent.com/275768/29465294-1652f8d4-8439-11e7-9a6c-ebefc2a25287.png)

I verified that the table `SESSION` exists:
![image](https://user-images.githubusercontent.com/275768/29465217-d2fca580-8438-11e7-84be-666c8bdde941.png)

So Peter, maybe you can recompile your Ampersand compiler and see if that solves the problem. I suggest you take `Ampersand-v3.8.6 [FormalAmpersand:562571467]`. Let's hope that helps, because I cannot make a diagnosis based on what I have done so far.

**Comment by stefjoosten** [comment]
@filetp Ik sluit dit issue. Wil je het open zetten als blijkt dat het issue toch niet gefikst is?
