### ISSUE TITLE
Importing xlsx file fails when case already exists in database

### ISSUE THREAD

**Issue by rvgast** [AmpersandTarski/Ampersand#672]
Scenario:
1) upload an xlsx file (f.i. the one attached
[Contracten - Copy.xlsx](https://github.com/AmpersandTarski/Ampersand/files/1111175/Contracten.-.Copy.xlsx)
)
2. Optionally: delete the case made by/for the file
3. Upload the file again
Result: error 
![afbeelding](https://user-images.githubusercontent.com/7569066/27676436-2d5c4e5c-5cae-11e7-9c3b-fe1dfc806e8c.png)

**Comment by stefjoosten** [comment]
# Analysis
What happens here is that a univalent relation is populated with a pair that already exists. Ampersand protests during an .xlsx interactive import.
This behaviour is inconsistent with the set-theoretical semantics of Ampersand.  After all: {x,x}={x} in set theory.
# Solution
I propose to adapt the .xlsx interactive importer to allow duplicate entries instead of forbidding them. The motivation is set theory.

**Comment by Michiel-s** [comment]
Sorry that you had to wait so long for this fix. Especially since it is a very small one.
