### ISSUE TITLE
No mutual exclusion enforced between subconcepts

### ISSUE THREAD

**Issue by Oblosys** [AmpersandTarski/Ampersand#68]
Currently subconcepts are not enforced to by mutually exclusive, so if `Orange ISA Citrus` and `Lemon ISA Citrus` and no other generalizations are declared, we may still have an atom (e.g. `strangeFruit`) that is in both `Lemon` and `Orange`. See ampersand-models/ISAtest/Strange.adl. This may cause unexpected behavior when such atoms are part of other relations, as they will be effectively treated as the same atom.

**Comment by sjcjoosten** [comment]
Tricky! I see two reasons to consider this to be a bug:

1. When creating a taxonomy, we naturally assume that the categories are distinct. Even though we only write "**Orange ISA Citrus**" and "**Lemon ISA Citrus**", we don't expect there to be any Rangpur (or strangeFruit as you call it) unless we specifically specify this. As a result, we can be surprised to see that a name change of the Lemon Rangpur, results in the same name change of the Citrus Rangpur. In this case, we mean that **I[Orange];I[Citrus];I[Lemon]** is always empty.
2. When composing patterns with separate populations, we sometimes mean a specialisation. For instance, when "**DateOfBirth ISA Date**" and "**ContractDate ISA Date**", we still conceptually separate these two dates. Note that this does not require us to physically separate these two dates: if we decide to change the day of the week because of an unexpected leap-day, the change should apply to all dates anyways.

However, I find the following reasons more convincing:

1. Every line added to an Ampersand script in fact restricts the populations. This is why designing Ampersand scripts scales so well. "**Orange ISA Citrus**" would mean that the population of Oranges is restricted to be at most that of Citrus. If we let Oranges and Lemons be distinct by default, then this is the only exception to this, because adding "**SomethingElse IS Orange /\ Lemon**" would remove a restriction.
2. There is a difference between using two separate relations, say "**name :: Orange -> String**" and "**name :: Lemon -> String**", and using just one, "**name :: Citrus -> String**". In the last case, we want the name of the orange, when it is interpreted as a Citrus. It makes sense that the name of the lemon, when interpreted as the same citrus, would change as well. In the first case, this means we are looking at this thing as an orange or as a lemon (but not as a citrus), and we keep the names separate.
3. If we want, we can mimic "**CLASSIFY Lemon, Orange ARE DISTINCT Citrus**" to get the behavior in which Lemons and Oranges are distinct (the introduced rule could be "**I[Lemon];I[Citrus];I[Orange] = -V[Citrus]**"). Note that for *n* concepts, we would introduce **n\*(n-1)/2** such rules. The other way around would require the syntax desugaring (or Ampersand user) to specifically name the concept standing for **Lemon /\ Orange**. This might seem OK, but if there are *n* non-distinct concepts, it means that **2^n-n** new concepts will have to be introduced, which is a lot larger than the **n\*(n-1)/2** additional rules (which will need to be checked anyways).
4. I like the line of thought in which an atom is its representation, but all relations are distinct. This means that we can compose all relations in the way of homogeneous relation algebra, but we use the type checker to make sure that we only do this when there is "sufficient glue" between them.
5. Suppose we have a script in which lemons and oranges are separate concepts, and we have the Rangpur in both of them. When creating a new concept **Citrus**, and adding the "**ISA Citrus**" with the necessary atoms, I do not expect any problems, as in violated rules or name changes of the atoms. When adding the "**ARE DISTINCT**" rule, I can in fact expect problems to happen. The same holds when I have the concept **Limorange**, which is **Lime /\ Orange**. Should I choose to remove this concept (and relations to- and from it) because I don't use it in any rules anymore, I do not expect to see errors.

I propose that this not a bug

**Comment by Oblosys** [comment]
Yeah, the main point of the issue is not so much that this is a bug, as well as something we need to be clear about (and describe somewhere). Unfortunately, my Ampersand time is almost over for now (and I have quite a lot of other things to do,) so I won't be able to contribute much to the discussion.

**Comment by stefjoosten** [comment]
The user of an Ampersand prototype can, in certain cases, create a new atom by typing the name of that atom in a field of a user interface. The user never has to state the type of this atom, because the compiler has assigned precisely one concept to every field. The type system ensures this. For that reason, the user interface needs no software to ensure integrity of the type system.

Doesn't it?

Suppose I have an editable field of type Lemon and another editable field of type Orange.
Suppose further that:
CLASSIFY Lemon ISA Citrus
CLASSIFY Orange ISA Citrus
And assume there is no intersection type between Lemon and Orange. In Ampersand this means that there cannot be an atom that is both Lemon and Orange.

Consider a use case: If the user types l1 into the Lemon field, Ampersand will put l1 in the concept table of both Lemon and Citrus. Similarly, if the user types l1 into the Orange field, this will be entered in the concept tables of Orange and Citrus. Hence, the user has effectively created an atom of an intersection type, whereas the Ampersand semantics explicitly excludes that. So this is a bug.

One way to resolve this bug is to change the Ampersand semantics, and allow atoms of intersection types that are not declared. I reject that solution. I want every atom in Ampersand to have precisely one type.

Another way to resolve this bug is to ensure that atoms of disjoint concepts within the same generic concept have different keys. That might be implemented as an invariant rule in the database, effectively rendering the above use case impossible.

**Comment by stefjoosten** [comment]
Here is an attempt to describe the atom semantics in Ampersand itself.

    RELATION key [Atom*AtomID] [UNI,TOT]
    MEANING "An internal storage code for this atom, used to identify the atom within a table."
    RELATION atomvalue[Atom*AtomValue] [UNI,TOT]
    MEANING "The value by which the atom is visible to users."
    RELATION source[Relation*Concept] [UNI,TOT]
    RELATION target[Relation*Concept] [UNI,TOT]
    RELATION in[Pair*Relation] [UNI]
    RELATION l[Pair*Atom] [UNI]
    RELATION r[Pair*Atom] [UNI]
    RELATION sub[Concept*Concept]
        MEANING "s sub g means that each element of concept s is an element of concept g as well."

The following are derivable relations, so we accompany each of them with a defining rule.

    RELATION type[Atom*Concept] [UNI,TOT]
    MEANING "The concept to which this atom belongs is called the type of an atom"
    RULE "Def of type" : type = l~;in;source \/ r~;in;target
    RELATION src[Pair*Concept] [UNI,TOT]
    RULE "Def of src" : src = in;source
    RELATION tgt[Pair*Concept] [UNI,TOT]
    RULE "Def of tgt" : tgt = in;target
    RELATION left[Pair*AtomValue] [UNI,TOT]
    RULE "Def of left" : left = l;atomvalue
    RELATION rght[Pair*AtomValue] [UNI,TOT]
    RULE "Def of rght" : rght = r;atomvalue

The following rules define how atoms are treated.

    PURPOSE RULE "typed atoms"
    {+In Ampersand, the type of an atom is determined by the relation in which it is stored.
    -}
    RULE "typed atoms" : in;in~ |- src;src~ /\ tgt;tgt~
    MEANING "Two pairs that are in the same relation have the same src and tgt concepts."

    PURPOSE RULE "identical atoms"
    {+The value and type are used to identify an atom.
    -}
    RULE "identical atoms" : atomvalue;atomvalue~ /\ type;type~ |- I[Atom]
    MEANING "Two atoms that have the same atomvalue and type are identical."

    PURPOSE RULE "specialized atoms (src)"
    {+The value and type are used to identify an atom.
    -}
    RULE "specialized atoms (src)" : in;source;sub |- (left;left~ /\ src;sub;src~);in;source
    MEANING "If a source atom is in a relation, its generalization is in the generalized relation as well."

    PURPOSE RULE "specialized atoms (tgt)"
    {+The value and type are used to identify an atom.
    -}
    RULE "specialized atoms (tgt)" : in;target;sub |- (rght;rght~ /\ tgt;sub;tgt~);in;target
    MEANING "If a target atom is in a relation, its generalization is in the generalized relation as well."

I would expect the preceding rules to exclude the existence of an atom that belongs to two disjoint concepts. That would mean that there is a proof of

    RULE type;(sub;sub~ /\ -(sub~;sub));type~ |- -(key;key~)

However, I could not find that proof...
(to be continued...)

**Comment by stefjoosten** [comment]
Note that the location of an atom is either `l~;in` or `r~;in`. Here is a derivation to prove that an atomvalue and the location of an atom identify the atom:

       atomvalue;atomvalue~ /\ l~;in;in~;l
    |-   { typed atoms }
       atomvalue;atomvalue~ /\ l~;src;src~;l
    |-   { Def of src }
       atomvalue;atomvalue~ /\ l~;in;source;source~;in~;l
    |-   { Def of type }
       atomvalue;atomvalue~ /\ type;type~
    |-   { identical atoms }
       I[Atom]

So `atomvalue;atomvalue~ /\ l~;in;in~;l |- I[Atom]`, which proves the point.
Similarly, it can be proven that `atomvalue;atomvalue~ /\ r~;in;in~;r |- I[Atom]`.

**Comment by sjcjoosten** [comment]
I'm afraid that no atom can belong to two concepts, merely because type[Atom*Concept] is UNI. This should allow you to prove that the same holds for distinct concepts.
I would also expect that according to your rules, if A ISA B, then A must be empty, but I have not tried to prove it.

You seem to have two ideas:

- An atom belongs to exactly one concept
- If (concept1,concept2) is a pair of sub, then all atoms belonging to concept1 must belong to concept2.

I suggest discarding one of these ideas, since they together imply that any concept in the domain of "sub" must be empty.

**Comment by hanjoosten** [comment]
Language is key, as we all know. In Stef's attempt to describe the Atom pattern (see above) there only exists one relation between Atom and Concept:

```
RELATION type[Atom*Concept] [UNI,TOT]
MEANING "The concept to which this atom belongs is called the type of an atom"
```
I think, the description of the meaning could be stronger. I suggest:
```
MEANING "The most specific concept to which this atom belongs is called the type of an atom"
```

Also, for talking about atoms, we seem to use the relation *belongsTo*:

```
RELATION belongsTo[Atom*Concept] [TOT]
MEANING "an element of a concept <or whatever better frase>"
```

RULE "element" : belongsTo = type;sub*

Since this relation can be expressed in terms of other relations, it is a derived one.

**Comment by WolframKahl** [comment]
I find it surprising and dangerous to automatically consider subconcepts of a common superconcept as disjoint. For example:
```
CLASSIFY Employee ISA Person
CLASSIFY Supervisor ISA Person
RELATION isSupervisedBy [ Employee * Supervisor ] [TOT]
RULE "No (indirect) self-supervision" : isSupervisedBy+ |- -I[Person]
RULE "Externals supervise at least two" : isSupervisedBy ; (I[Person] - I[Employee]) |-  -I[Person] ; isSupervisedBy
RULE "Externals supervise no supervisors" : - (isSupervisedBy ;isSupervisedBy ; (I[Person] - I[Employee]))
```
In most organisations, most supervisors are employees...

(But in all organisations satisfying the rules above, there is at least one external supervisor, unless the set of employees is either empty or infinite...)

(Can we write ```I[Person - Employee]```?)

**Comment by stefjoosten** [comment]
@WolframKahl, the reason I closed this issue was that this discussion in issue 68 was resolved by our Braga-contribution. Our Paper confirms that subconcepts of a common superconcept are not disjoint until you explicitly say so in a rule. Before that time I have lived quite some time being convinced of the disjointness, until @oblosys convincedcme that I was wrong.

**Comment by sjcjoosten** [comment]
I gather we all agree that this is not a bug, and that we should not assume disjointness of concepts (unless it is made explicit).
