### ISSUE TITLE
Deployment automation with Docker

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#686]
The purpose of having automated deployment is that every user of Ampersand can rely on the existence of the right docker images, so they only have to use them (as opposed to baking images for them).

@hidde-jan and @Michiel-s  have been making docker-files, the first of which were submitted on July 21st, 2017 on commit 634b2928572403c11726f67ab42dc8749ad5ab64. There was no particular issue for this in which we consolidate our choices and discussions about them. That's why I am raising the issue here.

The purpose of the docker-files is to generalize the docker-files made by @wentinkj to serve for automatic deployment of arbitrary Ampersand applications and to create a reliable automated release path. Maybe Hidde-Jan or Michiel would care to describe that path briefly in a comment in this issue, so we all understand it. The idea is:
 - [x] to add a linux executable to the monthly release (automatically)
 - [x] to create an Ampersand docker image that simply uses this executable (instead of compiling the sources)
 - [ ] to make the Ampersand docker image available through Docker-hub for every monthly release of Ampersand.
 - [x] to provide users with docker templates, by which they can automate the deployment of their own Ampersand application

**Comment by hidde-jan** [comment]
As far as I know, the first part of this issue has already been tackled. @michiels and I have set up Travis to automatically attach a binary to every new tag. We'll notice if it works automatically with the tags created by appveyor when Han creates the next release.

**Comment by hidde-jan** [comment]
@hanjoosten could you add me and @Michiel-s to https://hub.docker.com/u/ampersandtarski/ ?

**Comment by hanjoosten** [comment]
Hidde-jan, Ik ga er van uit dat je @Michiel-s (Michiel Stornebrink) bedoelt, niet @michiels (Michiel Sikkes). Ik had Michiel afgelopen vrijdag al toegang gegeven. (Hij is daar nu owner). Ik maak nu een members lijst aan, want dat lijkt me beter. Ik maak jou daar lid van. Ik ga mijn best doen om die groep voldoende rechten te geven. Mocht je niet kunnen wat je wilt kunnen, laat me dat dan nog maar even weten. Als de members ook voldoende kunnen, dan gaan we die groep verder gebruiken, zodat niet iedereen owner-rechten hoeft te hebben.

**Comment by hanjoosten** [comment]
Oh, en je moet ook eerst even zelf een account aanmaken op docker-hub, zodat ik die kan koppelen.

**Comment by hidde-jan** [comment]
@hanjoosten, klopt, ik bedoelde -s. Ik heb inmiddels een account met de naam hiddejan op docker hub

**Comment by hanjoosten** [comment]
Volgens mij moet je nu los kunnen op dockerhub

**Comment by michiels** [comment]
Bedankt heren ;-) Ik heb al een bugreport naar GitHub gestuurd omdat ik nog steeds notificaties van deze conversation krijg.

**Comment by hidde-jan** [comment]
Ok so I think we're on track w.r.t. this issue. Yesterday @stefjoosten and I managed to get RAP3 working using the new docker images. They have been deployed to [docker hub](https://hub.docker.com/u/ampersandtarski/). 

Sample files can be found [here](https://github.com/AmpersandTarski/Ampersand/tree/feature/dockerize/docker/sample). The only change a simple Ampersand project needs (without external includes) should be to change the `ADL_FILE: CHANGE_ME.adl` setting in the docker-composer.yml.

I know Stef is writing documentation on how to deploy (RAP3|a project) with docker and the new images, so we might want to make that easy to find for people.

I think the automatic binary compilation should work once Han uses appveyor to create a new release, fingers crossed 🤞. We could then set up some pipeline such that new docker images are automatically generated and deployed. I think it would be best to actually move the docker files into the docker-ampersand repository, since there isn't a direct connection between ampersand and it's docker containers. This should also make it easier to automatically compile new images and push them to docker hub with the right travis configuration for the docker-ampersand repo.

**Comment by stefjoosten** [comment]
@hidde-jan I have finished the [deployment documentation](https://ampersandtarski.gitbooks.io/the-tools-we-use-for-ampersand/content/installation_of_rap.html) on `Gitbook`, except for some details on making images. It contains three subsections: one on RAP for the Open University, one on RAP at Ordina, and one on making images. Could you please improve the "recipe" part of that third section, such that the instruction will work for others? Thx

**Comment by hidde-jan** [comment]
I've added the 3.8.7 binary myself, since I forgot to fix the travis.yml for that release. I hope the binary will be automatically deployed with 3.8.8. We'll see 🐳

**Comment by hidde-jan** [comment]
With @hanjoosten's newest release earlier today, we finally have an automatically compiled debian linux version of ampersand attached to a release: https://github.com/AmpersandTarski/Ampersand/releases/tag/Ampersand-v3.8.8

That means that we can now easily create docker images containing the latest ampersand version and push them to github. This updating is still a manual process, but luckily a relatively quick and easy one.

One final decision to be made: will we add the docker files in the feature/dockerize branch to the development branch or will we house them in ampersand-docker?

**Comment by hanjoosten** [comment]
I cannot oversee this. What are the pros and cons?

**Comment by hidde-jan** [comment]
Well, for one, dockerfiles can be tested and docker containers can be automatically generated using Travis, but this will be much more difficult (or maybe impossible to automate) if we keep the files in the main repository. 

Verstuurd vanaf mijn iPhone

**Comment by hanjoosten** [comment]
No cons? In that case it is a no-brainer.

**Comment by hidde-jan** [comment]
Michiel and Stef think it's a con that it would fracture the code base, but in my opinion the ampersand code and the docker images using the build artifacts are rather orthogonal.

Verstuurd vanaf mijn iPhone

**Comment by hanjoosten** [comment]
@Michiel-s and @stefjoosten , please comment, so we can get things done.

**Comment by Michiel-s** [comment]
I think automation of the process to push to docker hub is essential. I completely thrust @hidde-jan if he thinks that this is easier/better to have the docker files in a separate repo. We already have the [docker-ampersand](https://github.com/AmpersandTarski/docker-ampersand) repo, so I would say, clean that one up and make it happen!

**Comment by hidde-jan** [comment]
I've looked at what is necessary to finish automatically building the docker images. In the end, I think it will be easier to keep the docker files in the main ampersand repo, because that will make tagging images much easier. We'll need to:

- [ ] recreate the ampersandtarski/ampersand-prototype repository as a automated build
- [ ] disable automatic building on pushes
- [ ] add the following build rules:

Type | Name | Dockerfile Location | Docker Tag Name
------|--------|----------------------|---------------------
Tag | /^Ampersand-v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | docker/prototype/Dockerfile | latest
Tag | /^Ampersand-v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | docker/prototype/Dockerfile | {\1}.{\2}
Tag | /^Ampersand-v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | docker/prototype/Dockerfile | {\1}.{\2}.{\3}
Tag | /^Ampersand-v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | docker/prototype/texlive/Dockerfile | latest
Tag | /^Ampersand-v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | docker/prototype/texlive/Dockerfile | latest
Tag | /^Ampersand-v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | docker/prototype/texlive/Dockerfile | latest

**Comment by stefjoosten** [comment]
This issue is still open, because publication of the docker image to hub.docker.com is still to be done (automated) with every monthly release of the Ampersand compiler, for the purpose of having an Ampersand image `ampersandtarski/ampersand-prototype:<version>` and an image `ampersandtarski/ampersand-prototype:<version>-texlive` in `hub.docker.com` for every release of Ampersand.
@hidde-jan do you still have this on your todo-list, or should we add assignees?

**Comment by hidde-jan** [comment]
I'm going to discuss with @Michiel-s at the end of the week on how to move forward.

**Comment by stefjoosten** [comment]
The purpose of having automated deployment is that every user of Ampersand can rely on the existence of the right docker images, so they only have to use them (as opposed to baking images for them).

@hanjoosten has four questions regarding to this:

1. What images should be built?
2. In what cases do we want to trigger such a build?
3. What is the exact recipe to build such image?
4. How can we know that the build is successful?

Here are my answers:
1. images to be built: For every named release on https://github.com/AmpersandTarski/Ampersand/releases (e.g. 3.10.0) we need docker images on https://hub.docker.com/u/ampersandtarski/dashboard/. Which docker images we need is defined on  https://github.com/AmpersandTarski/docker-ampersand/build.sh. Currently we need:
   1. ampersandtarski/ampersand-prototype-db:3.10.0
   2. ampersandtarski/ampersand-prototype:3.10.0
   3. ampersandtarski/ampersand-prototype:texlive-3.10.0

2. we want to trigger these builds from the moment a new level-3 release tag is made, to ensure that for every release of Ampersand there are corresponding docker images.

3. The exact recipe is found on on  https://github.com/AmpersandTarski/docker-ampersand/build.sh and in the Dockerfile instances in the (sub-)directories of https://github.com/AmpersandTarski/docker-ampersand/

4. The build is successful if the desired docker-images exist. If there are more conditions, they should preferrably be included in the automatic testing sequence of Ampersand.

**Comment by stefjoosten** [comment]
I have been trying to make the Ampersand docker image available through Docker-hub for every monthly release of Ampersand. I did so by creating an automated build in docker hub: `https://hub.docker.com/r/ampersandtarski/ampersand_build/~/settings/automated-builds/`. Then I tried to fill out the form, only to discover that this requires a `Dockerfile` inside the Ampersand repo.

So my suggestion is to make two dockerfiles in the root of the Ampersand repo:
1. `Dockerfile` , which is the current `docker-ampersand/prototype/Dockerfile`, and
2. `Dockerfile_texlive` , which is the current `docker-ampersand/prototype/texlive/Dockerfile`.
Then I will clean out docker-ampersand (or repurpose it for example docker stuff)

@hidde-jan , what do you think?

**Comment by hidde-jan** [comment]
I'm currently also testing automated building by docker hub of the ampersand images: https://hub.docker.com/r/hiddejan/docker-ampersand/

From my testing:

1. The docker files don't need to be in the root, you can specify a directory
2. Automated builds clone source of the project to build the image (which we don't need, since we used a precompiled binary)
3. For DH's automated tagging to work, the 'tags' need to exist in the repository that you linked the automated build to

From 3, it means we can't easily trigger an automated build on another repository from the ampersand travis (since the tags for automated build image naming won't exist on the other repository).

If we are fine with 2 (I mean, cloning ampersand and then doing nothing with the source isn't that worrisome, and it still needs to source for the two docker files), then it might be a good idea to bring the docker files back into the main ampersand directory. We can then trigger a new build after travis uploads the binary and if en when travis is the 'main' CI solution for creating new releases we might even have docker hub listen for new releases and corresponding tags on GitHub. We can't do this currently because at the time of a new release the linux binary doesn't exist yet.
