### ISSUE TITLE
Docker vm fails to start and shows a perpeptual loading state

### ISSUE THREAD

**Issue by f-ten-bosch** [AmpersandTarski/Ampersand#699]
We tried to start the docker vm in different configuration in on different machines and Operating systems but no of the available images seems to work other then showing the startup screen
in the log the message API.error  cannot connect to database [][]  appears. 

![image](https://user-images.githubusercontent.com/31667854/30076614-bd87aac0-9279-11e7-94a0-2c0f5eaa2bf6.png)
![image](https://user-images.githubusercontent.com/31667854/30076831-7c2f3402-927a-11e7-95ef-4e0f844dc3c7.png)

**Comment by hanjoosten** [comment]
RAP3 is still experimental. With Ampersand v.3.8.8 there are problems with it (see issue #698 ). The problem you have has something to do with the database not being accessable. @stefjoosten might be able to help you with that. However, until issue #698 is fixed, RAP3 will not work, even if you have a proper connection to the database.

**Comment by stefjoosten** [comment]
To me it looks like something is wrong with the communication of database credentials from the RAP3 container to the MariaDB container.

**Comment by hidde-jan** [comment]
The RAP3 container expects the database to be available on the hostname 'db' (I think, the docker-compose.yml contains the proper hostnames). Kitematic doesn't give the containers these hostnames by default or links the containers. You'll need to do these things manually. 

Verstuurd vanaf mijn iPhone

**Comment by hidde-jan** [comment]
Btw the current docker images are still ampersand 3.8.7 based, so they should still work. 

Verstuurd vanaf mijn iPhone

**Comment by hidde-jan** [comment]
So, this is not really a bug, but a configuration error. In the [sample dockerfile](https://github.com/AmpersandTarski/Ampersand/blob/feature/dockerize/docker/sample/Dockerfile), we expose the AMPERSAND_DB_HOST env variable to easily configure the db host, but the custom settings of RAP3 hardcode it to 'db'.  I think it would be a good idea to incorporate this in the ampersand-prototype image itself instead of forcing users to do it themselves.

**Comment by dartheide** [comment]
I have the same problem. 
The database is running in the container named "rap3_db_1", and the container named "rap3_rap3_1" I get the message "[2017-11-10 15:41:31] API.ERROR: Cannot connect to database [] []". 
I think there no problem with the hostnames because, I am able to ping db inside the container, and with the container named 'rap3_phptools_1'  I can acces the database with phpadmin.

**Comment by hanjoosten** [comment]
@hidde-jan Could you help us with this?

**Comment by dartheide** [comment]
I made a tcp dump and analyse the packages with Wireshark: 	
MySQL	112	Response Error 1049  "Unknown database".
If I create the database the next error is unknown table. 

My analysis is that the database is not initialized

I attach the wireshark output. 

[Wiresharp network output.xml.txt](https://github.com/AmpersandTarski/Ampersand/files/1462960/Wiresharp.network.output.xml.txt)

[tcpdump docker container rap3_rap3_1.bin.zip](https://github.com/AmpersandTarski/Ampersand/files/1462961/tcpdump.docker.container.rap3_rap3_1.bin.zip)

**Comment by dartheide** [comment]
Initialize the database by hand with SQL script 2 and 3, then RAP3 is running normally.

https://github.com/AmpersandTarski/docker-ampersand/tree/master/RAP3DB

**Comment by hidde-jan** [comment]
Did you use the docker-compose file to start the ‘cluster’. Or did you use the ampersand-db image? If you are using the default mariadb image the db will not be initialized of course.

**Comment by hidde-jan** [comment]
Actually, would it be possible to detail how you try to start the different vms?

Running docker-compose up on the docker-compose.yml file included in the RAP3 folder should start a cluster regardless of operating system.

**Comment by dartheide** [comment]
I' am using /ampersand-models/RAP/docker-compose.yml then "docker-compose up -d".

**Comment by Michiel-s** [comment]
With RAP3 being built successfully now, I think this issue is fixed.
