### ISSUE TITLE
Plus-sign next to scripts creates error message

### ISSUE THREAD

**Issue by EstherHageraats** [AmpersandTarski/Ampersand#704]
The first script in RAP3 you have to create with the green plus-sign in the top-right of the screen.
When there is one script or more, plus-signs also appear on the right of the scripts. Clicking that will result in an error message as if the tool tries to find the script in stead of creating it (see picture) Clicking on the plus-sign on the top-right works fine. 
![schermafdruk 2017-09-22 13 28 47](https://user-images.githubusercontent.com/18698059/30744816-119cfd22-9fa4-11e7-87e9-208d16dffe70.png)

This happened before the problems described in issue #700 . Maybe related?

**Comment by stefjoosten** [comment]
The word 'CRuD' was used on line 3 of file `Scripts.ifc`. This should have been `cRuD`. I have changed the code accordingly in commit AmpersandTarski/ampersand-models@c10587d1cea81e57789319f1aff35513bd02e53b. This solution will become operational in the next release.

**Comment by stefjoosten** [comment]
I have fixed the problem by changing the `CRuD` annotation on line 3 of file `.../RAP3/Scripts.ifc` to `cRuD`. This does away with the green arrow entirely. I changed this in commit AmpersandTarski/ampersand-models@c10587d1cea81e57789319f1aff35513bd02e53b. This change will be operational in the next release and deployment of RAP3.

**Comment by stefjoosten** [comment]
# Diagnosis
I have not looked into this very deeply. It seems to me that a top-level crud-annotation should never be C or U, since it makes no sense to update the root atom on which the interface has been called.

**Comment by Michiel-s** [comment]
stefjoosten wrote:
> I have not looked into this very deeply. It seems to me that a top-level crud-annotation should never be C or U, since it makes no sense to update the root atom on which the interface has been called.

A top-level Update or Create are common in my own scripts, e.g. to create an overview of People and be able to create a new Person: `INTERFACE "People" : V[SESSION*Person] CRud COLS []`. And update is also possible.

Keep in mind that the crud rights are about the relation(expression) and not the root atom. In #141 we described the semantics of the CRUD syntax. In short:

CRUD | Tgt concept ISA Object | Tgt concept ISA Scalar
-- | -- | --
C | Be able to add a new link by creating a new atom (concept = tgt of expr). If expr is not a relation, the atom is created, but not the link. Depending on the expression, the newly created atom might appear or not. | NA Warning: Not possible, use update
c | Not allowed to create new tgt atom | NA
R | Read allowed | Read allowed
r | Read not allowed | Read not allowed
U | Add and/or remove link from src atom to existing atoms (concept = tgt of expr). When expr is not a relation -> Warning: Update not possible | Add and/or remove link from src atom to tgt atom. Tgt atom does not have to exists (because it is a scalar). When expr is not a relation -> Warning: Update not possible
u | Add/remove links not allowed | Add/remove links not allowed
D | Remove link by deleting tgt atom. All other links from/to tgt atom are also removed | NA Warning: Not possible, use update
d | Remove link by deleting tgt atom not allowed | NA

Maybe good to document this in our [gitbook](https://ampersandtarski.gitbooks.io/documentation/). @stefjoosten, can you do this, because I temporarily don't have access rights anymore?
