### ISSUE TITLE
Remove syntax for THEMES

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#723]
The syntax for themes causes quite some complexity in the generation of functional specification documents. The idea with themes was that it enabled developing of a script with several patterns and only generate documentation for a subset of those patterns. This was useful in the time that the INCLUDE statement wasn't there. Since then, THEMES hasn't been used as far as I know.

It makes sense to remove THEMES from the syntax, and clean up the code to reduce the complexity.

**Comment by stefjoosten** [comment]
Agree!

**Comment by RieksJ** [comment]
I don't agree with the argumentation. You cannot just not include a file and compile an fspec, in particular when you have interfaces that use relations in a file that is not included in the fspec.

However, since I have not used fspec for quite some time (and I guess neither have others), I currently do not object to throwing out THEMES under the argument of reducing development complexity. Perhaps we could even throw out the fspec generation completely.

I guess it makes sense to rethink the functional specs feature from the ground up (as a low priority). To me, it seems that if we would like to generate different texts/pdfs at all, what we would like their contents to be might depend on the purpose(s) we seek to fulfill in the project that we work in.

**Comment by hanjoosten** [comment]
This is fixed in developement now and will go into the next release.
