### ISSUE TITLE
The `--dev` switch is still in use, but has disappeared

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#728]
#### Version of ampersand that was used 
Ampersand-v3.9.0 [development:ebf13b7]

#### What I expected
I expected that the `--dev` switch would still be available.
After all, I do use scripts that have violations that get resolved when the prototype database is initialized.

#### What happened instead
See the screenshot
![image](https://user-images.githubusercontent.com/8522589/33873425-35d05cb4-df1b-11e7-99bc-a9845357ecd3.png)

**Comment by hanjoosten** [comment]
Interesting. It will be a small change to enable a switch like this. I couldn't think of a usecase and thought it wasn't in use any longer. 
I can implement a switch like this tonight, but I suggest to rename the switch to something that better reflects the intent. What about `--ignore-invariant-violations` ?
I am curious to hear about your usecase for this. Can you tell some more about that?

**Comment by hanjoosten** [comment]
NB: If you cannot wait, you could use commit 86d0329c9ad55904913131ce82f93b7ec6d43fe0 until this is fixed.

**Comment by hanjoosten** [comment]
see also issue #700

**Comment by RieksJ** [comment]
There are many use-cases, but here's a simple one. Suppose your script contains
~~~
INCLUDE "Something.pop"

status :: Something * Status [UNI,TOT]
~~~
and you have ExecEngine rules that automatically determine the status, based on properties of `S1` and `S2`. There should be no need to force the developer to spend time and specify that status for every population that he wants to INCLUDE with the script. 

W.r.t. the name, please keep the name of the switch short so I can type it quickly. I don't mind a verbose switch, but please then specify an abbreviation for it, e.g. `--ignore-invariant-violations` and `-iiv` for short or so.

**Comment by hanjoosten** [comment]
I'll come up with something short. I don't understand the usecase though. Just out of curiosity, what rule is there that triggers the execengine? Isn't that the same totality rule? Only the enforcement is automatic. Hence, the same rule as invariant seems wrong. With the current entangled implementation of rules and enformcemts your solution is a nice workaround. In the long run, this will (hopfully!) change, I guess.

**Comment by hanjoosten** [comment]
Closed with commit 4a8376e6456c986bee861e524f4716207bb73073

**Comment by Michiel-s** [comment]
Nice and clean now. Great work.

**Comment by RieksJ** [comment]
I disagree with @Michiel-s.
I also have problems with what @stefjoosten wrote:
> In Ampersand 4 we want to fix the problem with multiplicity constraints being invariant only. When that happens, you can confine exec-engine rules to fix process rules only. In that situation, there will be no need for using this "feature" anymore.

Here is why. Currently, Ampersand assumes that when a population is specified, it should satisfy all invariants, as should be the case outside transactions. However, prototypes treat a population that a developer speicifies as the first transaction after having created the database structure. This does not require that the population must satisfy all invariants, as the ExecEngine may be fixing such violations. Both approaches are valid, in different situations. 

Thus, there is no problem that needs to be fixed. Also, from the perspective of this issue, there is no problem with multiplicity constraints being invariant only (which by the way is currently already the case). Therefore,  Ampersand 4 is not going to make a contribution to resolving this non-existing problem, and consequently I have removed the label.

**Comment by Michiel-s** [comment]
I think by default Ampersand should only compile the script if any initial population satisfies the invariant constraints. When explaining the rule based approach and difference between invariants and signals and how Ampersand guarantees invariant satisfaction of the database at all times, it helps that from to start you have a valid state. 

I do understand @RieksJ's use case and the fact that the exec engine can help to fixes initial population. The switch 'allowInvariantViolations' that @hanjoosten specified (instead of the --dev) allows for this use case. Needing to specify this explicitly (on the cmd line or in the config yaml file) forces the developer to think of initial invariant violations that must be solved. Furthermore, the --allowInvariantViolations is more clear about the affect it has than the --dev.

The situation now is the same as before, but with a different, more clear, name for the switch. That's why I commented 'nice and clean now'.

**Comment by hanjoosten** [comment]
1. `--dev` works now as well, as a synonym for `--ignore-invariant-violations`  , only to facilitate backwards compatibility and @RieksJ .
2. The invariant rule: `The population of a context must not violate any invariant rule in that context` should hold at ALL times. Therefor, the usecase is not durable. There will be changes when we implement a better distinction between a rule and it's enforcement.

**Comment by Michiel-s** [comment]
> The invariant rule: The population of a context must not violate any invariant rule in that context should hold at ALL times

I would add "...should hold at ALL times outside a transaction".

And that is exactly the point @RieksJ is addressing. @hanjoosten assumes that the transaction ends right after generating the application and adding the iniatial population to the database. However, just before closing the transaction, the exec-engine kicks in and possibly solves invariant violations to restore the rule you mention.

I think what's happening here is that @hanjoosten horizon stops after generating the prototype at compile-time, while @RieksJ takes into account the run-time affects of the exec-engine. You both share the invariant rule that `The population of a context must not violate any invariant rule in that context`

**Comment by stefjoosten** [comment]
@RieksJ , I'm losing track of this discussion. As I understand it now, this is your example:
```
CONTEXT Something

status :: Something * Status [UNI,TOT]

POPULATION Something CONTAINS  [ "1", "2" ]

ROLE ExecEngine MAINTAINS r
RULE r : I |- status;status~
VIOLATION ( TXT "{EX} InsPair;status;Something;", SRC I, TXT ";Status;Initialstate" )

ENDCONTEXT
```
Currently, you cannot generate code, because you run into
```
Violations of rule "TOT status[Something*Status]":
- [("1","1"), ("2","2")]

Signals for initial population:
Rule(s): ["TOT status[Something*Status]","r"]
  Conjunct   : -I[Something] \/ status[Something*Status];status[Something*Status]~
  Violations : [("1","1"), ("2","2")]
ERROR: No prototype generated because of rule violations.
```
This is (as far as I can tell) your use case. If the enforcement of UNI and TOT would be user definable (instead of INVARIANT, as it is now), you would be free to enforce UNI and TOT in another way (e.g. NONE, or BY ExecEngine). That is what I'm planning for Ampersand4. (That would also eliminate the need to have the ``--dev`` switch.)

But judging by the previous discussion, you have a stronger use case that overrules this one. So please provide a more accurate example to make your point.

**Comment by RieksJ** [comment]
Talked to Han. He said that the relation between the example and enforcements have to do with muti-context stuff, as we discussed elsewhere. The example I give is also an example of the need of mutiple contexts, so if that can be arranged, chances are that `--dev` indeed becomes obsolete.  Since Ampersand4 seems to be tying enforcements and multiple contexts etc. all together (which I gather is predominantly obvious to those that are more or less daily involved in its developments), I all this together, since that will support multiple contexts as well as enforcements, I have restored that lablel.
