### ISSUE TITLE
Escape characters in Strings

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#744]
I used Ampersand-v3.9.1 [development:b051de7] when compiling the following script:
~~~
CONTEXT KvK_ZZPRegForms
INCLUDE "..\SSIF-Generic\SSIF_FormTemplates.adl"
-- etc...
ENDCONTEXT
~~~

I expected that the texts between quotes after the `INCLUDE` statement would be recognized as a string literal. However, It resulted in the following error message:
~~~
Lexer error at line 3:9, file C:\Ampersand\Git\tno-models\SSIF-KvK\KvK_ZZPRegistrationForms.adl
  Unterminated string literal
    Correct examples of Strings: "Ampersand (&) is cool" "Helium is cool too!" "abc\ndef" ""
Terminated at ...: 15:57:43,67
~~~

#### Diagnosis
After some tinkering, it turned out that I needed to replace the `\` characters with `/`. Perhaps the `\S` is treated as a separater that terminates the parsing of a literal, because I also tried the example `"abc\ndef"` as given in the error message.

It seems to me that if beginners get this error, they would have no clue where to look, let alone wehre to fix this.

**Comment by hanjoosten** [comment]
Since we like to be able to represent all imaginable strings, we need some way to denote a string that holds a double quote. If nothing was done, the first double quote in the string would be interpreted as the end of the string. Also, we want some way to represent multi-line strings. 
To do so, we have `\` as an escape character, as is done in C, in Haskell and in many other computer languages. For those interested, we use the same as Haskell does. ([documentation is here](http://book.realworldhaskell.org/read/characters-strings-and-escaping-rules.html)). 

In the above case, I would recomend to write:

```
CONTEXT KvK_ZZPRegForms
INCLUDE "../SSIF-Generic/SSIF_FormTemplates.adl"
-- etc...
ENDCONTEXT
```
but you could also write:

```
CONTEXT KvK_ZZPRegForms
INCLUDE "..\\SSIF-Generic\\SSIF_FormTemplates.adl"
-- etc...
ENDCONTEXT
```
In the latter case, the escape character is escaped itself!

Feel free to update the documentation if you find that usefull.

**Comment by RieksJ** [comment]
The bug is not the fact that the parsing is wrong, but that the error message does not help the user - particularly if they are beginners. As I have mentioned before, error messages are there to help the user, and I consider it a bug if they do not.

It would be nice if the error message could be extended to include the text `This error may be caused by a missing quote-character ('"'), or by the inadvertent use of the escape character ('\').` Would you be so kind as to grant me this wish?

**Comment by hanjoosten** [comment]
Poof! Wish granted 😁
