### ISSUE TITLE
Feature request: support paths in INCLUDE statements

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#75]
Currently, the `INCLUDE` statement only supports simple filenames.
In order to keep sources of &-modules in a single location, I would like to use constucts such as:

     INCLUDE "..\lib\login.adl"
     INCLUDE "C:\Ampersand\Library\login.adl"

Would that be possible?

**Comment by Oblosys** [comment]
Include paths are already supported, but the separator is '/' instead of '\'. The reason for that is that a path is an Ampersand string, so we would either need to escape each backslash (e.g. "dir\\Context.adl"), or add a special case to the scanner for include paths (which does not seem to be worth the effort.)

Drive selection is not supported, but we probably want to avoid absolute paths anyway, as they make the sources very non-portable.
