### ISSUE TITLE
TYPEs (IT-TYPEs) in Ampersand, DB and FrontEnd

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#76]
A construct in an adl script such as:

    CONCEPT Criterion "a text used for ..." TYPE "Blob"

results in tables where the column is a `BLOB` rather than a `VARCHAR(255)`. However, importing an EXCEL file that populates such tables results in messages such as

     Error! Concept BLOB does not exists in allConcepts
     Error! Cannot find relation with signature 'ctrlCriterion[Control*BLOB]'
     Error! Cannot find relation with signature 'bfcCriterion[BFControl*BLOB]'

and so on. Michiel, can you fix this?

**Comment by Michiel-s** [comment]
Hi Rieks,

First notice the difference in uppercasing of `.. TYPE "Blob"` with `Error! Concept BLOB`. These are two different concepts. But that has nothing to do with the Error your seeing.

The concept names, such as Criterion and BLOB are used in the new frontend to determine the template that is used. We've introduced the prim. datatypes BLOB, BOOL, DATE, TEXT and PASSWORD for certain behavior in the UI.

The TYPE definition in Ampersand on the other hand determines the SQL database field type. This is not used by the new frontend. Only Text (default) and Blob are supported as far as I know.

You should use: 
```
ctrlCriterion :: Control * BLOB
CONCEPT BLOB "" TYPE "Blob"
```

The above way of working is far from ideal and has a relation with the discussion in http://sourceforge.net/p/ampersand/tickets/456/. For now, I will rename the prim. datatypes in the new frontend from BLOB to Blob, TEXT to Text, etc, to make it at least more consistent with the TYPE definition. However the matching for templates still is based on the concept name and not the type definition.

That means that you should use:
```
ctrlCriterion :: Control * Blob
CONCEPT Blob "" TYPE "Blob"
```

**Comment by RieksJ** [comment]
Michiel, you suggested that the following would work:

     ctrlKPI :: Control * KPI
     VIEW KPI : KPI DEFAULT { "value" : I } HTML TEMPLATE "Atomic-BLOB.html" ENDVIEW

However, this leads to the following output

![untitled](https://cloud.githubusercontent.com/assets/8522589/7271498/13fcb9e6-e8e4-11e4-84e9-f2cfb9bc9db6.png)

**Comment by stefjoosten** [comment]
Apparently, we have two different sets of primitive data types: the set in Michiels' front end and the set in the MySQL database. Of course, we might unify those two sets, but the problem would pop back up the moment we add connectors with different primitive types. What is wisdom?

**Comment by RieksJ** [comment]
Michiel and I discussed this, and concluded that there are three distinct representations of (real world?) entities and we should strictly distinguish between them:

1)     representations in Ampersand. Here we talk about concepts, atoms and relations. ISA’s, generalization etc. belong in this realm.

2)     representations in a database. Here we talk about table structures and how we represent &-atoms, using DB-fields of type text (e.g. for atoms) or blobs (for long texts). In future, we might also want to use other DB-fields. Currently, there is a limited possibility to map ampersand atoms to DB-fields, using the keyword TYPE in combination with CONCEPT.

3)     representations on the screen. Here we talk about VIEWs (and associated HTML templates).

It might be a good idea to use names for DB-fields and VIEWs that are unambiguous w.r.t. the realm they refer to. If, for example, a VIEW would be called BLOB (the same name as a DB-field), this would cause confusion. VIEWs for a (long) text should therefore have different names, e.g. “rectangulartext” or such.
This message may contain information that is not intended for you. If you are not the addressee or if this message was sent to you by mistake, you are requested to inform the sender and delete the message. TNO accepts no liability for the content of this e-mail, for the manner in which you use it and for damage of any kind resulting from the risks inherent to the electronic transmission of messages.

**Comment by hanjoosten** [comment]
Last friday, Michiel, Stef and I sat together to discuss this issue. A summary of that discussion:

Principles:

1.  Concept names should not be used to reflect the type/domain of a concept, because Concept names are Business artifacts.
1.  The Ampersand modeller should not have to be aware of all kind of technical stuff in different technical 'worlds'. 
1.  The Ampersand modeller should be enabled to influence downstream behaviour if there is a need to do so.

Conclusions: 

1. The Ampersand syntax will be enriched with non-technical domains of data-types. 
   * Initially these domains are in scope: ***Alphanumeric***, ***BigAlphanumeric***, ***HugeAalphanumeric***, ***Password***, ***Binary***, ***BigBinary***, ***HugeBinary***, ***Date***, ***DateTime***, ***Boolean***, ***Numeric***, ***AutoIncrement***
1. For each relevant context (PHP, SQL, HTML, ADL ...) appropriate conversions will be implemented to cope with the non-technical domains in that specific context. This will all be part of ampersand tooling, out of scope of the Ampersand modeller
1. The TYPE addendum to the CONCEPT statement will be replaces by a new statement: 
    * `REPRESENT <Concept> TYPE <Domain>`
 
Work in progress :construction: 
1. Changes will be made in a separate branch first, data_type. Currently, the parser accepts the new syntax. 
1. Populations in ampersand scripts are still strings only. Restrictions will have to be made in place, in order to accept only atomvalues in the appropriate domains. 
1. Transformation to SQL data definitions are to be made. 
1. Information about the domains will have to be passed to the new frontend 
1. The new frontend will have to cope with the domains
1.  
1.
