### ISSUE TITLE
Erroneous showing of CLASSIFYd populations

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#769]
When I devised a script for @sjcjoosten, so that he could do some testing regarding #759 , I ran into what I consider to be a bug.

I compiled the following script using Ampersand-v3.9.4 [development:2c97107]:
~~~
CONTEXT Issue766

biaVerplichting_Def :: Bedrijfsfunctie * Verplichting [INJ]
CLASSIFY ExterneVerplichting ISA Verplichting

RULE "BIAlijst integriteit": -- Invariant
biaVerplichting_Def |- biaVerplichting_Def;I[ExterneVerplichting]
MEANING "De BIA-lijst bevat alleen externe verplichtingen."
VIOLATION (TXT "De BIA-lijst van ", SRC I, TXT " mag alleen externe verplichtingen bevatten; ", TGT I, TXT " is dat niet.")

INTERFACE "Check Issue766": I[SESSION] cRud ROWS
   [ "Bedrijfsfuncties": V[SESSION*Bedrijfsfunctie] COLS
      [ "Bedrijfsfunctie": I 
      , "Verplichtingen": biaVerplichting_Def
      , "ExterneVerplichting": biaVerplichting_Def;I[ExterneVerplichting]
      ]
   , "Verplichtingen": V[SESSION*Verplichting] COLS
      [ "Verplichting": I[Verplichting]
      , "Extern?": I[ExterneVerplichting]
      , "Bedrijfsfunctie": biaVerplichting_Def~ cRud
      ]
   ]

POPULATION Verplichting        CONTAINS [ "v1", "v2", "v3" ]
POPULATION ExterneVerplichting CONTAINS [ "e1", "e2", "e3" ]

POPULATION biaVerplichting_Def CONTAINS
   [ ("b1", "e1")
   ; ("b1", "e3")
   ]

ENDCONTEXT
~~~

After initializing, here is what the interface "Check Issue766" shows. I have marked the populations that IMHO should not have appeared. 

![image](https://user-images.githubusercontent.com/8522589/37829270-ae3f9534-2e9e-11e8-9e2d-abeb56c445f8.png)

**Comment by RieksJ** [comment]
Further analysis with @Michiel-s has shown that the tables in the database are properly populated. 

The problem is a difference in interpretation of the `isIdent` element in the `interface.json` file (which reminds me of #768). This difference is in whether or not an epsilon may, or may not be part of the `isIdent`. The prototype generator does not care about whether or not there is an epsilon, but the prototype code itself does.

There are different ways this can be fixed depending on how the semantics of `isIdent` will be resolved. This is a discussion between @hanjoosten and @Michiel-s

**Comment by Michiel-s** [comment]
No. Backend expects isIdent bool to be really the ident I relation. Instead epsilons are also included. Just discussed with Han that he implements a change.

**Comment by Michiel-s** [comment]
FYI, the backend uses this information to reduce database interaction. If in a subinterface you specify the expression I[Concept], eg to subbox some data, no query is needed, because we already know the tgt atom.

**Comment by stefjoosten** [comment]
My point is that all of Ampersand's semantics should be delivered by the generator, i.c. Han. Whether it is the Zwolle, Enschede, Milan, or Monastir or any future interface, any runtime module should be agnostic of Ampersand's semantics. This architectural principle is meant to guarantee the semantics to the user from a single source (i.c. the generator).

So if any query is needed, its code (irrespective of form) must be made available to the Enschede interface by the generator, taking away the need to interpret Ampersand. Michiel's code must be free of any knowledge of Ampersand's semantics. So if Rieks' error (mentioned in this issue) is caused in the Enschede interface, that signals a violation of this principle. Michiel's answer reassures me that Rieks' error was caused in the generator. (Reassurance example: things like transformations from JSON to SQL do not violate this architectural constraint, so long as they don't interpret Ampersand's semantics.)

So my question was: are we violating this principle? @Michiel-s 's answer, No, is fine. We have no problem and Han can fix (or has fixed) this mistake in the generator. Otherwise, this would involve a change in the communication between generator and Enschede interface, perhaps to be solved temporarily using "comply or explain".

**Comment by hanjoosten** [comment]
It seems to me that this issue reveals an implementation issue. We have a function isIdent, that only guarantees on the False outcome. @Michiel-s needs a function that guarantees the True outcome. In case of isIdent, that is not the same, for sometimes it is unknown if an expression is equivalent to I.

Further, the implementation is odd (and very old!) too. I think these functions should only be defined for Expression. Currently, it is in the class Relational, which makes no sense. @stefjoosten How should these properties be defined in FormalAmpersand?

**Comment by hanjoosten** [comment]
I have put an extra check into place, that guarantees that isIdent is true only for *real* I. This check didn't reveal any errors. So now we can guarantee that isIdent has a correct implementation.

**Comment by Michiel-s** [comment]
After discussion with @hanjoosten and respecting the principles addressed by @stefjoosten, we've decided to leave the semantics of the interface expression isIdent info as is and change the logic in the run-time environment. The isIdent info was used to decided if a query can be skipped, but now also the provided target concept of the parent interface is taking into consideration (because of the possibility of an epsilon). Nothing is computed, all required information is provided by the generator.

> @stefjoosten wrote: Michiel's code must be free of any knowledge of Ampersand's semantics
That's practically impossible given the current architecture, but let's discuss this sometime later.
