### ISSUE TITLE
Incomplete error checking when using meatgrinder

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#784]
Using switches such as `meta-file` or `add-semantic-metamodel` will get me the relations as defined in formal-ampersand. However, these relations may pose conflicts with relations defined in my applications (or worse: in a module that I import, such as semantic tree house (STH)).

An example is the concept `Property`, which is defined in formal ampersand as well as in STH. Formal ampersand has `REPRESENT Property TYPE ALPHANUMERIC`, whereas STH expects it to be a regular object. If formal ampersand had to be compiled as any other ampersand source, this would have given me an error message at compile time. However, formal ampersand relations enter into the application through an unchecked backdoor, resulting in a runtime error rather than a compile time error.
The fact that the user expects to see a compile time error, and the fact that he may not be acutely aware of the 'hidden' inclusion of formal-ampersand relations, leaves him puzzled at runtime, because he cannot find the cause of the error in the files that he has included himself.

I would like to request two different things:

- [ ] switches that enter formal ampersand into the model should do that in such a way that all checks are done that would also have been done if formal ampersand were INCLUDEd as .adl files (which means we get proper compile time errors), and
- [ ] names of concepts, relations and rules that originate from formal ampersand must be made easily distinguishable from names that have another origin, e.g. by prefixing them (e.g. with `famp` or `famp_`), such that collisions with user-scripts are highly unlikely to occur (perhaps this may trigger a revision of the names that are used for concepts, relations and rules in formal ampersand, which would be nice too)

![image](https://user-images.githubusercontent.com/8522589/40637184-a49e11d8-6303-11e8-9a82-de0495168959.png)

**Comment by hanjoosten** [comment]
About the requests:
  1. This error should be handled correctly. I reopend issue #163 for this.
  2. Prefixing names in formal ampersand is not an option, as far as I am concerned. These names should even be made more clean than they are now. I remember You argued for this repeatedly before. This is ongoing work as the meatgrinder evolves. The switch is still a hidden switch, because it is still in alpha state. The description says: 
~~~~
All relations, views, idents etc. from formal-ampersand will be available for use in your model. These artefacts do not have to be declared explicitly in your own model.
~~~~
This is exactly what happens. **By design!**. It would be nice to have a way the user could get the documentation of formal ampersand in an easy way. I'll make a separate issue for that, and then this issue will be closed, because there is no work to be done from it.

**Comment by hanjoosten** [comment]
This issue can be closed, because it duplicates issues #163 and #786.

**Comment by RieksJ** [comment]
While issue #163 would resolve the instance of the error, it does not resolve the kind of error, which is that the formal ampersand stuff is imported through a backdoor that does not do the checks that would have been done if it were included as regular .adl files. This means that this issue does not duplicate #163 and has its own right of existence.

**Comment by hanjoosten** [comment]
This is not how this is implemented. There is no backdoor. All checks are properly done, as far as the checks are in place. As soon as #163 is fixed, you will have your error message during compiletime. You can observe this behaviour if you use the --verbose flag. Then you will see that all formal ampersand files are read as well, as are all files from your own script.
