### ISSUE TITLE
Use keyword "API" as a synonym for keyword "INTERFACE"

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#789]
The dudes at TNO claim to have a usecase for an alternative keyword. They asked me to modify the parser. I asked @RieksJ to motivate this request in an issue. Then, I'll make it happen.

@RieksJ , feel free to go ahead!

**Comment by RieksJ** [comment]
Humans that interact with IT systems most often use GUIs to do so. The behaviour of a GUI is that users can type in stuff all over the place, and the system responds by showing modifications on the screen. This interaction is stateful (the state being the data that is shown in the GUI).

Systems can also interact with IT systems, and do so using APIs. Current state of the art is REST, i.e. no state is kept during the interaction (as part of the session). When calling an API, a system will have to send the complete state in its request.

In ampersand, we use the INTERFACE construct to specify GUIs. It so happens that each INTERFACE also (already) specifies an API, which is used by the frontend JS code. In theory (and in practice), we need no additional functionality for specifying APIs. 

However, writing ADL to process data sent through an INTERFACE that models a GUI is quite different (some say: easier) than writing ADL that processes data from a REST API: the latter requires to build up an internal construct for the state that is being sent with the request, to define rules to ensure that the request is actually valid, then do the stuff you would also do in a GUI, and then provide some way to return (a URL that the caller can use to obtain) the results.

In order to make ADL scripts more readable, i.e. make the intention of modeling a REST API rather than a stateful GUI obvious, I would like to have a keyword API that behaves exactly as INTERFACE does.
