### ISSUE TITLE
Title text in interface does not work i.c.m. HTML TEMPLATEs

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#79]
The idea of `HTML TEMPLATE`s in `VIEW`s is to 'paint' a view on an atom and it is being used in increasingly fashionable ways. The tltle text that is produced in `INTERFACES` also use `VIEW`s - in particular: the `DEFAULT` view. This means that currently, if you use a `DEFAULT` view that does some nice things (such as display risks in a fashionable way), this corrupts the title in the interface where you can edit such risks, by displaying all arguments that are passed to the view.

There are several options to go about this issue:
1. only define DEFAULT views for titles and explicitly state the views to use everywhere else. This is not a solution, but it serves as a workaround.
2. allow the use of `VIEW`s after the title expression, and use that to display the title. 
3. ...

**Comment by Michiel-s** [comment]
There should be changed something to the VIEW definition, but I'm not yet sure about the solution. Please comment on the suggestion below.

**Current situation**
Now, we use the VIEW statement for 2 different purposes:
1) Create labels for atoms to be displayed instead of dirty identifiers.
2) Providing key-value pairs with data to the html templates to build fancy views

The first is functionality that was already present before the Zwolle interface (new front end). The second has everything to do with templating stuff.

Furthermore we have the old and new VIEW syntax, both still in use (*part between [] are optional*):
old: `VIEW "<ViewId>" : <Concept> (<rel>[, <rel>, <etc>])`
There can be only one old VIEW statement for a concept, this one is set as DEFAULT.
new: `VIEW "<ViewId>" : <Concept> { <key> : <rel>[, <key> : <rel>, <etc>] } [DEFAULT] [HTML TEMPLATE "<path.html>"] ENDVIEW`
There can be multiple new VIEW statements for a concept, optionally a DEFAULT can be specified.

**Solution to issue**
Maybe we can add an optional LABEL part to the new VIEW syntax to explicitly state how the atom should be represented on the screen. This LABEL part has the same functionality as the old view statement. So it can also contain TXT parts.
```VIEW "<ViewId>" : <Concept> 
            [LABEL ( <rel>[, <rel>, TXT "test", <etc>] ) ] 
            { <key> : <rel>[, <key> : <rel>, <etc> ] }
            [DEFAULT] 
            [HTML TEMPLATE "<path.html>" ] 
ENDVIEW```

**Improved solution**
This also makes it possible to make the `{ ... }` part optional and only specify a template. I suggest to add a DATA statement to specify this part. And place the DEFAULT statement to the beginning of the VIEW definition. That would be:
```VIEW "<ViewId>" : <Concept> 
            [DEFAULT] 
            [LABEL ( <rel>[, <rel>, TXT "test", <etc>] ) ] 
            [DATE { <key> : <rel>[, <key> : <rel>, <etc>] } ] 
            [HTML TEMPLATE "<path.html>" ]
ENDVIEW```

@stefjoosten, @RieksJ, @hanjoosten what do you think.

**Comment by Michiel-s** [comment]
How to reflect the solution from my reply above in Generics.php:

Part in VIEW definition | Part in Generics.php
-----------------------------|---------------------------
ViewId | label
Concept | concept
DEFAULT | isDefault
LABEL () | segments\*
DATA | dataSegments
HTML TEMPALTE | htmlTemplate

\*The label part is mapped to the existing *segments* attribute to be backwards compatible with the old frontend.

This will look like:
```
$allViews =
  array
    (   array ( 'label' => '<ViewID>'
              , 'concept' => '<Concept>'
              , 'isDefault' => '<true/false based on presence of DEFAULT statement>'
              , 'segments' =>
                  array
                    ( array ( 'segmentType' => 'Exp'
                            , 'label' => 'seg_1' // view exp: propertyNS
                            , 'expSQL' => '<expr here>'
                            )
                    , array ( 'segmentType' => 'Text'
                            , 'label' => 'seg_2'
                            , 'Text' => '<txt here>'
                            )
                     )
               , 'dataSegments' =>
                    <same structure as segments here>
               , 'htmlTemplate' => '<path.html>'
        array ( 'label' => 'Another view'
                    <etc>
```

**Comment by hanjoosten** [comment]
If I try to express this in Ampersand meta language, we have (don't focus on the names of these relations, but rather on ther properties)

RELATION viewOf [View*Concept] [UNI,TOT]
RELATION label [View*Label] [UNI,TOT]

IDENT View View(viewOf,label)

RELATION isDefault[View*View][PROP]
RULE max1DefaultPerConcept: isDefault;viewOf;viewOf~|-I[View]

**Comment by hanjoosten** [comment]
I try to figure out what you mean. The current syntax of the new VIEW statement is

![fancyviewdef](https://cloud.githubusercontent.com/assets/1159672/9613595/969f988a-50ec-11e5-95c2-1dfe50897c4d.png)

```ebnf
FancyViewDef ::= 'VIEW' Label ('ONE' | ConceptRef)'DEFAULT'? '{' Label Term(',' Label Term)*'}' ('HTML' 'TEMPLATE' String)? 'ENDVIEW'
```

I am still confused about what you think would be the new syntax. Could you paint a [railroad diagram](http://www.bottlecaps.de/rr/ui) for me?

**Comment by hanjoosten** [comment]
I think we should be very carefull to add extra syntax to this statement, for it is getting pretty ugly this way. At the other hand, improved possibilities for painting interfaces are very welcome. 

Maybe, instead of discussing how the syntax should look like, we might better discuss about the elements that could be contained in a view definition. @Michiel-s already had a table of these things, but without elaborating. 

Part in VIEW definition | Part in Generics.php | comments
-----------------------------|----------------------|-----
ViewId | label | A concept can have multiple views defined for it. However, each view for a concept must have another label. 
Concept | concept | Each view will be for exactly one concept. It will be the source of Terms used within the definition. 
DEFAULT | isDefault | Any concept can only have one default view. 
LABEL () | segments\* | @Michiel-s Please elaborate on the intent of these segments
DATA | dataSegments | @Michiel-s Please elaborate on the intent of these segments
HTML TEMPLATE | htmlTemplate | @Michiel-s In the current syntax multiple templates may be specified. Is that correct?

**Comment by Michiel-s** [comment]
It's nothing new. Instead I propose to make things easier by combining the old and new view syntax. And solving the issue addressed by Rieks in this request.

The LABEL part is the same as the 'old' view syntax and is used to display atoms on the screen.

The DATA part is from the new syntax and is used to provide key-value pairs to be used by the HTML template

Only one HTML template may be specified (for now). 

All parts are optional because you can specify a label to display the atom without a template (just using the build-in templates). You can specify a html template without the need for additional data (e.g. an image). Any other combination is thinkable.

When introducing CRUD rigths in interfaces I foresee the possibility to specify a template for each operation. But let's take it step by step.

**Comment by hanjoosten** [comment]
If the DATA part is directly related to the HTML template, it makse sense to keep the list of key-value pairs from your DATA part and the HTML template name tight together. It does not make sense to have a DATA part without specifying a HTML template, does it? For this I propose a slightly different syntax. Let me explain:

Currently, the new View statement is like this:

![newviewdef](https://cloud.githubusercontent.com/assets/1159672/9624877/25254186-5151-11e5-94fd-4db7046cb675.png)
```
NewViewDef   ::= 'VIEW' ADLid ':' Concept 'DEFAULT'? '{' ADLid ':' Term(',' ADLid ':' Term)*'}' HtmlTemplateUsage? 'ENDVIEW'
```

We could simply extend the HtmlTemplateUsage with your DATA part (without the DATA keyword):

![htmltemplateusage](https://cloud.githubusercontent.com/assets/1159672/9625012/9a2f7e00-5152-11e5-995a-e9b38f2f5d9c.png)

```
HtmlTemplateUsage ::= 'HTML' 'TEMPLATE' String ('[' (('(' Key ',' Value ')')(',' ('(' Key ',' Value ')'))*)? ']')?
```

This will ensure, that if we ever have the wish for multiple HtmlTemplateUsages in a single View, statement, the DATA part stays together with the template. Besides, keeping everything together with the template part makes it even easier to fix...

@Michiel-s Please comment.

**Comment by hanjoosten** [comment]
After a chat with @Michiel-s , I modified the syntax of the new VIEW statement to allow an empty list of attributes:

![newviewdef2](https://cloud.githubusercontent.com/assets/1159672/9698558/6b32ebd4-53bc-11e5-94e9-2f1432833473.png)

```
NewViewDef  ::= 'VIEW' ADLid ':' Concept 'DEFAULT'? ( '{' ( ADLid ':' Term(',' ADLid ':' Term)* )? '}' )? HtmlTemplateUsage? 'ENDVIEW'
```

**Comment by hanjoosten** [comment]
@Michiel-s , please add [railroad diagrams](http://www.bottlecaps.de/rr/ui) if there is anything else you need to be changed for the DATA syntax.

**Comment by Michiel-s** [comment]
Hi @hanjoosten ,

We're almost there. I've finally created the railroad diagram of how I would like to have the "new" VIEW syntax.

Notice that I added the `LABEL ( .... )` part and only added the keyword DATA before the `{ .... }` part. The LABEL part is to be used when printing the atom on screen (kind of toString method) and the DATA part is for the required data in the html templates.

![newviewdef](https://cloud.githubusercontent.com/assets/7961582/10894397/a62f55a4-81ae-11e5-994f-58e082d7b051.png)

`NewViewDef  ::= 'VIEW' ADLid ':' Concept 'DEFAULT'? ( 'DATA {' ( ADLid ':' Term(',' ADLid ':' Term)* )? '}' )? ('LABEL (' ((ADLid ':')? Term | 'TXT' String ) (',' ((ADLid ':')? Term | 'TXT' String ) )* ')')? HtmlTemplateUsage? 'ENDVIEW'`

Does this make sense to you?

**Comment by Michiel-s** [comment]
@hanjoosten as discussed I updated the raildiagram.

**Comment by hanjoosten** [comment]
Michiel, Do you need the possibility of empty DATA{ } ? I assumed that you didn't mean that in the above railroad diagram.

**Comment by hanjoosten** [comment]
I've done some testing this morning. Unfortunately, it doesn't work yet. The parser code around this feature us REALLY ugly, and there is a lot more to it than I initially thought. I'll look into it later.

**Comment by RieksJ** [comment]
@hanjoosten's comment of 1 september (sorry for the late reply): `RULE max1DefaultPerConcept' is wrong. It should be:

    RULE max1DefaultPerConcept: isDefault /\ viewOf;viewOf~ |- I[View]

**Comment by DebbieGit** [comment]
Beste Rieks, kun je me helpen?

Ik zoek een recent Ampersand script met een uitgebreid voorbeeld van een USER INTERFACE er in. Ik hoef niet per se de rest van het script te zien, maar geeft misschien wel meer informatie.

Kun je me doorverwijzen naar één van de scripts in Git?



Vriendelijke groeten,

Debbie Tarenskeen
Informatica Communicatie Academie
Hogeschool van Arnhem en Nijmegen
Ruitenberglaan 26, 6826 CC Arnhem
Postbus 2217, 6802 CE Arnhem

Mobiel 0653582390
Fax 026-3645066


e-mail: debbie.tarenskeen@han.nl<mailto:debbie.tarenskeen@han.nl>
aanwezig op ma. di. wo. do.
________________________________
Van: Rieks <notifications@github.com>
Verzonden: maandag 30 november 2015 09:10
Aan: AmpersandTarski/ampersand
Onderwerp: Re: [ampersand] Title text in interface does not work i.c.m. HTML TEMPLATEs (#79)


@hanjoosten<https://github.com/hanjoosten>'s comment of 1 september (sorry for the late reply): `RULE max1DefaultPerConcept' is wrong. It should be:

RULE max1DefaultPerConcept: isDefault /\ viewOf;viewOf~ |- I[View]


-

**Comment by stefjoosten** [comment]
Debbie,  deze vind ik zelf wel leuk...  (Je moet Atoms.ifc draaien. Dat is het "hoofdprogramma")

Stef Joosten

M +31 (0)6 51348895
skype: stef.joosten



-----Oorspronkelijk bericht-----
Van: DebbieGit [mailto:notifications@github.com]
Verzonden: maandag 7 december 2015 19:44
Aan: Joosten, Stef
Onderwerp: Re: [ampersand] Title text in interface does not work i.c.m. HTML TEMPLATEs (#79)

Beste Rieks, kun je me helpen?

Ik zoek een recent Ampersand script met een uitgebreid voorbeeld van een USER INTERFACE er in. Ik hoef niet per se de rest van het script te zien, maar geeft misschien wel meer informatie.

Kun je me doorverwijzen naar één van de scripts in Git?



Vriendelijke groeten,

Debbie Tarenskeen
Informatica Communicatie Academie
Hogeschool van Arnhem en Nijmegen
Ruitenberglaan 26, 6826 CC Arnhem
Postbus 2217, 6802 CE Arnhem

Mobiel 0653582390
Fax 026-3645066


e-mail: debbie.tarenskeen@han.nl<mailto:debbie.tarenskeen@han.nl>
aanwezig op ma. di. wo. do.
________________________________
Van: Rieks <notifications@github.com>
Verzonden: maandag 30 november 2015 09:10
Aan: AmpersandTarski/ampersand
Onderwerp: Re: [ampersand] Title text in interface does not work i.c.m. HTML TEMPLATEs (#79)


@hanjoosten<https://github.com/hanjoosten>'s comment of 1 september (sorry for the late reply): `RULE max1DefaultPerConcept' is wrong. It should be:

RULE max1DefaultPerConcept: isDefault /\ viewOf;viewOf~ |- I[View]


-
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/79#issuecomment-160551280>.

—
Reply to this email directly or view it on GitHub<https://github.com/AmpersandTarski/ampersand/issues/79#issuecomment-162619664>.

________________________________
Deze e-mail is uitsluitend bestemd voor de geadresseerde(n). Verstrekking aan en gebruik door anderen is niet toegestaan. Open Universiteit sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending. Aan de inhoud van deze e-mail en/of eventueel toegevoegde bijlagen kunnen geen rechten worden ontleend.

This e-mail is intended exclusively for the addressee(s), and may not be passed on to, or made available for use by any person other than the addressee(s). Open Universiteit rules out any and every liability resulting from any electronic transmission. No rights may be derived from the contents of this message.

Disclaimer
Dit bericht met eventuele bijlagen is vertrouwelijk en uitsluitend bestemd voor de geadresseerde. Indien u niet de bedoelde ontvanger bent, wordt u verzocht de afzender te waarschuwen en dit bericht met eventuele bijlagen direct te verwijderen en/of te vernietigen. Het is niet toegestaan dit bericht en eventuele bijlagen te vermenigvuldigen, door te sturen, openbaar te maken, op te slaan of op andere wijze te gebruiken. Ordina N.V. en/of haar groepsmaatschappijen accepteren geen verantwoordelijkheid of aansprakelijkheid voor schade die voortvloeit uit de inhoud en/of de verzending van dit bericht.

This e-mail and any attachments are confidential and are solely intended for the addressee. If you are not the intended recipient, please notify the sender and delete and/or destroy this message and any attachments immediately. It is prohibited to copy, to distribute, to disclose or to use this e-mail and any attachments in any other way. Ordina N.V. and/or its group companies do not accept any responsibility nor liability for any damage resulting from the content of and/or the transmission of this message.

**Comment by RieksJ** [comment]
@DebbieGit: voldoet Stef's suggestie?

**Comment by DebbieGit** [comment]
Beste Rieks, Stef,

Ik heb Atoms gegenereerd en gedraaid. De database wordt gemaakt. Ik probeer de database te reïnitialiseren en de xlsx bestanden te importeren. Helaas verschijnen er geen data in de database en ik krijg dus ook geen andere schermen.



Ik heb een database user ampersand met wachtwoord ampersand van te voren aangemaakt. De tabellen zijn er wel. Ik ga even zoeken of ik iets vind betreffende rechten.

Hetzelfde gebeurt bij het script van Michiel.



Vriendelijke groeten,

Debbie
Informatica Communicatie Academie
Hogeschool van Arnhem en Nijmegen
Ruitenberglaan 26, 6826 CC Arnhem
Postbus 2217, 6802 CE Arnhem

Mobiel 0653582390
Fax 026-3645066


e-mail: debbie.tarenskeen@han.nl<mailto:debbie.tarenskeen@han.nl>
aanwezig op ma. di. wo. do.
________________________________
Van: Rieks <notifications@github.com>
Verzonden: woensdag 9 december 2015 08:54
Aan: AmpersandTarski/ampersand
CC: Tarenskeen Debbie
Onderwerp: Re: [ampersand] Title text in interface does not work i.c.m. HTML TEMPLATEs (#79)


@DebbieGit<https://github.com/DebbieGit>: voldoet Stef's suggestie?

-

**Comment by DebbieGit** [comment]
Beste Rieks, Stef,

Het is in orde, het lag toch aan de Violations.

Blijft de vraag naar de uitgebreidheid van de Interface Syntax. Hoe uitgebreid is die?



Vriendelijk dank,

Debbie




Informatica Communicatie Academie
Hogeschool van Arnhem en Nijmegen
Ruitenberglaan 26, 6826 CC Arnhem
Postbus 2217, 6802 CE Arnhem

Mobiel 0653582390
Fax 026-3645066


e-mail: debbie.tarenskeen@han.nl<mailto:debbie.tarenskeen@han.nl>
aanwezig op ma. di. wo. do.
________________________________
Van: Tarenskeen Debbie
Verzonden: woensdag 9 december 2015 16:30
Aan: AmpersandTarski/ampersand
Onderwerp: RE: [ampersand] Title text in interface does not work i.c.m. HTML TEMPLATEs (#79)


Beste Rieks, Stef,

Ik heb Atoms gegenereerd en gedraaid. De database wordt gemaakt. Ik probeer de database te reïnitialiseren en de xlsx bestanden te importeren. Helaas verschijnen er geen data in de database en ik krijg dus ook geen andere schermen.



Ik heb een database user ampersand met wachtwoord ampersand van te voren aangemaakt. De tabellen zijn er wel. Ik ga even zoeken of ik iets vind betreffende rechten.

Hetzelfde gebeurt bij het script van Michiel.



Vriendelijke groeten,

Debbie
Informatica Communicatie Academie
Hogeschool van Arnhem en Nijmegen
Ruitenberglaan 26, 6826 CC Arnhem
Postbus 2217, 6802 CE Arnhem

Mobiel 0653582390
Fax 026-3645066


e-mail: debbie.tarenskeen@han.nl<mailto:debbie.tarenskeen@han.nl>
aanwezig op ma. di. wo. do.
________________________________
Van: Rieks <notifications@github.com>
Verzonden: woensdag 9 december 2015 08:54
Aan: AmpersandTarski/ampersand
CC: Tarenskeen Debbie
Onderwerp: Re: [ampersand] Title text in interface does not work i.c.m. HTML TEMPLATEs (#79)


@DebbieGit<https://github.com/DebbieGit>: voldoet Stef's suggestie?

-

**Comment by hanjoosten** [comment]
@Michiel-s is this ticket still relevant? Maybe we should pick this up when we both are ready to give it a go

**Comment by hanjoosten** [comment]
Since I don't get answers, I assume this is not a high priority bug.

**Comment by Michiel-s** [comment]
Yes, this issue is still relevant. But there is nothing new to discuss.

This has everything to do with difference in semantics between the old and new view statement.

In short, what I explained in previous posts:
* The old view statement is used to view an atom by a certain string. View segments are concatenated to a single string which represents the atom. I call this the **label** of an atom. Not its **id**, but its **label**. Restriction is that you can only specify one old view for a concept, which is thereby its default view.
* The new view statement is used to communicate key-value pairs to html templates. I call this the **data** needed for a specific view. You can define multiple new views for a concept and make 1 default. If there is no html template, or the atom must be represented as string anyway, the segments of the new view segment are also concatenated into a sting.
* the old and new view statement syntactically look very much alike, but have its differences (for good reasons). e.g. old view segments can have (but don't require) the key part of key-value pairs. That is because the segments are concatenated to a string in the order specified in the view statement. The key is therefore not needed. The new view segments do require this key parts.

There are use cases where you want both the functionality of the old view (label/stringify) and new view (template data). For example, a template to display the atoms in a relation, and a single string in the selectbox to add another atom in the relation.

Therefore, this ticket requests to have a **label** and **data** part in the new view statement.

![image](https://cloud.githubusercontent.com/assets/7961582/15337829/b5c208e4-1c7d-11e6-89eb-3b4c5e16e88b.png)

**Comment by Michiel-s** [comment]
Combine and look into this again when picking up issue #133
