### ISSUE TITLE
Reduce size of texlive prototype image

### ISSUE THREAD

**Issue by hidde-jan** [AmpersandTarski/Ampersand#811]
Currently the `ampersand-prototype:texlive` image contains a complete texlive installation. I don't know if that is really necessary. Maybe we can change the Dockerfile so it only installs a small subset of all 3600+ texlive packages.

**Comment by stefjoosten** [comment]
That's a good idea, because the use of LaTeX is quite limited. However, a user may use things that are not loaded. In that case, the automatic loading facility of tex should kick in and load the missing module. That works automatically, so I guess we must check that it works when testing the limited texlive installation.

Probably this might work: install a minimal texlive installation. Then run an Ampersand job that uses latex, because it will load a bunch of latex modules into the container. Then save the image as a texlive image. This means that the first user will have the minimal image preloaded and it will load more as needed (which might rarely or maybe never happen).

**Comment by Michiel-s** [comment]
We can close this stale issue. We don't build prototype framework image with text live anymore. There's no use case for that.
