### ISSUE TITLE
Resource type not found

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#826]
I am using Ampersand vs.3.11.0, I am trying to make Analyse.adl from commit AmpersandTarski/ampersand-models@03eca631c6d6c0794e9e27a9c7a52f1e8102778b work. 

#### What I expected
I am creating an ADL file, because I want a quick prototype.
I expected some errors on the way, trusting that Ampersand is helpful in finding the errors.
I compiled the file (including the `INCLUDE` statement with the spreadsheet.) successfully.

#### What happened instead
When I ran the prototype, I got an error with too little information to be of any help. That is frustrating, because I might be able to do something about it if I only knew where to look...

<img width="1680" alt="issue resource type not found" src="https://user-images.githubusercontent.com/275768/44959805-1c4f9c00-aef5-11e8-82c5-480f2e1fbc2a.png">

![image](https://user-images.githubusercontent.com/275768/44968913-d6bdbe00-af4a-11e8-9d66-a0ab72951879.png)

#### Steps to reproduce
1.  release port 80 and 8080 on your local host, so this application can use them.
2.  run docker-compose -f ampersand-models/Wjsg/ProbleemAnalyse/docker-compose.yml up -d --build
3.  navigate to "http://localhost"
4.  use the excel importer to import the spreadsheet.

#### Context / Source of ampersand script
 
```
CONTEXT Analyse
--INCLUDE "Inventarisatie nut en noodzaak v0.1.xlsx"

REPRESENT Vraag, Tekst, Opmerking TYPE BIGALPHANUMERIC

RELATION vraag [Vraag*Tekst] [UNI]
RELATION bate [Vraag*Bate]
RELATION bron [Vraag*Bron]
RELATION bereik [Vraag*Scope]
RELATION onderbouwing [Vraag*Waarneming]
RELATION effect [Vraag*Tekst]
RELATION opmerking [Vraag*Opmerking]
RELATION interview [Vraag*Persoon]

RELATION tekst [Waarneming*Tekst]
RELATION bron [Waarneming*Bron]

RELATION belang [Persoon*Belang]
RELATION naam [Persoon*Naam]
RELATION waarneming [Persoon*Waarneming]

RELATION brontekst[Bron*Tekst]
VIEW Bron : Bron(brontekst)

INTERFACE Overzicht FOR User : "_SESSION"[SESSION] cRud
TABS [ Enquete : V[SESSION*Vraag]
        BOX [ Vraag : vraag
--            , "Mijn antwoord (1-5)" : Likert
--            , "Hoe belangrijk is deze vraag voor Justid? (1-5)" : Likert
            ]
     , Vragenlijst : V[SESSION*Vraag]
     , Personen : V[SESSION*Persoon]
     , Bronnen : V[SESSION*Bron]
     , "Mijn waarnemingen" : V[SESSION*Waarneming]
     ]

INTERFACE Vraag : I[Vraag] cRud
 BOX [ vraag : vraag          cRUd
     , bron : bron
     , bate : bate
     , bereik : bereik
     , onderbouwingen : onderbouwing
     , effecten : effect
     , opermerkingen : opmerking
     , geïnterviewden : interview     CRUd LINKTO INTERFACE Persoon
     ]

INTERFACE Persoon : I[Persoon]
 BOX [ naam : naam                      cRUd
     , belang : belang
--     , "edit vragen" : interview~       LINKTO INTERFACE Vragen
     , "beantwoord vragen" : waarneming LINKTO INTERFACE Waarneming
     ]

INTERFACE Waarneming : I[Waarneming]
 BOX [ "mijn waarneming" : waarneming~
--     , bron : bron
--     , "edit vragen" : interview~          LINKTO INTERFACE Vragen
     , "beantwoord vragen" : onderbouwing~ --LINKTO INTERFACE Vraag
     ]

ENDCONTEXT
```

**Comment by stefjoosten** [comment]
The problem here is not the reported bug, but the behavior of Ampersand when such bugs occur. There are (at least) two things we might consider:
1. how to get more meaningful run time messages.
2. how to prevent such messages by predicting the erroneous behaviour at compile time.

**Comment by hanjoosten** [comment]
I do not believe we can prevent *all* cases of runtime errors. However, the goal should be to prevent all preventable ones, and limit the pain for the end user in unpreventable cases by giving more details when errors occur. 

In the first case, there is a php call looking for some resourcetype. An event is thrown, which is a kindof runtime fatal. It shouldn't happen, but it does. In ALL cases that an event is thrown, we want to supply as many details that we can in the error message. In this specific case, the code looks like:

```.php
if (!$concept->isObject()) {
            throw new Exception("Resource type not found", 404);
        }
```
The message should tell about the details of the concept it is looking for. In general, whenever an exception is thrown, spitting out details is a good idea, because it helps to find out what is wrong. 

@Michiel-s , could you traverse ALL instances of `throw new Exception` in the code to add these details to the message? 

In the second case, the database fails to insert some value in some table. Here too, there is a shortage of info. If the query could be dumped in the log, that would help the user to diagnose what is going on. Looking at the code, and thinking of the details that could be given when throwing an exception, that would probably come up as a logical thing to do. So I hope that after all pieces of code where exceptions are being thrown are being fixed, the user will have much more meaningful messages. 

Of course, these messages cannot be prevented in all cases. If the user tries to populate a string that is too long in some alphanumeric typed value, it just doesn't fit. There should be an error thrown. That is preferable to skipping the error and just continue without warning.

**Comment by Michiel-s** [comment]
I've documented how errors and exceptions are handled here: [doc](https://ampersandtarski.gitbook.io/the-tools-we-use-for-ampersand/prototype-framework#errors-and-exceptions). This is a start of more documentation to come regarding the prototype framework.

@hanjoosten, as requested, I looked at places where exceptions are thrown and to be honest they have pretty good messages. Especially given the fact almost all of them are errors that are not caused by the user. They need to be checked by us/myself.

@stefjoosten, regarding your comment:
> The problem here is not the reported bug, but the behavior of Ampersand when such bugs occur. There are (at least) two things we might consider:
1 how to get more meaningful run time messages.
2 how to prevent such messages by predicting the erroneous behaviour at compile time.

1. Provide as much context as possible in the error message. I try to do so as much as possible. I can look into specific cases if you have them.
2. Recently we use a static analyzer for php code. See the documentation I mention above.
