### ISSUE TITLE
configuring https instead of http in containers

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#831]
I am trying to deploy an Ampersand-application under [https instead of http for obvious reasons](https://www.eff.org/deeplinks/2018/07/moving-your-site-not-secure-secure). I have been searching the internet for information on how to do that in docker. It is not trivial. This issue documents the process of how that works. I have asked @hidde-jan to join in, as he knows more about docker than I do.

# Analysis
The [docker-daemon](https://docs.docker.com/engine/reference/commandline/dockerd/#description) is the process on the host that is responsible for running the docker platform. It has to be configured to work with TLS (TLS is the transport-layer security protocol. soundbite: HTTPS = TLS+HTTP). The first thing to do is to configure the docker daemon correctly. This is done in a [daemon.json file](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file). On my Mac I can edit it by opening the whale icon > Preferences > Daemon > advanced in the menu bar at the top of my screen:
<img width="612" alt="afbeelding" src="https://user-images.githubusercontent.com/275768/45262772-d37c7380-b41d-11e8-9333-6c8f9259bf83.png">
Apparently, the TLS configuration is absent. I found [the following example](https://docs.docker.com/config/daemon/#configure-the-docker-daemon) in the docker documentation, giving me a starting point to work from:

```json
{
  "debug": true,
  "tls": true,
  "tlscert": "/var/docker/server.pem",
  "tlskey": "/var/docker/serverkey.pem",
  "hosts": ["tcp://192.168.59.3:2376"]
}
```
So now what I need is a certificate, a key, and an IP-number and port.

# Getting a certificate
The Electronic Frontier Foundation (EFF) helped create a free, automated, publicly-trusted certificate authority called Let’s Encrypt, which is now the most-used certificate authority on the web. In this post, we’re going to provide advice about the process of getting a certificate from Let’s Encrypt. It’s a convenient option in many cases because it doesn’t charge money for the certificates, they’re accepted by all mainstream browsers, and the certificate renewal process can be automated with EFF’s tool Certbot.

I found [this tutorial](https://www.humankode.com/ssl/how-to-set-up-free-ssl-certificates-from-lets-encrypt-using-docker-and-nginx) with an excellent explanation which suits our purpose. The only thing is that this tutorial is  written for Nginx and we are using Apache.

# Summary
1. 
2.
3.
4.

**Comment by hidde-jan** [comment]
Hi Stef,

What your currently doing is making the docker daemon available over https. This is completely different from making Ampersand-based prototypes available over https instead of (only) over http.

Some notes:

1. HTTPS is only useful for ampersand prototypes that are available over the internet (like RAP3)
2. from what I can see Ampersand (prototypes) are pretty agnostic wrt how they are served
3. The easiest way to get a dockerized ampersand prototype served over https would probably be to have a reverse proxy sitting in front of it that handles https connections. You could use something like https://github.com/SteveLTN/https-portal

**Comment by stefjoosten** [comment]
Thanks for that remark. I agree that an Ampersand prototype is pretty agnostic wrt how they are served. I would think that a reverse proxy would sit in the same pod as the application. I've seen that pattern a couple of times. How is that different from what I read in the tutorial (above)? I got the impression that this tutorial implements precisely that pattern... It's' just that we use Apache rather than Nginx, but I don't think we are picky about that either.

**Comment by hidde-jan** [comment]
It’s pretty similar to the last tutorial. My first remark was about getting the docker daemon to listen on a https connection.

I wouldn’t have the prototype container also manage the https connection. I would make another container to run the reverse proxy in. Containers should run one logical ‘process’. Since there are already docker images that can be set up to run as a https reverse proxy that would be a better route in my opinion.

**Comment by stefjoosten** [comment]
So what you are saying is: The docker-daemon need not listen to https. The reverse proxy should. These are two different things.

So any effort in configuring the docker daemon is misdirected. I should focus on a container with the reverse proxy. Similar to this:
![image](https://user-images.githubusercontent.com/275768/45277876-9de19400-b4ca-11e8-88db-1ef483160047.png)
(image from [George's blog](https://blog.georgejose.com/moving-my-http-website-to-https-using-letsencrypt-haproxy-and-docker-deb56ff6be9b). Thank you George!)
Is that correct @hidde-jan ?

**Comment by hidde-jan** [comment]
> Is that correct @hidde-jan ?

Yep!

**Comment by Michiel-s** [comment]
We can close this issue as serving the prototypes over https is not something we can add/configure in the compiler nor the prototype framework. As explained above a reverse proxy is the way forward. This is project specific and outside scope of our repos.
