### ISSUE TITLE
Bug in evaluation of rules using specializations

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#88]
Consider the following script 

     sPerson :: SESSION * Person [UNI]
     sManagesX :: SESSION * X
     
     CLASSIFY Y ISA X
     
     personManagesX :: Person * X =[ ("John", "Johns X") ]
     personManagesY :: Person * Y =[ ("Pete", "Petes Y"); ("John", "Johns Y") ] 
     
     RULE "sManagement" : sManagesX = sPerson;personManagesX
     VIOLATION (TXT "Sessie=", SRC I, TXT "; sPerson=", SRC sPerson, TXT "; sMgsX=", TGT I)
     
     POPULATION sPerson CONTAINS [ ("S1", "John") ]
     POPULATION sManagesX CONTAINS [ ("S1", "Johns X"); ("S1", "Johns Y") ]
     
     POPULATION sPerson CONTAINS [ ("S2", "Pete") ]
     POPULATION sManagesX CONTAINS [ ("S2", "Petes Y") ]

This produces the following errors, which are not errors:

     Violations of rule "sManagement":
     - [('S1','Johns Y'), ('S2','Petes Y')]

**Comment by stefjoosten** [comment]
In order to find the violations of `RULE "sManagement"`, let us determine the pairs of the left hand side `sManagesX` and right hand side `sPerson;personManagesX`:

     sManagesX = [ ("S1", "Johns X"); ("S1", "Johns Y"); ("S2", "Petes Y") ]
     sPerson;personManagesX = [ ("S1", "Johns X") ]

The difference set of `sManagesX` and `sPerson;personManagesX` represents the violations of rule "sManagement":

       [('S1','Johns Y'), ('S2','Petes Y')]

I don't see why Ampersand made a mistake.

I don't understand what `CLASSIFY` has to do with this.

I have closed the issue and removed `Issue88.adl` from the test set.
