### ISSUE TITLE
Prevent disk space from filling up

### ISSUE THREAD

**Issue by LloydRutledge** [AmpersandTarski/Ampersand#880]
This issue is ported from https://github.com/AmpersandTarski/RAP/issues/52#issuecomment-450861199 as suggested there.

The RAP3 server for the Open University Rule-based Design course fills up quickly, clogging the disk space, and thus crashing the server with an SQL 1114 full table error. The resulting server instability is the largest problem of Ampersand for the RBD students. About 80 students in 20 teams of four use the server: mostly in the cycle nov-feb every year, and the mostly in January. Short term solution is that I check the disk space several times a week and when needed delete a bunch of files. But is there a more stable, less maintenance intensive long-term solution?

@Michiel-s posted at https://github.com/AmpersandTarski/RAP/issues/52#issuecomment-450861199:

"The solution that is really going to help is using a single deployment of the prototype framework (php backend and javascript frontend files). This is roughly 20 Mb, consisting of only 200 Kb of project/model specific files (generated output). The rest is all there to be able the run the prototype.

It probably would require some time to set it up, but you could make it so that the generic code is deployed once on the machine and the project specific files are loaded depending on the script that is requested. A change/issue in the Ampersand repo is required to support this way of deploying/running prototypes."

**Comment by stefjoosten** [comment]
# Analysis
This problem may have occured because I deleted log directories and generated directories from the virtual machine (VM). This cause seems likely, because since that moment no logs or generated files have been written by RAP3. @Michiel-s and I developed the theory that it might have to do with the docker volume. The files and directories I deleted in the VM are being written to by two docker containers by means of a volume-link. I expected those directories to be recreated when written to, but it looks like this expectation was not correct.

# Solution
Anyway, I restarted the docker containers and that seems to help. To be continued, because the diagnosis of this issue is not yet complete.

**Comment by stefjoosten** [comment]
I'm closing this issue until the above solution is proven wrong.
