### ISSUE TITLE
png files not found when generating fspec

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#91]
When I create a functional specification, and specify the option `--outputDir=".\fspec"`, this specifies the output directory for functional specification files. In the resulting .TEX file, I find lines that refer to .PNG files such as 

     \scalebox{0.5}[0.5]{\includegraphics{./fspec/RelationsInPatternAccounts.png}}

Note that they have the specified output directory in the path of the file. However, it looks like it is the case that this output directory is the current directory when the .PDF file is generated, which results in the error message 

     pdflatex> ! Package pdftex.def Error: File `./fspec/RelationsInPatternAccounts.png' not found.

This happens fo all picture files. Maybe it helps to leave out the output direcctory in the file path.

**Comment by hanjoosten** [comment]
outputDir is ment to contain an absolute path. However, in this case, it contains a relative path. When ampersand generates the .png files, it will write them  (not for sure, but my edugated guess for now) relative to the path where the ampersand.exe resides. 
The same path is used to write the .tex file. 
As you have noticed, the relational path is also written in the .tex file to point to the .png file. Of course, it will not be there. 
As a workaround, use an absolute path. 
the solution would be to omit the path in the latex file, because the .tex file and the .png file will all be written into the same directory anyway.

**Comment by RieksJ** [comment]
Thanks for the workaround. 
Perhaps, when work is being done on the fspec generator, it would be nice to remove this path from the file as generated within latex.
Having said that, there are many, many more LaTeX errors that at a first glance appear to do no harm, but then they do indicate that perhaps things have gotten a bit too complex here...
