### ISSUE TITLE
Storing population in P-structure is errorprone

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#915]
While diagnosing an issue during development of the new navbar feature, @Michiel-s and I noticed that some population wasn't available where we thought it should. During further investigation, I noticed that in the P-strucure, there are two places to store population of relations. Storing population inside a relation is wrong:
The dataconstrucor P_Relation contains a function `dec_popu`, holding tuples in that relation. However, a relation could be defined in a user's script multiple times. The equality on relation is on its source and target concept and its name. A couple of months ago a lot of handling of relations has been converted from lists to sets. This drastically improves performance, but it relies on Eq, for there cannot be doubles in a Set. This combination is an obvious cause for errors. 
The solution is obvious: Get rid of `dec_popu`. Store population in all cases in `P_Population`.

**Comment by stefjoosten** [comment]
@hanjoosten : Your reasoning is cyclic. Your argument boils down to: "Storing the population inside a relation is wrong because storing the population inside a relation is wrong."

Cyclic reasoning is wrong.

The reason some population disappeared was that the equality relation Eq was incorrect. That has been fixed, as you showed me.

By the way, I agree with your conclusion: "Get rid of dec_popu. Store population in all cases in P_Population." But for a different reason.

**Comment by hanjoosten** [comment]
@stefjoosten : Thanks, point taken
