### ISSUE TITLE
Deployment of prototype framework produces UnsafePath error

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#933]
When I compile a script with the option `prototype-framework-version=development`, and the script has no Ampersand/ADL errors, a prototype shuld be generated. However, it results in the following output:
~~~
Starting at .....: 11:37:24,96
"C:\Ampersand\AMPprogs\ampersand.exe" "GRC" --ignore-invariant-violations -p"C:\xampp\htdocs\GRC"
Reading config file: GRC.yaml
Processing your model...
There are signals for the initial population. Use --verbose to output the violations
Generating prototype...
Error encountered during deployment of prototype framework:
UnsafePath "C:\\xampp\\htdocs\\GRC\\.bowerrc"
Terminated at ...: 11:37:27,29
~~~

**Comment by hanjoosten** [comment]
The compiler tries to download the code for the prototype frontend, which is in a separate repository. This is a compressed archive. Obviously, there are a lot of things that could go wrong. The error that you get is not specific about what exactly went wrong. 

1. The download of the archive failed. (due to not having a valid internet connection, or because the version supplied was not correct, wrong name etc.) A non-valid filename in your `.bowerrc` could also be one of these causes.
2. The exctraction of the archive failed. This is unlikely, but a glitch of the universe in the hands of Murphy is enough. 

There is not much we can do to solve the above causes, but the error message could be made somewhat more specific.

**Comment by RieksJ** [comment]
I don't care about the causes. What I care about is how I get the stuff running again (frustration, frustration). Please ensure that a more specific error message helps users like me to get up and running again. 

Until I know what's wrong and it is fixed (by me or by ...), this is a bug and it is certainly critical.

**Comment by hanjoosten** [comment]
well, just check what is in your .bowerrc file, as the error message says.

**Comment by RieksJ** [comment]
This issue is not fixed. Here is some more details:

I only use the following switches in the yaml file:
  - `ignore-invariant-violations`
  - `customizations=customizations`
  - `crud-defaults=cRud`
  - `prototype-framework-version=development`

I use Ampersand-v3.16.0 [feature/issue932:7697f8c1a], and on the commandline I use the switches `--ignore-invariant-violations -p"C:\xampp\htdocs\GRC"`

### Analysis

1.  When the target directory does not exist, the error occurs. 
2.  When the target directory exists, and it is empty, the directory is deleted and the error occurs.
3.  When the target directory exists, and there is a single (arbitrary) file in it, I get another error:

~~~Generating prototype...
ampersand.exe: Cannot read template file Atomic-ALPHANUMERIC.html
C:\xampp\htdocs\GRC\templates\Atomic-ALPHANUMERIC.html: openBinaryFile: does not exist (No such file or directory)
CallStack (from HasCallStack):
  error, called at src/Ampersand\Prototype\GenFrontend.hs:438:30 in ampersand-.16.0-5CQj4XKiwH6IYfjfcFh1CX:Ampersand.Prototype.GenFrontend
~~~

4.  When the target directory exists, and it contains a (relatively recently generated) prototype, a prototype is generated. This may serve as a workaround (so I change the priority from critical to high)

**Comment by RieksJ** [comment]
Since this issue is currently preventing me from compiling several projects (SSIF, GRC, V1622), I have raised the priority to 'critical' again.

**Comment by Michiel-s** [comment]
This is due to an update of the zip-archive library @hanjoosten forced in this commit 62552baa46eaf11fb0437a313df2acabd952dc47. I'll do a commit to revert this, but let's keep this issue open to fix the problem with zip-archive v0.4

**Comment by hanjoosten** [comment]
> This is due to an update of the zip-archive library @hanjoosten forced in this commit [62552ba](https://github.com/AmpersandTarski/Ampersand/commit/62552baa46eaf11fb0437a313df2acabd952dc47). I'll do a commit to revert this, but let's keep this issue open to fix the problem with zip-archive v0.4

This work-around is ok for now. This issue is caused by a [security feature introduced in zip-archive v0.4](https://github.com/jgm/zip-archive/issues/50). 

The folks of Elm have bumped into the same issue. They proposed [this idea](https://github.com/elm/compiler/issues/1882#issuecomment-455875799) to fix it. Not sure if that will do it for us too. 
  
> Is dat taart door @hanjoosten ?
Nope. Unfortunatly no taart. That is only on checking in something in development branch that does not compile.

**Comment by hanjoosten** [comment]
I think this is an issue with zip-archive. I raised issue https://github.com/jgm/zip-archive/issues/55

**Comment by hanjoosten** [comment]
It has been confirmed that it is an issue with zip-archive. We will wait until this is fixed before upgrading.
