### ISSUE TITLE
Code fragment in ADL2Plug suspected of containing errors.

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#941]
#### Version of Ampersand that was used 
I used Ampersand-v3.16.0 [data-analysis:9e4a6c084*]. I was triggered by the observation that `attNull = isTot trgExpr` on line 161 of file `ADL2Plug.hs`. This is wrong because `attNull` means that the attribute may contain a `NULL` value.

![Screenshot 2019-05-01 at 16 28 22](https://user-images.githubusercontent.com/275768/57022059-409f7c00-6c2e-11e9-85b5-a28a515261d3.png)

#### What I expected
I expected to see the correct code, which is: `not.isTot $ trgExpr`. However, before I start fixing things that are not broken, I would like @hanjoosten to comment on this. This is your code from 4 years ago.

Upon closer inspection, I'm also puzzled by `attNull = isSur trgExpr` in the code of `trgAtt`. I would have expected `attNull = isSur srcExpr` for symmetry reasons with the code of `srcAtt`. And then, of course, I would expect that to be `attNull = not.isSur $ trgExpr`

Anyway, I am curious as to why we have never discovered these mistakes.

**Comment by Michiel-s** [comment]
I would like to check for the affect in prototypes before we merge any change.

**Comment by stefjoosten** [comment]
@Michiel-s, I share your worries. Do you expect our regular regression tests to be sufficient?

**Comment by Michiel-s** [comment]
A change is done in commit:  

However, I think there is no effect (at least not for the prototypes), because to generate the SQL code we use `attDBNull`, not `attNull`. See data structure `SqlAttribute` below. I don't understand the difference. `attNull` is in FSpec2ClassDiagrams.hs and ChapterDataAnalysis.hs but we can use `attDBNull` there also.

I propose to remove/replace `attNull` by `attDBNull`.

```hs
data SqlAttribute = Att { attName ::    Text
                        , attExpr ::    Expression     -- ^ De target van de expressie geeft de waarden weer in de SQL-tabel-kolom.
                        , attType ::    TType
                        , attUse ::     SqlAttributeUsage
                        , attNull ::    Bool
                        , attDBNull ::  Bool
                        , attUniq ::    Bool
                        , attFlipped :: Bool
                        } deriving (Eq, Show,Typeable)
```

**Comment by Michiel-s** [comment]
Ah wait... while changing the code the reason for having these two different aspects occured to me.

Basically what we want is to have the SqlAttribute reflect the TOT/SUR constraints in the `attNull` depending on the implementation of the relation, with the options:
* Relation is in concept table of src: TOT -> attNull = False, otherwise True
* Relation is in concept table of tgt: SUR -> attNull = False, otherwise True
* Relation is in link table: attNull = False

However, we have the TOT and SUR constraints handled by the invariant violations. And for them to work, we need to be able to add records to concept tables without the database throwing a error for null values. So for the database implementations we always allow for NULL values (except for the primary key column).

But for that reason we don't need both `attNull` and `attDBNull`. We can merge the two anyway and at the point where we construct the database structure queries, add the logic to allow NULL values anyway.
