### ISSUE TITLE
How to write CLASSIFY-constraints

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/ampersand#95]
Consider a use-case where (electrical) components have inputs and outputs to which wires can be connected. We use the term 'IOPort' to refer to such inputs and outputs. This can be modelled as:

     CLASSIFY Input  ISA IOPort
     CLASSIFY Output ISA IOPort
     
In order enable the detection of erroneous wiring, we decide that inputs and outputs are distinct. The question is how to formally express this rule. After many attempts, for each of which the type checker produces messages, I was left with:

     RULE "IOPort integrity": V[IOPort];I[Input];V[IOPort] /\ V[IOPort];I[Output];V[IOPort] = -V
     MESSAGE "IOPorts must be either inputs or outputs, but not both."

Is there another, more elegant way of doing this?

**Comment by sjcjoosten** [comment]
This rule should work and be equivalent to your rule:
I[Input];I[IOPort];I[Output] |- -V[Input*Output]

(there is no elegant way to say "is empty", but otherwise this looks pretty straightforward)

I would express the rule "IOPorts must be either inputs or outputs, but not both."
as:
RULE I[IOPort] - I[Input] = I[Output]
Which is excepted as well, but not equivalent to what you wrote (your rule allows that IOPorts are neither Input or Output, the last rule forbids this).

**Comment by stefjoosten** [comment]
@sjcjoosten Bas, can you remind me of the reason why Ampersand rejects this:

    CONTEXT IOports IN ENGLISH

    CLASSIFY Input  ISA IOPort
    CLASSIFY Output ISA IOPort

    RULE I[Input] /\ I[Output] = -V[IOport]

    ENDCONTEXT

The current Ampersand type checker says:

    Ambiguous type when matching: Src of I[Input]
     and Src of I[Output].
      The type can be "Output" or "Input"
      None of these concepts is known to be the smallest, you may want to add an order between them.
      Error at symbol /\ in file Try.adl at line 6 : 15

In my "new" thinking, I see no reason to forbid this. This type error stems from the time that I insisted there be a unique smallest type for every atom. However, since Martijn has shown this to cause dynamic type checking, I have abandoned this position. So as far as I'm concerned this message can be removed from the type system. Do you agree?

**Comment by sjcjoosten** [comment]
The only problem I see is in determining the type of `I[Input] /\ I[Output]`. Currently, the parser is bottom up (although disambiguation is not), and I believe it has to be in order for it to behave predicable.
We wanted many laws of RA to hold for Ampersand. DeMorgan was one of them, which we fixed by not allowing unbounded negations (although this appears to be broken in the current version, probably because I never built it right). An effect of this is that we are no longer able to express DeMorgan without type annotations.
Another law which would be nice, is distributivity of `\/` over `/\`. This means that `(I[Input] /\ I[Output]) \/ I[Zero] = (I[Input] \/ I[Zero]) /\ (I[Output] \/ I[Zero])` must hold, and both sides of the equation must be typed equal as well.
Indeed, the following typechecks:

    CLASSIFY Input  ISA IOPort
    CLASSIFY Output ISA IOPort
    CLASSIFY Zero   ISA Output
    CLASSIFY InOut IS Input /\ Output
 
    RULE (I[Input] /\ I[Output]) \/ I[Zero] = (I[Input] \/ I[Zero]) /\ (I[Output] \/ I[Zero])

The following does not:

    CLASSIFY Input  ISA IOPort
    CLASSIFY Output ISA IOPort
    CLASSIFY Zero   ISA Output
 
    RULE (I[Input] /\ I[Output]) \/ I[Zero] = (I[Input] \/ I[Zero]) /\ (I[Output] \/ I[Zero])

So how would you determine the type of `I[Input] /\ I[Output]`. Clearly, `[Zero]` is not large enough. Since `I[Input] /\ I[Output] = I[Output] /\ I[Input]`, we cannot allow `[Input]`, for otherwise it should have the type `[Output]` as well, and a term can only have one type. The only option that is left, is `[IOPort]`, which means that the type on the left hand side should be `[IOPort]`.
Unless you have some radical changes in mind for the type checker, the right hand side will be of type `[IOPort] /\ [Output]` = `[Output]`, so clearly distributivity of `\/` over `/\` does not hold. Therefore, unless you intend to annotate the `/\` and `\/` like we currently annotate the unary complement `-`, I believe we cannot type `I[Input] /\ I[Output]` unless the user gave a deliberate name for the intersection of `Input` and `Output`.

**Comment by stefjoosten** [comment]
Hm, @RieksJ, how do you value this answer? Sufficient to close the issue?
