### ISSUE TITLE
Something seems to be wrong in session mgt and/or interface access control

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#966]
Using `Ampersand-v3.17.0 [development:1d0e24131]`, I can succesfully compile the ButtonCRUD application (from the ampersand-models repo, commit `6f0c07ae`). However, whenever I go to the interface `ButtonCRUDPortal`, I get the following stuff on my screen:

![afbeelding](https://user-images.githubusercontent.com/8522589/57983184-37e0df80-7a4f-11e9-974c-e7e7e2b23a8c.png)

which basically says that I don't have acces to the page that is shown. And that seems to be the case in the sense that when I click on a button, eg `XXXXs`, which I would expect to populate a property on the concept `SESSION`, I get the following: 

![afbeelding](https://user-images.githubusercontent.com/8522589/57983218-9b6b0d00-7a4f-11e9-9fca-724fb914a917.png)

and the property wasn't set. 

Note that the resource that could not be found is the SESSION id of the current session, as you can see in the figure. Any idea what's going on here? Can we look at this together perhaps?

**Comment by Michiel-s** [comment]
Yeah, let’s diagnose together.

**Comment by Michiel-s** [comment]
This consisted of two issues:
1. The ‘not allowed’ is thrown because you try to access the list of all sessions by having a select box with target concept SESSION. Due to security reasons (risk of session hijacking) this is not allowed.
1. The other patch issue was a bug in reference interfaces and query optimization. Fixed in [this commit](https://github.com/AmpersandTarski/Prototype/commit/fa3d5c91ebd88a91a0fd875c90ad229173bb7542)
