### ISSUE TITLE
Disambiguation issue with INTERFACE statement.

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand#980]
#### Version of ampersand that was used 
Ampersand-v3.17.1 [development:cc87ba813]

#### Script used:
```
CONTEXT Issue980 IN ENGLISH

CONCEPT Fruit "Most general concept"
CLASSIFY Citrus ISA Fruit
CLASSIFY Orange ISA Citrus
CLASSIFY Lemon ISA Citrus

RELATION name[Citrus*Name]
RELATION name[A * B]  -- This relation's purpose is to distract the typechecker. 

INTERFACE Orange(name) : I[Orange]
BOX [ "I" : I
    , "name" : name
    ]

INTERFACE Lemon(name) : I[Lemon]
BOX [ "I" : I
    , "name" : name[Citrus*Name]
    ]

ENDCONTEXT

```

#### What I expected
I expected the typechecker to resolve all disambiguation correctly

#### What happened instead
The typechecker threw the following error:

~~~
D:\git\Ampersand\testing\Travis\testcases\prototype\ISAtest\Issue980.adl:13:16 error:
  Cannot disambiguate the relation: name
    Please add a signature (e.g. [A*B]) to the relation.
    Relations you may have intended:
    name [A*B]
    name [Citrus*Name]
~~~

The relation `name[A*B]` obviously does not belong here. An `A` has no relation whatsovever with an `Orange`, which is the type of the target of the interface expression.

**Comment by hanjoosten** [comment]
@sjcjoosten , kan jij hier naar kijken?

**Comment by sjcjoosten** [comment]
The following also does not disambiguate:

```
RULE I[Orange];name = I[Orange];name
```

The non-disambiguation is on purpose here. There are several reasons for this.

## Disambiguating `I` and `V`
Consider the following rule (which states that there is at most one atom in the concept Orange):
```
RULE I[Orange];I = V
```

The occurrence of ``I`` should obviously be disambiguated to `Orange`. However, there is another type-correct way of interpreting the `I`, namely as `Citrus` or `Fruit`. Similarly, the `V` should obviously be `Orange*Orange`, but there are many other ways to interpret this.

In order to resolve the ambiguous occurrences of `I` and `V`, disambiguation ignores the type lattice and uses precise types. We could ask the disambiguation to come up with the precisest type possible, but that would require adding a lot of information about the type lattice into the disambiguation process (in some places, types can only be generalised, in others they can only be restricted, in others both are allowed). I would not be comfortable adding that without investigating some of the resulting properties separately.

## Keep type-correct scripts to semantically mean the same after extensions
I give two scripts that would both be type-correct under some disambiguation, however, we will see that the relations to which the relations are disambiguated will differ. A problem is that as a script evolves, it would be conceivable for someone to add the lines that make up the difference, causing a change in a (potentially far-away) part of the code that has not been touched at all. I'll call this 'spooky action at a distance'.

Script one (which currently would give a type error):

```
CLASSIFY Citrus ISA Fruit
CLASSIFY PlainString ISA String -- a string that does not need escaping is a string that might
RELATION name[Citrus*Name]
RELATION name[Fruit * PlainString]
RELATION quote[String*String] -- relation which adds quotes to string
RELATION quotedName[Citrus*String]
RULE quotedName = name;quote -- disambiguates to name[Fruit*PlainString]
```

Script two (which currently would type-check):

```
CLASSIFY Citrus ISA Fruit
CLASSIFY PlainString ISA String
CLASSIFY Name ISA String -- this line is the only difference between the two examples
RELATION name[Citrus*Name]
RELATION name[Fruit * String]
RELATION quote[String*String]
RELATION quotedName[Citrus*String]
RULE quotedName = name;quote -- disambiguates to name[Citrus*Name]
```

At the expense of making the example much more complicated, there would be possible changes of meaning that seem even more unrelated. If we were to fix the disambiguation issue stated at the top of this issue and avoid spooky-action at a distance, we need to refuse the script that is accepted now, i.e. have a breaking change. I don't know if any of the current ADL files would break because of this, but I think that's quite likely.

I'm not saying that spooky action at a distance cannot happen right now, but I have been resistant to making changes to the disambiguation where I foresee it happening.

## Better error messages
As disambiguation becomes smarter, some of the scripts that do not type-check will start giving type-errors rather than asking for disambiguation. It is likely that this is something that can be resolved by adding more complicated code for the error messages, but so far the code for error message generation has been really straightforward and complicated enough as is.

## Question
Do we wish to close this as a won't fix? If so, is there a good place to put the explanation of why we are not fixing disambiguation issues like these (aside from where it is currently)?

**Comment by hanjoosten** [comment]
I see your point, but I am still confused. If in above example we drop the line that says `RELATION name[A * B]  -- This relation's purpose is to distract the typechecker. `, disambiguation is totally happy. This means that your narrative about disambiguating `I` and `V`, while valid in itself, is out of context.
That is only relevant within the context of a typology (a lattice of concepts that are related by CLASSIFY statements). 
The disambiguator should look to see if there is a single typology to be bound. Currently it looks for a single concept, which leads to this error. If the correct typology could be found, then in a second step it could be figured out if a use of Epsilon could make the types work.

**Comment by sjcjoosten** [comment]
Looking for a typology rather than a type would indeed change the two examples: the previously succeeding one would fail and vice-versa. The reasoning for `I` and `V` is completely relevant here: if there were only one type for `I` and `V`, the disambiguation would be happy too, but we cannot drop `I[Citrus]` in the same way we can drop `name[A*B]`.

So if we want to implement typology-based disambiguation, we have a couple of options:

- require more annotations around `I` and `V` if they occur in a non-trivial typology. This would improve the quality of the Ampersand code in general.
- treat `I` and `V` different from ordinary relations, by making them behave the same as they do now (which is what would happen if we consider `I` and `V` to be out of context). This has the problem that it keep the disambiguation unpredictable (It already is: consider `(I[Orange];I;I);I[Citrus]`, for instance.)

**Comment by hanjoosten** [comment]
You might be right, but I am not convinced yet (this could be totally due to me). In the current situation, the error message that is a result of the disambiguation is false. It says:

```
D:\git\Ampersand\testing\Travis\testcases\prototype\ISAtest\Issue980.adl:13:16 error:
  Cannot disambiguate the relation: name
    Please add a signature (e.g. [A*B]) to the relation.
    Relations you may have intended:
    name [A*B]
    name [Citrus*Name]
```
It suggests, that if any of the suggestions is adopted, this would lead to either a correct specification or at least a _less ambigous_ specification. All but one of the suggestions however lead to a type error in the script.

**Comment by sjcjoosten** [comment]
The error message does a good job at diagnosing the problem with the script from my perspective, but I'm not a user. So I would be happy if there were a better message. Any ideas?

**Comment by hanjoosten** [comment]
What about:

```
D:\git\Ampersand\testing\Travis\testcases\prototype\ISAtest\Issue980.adl:13:16 error:
  Cannot disambiguate the relation: name
    Please add a signature (e.g. [A*B]) to the relation.
    Relation you may have intended:
    name [Citrus*Name]
```
This feels better, because the other suggestion is not a valid option.

**Comment by sjcjoosten** [comment]
That looks good. We'll need to do type-checking using a bunch of ambiguous relations, which allows me to encode an NP-hard problem. If there is only one ambiguous relation, this is not a problem (in runtime or otherwise). Do we want to allow for a potentially very long runtime, or do we allow the error message to list too many options in certain corner-cases?

**Comment by hanjoosten** [comment]
This issue has been closed, not fixed. In case of a disambiguation error, the user is pointed to the [comment of @sjcjoosten above](https://github.com/AmpersandTarski/Ampersand/issues/980#issuecomment-508985676).

**Comment by hanjoosten** [comment]
This issue is related to #437
